In [1]:
import pandas as pd

In [2]:
merged2013_2017 = pd.read_csv('merged2013_2017.csv')

In [3]:
merged2013_2017.head()

,Unnamed: 0,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,...,Unnamed: 0.2,rideable_type,from_city,from_landmark,to_city,to_landmark,start_date,end_date,from_dpcapacity,to_dpcapacity
0,0,9651,00:00,00:09,478,487,34,Cannon Dr & Fullerton Ave,67,Sheffield Ave & Fullerton Ave,...,0.0,classic_bike,Chicago,124.0,Chicago,60.0,2013-06-30,2013-06-30,15,15
1,1,19385,00:00,00:06,893,359,20,Sheffield Ave & Kingsbury St,60,Dayton St & North Ave,...,0.0,classic_bike,Chicago,154.0,Chicago,58.0,2013-07-03,2013-07-03,15,19
2,2,29952,00:00,00:27,311,1623,59,Wabash Ave & Roosevelt Rd,97,Museum Campus,...,0.0,classic_bike,Chicago,31.0,Chicago,29.0,2013-07-06,2013-07-06,19,19
3,3,37222,00:00,00:44,420,2639,76,Lake Shore Dr & Monroe St,76,Lake Shore Dr & Monroe St,...,0.0,classic_bike,Chicago,300.0,Chicago,300.0,2013-07-08,2013-07-08,11,11
4,4,59638,00:00,00:25,187,1479,27,Larrabee St & North Ave,24,Fairbanks Ct & Grand Ave,...,0.0,classic_bike,Chicago,174.0,Chicago,262.0,2013-07-14,2013-07-14,19,15

In [4]:
merged2013_2017.drop('Unnamed: 0', axis=1, inplace=True)

In [5]:
merged2018_2019 = pd.read_csv('merged2018_2019.csv')

In [6]:
merged2018_2019.head()

,Unnamed: 0,index,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
0,0,0,17536702,00:12:00,00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,...,-87.677692,19.0,65.0,Chicago,41.907781,-87.685854,11.0,245.0,Chicago,classic_bike
1,1,1,17536703,00:41:35,00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,...,-87.658857,15.0,104.0,Chicago,41.973385,-87.668365,15.0,392.0,Chicago,classic_bike
2,2,2,17536704,00:44:46,01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,...,-87.632530,15.0,6.0,Chicago,41.909769,-87.705280,15.0,653.0,Chicago,classic_bike
3,3,3,17536705,00:53:10,01:05:37,2302,747.0,125,Rush St & Hubbard St,364,...,-87.626293,15.0,533.0,Chicago,41.900219,-87.642985,15.0,527.0,Chicago,classic_bike
4,4,4,17536706,00:53:37,00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,...,-87.661535,15.0,135.0,Chicago,41.857901,-87.668745,15.0,88.0,Chicago,classic_bike

In [7]:
merged2018_2019.drop(['Unnamed: 0', 'index'], axis=1, inplace=True)

In [8]:
merged2018_2019.rename(columns={'dpcapacity_x':'from_dpcapacity', 'dpcapacity_y':'to_dpcapacity'}, inplace=True)

In [9]:
merged2020_2022 = pd.read_csv('merged2020_2022.csv')

In [10]:
merged2020_2022.head()

,Unnamed: 0,trip_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,...,usertype,start_date,end_date,end_dpcapacity,from_landmark,from_city,start_dpcapacity,to_landmark,to_city,tripduration
0,0,EACB19130B0CDA4A,docked_bike,20:06:59,20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.9665,...,member,2020-01-21,2020-01-21,15,112.0,Chicago,11,239.0,Chicago,451
1,1,8FED874C809DC021,docked_bike,14:22:39,14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.9616,...,member,2020-01-30,2020-01-30,19,316.0,Chicago,15,321.0,Chicago,223
2,2,789F3C21E472CA96,docked_bike,19:29:26,19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.9401,...,member,2020-01-09,2020-01-09,15,277.0,Chicago,23,69.0,Chicago,171
3,3,C9A388DAC6ABF313,docked_bike,16:17:07,16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.8846,...,member,2020-01-06,2020-01-06,31,5.0,Chicago,15,262.0,Chicago,529
4,4,943BC3CBECCFD662,docked_bike,08:37:16,08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.8856,...,member,2020-01-30,2020-01-30,19,21.0,Chicago,19,264.0,Chicago,332

In [11]:
merged2020_2022.drop('Unnamed: 0', axis=1, inplace=True)

In [12]:
sorted(set(list(merged2013_2017.columns))) == sorted(set(list(merged2018_2019.columns)))

False

In [13]:
list_1 = sorted(set(list(merged2020_2022.columns)))
list_2 = sorted(set(list(merged2013_2017.columns)))

[item for item in list_2 if item not in list_1]

['Unnamed: 0.2',
 'bikeid',
 'birthyear',
 'from_dpcapacity',
 'from_lat',
 'from_long',
 'gender',
 'to_dpcapacity',
 'to_lat',
 'to_long',
 'to_station_id']

In [14]:
merged2013_2017.rename(columns = {'to_station_id':'end_station_id', 'from_station_id':'start_station_id',
                                  'from_dpcapacity':'start_dpcapacity', 'to_dpcapacity':'end_dpcapacity', 
                                  'from_lat':'start_lat', 'from_long':'start_lng', 'to_lat':'end_lat', 
                                  'to_long':'end_lng'}, inplace=True)                                                 
merged2018_2019.rename(columns = {'to_station_id':'end_station_id', 'from_station_id':'start_station_id',
                                  'from_dpcapacity':'start_dpcapacity', 'to_dpcapacity':'end_dpcapacity',
                                  'from_lat':'start_lat', 'from_long':'start_lng', 'to_lat':'end_lat', 
                                  'to_long':'end_lng'}, inplace=True)
merged2020_2022.rename(columns = {'from_station_id':'start_station_id'}, inplace=True)

In [15]:
merged2013_2017.rename(columns={'from_station_name':'start_station_name', 'to_station_name':'end_station_name',
                                'from_city':'start_city', 'to_city':'end_city', 'from_landmark':'start_landmark',
                                'to_landmark':'end_landmark'}, inplace=True)
merged2018_2019.rename(columns={'from_station_name':'start_station_name', 'to_station_name':'end_station_name',
                                'from_city':'start_city', 'to_city':'end_city', 'from_landmark':'start_landmark',
                                'to_landmark':'end_landmark'}, inplace=True)
merged2020_2022.rename(columns={'from_station_name':'start_station_name', 'to_station_name':'end_station_name',
                                'from_city':'start_city', 'to_city':'end_city', 'from_landmark':'start_landmark',
                                'to_landmark':'end_landmark'}, inplace=True)

In [16]:
list_1 = sorted(set(list(merged2020_2022.columns)))
list_2 = sorted(set(list(merged2013_2017.columns)))

[item for item in list_2 if item not in list_1]

['Unnamed: 0.2', 'bikeid', 'birthyear', 'gender']

In [17]:
# dropping bikeid because it is not present in 2020-2022
merged2013_2017.drop('bikeid', axis=1, inplace=True)
merged2018_2019.drop('bikeid', axis=1, inplace=True)

In [18]:
list_1 = sorted(set(list(merged2020_2022.columns)))
list_2 = sorted(set(list(merged2013_2017.columns)))

[item for item in list_2 if item not in list_1]

['Unnamed: 0.2', 'birthyear', 'gender']

In [19]:
merged2020_2022.shape[0]

11942201

In [20]:
# birthyear and gender will be added to merged2020_2022, however it will simply
# be added in a way that makes it easy to figure out that the values are
# basically invalids
merged2020_2022['birthyear'] = [0] * merged2020_2022.shape[0]
merged2020_2022['gender'] = [-1] * merged2020_2022.shape[0]

In [21]:
list_1 = sorted(set(list(merged2020_2022.columns)))
list_2 = sorted(set(list(merged2013_2017.columns)))

[item for item in list_2 if item not in list_1]

['Unnamed: 0.2']

In [22]:
merged2013_2022 = pd.concat([merged2013_2017, merged2018_2019, merged2020_2022])

In [23]:
del(merged2013_2017)
del(merged2018_2019)
del(merged2020_2022)

In [24]:
merged2013_2022.to_csv('backup_merged2013_2022_incase_from_1FullDivvyDataframept1unifinished')

In [25]:
merged2013_2022.head()

,trip_id,start_time,end_time,tripduration,start_station_id,start_station_name,end_station_id,end_station_name,usertype,gender,...,Unnamed: 0.2,rideable_type,start_city,start_landmark,end_city,end_landmark,start_date,end_date,start_dpcapacity,end_dpcapacity
0,9651,00:00,00:09,487,34,Cannon Dr & Fullerton Ave,67,Sheffield Ave & Fullerton Ave,casual,0,...,0.0,classic_bike,Chicago,124.0,Chicago,60.0,2013-06-30,2013-06-30,15.0,15.0
1,19385,00:00,00:06,359,20,Sheffield Ave & Kingsbury St,60,Dayton St & North Ave,member,Male,...,0.0,classic_bike,Chicago,154.0,Chicago,58.0,2013-07-03,2013-07-03,15.0,19.0
2,29952,00:00,00:27,1623,59,Wabash Ave & Roosevelt Rd,97,Museum Campus,casual,0,...,0.0,classic_bike,Chicago,31.0,Chicago,29.0,2013-07-06,2013-07-06,19.0,19.0
3,37222,00:00,00:44,2639,76,Lake Shore Dr & Monroe St,76,Lake Shore Dr & Monroe St,casual,0,...,0.0,classic_bike,Chicago,300.0,Chicago,300.0,2013-07-08,2013-07-08,11.0,11.0
4,59638,00:00,00:25,1479,27,Larrabee St & North Ave,24,Fairbanks Ct & Grand Ave,casual,0,...,0.0,classic_bike,Chicago,174.0,Chicago,262.0,2013-07-14,2013-07-14,19.0,15.0

In [26]:
merged2013_2022.drop(['Unnamed: 0.2'], axis=1, inplace=True)

In [27]:
merged2013_2022.sort_values(by=['start_date', 'start_time'], inplace=True)

In [28]:
merged2013_2022.head(60)

,trip_id,start_time,end_time,tripduration,start_station_id,start_station_name,end_station_id,end_station_name,usertype,gender,...,end_lng,rideable_type,start_city,start_landmark,end_city,end_landmark,start_date,end_date,start_dpcapacity,end_dpcapacity
46240,3940,01:06,09:46,31177,91,Clinton St & Washington Blvd,48,Larrabee St & Kingsbury St,member,Male,...,-87.642884,classic_bike,Chicago,10.0,Chicago,12.0,2013-06-27,2013-06-27,31.0,27.0
2032644,4113,11:09,11:11,140,88,May St & Randolph St,88,May St & Randolph St,member,Male,...,-87.655688,classic_bike,Chicago,155.0,Chicago,155.0,2013-06-27,2013-06-27,15.0,15.0
2064015,4119,11:12,11:13,87,88,May St & Randolph St,88,May St & Randolph St,member,Male,...,-87.655688,classic_bike,Chicago,155.0,Chicago,155.0,2013-06-27,2013-06-27,15.0,15.0
2195196,4134,11:24,14:38,11674,17,Wood St & Division St,61,Wood St & Milwaukee Ave,member,Male,...,-87.672552,classic_bike,Chicago,246.0,Chicago,221.0,2013-06-27,2013-06-27,15.0,15.0
2373269,4162,11:39,16:01,15758,88,May St & Randolph St,34,Cannon Dr & Fullerton Ave,member,Male,...,-87.634429,classic_bike,Chicago,155.0,Chicago,124.0,2013-06-27,2013-06-27,15.0,15.0
2733131,4095,12:06,12:11,301,85,Michigan Ave & Oak St,85,Michigan Ave & Oak St,member,Male,...,-87.623777,classic_bike,Chicago,42.0,Chicago,42.0,2013-06-27,2013-06-27,15.0,15.0
2802172,4118,12:11,12:16,316,85,Michigan Ave & Oak St,28,Larrabee St & Menomonee St,casual,0,...,-87.643320,classic_bike,Chicago,42.0,Chicago,282.0,2013-06-27,2013-06-27,15.0,15.0
2857028,4192,12:15,12:16,60,28,Larrabee St & Menomonee St,28,Larrabee St & Menomonee St,member,Male,...,-87.643320,classic_bike,Chicago,282.0,Chicago,282.0,2013-06-27,2013-06-27,15.0,15.0
3477277,4216,13:00,13:03,171,45,Michigan Ave & Congress Pkwy,90,Millennium Park,member,Male,...,-87.624084,classic_bike,Chicago,40.0,Chicago,8.0,2013-06-27,2013-06-27,15.0,35.0
3732005,4255,13:18,19:34,22549,45,Michigan Ave & Congress Pkwy,54,Ogden Ave & Chicago Ave,member,Male,...,-87.654061,classic_bike,Chicago,40.0,Chicago,44.0,2013-06-27,2013-06-27,15.0,19.0
4854214,4263,14:39,14:40,62,61,Wood St & Milwaukee Ave,300,Broadway & Barry Ave,member,Male,...,-87.644094,classic_bike,Chicago,221.0,Chicago,137.0,2013-06-27,2013-06-27,15.0,15.0
4922947,4275,14:44,14:45,64,32,Racine Ave & Congress Pkwy,32,Racine Ave & Congress Pkwy,casual,0,...,-87.657030,classic_bike,Chicago,76.0,Chicago,76.0,2013-06-27,2013-06-27,19.0,19.0
5089662,4288,14:56,14:57,66,68,Clinton St & Tilden St,68,Clinton St & Tilden St,member,Male,...,-87.640795,classic_bike,Chicago,37.0,Chicago,37.0,2013-06-27,2013-06-27,23.0,23.0
5103794,4289,14:57,15:05,487,32,Racine Ave & Congress Pkwy,349,Halsted St & Wrightwood Ave,member,Female,...,-87.649077,classic_bike,Chicago,76.0,Chicago,210.0,2013-06-27,2013-06-27,19.0,15.0
5117796,4291,14:58,15:05,433,32,Racine Ave & Congress Pkwy,19,Loomis St & Taylor St,casual,0,...,-87.660996,classic_bike,Chicago,76.0,Chicago,139.0,2013-06-27,2013-06-27,19.0,15.0
5232487,4316,15:06,15:09,123,19,Loomis St & Taylor St,19,Loomis St & Taylor St,casual,0,...,-87.660996,classic_bike,Chicago,139.0,Chicago,139.0,2013-06-27,2013-06-27,15.0,15.0
5277214,4343,15:09,15:14,272,68,Clinton St & Tilden St,68,Clinton St & Tilden St,member,Male,...,-87.640795,classic_bike,Chicago,37.0,Chicago,37.0,2013-06-27,2013-06-27,23.0,23.0
5336826,4342,15:13,15:27,852,19,Loomis St & Taylor St,55,Halsted St & James M Rochford St,casual,0,...,-87.646611,classic_bike,Chicago,139.0,Chicago,166.0,2013-06-27,2013-06-27,15.0,15.0
5351363,4346,15:14,00:18,32646,61,Wood St & Milwaukee Ave,91,Clinton St & Washington Blvd,member,Male,...,-87.641170,classic_bike,Chicago,221.0,Chicago,10.0,2013-06-27,2013-06-28,15.0,31.0
5366056,4350,15:15,15:27,730,349,Halsted St & Wrightwood Ave,55,Halsted St & James M Rochford St,member,Female,...,-87.646611,classic_bike,Chicago,210.0,Chicago,166.0,2013-06-27,2013-06-27,15.0,15.0
5981445,4378,15:54,23:15,26479,320,Loomis St & Lexington St,27,Larrabee St & North Ave,member,Male,...,-87.643500,classic_bike,Chicago,332.0,Chicago,174.0,2013-06-27,2013-06-27,15.0,19.0
6338702,4345,16:14,16:15,83,34,Cannon Dr & Fullerton Ave,311,Lincoln Ave & Eastwood Ave,member,Male,...,-87.686510,classic_bike,Chicago,124.0,Chicago,237.0,2013-06-27,2013-06-27,15.0,15.0
6739224,4389,16:34,16:36,127,42,Wabash Ave & Cermak Rd,42,Wabash Ave & Cermak Rd,member,Female,...,-87.625337,classic_bike,Chicago,170.0,Chicago,170.0,2013-06-27,2013-06-27,15.0,15.0
6901728,4390,16:41,16:50,528,42,Wabash Ave & Cermak Rd,42,Wabash Ave & Cermak Rd,member,Female,...,-87.625337,classic_bike,Chicago,170.0,Chicago,170.0,2013-06-27,2013-06-27,15.0,15.0
6924312,4384,16:42,22:23,20457,55,Halsted St & James M Rochford St,31,Franklin St & Chicago Ave,member,Female,...,-87.635638,classic_bike,Chicago,166.0,Chicago,17.0,2013-06-27,2013-06-27,15.0,23.0
9412934,4415,18:21,18:37,973,36,Franklin St & Jackson Blvd,36,Franklin St & Jackson Blvd,member,Male,...,-87.635321,classic_bike,Chicago,19.0,Chicago,19.0,2013-06-27,2013-06-27,27.0,27.0
9620216,4427,18:32,18:37,308,81,Daley Center Plaza,81,Daley Center Plaza,member,Male,...,-87.630183,classic_bike,Chicago,23.0,Chicago,23.0,2013-06-27,2013-06-27,47.0,47.0
9726255,4476,18:38,19:35,3401,81,Daley Center Plaza,67,Sheffield Ave & Fullerton Ave,member,Male,...,-87.653708,classic_bike,Chicago,23.0,Chicago,60.0,2013-06-27,2013-06-27,47.0,15.0
9845135,4490,18:45,19:03,1094,37,Dearborn St & Adams St,76,Lake Shore Dr & Monroe St,casual,0,...,-87.616970,classic_bike,Chicago,20.0,Chicago,300.0,2013-06-27,2013-06-27,19.0,11.0
9893780,4495,18:48,18:54,408,81,Daley Center Plaza,37,Dearborn St & Adams St,member,Male,...,-87.629791,classic_bike,Chicago,23.0,Chicago,20.0,2013-06-27,2013-06-27,47.0,19.0
9957834,4500,18:52,20:49,7031,37,Dearborn St & Adams St,45,Michigan Ave & Congress Pkwy,member,Female,...,-87.624433,classic_bike,Chicago,20.0,Chicago,40.0,2013-06-27,2013-06-27,19.0,15.0
9973592,4513,18:53,19:06,781,81,Daley Center Plaza,75,Canal St & Jackson Blvd,member,Male,...,-87.639971,classic_bike,Chicago,23.0,Chicago,138.0,2013-06-27,2013-06-27,47.0,35.0
10034727,4516,18:57,18:59,122,44,State St & Randolph St,44,State St & Randolph St,member,Male,...,-87.627734,classic_bike,Chicago,2.0,Chicago,2.0,2013-06-27,2013-06-27,27.0,27.0
10079424,4518,19:00,19:10,607,81,Daley Center Plaza,251,Clarendon Ave & Leland Ave,member,Male,...,-87.650001,classic_bike,Chicago,23.0,Chicago,385.0,2013-06-27,2013-06-27,47.0,15.0
10365433,4564,19:20,19:44,1424,94,Lincoln Ave & Armitage Ave,94,Lincoln Ave & Armitage Ave,member,Female,...,-87.638116,classic_bike,Chicago,146.0,Chicago,146.0,2013-06-27,2013-06-27,19.0,19.0
10405345,4572,19:23,19:44,1280,340,Clark St & Wrightwood Ave,94,Lincoln Ave & Armitage Ave,member,Male,...,-87.638116,classic_bike,Chicago,209.0,Chicago,146.0,2013-06-27,2013-06-27,15.0,19.0
10481945,4586,19:29,19:37,493,76,Lake Shore Dr & Monroe St,90,Millennium Park,member,Male,...,-87.624084,classic_bike,Chicago,300.0,Chicago,8.0,2013-06-27,2013-06-27,11.0,35.0
10481946,4587,19:29,19:38,506,76,Lake Shore Dr & Monroe St,90,Millennium Park,member,Male,...,-87.624084,classic_bike,Chicago,300.0,Chicago,8.0,2013-06-27,2013-06-27,11.0,35.0
10481947,4589,19:29,19:38,495,76,Lake Shore Dr & Monroe St,90,Millennium Park,member,Female,...,-87.624084,classic_bike,Chicago,300.0,Chicago,8.0,2013-06-27,2013-06-27,11.0,35.0
10481948,4588,19:29,19:38,506,76,Lake Shore Dr & Monroe St,190,Southport Ave & Wrightwood Ave,member,Female,...,-87.663170,classic_bike,Chicago,300.0,Chicago,298.0,2013-06-27,2013-06-27,11.0,15.0
10542586,4592,19:34,19:51,1020,90,Millennium Park,75,Canal St & Jackson Blvd,casual,0,...,-87.639971,classic_bike,Chicago,8.0,Chicago,138.0,2013-06-27,2013-06-27,35.0,35.0
10601248,4597,19:39,20:04,1489,81,Daley Center Plaza,67,Sheffield Ave & Fullerton Ave,member,Male,...,-87.653708,classic_bike,Chicago,23.0,Chicago,60.0,2013-06-27,2013-06-27,47.0,15.0
10612721,4480,19:40,22:28,10105,340,Clark St & Wrightwood Ave,46,Wells St & Walton St,casual,0,...,-87.634430,classic_bike,Chicago,209.0,Chicago,46.0,2013-06-27,2013-06-27,15.0,19.0
10635661,4598,19:42,20:05,1394,52,Michigan Ave & Lake St,59,Wabash Ave & Roosevelt Rd,member,Male,...,-87.625955,classic_bike,Chicago,43.0,Chicago,31.0,2013-06-27,2013-06-27,23.0,19.0
10669302,4602,19:45,20:42,3419,37,Dearborn St & Adams St,37,Dearborn St & Adams St,casual,0,...,-87.629791,classic_bike,Chicago,20.0,Chicago,20.0,2013-06-27,2013-06-27,19.0,19.0
10680253,4607,19:46,19:57,653,51,Clark St & Randolph St,340,Clark St & Wrightwood Ave,casual,0,...,-87.643118,classic_bike,Chicago,5.0,Chicago,209.0,2013-06-27,2013-06-27,31.0,15.0
10691273,4609,19:47,20:16,1764,90,Millennium Park,54,Ogden Ave & Chicago Ave,member,Male,...,-87.654061,classic_bike,Chicago,8.0,Chicago,44.0,2013-06-27,2013-06-27,35.0,19.0
10691274,4613,19:47,20:16,1736,90,Millennium Park,54,Ogden Ave & Chicago Ave,member,Male,...,-87.654061,classic_bike,Chicago,8.0,Chicago,44.0,2013-06-27,2013-06-27,35.0,19.0
10691275,4612,19:47,20:16,1766,90,Millennium Park,54,Ogden Ave & Chicago Ave,member,Female,...,-87.654061,classic_bike,Chicago,8.0,Chicago,44.0,2013-06-27,2013-06-27,35.0,19.0
10691276,4611,19:47,20:16,1768,190,Southport Ave & Wrightwood Ave,54,Ogden Ave & Chicago Ave,member,Female,...,-87.654061,classic_bike,Chicago,298.0,Chicago,44.0,2013-06-27,2013-06-27,15.0,19.0
10723626,4617,19:50,20:19,1738,44,State St & Randolph St,44,State St & Randolph St,casual,0,...,-87.627734,classic_bike,Chicago,2.0,Chicago,2.0,2013-06-27,2013-06-27,27.0,27.0
10745114,4619,19:52,20:50,3482,24,Fairbanks Ct & Grand Ave,24,Fairbanks Ct & Grand Ave,casual,0,...,-87.620620,classic_bike,Chicago,262.0,Chicago,262.0,2013-06-27,2013-06-27,15.0,15.0
10745115,4620,19:52,20:05,776,61,Wood St & Milwaukee Ave,61,Wood St & Milwaukee Ave,member,Male,...,-87.672552,classic_bike,Chicago,221.0,Chicago,221.0,2013-06-27,2013-06-27,15.0,15.0
10933506,4623,20:07,20:13,383,17,Wood St & Division St,17,Wood St & Division St,member,Male,...,-87.672730,classic_bike,Chicago,246.0,Chicago,246.0,2013-06-27,2013-06-27,15.0,15.0
11064787,4641,20:21,20:34,795,54,Ogden Ave & Chicago Ave,17,Wood St & Division St,member,Female,...,-87.672730,classic_bike,Chicago,44.0,Chicago,246.0,2013-06-27,2013-06-27,19.0,15.0
11073702,4642,20:22,20:34,759,54,Ogden Ave & Chicago Ave,17,Wood St & Division St,member,Male,...,-87.672730,classic_bike,Chicago,44.0,Chicago,246.0,2013-06-27,2013-06-27,19.0,15.0
11073703,4643,20:22,20:34,735,54,Ogden Ave & Chicago Ave,17,Wood St & Division St,member,Male,...,-87.672730,classic_bike,Chicago,44.0,Chicago,246.0,2013-06-27,2013-06-27,19.0,15.0
11073704,4645,20:22,20:34,736,54,Ogden Ave & Chicago Ave,17,Wood St & Division St,member,Female,...,-87.672730,classic_bike,Chicago,44.0,Chicago,246.0,2013-06-27,2013-06-27,19.0,15.0
11073705,4644,20:22,20:50,1712,20,Sheffield Ave & Kingsbury St,46,Wells St & Walton St,casual,0,...,-87.634430,classic_bike,Chicago,154.0,Chicago,46.0,2013-06-27,2013-06-27,15.0,19.0
11073706,4646,20:22,20:39,996,52,Michigan Ave & Lake St,52,Michigan Ave & Lake St,casual,0,...,-87.624289,classic_bike,Chicago,43.0,Chicago,43.0,2013-06-27,2013-06-27,23.0,23.0

In [29]:
merged2013_2022.reset_index(inplace=True)

In [30]:
merged2013_2022.head(60)

,index,trip_id,start_time,end_time,tripduration,start_station_id,start_station_name,end_station_id,end_station_name,usertype,...,end_lng,rideable_type,start_city,start_landmark,end_city,end_landmark,start_date,end_date,start_dpcapacity,end_dpcapacity
0,46240,3940,01:06,09:46,31177,91,Clinton St & Washington Blvd,48,Larrabee St & Kingsbury St,member,...,-87.642884,classic_bike,Chicago,10.0,Chicago,12.0,2013-06-27,2013-06-27,31.0,27.0
1,2032644,4113,11:09,11:11,140,88,May St & Randolph St,88,May St & Randolph St,member,...,-87.655688,classic_bike,Chicago,155.0,Chicago,155.0,2013-06-27,2013-06-27,15.0,15.0
2,2064015,4119,11:12,11:13,87,88,May St & Randolph St,88,May St & Randolph St,member,...,-87.655688,classic_bike,Chicago,155.0,Chicago,155.0,2013-06-27,2013-06-27,15.0,15.0
3,2195196,4134,11:24,14:38,11674,17,Wood St & Division St,61,Wood St & Milwaukee Ave,member,...,-87.672552,classic_bike,Chicago,246.0,Chicago,221.0,2013-06-27,2013-06-27,15.0,15.0
4,2373269,4162,11:39,16:01,15758,88,May St & Randolph St,34,Cannon Dr & Fullerton Ave,member,...,-87.634429,classic_bike,Chicago,155.0,Chicago,124.0,2013-06-27,2013-06-27,15.0,15.0
5,2733131,4095,12:06,12:11,301,85,Michigan Ave & Oak St,85,Michigan Ave & Oak St,member,...,-87.623777,classic_bike,Chicago,42.0,Chicago,42.0,2013-06-27,2013-06-27,15.0,15.0
6,2802172,4118,12:11,12:16,316,85,Michigan Ave & Oak St,28,Larrabee St & Menomonee St,casual,...,-87.643320,classic_bike,Chicago,42.0,Chicago,282.0,2013-06-27,2013-06-27,15.0,15.0
7,2857028,4192,12:15,12:16,60,28,Larrabee St & Menomonee St,28,Larrabee St & Menomonee St,member,...,-87.643320,classic_bike,Chicago,282.0,Chicago,282.0,2013-06-27,2013-06-27,15.0,15.0
8,3477277,4216,13:00,13:03,171,45,Michigan Ave & Congress Pkwy,90,Millennium Park,member,...,-87.624084,classic_bike,Chicago,40.0,Chicago,8.0,2013-06-27,2013-06-27,15.0,35.0
9,3732005,4255,13:18,19:34,22549,45,Michigan Ave & Congress Pkwy,54,Ogden Ave & Chicago Ave,member,...,-87.654061,classic_bike,Chicago,40.0,Chicago,44.0,2013-06-27,2013-06-27,15.0,19.0
10,4854214,4263,14:39,14:40,62,61,Wood St & Milwaukee Ave,300,Broadway & Barry Ave,member,...,-87.644094,classic_bike,Chicago,221.0,Chicago,137.0,2013-06-27,2013-06-27,15.0,15.0
11,4922947,4275,14:44,14:45,64,32,Racine Ave & Congress Pkwy,32,Racine Ave & Congress Pkwy,casual,...,-87.657030,classic_bike,Chicago,76.0,Chicago,76.0,2013-06-27,2013-06-27,19.0,19.0
12,5089662,4288,14:56,14:57,66,68,Clinton St & Tilden St,68,Clinton St & Tilden St,member,...,-87.640795,classic_bike,Chicago,37.0,Chicago,37.0,2013-06-27,2013-06-27,23.0,23.0
13,5103794,4289,14:57,15:05,487,32,Racine Ave & Congress Pkwy,349,Halsted St & Wrightwood Ave,member,...,-87.649077,classic_bike,Chicago,76.0,Chicago,210.0,2013-06-27,2013-06-27,19.0,15.0
14,5117796,4291,14:58,15:05,433,32,Racine Ave & Congress Pkwy,19,Loomis St & Taylor St,casual,...,-87.660996,classic_bike,Chicago,76.0,Chicago,139.0,2013-06-27,2013-06-27,19.0,15.0
15,5232487,4316,15:06,15:09,123,19,Loomis St & Taylor St,19,Loomis St & Taylor St,casual,...,-87.660996,classic_bike,Chicago,139.0,Chicago,139.0,2013-06-27,2013-06-27,15.0,15.0
16,5277214,4343,15:09,15:14,272,68,Clinton St & Tilden St,68,Clinton St & Tilden St,member,...,-87.640795,classic_bike,Chicago,37.0,Chicago,37.0,2013-06-27,2013-06-27,23.0,23.0
17,5336826,4342,15:13,15:27,852,19,Loomis St & Taylor St,55,Halsted St & James M Rochford St,casual,...,-87.646611,classic_bike,Chicago,139.0,Chicago,166.0,2013-06-27,2013-06-27,15.0,15.0
18,5351363,4346,15:14,00:18,32646,61,Wood St & Milwaukee Ave,91,Clinton St & Washington Blvd,member,...,-87.641170,classic_bike,Chicago,221.0,Chicago,10.0,2013-06-27,2013-06-28,15.0,31.0
19,5366056,4350,15:15,15:27,730,349,Halsted St & Wrightwood Ave,55,Halsted St & James M Rochford St,member,...,-87.646611,classic_bike,Chicago,210.0,Chicago,166.0,2013-06-27,2013-06-27,15.0,15.0
20,5981445,4378,15:54,23:15,26479,320,Loomis St & Lexington St,27,Larrabee St & North Ave,member,...,-87.643500,classic_bike,Chicago,332.0,Chicago,174.0,2013-06-27,2013-06-27,15.0,19.0
21,6338702,4345,16:14,16:15,83,34,Cannon Dr & Fullerton Ave,311,Lincoln Ave & Eastwood Ave,member,...,-87.686510,classic_bike,Chicago,124.0,Chicago,237.0,2013-06-27,2013-06-27,15.0,15.0
22,6739224,4389,16:34,16:36,127,42,Wabash Ave & Cermak Rd,42,Wabash Ave & Cermak Rd,member,...,-87.625337,classic_bike,Chicago,170.0,Chicago,170.0,2013-06-27,2013-06-27,15.0,15.0
23,6901728,4390,16:41,16:50,528,42,Wabash Ave & Cermak Rd,42,Wabash Ave & Cermak Rd,member,...,-87.625337,classic_bike,Chicago,170.0,Chicago,170.0,2013-06-27,2013-06-27,15.0,15.0
24,6924312,4384,16:42,22:23,20457,55,Halsted St & James M Rochford St,31,Franklin St & Chicago Ave,member,...,-87.635638,classic_bike,Chicago,166.0,Chicago,17.0,2013-06-27,2013-06-27,15.0,23.0
25,9412934,4415,18:21,18:37,973,36,Franklin St & Jackson Blvd,36,Franklin St & Jackson Blvd,member,...,-87.635321,classic_bike,Chicago,19.0,Chicago,19.0,2013-06-27,2013-06-27,27.0,27.0
26,9620216,4427,18:32,18:37,308,81,Daley Center Plaza,81,Daley Center Plaza,member,...,-87.630183,classic_bike,Chicago,23.0,Chicago,23.0,2013-06-27,2013-06-27,47.0,47.0
27,9726255,4476,18:38,19:35,3401,81,Daley Center Plaza,67,Sheffield Ave & Fullerton Ave,member,...,-87.653708,classic_bike,Chicago,23.0,Chicago,60.0,2013-06-27,2013-06-27,47.0,15.0
28,9845135,4490,18:45,19:03,1094,37,Dearborn St & Adams St,76,Lake Shore Dr & Monroe St,casual,...,-87.616970,classic_bike,Chicago,20.0,Chicago,300.0,2013-06-27,2013-06-27,19.0,11.0
29,9893780,4495,18:48,18:54,408,81,Daley Center Plaza,37,Dearborn St & Adams St,member,...,-87.629791,classic_bike,Chicago,23.0,Chicago,20.0,2013-06-27,2013-06-27,47.0,19.0
30,9957834,4500,18:52,20:49,7031,37,Dearborn St & Adams St,45,Michigan Ave & Congress Pkwy,member,...,-87.624433,classic_bike,Chicago,20.0,Chicago,40.0,2013-06-27,2013-06-27,19.0,15.0
31,9973592,4513,18:53,19:06,781,81,Daley Center Plaza,75,Canal St & Jackson Blvd,member,...,-87.639971,classic_bike,Chicago,23.0,Chicago,138.0,2013-06-27,2013-06-27,47.0,35.0
32,10034727,4516,18:57,18:59,122,44,State St & Randolph St,44,State St & Randolph St,member,...,-87.627734,classic_bike,Chicago,2.0,Chicago,2.0,2013-06-27,2013-06-27,27.0,27.0
33,10079424,4518,19:00,19:10,607,81,Daley Center Plaza,251,Clarendon Ave & Leland Ave,member,...,-87.650001,classic_bike,Chicago,23.0,Chicago,385.0,2013-06-27,2013-06-27,47.0,15.0
34,10365433,4564,19:20,19:44,1424,94,Lincoln Ave & Armitage Ave,94,Lincoln Ave & Armitage Ave,member,...,-87.638116,classic_bike,Chicago,146.0,Chicago,146.0,2013-06-27,2013-06-27,19.0,19.0
35,10405345,4572,19:23,19:44,1280,340,Clark St & Wrightwood Ave,94,Lincoln Ave & Armitage Ave,member,...,-87.638116,classic_bike,Chicago,209.0,Chicago,146.0,2013-06-27,2013-06-27,15.0,19.0
36,10481945,4586,19:29,19:37,493,76,Lake Shore Dr & Monroe St,90,Millennium Park,member,...,-87.624084,classic_bike,Chicago,300.0,Chicago,8.0,2013-06-27,2013-06-27,11.0,35.0
37,10481946,4587,19:29,19:38,506,76,Lake Shore Dr & Monroe St,90,Millennium Park,member,...,-87.624084,classic_bike,Chicago,300.0,Chicago,8.0,2013-06-27,2013-06-27,11.0,35.0
38,10481947,4589,19:29,19:38,495,76,Lake Shore Dr & Monroe St,90,Millennium Park,member,...,-87.624084,classic_bike,Chicago,300.0,Chicago,8.0,2013-06-27,2013-06-27,11.0,35.0
39,10481948,4588,19:29,19:38,506,76,Lake Shore Dr & Monroe St,190,Southport Ave & Wrightwood Ave,member,...,-87.663170,classic_bike,Chicago,300.0,Chicago,298.0,2013-06-27,2013-06-27,11.0,15.0
40,10542586,4592,19:34,19:51,1020,90,Millennium Park,75,Canal St & Jackson Blvd,casual,...,-87.639971,classic_bike,Chicago,8.0,Chicago,138.0,2013-06-27,2013-06-27,35.0,35.0
41,10601248,4597,19:39,20:04,1489,81,Daley Center Plaza,67,Sheffield Ave & Fullerton Ave,member,...,-87.653708,classic_bike,Chicago,23.0,Chicago,60.0,2013-06-27,2013-06-27,47.0,15.0
42,10612721,4480,19:40,22:28,10105,340,Clark St & Wrightwood Ave,46,Wells St & Walton St,casual,...,-87.634430,classic_bike,Chicago,209.0,Chicago,46.0,2013-06-27,2013-06-27,15.0,19.0
43,10635661,4598,19:42,20:05,1394,52,Michigan Ave & Lake St,59,Wabash Ave & Roosevelt Rd,member,...,-87.625955,classic_bike,Chicago,43.0,Chicago,31.0,2013-06-27,2013-06-27,23.0,19.0
44,10669302,4602,19:45,20:42,3419,37,Dearborn St & Adams St,37,Dearborn St & Adams St,casual,...,-87.629791,classic_bike,Chicago,20.0,Chicago,20.0,2013-06-27,2013-06-27,19.0,19.0
45,10680253,4607,19:46,19:57,653,51,Clark St & Randolph St,340,Clark St & Wrightwood Ave,casual,...,-87.643118,classic_bike,Chicago,5.0,Chicago,209.0,2013-06-27,2013-06-27,31.0,15.0
46,10691273,4609,19:47,20:16,1764,90,Millennium Park,54,Ogden Ave & Chicago Ave,member,...,-87.654061,classic_bike,Chicago,8.0,Chicago,44.0,2013-06-27,2013-06-27,35.0,19.0
47,10691274,4613,19:47,20:16,1736,90,Millennium Park,54,Ogden Ave & Chicago Ave,member,...,-87.654061,classic_bike,Chicago,8.0,Chicago,44.0,2013-06-27,2013-06-27,35.0,19.0
48,10691275,4612,19:47,20:16,1766,90,Millennium Park,54,Ogden Ave & Chicago Ave,member,...,-87.654061,classic_bike,Chicago,8.0,Chicago,44.0,2013-06-27,2013-06-27,35.0,19.0
49,10691276,4611,19:47,20:16,1768,190,Southport Ave & Wrightwood Ave,54,Ogden Ave & Chicago Ave,member,...,-87.654061,classic_bike,Chicago,298.0,Chicago,44.0,2013-06-27,2013-06-27,15.0,19.0
50,10723626,4617,19:50,20:19,1738,44,State St & Randolph St,44,State St & Randolph St,casual,...,-87.627734,classic_bike,Chicago,2.0,Chicago,2.0,2013-06-27,2013-06-27,27.0,27.0
51,10745114,4619,19:52,20:50,3482,24,Fairbanks Ct & Grand Ave,24,Fairbanks Ct & Grand Ave,casual,...,-87.620620,classic_bike,Chicago,262.0,Chicago,262.0,2013-06-27,2013-06-27,15.0,15.0
52,10745115,4620,19:52,20:05,776,61,Wood St & Milwaukee Ave,61,Wood St & Milwaukee Ave,member,...,-87.672552,classic_bike,Chicago,221.0,Chicago,221.0,2013-06-27,2013-06-27,15.0,15.0
53,10933506,4623,20:07,20:13,383,17,Wood St & Division St,17,Wood St & Division St,member,...,-87.672730,classic_bike,Chicago,246.0,Chicago,246.0,2013-06-27,2013-06-27,15.0,15.0
54,11064787,4641,20:21,20:34,795,54,Ogden Ave & Chicago Ave,17,Wood St & Division St,member,...,-87.672730,classic_bike,Chicago,44.0,Chicago,246.0,2013-06-27,2013-06-27,19.0,15.0
55,11073702,4642,20:22,20:34,759,54,Ogden Ave & Chicago Ave,17,Wood St & Division St,member,...,-87.672730,classic_bike,Chicago,44.0,Chicago,246.0,2013-06-27,2013-06-27,19.0,15.0
56,11073703,4643,20:22,20:34,735,54,Ogden Ave & Chicago Ave,17,Wood St & Division St,member,...,-87.672730,classic_bike,Chicago,44.0,Chicago,246.0,2013-06-27,2013-06-27,19.0,15.0
57,11073704,4645,20:22,20:34,736,54,Ogden Ave & Chicago Ave,17,Wood St & Division St,member,...,-87.672730,classic_bike,Chicago,44.0,Chicago,246.0,2013-06-27,2013-06-27,19.0,15.0
58,11073705,4644,20:22,20:50,1712,20,Sheffield Ave & Kingsbury St,46,Wells St & Walton St,casual,...,-87.634430,classic_bike,Chicago,154.0,Chicago,46.0,2013-06-27,2013-06-27,15.0,19.0
59,11073706,4646,20:22,20:39,996,52,Michigan Ave & Lake St,52,Michigan Ave & Lake St,casual,...,-87.624289,classic_bike,Chicago,43.0,Chicago,43.0,2013-06-27,2013-06-27,23.0,23.0

In [31]:
# Now I will bring functions from previous seperate cleanings in, to filter out improper data and time values. Once we are done
# filtering out all of the invalid dates, we can filter out invalid times

def leap_year_check(year):
    if year % 4 == 0:
        
        if year % 100 != 0:
            if year % 400 == 0:
                return True
        else:
            return False
        
        return True
    
    else:
        return False
        


# this function takes start and end date combinations and checks if they are valid. It returns the index position of all invalid
# date combinations so that they can be dropped.
def date_checker(test_start_dates=[],test_end_dates=[]):
    
    month_max_days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    date_invalid_check = []
    
    for i in range(len(test_start_dates)):
    
        start_d_test = test_start_dates[i].split('-')
        end_d_test = test_end_dates[i].split('-')
        
        # These are our years
        st_year = int(start_d_test[0])
        ed_year = int(end_d_test[0])
        
        # These are our months
        st_month = int(start_d_test[1])
        ed_month = int(end_d_test[1])

        # These are our days
        st_day = int(start_d_test[2])
        ed_day = int(end_d_test[2])
        
        # if the years of the dates are not the same        
        
        if st_year + 1 == ed_year and st_month == 12 and ed_month == 1 and ed_day == 1: 
                #print('Start Month end to Next month beginning: ', i)
                month_max = month_max_days[st_month - 1]

                # accounting for february leap years
                if leap_year_check(st_year) and st_month == 2:
                    #print('February: ', i)
                    month_max = 29
                
                # if our st_day is not the last day of the respective st_month, the date is invalid
                if st_day - month_max != 0:
                    #print('Start Month not ended yet, or day does not exist: ', i)
                    date_invalid_check.append(i)
        
        elif st_year != ed_year:
            #print('Year: ', i)
            date_invalid_check.append(i)

        # If st_month is after ed_month
        elif st_month > ed_month:
            #print(st_month == ed_month)
            #print('Start Month occurs after end month: ', i)
            date_invalid_check.append(i)
        
        # if st_month is more than 1 month before ed_month
        elif ed_month - st_month > 1:    
            #print(st_month == ed_month)
            #print('Start Month is too far from end month: ', i)
            date_invalid_check.append(i)
        
        elif ed_month == st_month + 1 and ed_day != 1:
            date_invalid_check.append(i)
        
        # If the ed_day is more than one day after the st_day, this works regardless of month
        elif ed_day - st_day > 1:
            #print('Day: ', i)
            date_invalid_check.append(i)
        
        # if ed_day - st_day is negative, we have to examine why, because we don't want to delete all overnight ride rentals
        # just because the person rented at the very end of the month
        elif ed_day - st_day < 0:
            #print('Day difference Negative: ', i)
            
            # if the month is the same, this chronological difference make no sense
            if ed_month == st_month:
                #print('Month is same: ', i)
                date_invalid_check.append(i)
            
            # if the st_month is the month before ed_month and it is the first day of ed_month
            elif ed_month == st_month + 1 and ed_day == 1:
                #print('Start Month end to Next month beginning: ', i)
                month_max = month_max_days[st_month - 1]

                # accounting for february leap years
                if leap_year_check(st_year) and st_month == 2:
                    #print('February: ', i)
                    month_max = 29
                
                # if our st_day is not the last day of the respective st_month, the date is invalid
                if st_day - month_max != 0:
                    #print('Start Month not ended yet, or day does not exist: ', i)
                    date_invalid_check.append(i)

    return date_invalid_check


drop_these_rows = date_checker(merged2013_2022['start_date'].values, merged2013_2022['end_date'].values)

In [32]:
len(drop_these_rows)

2194

In [33]:
merged2013_2022.loc[drop_these_rows]

,index,trip_id,start_time,end_time,tripduration,start_station_id,start_station_name,end_station_id,end_station_name,usertype,...,end_lng,rideable_type,start_city,start_landmark,end_city,end_landmark,start_date,end_date,start_dpcapacity,end_dpcapacity
13820678,9,17536711,01:07:54,10:04:02,"464,168.0",99,Lake Shore Dr & Ohio St,99,Lake Shore Dr & Ohio St,casual,...,-87.614492,classic_bike,Chicago,337.0,Chicago,337.0,2018-01-01,2018-01-06,19.0,19.0
13830902,10233,17550955,23:29:38,14:29:05,"399,567.0",125,Rush St & Hubbard St,133,Kingsbury St & Kinzie St,casual,...,-87.638506,classic_bike,Chicago,533.0,Chicago,532.0,2018-01-06,2018-01-11,15.0,27.0
13834182,13514,17555348,15:18:27,20:58:25,"193,198.0",471,Francisco Ave & Foster Ave,471,Francisco Ave & Foster Ave,member,...,-87.701419,classic_bike,Chicago,613.0,Chicago,613.0,2018-01-08,2018-01-10,15.0,15.0
13841011,20342,17563555,18:18:46,09:53:44,"574,498.0",53,Wells St & Huron St,88,Racine Ave & Randolph St,member,...,-87.655688,classic_bike,Chicago,64.0,Chicago,155.0,2018-01-09,2018-01-16,19.0,15.0
13856145,35476,17581977,01:35:05,19:16:20,"236,475.0",24,Fairbanks Ct & Grand Ave,365,Halsted St & North Branch St,casual,...,-87.648480,classic_bike,Chicago,262.0,Chicago,528.0,2018-01-14,2018-01-16,15.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21204799,7384131,25953956,11:48:34,14:50:36,"183,721.0",110,Dearborn St & Erie St,110,Dearborn St & Erie St,casual,...,-87.628623,classic_bike,Chicago,45.0,Chicago,45.0,2019-12-29,2019-12-31,23.0,23.0
21206413,7385743,25955666,15:32:46,12:21:38,"334,131.0",349,Halsted St & Wrightwood Ave,349,Halsted St & Wrightwood Ave,casual,...,-87.649077,classic_bike,Chicago,210.0,Chicago,210.0,2019-12-29,2020-01-02,15.0,15.0
21211610,7390942,25961153,10:02:20,18:33:31,"203,471.0",628,Walsh Park,17,Honore St & Division St,member,...,-87.672730,classic_bike,Chicago,0.0,Chicago,246.0,2019-12-31,2020-01-02,24.0,15.0
21212326,7391657,25961900,14:56:05,11:59:00,"162,175.0",110,Dearborn St & Erie St,110,Dearborn St & Erie St,casual,...,-87.628623,classic_bike,Chicago,45.0,Chicago,45.0,2019-12-31,2020-01-02,23.0,23.0
21212327,7391658,25961901,14:56:20,11:58:36,"162,136.0",110,Dearborn St & Erie St,110,Dearborn St & Erie St,casual,...,-87.628623,classic_bike,Chicago,45.0,Chicago,45.0,2019-12-31,2020-01-02,23.0,23.0

In [34]:
merged2013_2022.drop(drop_these_rows, inplace=True)

In [35]:
merged2013_2022.dtypes

index                   int64
trip_id                object
start_time             object
end_time               object
tripduration           object
start_station_id       object
start_station_name     object
end_station_id         object
end_station_name       object
usertype               object
gender                 object
birthyear             float64
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
rideable_type          object
start_city             object
start_landmark        float64
end_city               object
end_landmark          float64
start_date             object
end_date               object
start_dpcapacity      float64
end_dpcapacity        float64
dtype: object

In [36]:
# If this is true, we don't have to drop on subset = 'trip_id'
len(set(merged2013_2022['trip_id'].values)) == len(merged2013_2022['trip_id'].values)

True

In [37]:
# don't need 'trip_id' anymore, as it was used to remove duplicates
merged2013_2022.drop('trip_id', axis=1, inplace=True)

In [38]:
merged2013_2022.reset_index(inplace=True)

In [39]:
merged2013_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33153270 entries, 0 to 33153269
Data columns (total 25 columns):
 #   Column              Dtype
---  ------              -----
 0   level_0             int64
 1   index               int64
 2   start_time          object
 3   end_time            object
 4   tripduration        object
 5   start_station_id    object
 6   start_station_name  object
 7   end_station_id      object
 8   end_station_name    object
 9   usertype            object
 10  gender              object
 11  birthyear           float64
 12  start_lat           float64
 13  start_lng           float64
 14  end_lat             float64
 15  end_lng             float64
 16  rideable_type       object
 17  start_city          object
 18  start_landmark      float64
 19  end_city            object
 20  end_landmark        float64
 21  start_date          object
 22  end_date            object
 23  start_dpcapacity    float64
 24  end_dpcapacity      float64
dtypes: float64(9), int64(2), object(14)
memory usage: 6.2+ GB

In [40]:
merged2013_2022.head()

,level_0,index,start_time,end_time,tripduration,start_station_id,start_station_name,end_station_id,end_station_name,usertype,...,end_lng,rideable_type,start_city,start_landmark,end_city,end_landmark,start_date,end_date,start_dpcapacity,end_dpcapacity
0,0,46240,01:06,09:46,31177,91,Clinton St & Washington Blvd,48,Larrabee St & Kingsbury St,member,...,-87.642884,classic_bike,Chicago,10.0,Chicago,12.0,2013-06-27,2013-06-27,31.0,27.0
1,1,2032644,11:09,11:11,140,88,May St & Randolph St,88,May St & Randolph St,member,...,-87.655688,classic_bike,Chicago,155.0,Chicago,155.0,2013-06-27,2013-06-27,15.0,15.0
2,2,2064015,11:12,11:13,87,88,May St & Randolph St,88,May St & Randolph St,member,...,-87.655688,classic_bike,Chicago,155.0,Chicago,155.0,2013-06-27,2013-06-27,15.0,15.0
3,3,2195196,11:24,14:38,11674,17,Wood St & Division St,61,Wood St & Milwaukee Ave,member,...,-87.672552,classic_bike,Chicago,246.0,Chicago,221.0,2013-06-27,2013-06-27,15.0,15.0
4,4,2373269,11:39,16:01,15758,88,May St & Randolph St,34,Cannon Dr & Fullerton Ave,member,...,-87.634429,classic_bike,Chicago,155.0,Chicago,124.0,2013-06-27,2013-06-27,15.0,15.0

In [41]:
merged2013_2022.columns

Index(['level_0', 'index', 'start_time', 'end_time', 'tripduration',
       'start_station_id', 'start_station_name', 'end_station_id',
       'end_station_name', 'usertype', 'gender', 'birthyear', 'start_lat',
       'start_lng', 'end_lat', 'end_lng', 'rideable_type', 'start_city',
       'start_landmark', 'end_city', 'end_landmark', 'start_date', 'end_date',
       'start_dpcapacity', 'end_dpcapacity'],
      dtype='object')

In [42]:
merged2013_2022.drop(['level_0', 'index'], axis=1, inplace=True)

In [43]:
# Changing start/end city to int values

merged2013_2022.loc[merged2013_2022['start_city'] == 'Chicago', 'start_city'] = 0
merged2013_2022.loc[merged2013_2022['start_city'] == 'Evanston', 'start_city'] = 1
merged2013_2022.loc[merged2013_2022['start_city'] == 'Oak Park', 'start_city'] = 2

merged2013_2022.loc[merged2013_2022['end_city'] == 'Chicago', 'end_city'] = 0
merged2013_2022.loc[merged2013_2022['end_city'] == 'Evanston', 'end_city'] = 1
merged2013_2022.loc[merged2013_2022['end_city'] == 'Oak Park', 'end_city'] = 2

In [44]:
merged2013_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33153270 entries, 0 to 33153269
Data columns (total 23 columns):
 #   Column              Dtype
---  ------              -----
 0   start_time          object
 1   end_time            object
 2   tripduration        object
 3   start_station_id    object
 4   start_station_name  object
 5   end_station_id      object
 6   end_station_name    object
 7   usertype            object
 8   gender              object
 9   birthyear           float64
 10  start_lat           float64
 11  start_lng           float64
 12  end_lat             float64
 13  end_lng             float64
 14  rideable_type       object
 15  start_city          object
 16  start_landmark      float64
 17  end_city            object
 18  end_landmark        float64
 19  start_date          object
 20  end_date            object
 21  start_dpcapacity    float64
 22  end_dpcapacity      float64
dtypes: float64(9), object(14)
memory usage: 5.7+ GB

In [45]:
merged2013_2022['end_city'].unique()

array([0, 2, 1], dtype=object)

In [46]:
merged2013_2022['end_city'] = merged2013_2022['end_city'].astype('int64')

In [47]:
merged2013_2022['start_city'].unique()

array([0, 2, 1], dtype=object)

In [48]:
merged2013_2022['start_city'] = merged2013_2022['start_city'].astype('int64')

In [49]:
merged2013_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33153270 entries, 0 to 33153269
Data columns (total 23 columns):
 #   Column              Dtype
---  ------              -----
 0   start_time          object
 1   end_time            object
 2   tripduration        object
 3   start_station_id    object
 4   start_station_name  object
 5   end_station_id      object
 6   end_station_name    object
 7   usertype            object
 8   gender              object
 9   birthyear           float64
 10  start_lat           float64
 11  start_lng           float64
 12  end_lat             float64
 13  end_lng             float64
 14  rideable_type       object
 15  start_city          int64
 16  start_landmark      float64
 17  end_city            int64
 18  end_landmark        float64
 19  start_date          object
 20  end_date            object
 21  start_dpcapacity    float64
 22  end_dpcapacity      float64
dtypes: float64(9), int64(2), object(12)
memory usage: 5.7+ GB

In [50]:
merged2013_2022['start_landmark'] = merged2013_2022['start_landmark'].astype('int64')

In [51]:
merged2013_2022['end_landmark'] = merged2013_2022['end_landmark'].astype('int64')

In [52]:
merged2013_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33153270 entries, 0 to 33153269
Data columns (total 23 columns):
 #   Column              Dtype
---  ------              -----
 0   start_time          object
 1   end_time            object
 2   tripduration        object
 3   start_station_id    object
 4   start_station_name  object
 5   end_station_id      object
 6   end_station_name    object
 7   usertype            object
 8   gender              object
 9   birthyear           float64
 10  start_lat           float64
 11  start_lng           float64
 12  end_lat             float64
 13  end_lng             float64
 14  rideable_type       object
 15  start_city          int64
 16  start_landmark      int64
 17  end_city            int64
 18  end_landmark        int64
 19  start_date          object
 20  end_date            object
 21  start_dpcapacity    float64
 22  end_dpcapacity      float64
dtypes: float64(7), int64(4), object(12)
memory usage: 5.7+ GB

In [53]:
merged2013_2022['start_dpcapacity'] = merged2013_2022['start_dpcapacity'].astype('int64')
merged2013_2022['end_dpcapacity'] = merged2013_2022['end_dpcapacity'].astype('int64')

In [54]:
merged2013_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33153270 entries, 0 to 33153269
Data columns (total 23 columns):
 #   Column              Dtype
---  ------              -----
 0   start_time          object
 1   end_time            object
 2   tripduration        object
 3   start_station_id    object
 4   start_station_name  object
 5   end_station_id      object
 6   end_station_name    object
 7   usertype            object
 8   gender              object
 9   birthyear           float64
 10  start_lat           float64
 11  start_lng           float64
 12  end_lat             float64
 13  end_lng             float64
 14  rideable_type       object
 15  start_city          int64
 16  start_landmark      int64
 17  end_city            int64
 18  end_landmark        int64
 19  start_date          object
 20  end_date            object
 21  start_dpcapacity    int64
 22  end_dpcapacity      int64
dtypes: float64(5), int64(6), object(12)
memory usage: 5.7+ GB

In [55]:
merged2013_2022['rideable_type'].unique()

array(['classic_bike', 'docked_bike', 'electric_bike'], dtype=object)

In [56]:
# Changing rideable_type to int values

merged2013_2022.loc[merged2013_2022['rideable_type'] == 'classic_bike', 'rideable_type'] = 0
merged2013_2022.loc[merged2013_2022['rideable_type'] == 'docked_bike', 'rideable_type'] = 1
merged2013_2022.loc[merged2013_2022['rideable_type'] == 'electric_bike', 'rideable_type'] = 2

In [57]:
merged2013_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33153270 entries, 0 to 33153269
Data columns (total 23 columns):
 #   Column              Dtype
---  ------              -----
 0   start_time          object
 1   end_time            object
 2   tripduration        object
 3   start_station_id    object
 4   start_station_name  object
 5   end_station_id      object
 6   end_station_name    object
 7   usertype            object
 8   gender              object
 9   birthyear           float64
 10  start_lat           float64
 11  start_lng           float64
 12  end_lat             float64
 13  end_lng             float64
 14  rideable_type       object
 15  start_city          int64
 16  start_landmark      int64
 17  end_city            int64
 18  end_landmark        int64
 19  start_date          object
 20  end_date            object
 21  start_dpcapacity    int64
 22  end_dpcapacity      int64
dtypes: float64(5), int64(6), object(12)
memory usage: 5.7+ GB

In [58]:
merged2013_2022['rideable_type'] = merged2013_2022['rideable_type'].astype('int64')

In [59]:
merged2013_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33153270 entries, 0 to 33153269
Data columns (total 23 columns):
 #   Column              Dtype
---  ------              -----
 0   start_time          object
 1   end_time            object
 2   tripduration        object
 3   start_station_id    object
 4   start_station_name  object
 5   end_station_id      object
 6   end_station_name    object
 7   usertype            object
 8   gender              object
 9   birthyear           float64
 10  start_lat           float64
 11  start_lng           float64
 12  end_lat             float64
 13  end_lng             float64
 14  rideable_type       int64
 15  start_city          int64
 16  start_landmark      int64
 17  end_city            int64
 18  end_landmark        int64
 19  start_date          object
 20  end_date            object
 21  start_dpcapacity    int64
 22  end_dpcapacity      int64
dtypes: float64(5), int64(7), object(11)
memory usage: 5.7+ GB

In [60]:
merged2013_2022['gender'].unique()

array(['Male', '0', 'Female', -1], dtype=object)

In [61]:
merged2013_2022.loc[merged2013_2022['gender'] == 'Male', 'gender'] = 0
merged2013_2022.loc[merged2013_2022['gender'] == '0', 'gender'] = -1
merged2013_2022.loc[merged2013_2022['gender'] == 'Female', 'gender'] = 1

In [62]:
merged2013_2022['gender'] = merged2013_2022['gender'].astype('int64')

In [63]:
merged2013_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33153270 entries, 0 to 33153269
Data columns (total 23 columns):
 #   Column              Dtype
---  ------              -----
 0   start_time          object
 1   end_time            object
 2   tripduration        object
 3   start_station_id    object
 4   start_station_name  object
 5   end_station_id      object
 6   end_station_name    object
 7   usertype            object
 8   gender              int64
 9   birthyear           float64
 10  start_lat           float64
 11  start_lng           float64
 12  end_lat             float64
 13  end_lng             float64
 14  rideable_type       int64
 15  start_city          int64
 16  start_landmark      int64
 17  end_city            int64
 18  end_landmark        int64
 19  start_date          object
 20  end_date            object
 21  start_dpcapacity    int64
 22  end_dpcapacity      int64
dtypes: float64(5), int64(8), object(10)
memory usage: 5.7+ GB

In [64]:
merged2013_2022['usertype'].unique()

array(['member', 'casual'], dtype=object)

In [65]:
merged2013_2022.loc[merged2013_2022['usertype'] == 'casual', 'usertype'] = 0
merged2013_2022.loc[merged2013_2022['usertype'] == 'member', 'usertype'] = 1

In [66]:
merged2013_2022['usertype'] = merged2013_2022['usertype'].astype('int64')

In [67]:
merged2013_2022['birthyear'] = merged2013_2022['birthyear'].astype('int64')

In [68]:
merged2013_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33153270 entries, 0 to 33153269
Data columns (total 23 columns):
 #   Column              Dtype
---  ------              -----
 0   start_time          object
 1   end_time            object
 2   tripduration        object
 3   start_station_id    object
 4   start_station_name  object
 5   end_station_id      object
 6   end_station_name    object
 7   usertype            int64
 8   gender              int64
 9   birthyear           int64
 10  start_lat           float64
 11  start_lng           float64
 12  end_lat             float64
 13  end_lng             float64
 14  rideable_type       int64
 15  start_city          int64
 16  start_landmark      int64
 17  end_city            int64
 18  end_landmark        int64
 19  start_date          object
 20  end_date            object
 21  start_dpcapacity    int64
 22  end_dpcapacity      int64
dtypes: float64(4), int64(10), object(9)
memory usage: 5.7+ GB

In [69]:
new_column = []
trip_dur = merged2013_2022['tripduration'].values

In [70]:
for i in range(len(trip_dur)):
    try:
        new_column.append(int(float(trip_dur[i])))
    except ValueError:
        new_column.append(int(float(trip_dur[i].replace(',',''))))

In [71]:
merged2013_2022.shape

(33153270, 23)

In [72]:
trip_dur[:10]

array([31177, 140, 87, 11674, 15758, 301, 316, 60, 171, 22549],
      dtype=object)

In [73]:
new_column[:10]

[31177, 140, 87, 11674, 15758, 301, 316, 60, 171, 22549]

In [74]:
merged2013_2022['tripduration'] = new_column

In [75]:
merged2013_2022['tripduration'] = merged2013_2022['tripduration'].astype('int64')

In [76]:
merged2013_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33153270 entries, 0 to 33153269
Data columns (total 23 columns):
 #   Column              Dtype
---  ------              -----
 0   start_time          object
 1   end_time            object
 2   tripduration        int64
 3   start_station_id    object
 4   start_station_name  object
 5   end_station_id      object
 6   end_station_name    object
 7   usertype            int64
 8   gender              int64
 9   birthyear           int64
 10  start_lat           float64
 11  start_lng           float64
 12  end_lat             float64
 13  end_lng             float64
 14  rideable_type       int64
 15  start_city          int64
 16  start_landmark      int64
 17  end_city            int64
 18  end_landmark        int64
 19  start_date          object
 20  end_date            object
 21  start_dpcapacity    int64
 22  end_dpcapacity      int64
dtypes: float64(4), int64(11), object(8)
memory usage: 5.7+ GB

In [77]:
change_times_st = merged2013_2022['start_time'].values
change_times_ed = merged2013_2022['end_time'].values

new_st_times = []
new_ed_times = []

for i in range(len(change_times_st)):
    if len(change_times_st[i]) == 4:
        new_st_times.append('0' + change_times_st[i] + ':00')
    elif len(change_times_st[i]) == 5:
        new_st_times.append(change_times_st[i] + ':00')
    else:
        new_st_times.append(change_times_st[i])
    
    if len(change_times_ed[i]) == 4:
        new_ed_times.append('0' + change_times_ed[i] + ':00')
    elif len(change_times_ed[i]) == 5:
        new_ed_times.append(change_times_ed[i] + ':00')
    else:
        new_ed_times.append(change_times_ed[i])

In [78]:
len(new_st_times) == len(new_ed_times)

True

In [79]:
len(new_st_times)

33153270

In [80]:
merged2013_2022['start_time'] = new_st_times
merged2013_2022['end_time'] = new_ed_times

In [81]:
def time_check(start_time=[],end_time=[],test_start_dates=[],test_end_dates=[]):
    time_invalid = []
    for i in range(len(start_time)):
        
        # if start_time is after end time on the same day, then the entry is invalid
        if test_start_dates[i] == test_end_dates[i]:
            if start_time[i] > end_time[i]:
                time_invalid.append(i)

    return time_invalid


remove_times = time_check(merged2013_2022['start_time'].values, merged2013_2022['end_time'].values, merged2013_2022['start_date'].values, merged2013_2022['end_date'].values)

In [82]:
len(remove_times)

10304

In [83]:
merged2013_2022.loc[remove_times]

,start_time,end_time,tripduration,start_station_id,start_station_name,end_station_id,end_station_name,usertype,gender,birthyear,...,end_lng,rideable_type,start_city,start_landmark,end_city,end_landmark,start_date,end_date,start_dpcapacity,end_dpcapacity
13535378,01:24:00,01:04:00,2385,144,Larrabee St & Webster Ave,76,Lake Shore Dr & Monroe St,1,0,1993,...,-87.616743,0,0,193,0,300,2017-11-05,2017-11-05,15,11
13535389,01:29:00,01:05:00,2158,144,Larrabee St & Webster Ave,76,Lake Shore Dr & Monroe St,1,1,1992,...,-87.616743,0,0,193,0,300,2017-11-05,2017-11-05,15,11
13535427,01:47:00,01:04:00,1028,210,Ashland Ave & Division St,274,Racine Ave & 15th St,1,0,1988,...,-87.656625,0,0,61,0,304,2017-11-05,2017-11-05,19,15
13535435,01:51:00,01:07:00,932,349,Halsted St & Wrightwood Ave,61,Wood St & Milwaukee Ave,1,1,1993,...,-87.672552,0,0,210,0,221,2017-11-05,2017-11-05,15,15
13535436,01:54:00,01:06:00,716,321,Wabash Ave & 9th St,197,Michigan Ave & Madison St,0,-1,0,...,-87.625125,0,0,54,0,36,2017-11-05,2017-11-05,19,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32349689,18:00:55,18:00:32,86376,chargingstx5,Lincoln Ave & Roscoe St*,chargingstx5,Lincoln Ave & Roscoe St*,1,-1,0,...,-87.670668,2,0,0,0,0,2022-09-08,2022-09-08,0,0
32451336,17:47:44,17:47:34,86389,chargingstx5,Lincoln Ave & Roscoe St*,chargingstx5,Lincoln Ave & Roscoe St*,1,-1,0,...,-87.670668,0,0,0,0,0,2022-09-14,2022-09-14,0,0
32733633,17:27:30,17:27:26,86395,TA1307000121,Halsted St & Polk St,TA1307000121,Halsted St & Polk St,1,-1,0,...,-87.646640,2,0,0,0,0,2022-09-30,2022-09-30,0,0
32774785,08:55:01,08:54:45,86383,E008,Chicago Ave & Sheridan Rd,E008,Chicago Ave & Sheridan Rd,1,-1,0,...,-87.677821,2,0,0,0,0,2022-10-03,2022-10-03,0,0
32921028,14:42:10,11:53:28,76277,chargingstx0,Wilton Ave & Diversey Pkwy*,chargingstx0,Wilton Ave & Diversey Pkwy*,1,-1,0,...,-87.652705,0,0,0,0,0,2022-10-13,2022-10-13,0,0

In [84]:
merged2013_2022.drop(remove_times, inplace=True)

In [85]:
remove_time_df = pd.DataFrame(remove_times)

In [86]:
remove_time_df.to_csv('remove times.csv')

In [87]:
merged2013_2022.isnull().sum()

start_time            0
end_time              0
tripduration          0
start_station_id      0
start_station_name    0
end_station_id        0
end_station_name      0
usertype              0
gender                0
birthyear             0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
rideable_type         0
start_city            0
start_landmark        0
end_city              0
end_landmark          0
start_date            0
end_date              0
start_dpcapacity      0
end_dpcapacity        0
dtype: int64

In [88]:
merged2013_2022.to_csv('1 Full Divvy Dataframe pt1.csv')