In [1]:
import pandas as pd

stations = pd.read_csv('master_station_list.csv')
stations = stations.drop(['Unnamed: 0'], axis=1)

In [2]:
stations

,id,name,latitude,longitude,dpcapacity,landmark,city
0,5,State St & Harrison St,41.873958,-87.627739,19,30.0,Chicago
1,13,Wilton Ave & Diversey Pkwy,41.932500,-87.652681,19,66.0,Chicago
2,14,Morgan St & 18th St,41.858086,-87.651073,15,163.0,Chicago
3,15,Racine Ave & 18th St,41.858181,-87.656487,15,164.0,Chicago
4,16,Wood St & North Ave,41.910329,-87.672516,15,223.0,Chicago
...,...,...,...,...,...,...,...
581,622,California Ave & Cortez St,41.900363,-87.696704,0,0.0,Chicago
582,623,Michigan Ave & 8th St,41.872773,-87.623981,23,0.0,Chicago
583,624,Dearborn St & Van Buren St (*),41.876268,-87.629155,16,0.0,Chicago
584,625,Chicago Ave & Dempster St,42.041691,-87.680687,15,0.0,Evanston
585,626,Delano Ct & Roosevelt Rd,41.867491,-87.632190,19,0.0,Chicago

In [3]:
# city for both is chicago, landmark for both is 0

# Humboldt Dr & Luis Munoz Marin Dr -  372: id 

# California Ave & Augusta Blvd -  357 : id

In [4]:
# only values are Clark Clark St & 9th St (AMLI) so we can just set all
# from_lat and from_long to the above numbers

# merged2013_2017.from_lat = merged2013_2017.from_lat.fillna(41.87048)
# merged2013_2017.from_long = merged2013_2017.from_long.fillna(-87.63100)

In [5]:
stations.loc[stations['id'] == 372]

,id,name,latitude,longitude,dpcapacity,landmark,city
342,372,California Ave & Augusta Blvd,41.899358,-87.696439,19,660.0,Chicago

In [6]:
372 in stations['id'].values

True

In [7]:
# this means we have to add into our from_city section entires for california Ave & August Blvd and Humbol Dr & 
# Luis Munoz Marin Dr

# first however I will check if they are even present in the dataset from 2018-2019

In [8]:
headers = pd.read_csv('merged2013_2017.csv')

In [9]:
headers = headers.drop('Unnamed: 0', axis=1)
headers

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,to_long,rideable_type,from_city,from_landmark,to_city,to_landmark,start_date,end_date,from_dpcapacity,to_dpcapacity
0,9651,00:00,00:09,478,487,34,Cannon Dr & Fullerton Ave,67,Sheffield Ave & Fullerton Ave,casual,...,-87.653708,classic_bike,Chicago,124.0,Chicago,60.0,2013-06-30,2013-06-30,15,15
1,19385,00:00,00:06,893,359,20,Sheffield Ave & Kingsbury St,60,Dayton St & North Ave,member,...,-87.649422,classic_bike,Chicago,154.0,Chicago,58.0,2013-07-03,2013-07-03,15,19
2,29952,00:00,00:27,311,1623,59,Wabash Ave & Roosevelt Rd,97,Museum Campus,casual,...,-87.617759,classic_bike,Chicago,31.0,Chicago,29.0,2013-07-06,2013-07-06,19,19
3,37222,00:00,00:44,420,2639,76,Lake Shore Dr & Monroe St,76,Lake Shore Dr & Monroe St,casual,...,-87.616970,classic_bike,Chicago,300.0,Chicago,300.0,2013-07-08,2013-07-08,11,11
4,59638,00:00,00:25,187,1479,27,Larrabee St & North Ave,24,Fairbanks Ct & Grand Ave,casual,...,-87.620620,classic_bike,Chicago,174.0,Chicago,262.0,2013-07-14,2013-07-14,19,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13382744,17528056,9:59,10:04,1171,326,346,Ada St & Washington Blvd,198,Green St & Madison St,member,...,-87.648789,classic_bike,Chicago,353.0,Chicago,159.0,2017-12-26,2017-12-26,15,19
13382745,17531658,9:59,10:07,4710,446,39,Wabash Ave & Adams St,195,Columbus Dr & Randolph St,member,...,-87.619521,classic_bike,Chicago,0.0,Chicago,263.0,2017-12-28,2017-12-28,23,23
13382746,17531657,9:59,10:10,5932,672,110,Dearborn St & Erie St,195,Columbus Dr & Randolph St,member,...,-87.619521,classic_bike,Chicago,45.0,Chicago,263.0,2017-12-28,2017-12-28,23,23
13382747,17535685,9:59,10:06,6449,413,84,Milwaukee Ave & Grand Ave,198,Green St & Madison St,member,...,-87.648789,classic_bike,Chicago,33.0,Chicago,159.0,2017-12-31,2017-12-31,19,19
13382748,17535686,9:59,10:13,2898,818,249,Montrose Harbor,334,Lake Shore Dr & Belmont Ave,member,...,-87.639192,classic_bike,Chicago,388.0,Chicago,233.0,2017-12-31,2017-12-31,15,19

In [10]:
# We want the same headers to be in our next set of dataframes for 2018 and 2019, because at the end we will merge them together
required_headers = headers.columns

In [11]:
df1 = pd.read_csv('Divvy 2018 merged nostation.csv').drop('Unnamed: 0', axis=1)

In [12]:
df1

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber,Male,1988.0
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber,Male,1984.0
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber,Male,1989.0
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber,Male,1983.0
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber,Male,1989.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3603077,21742438,2018-12-31 23:45:17,2018-12-31 23:50:05,2931,288.0,49,Dearborn St & Monroe St,164,Franklin St & Lake St,Subscriber,Female,1983.0
3603078,21742439,2018-12-31 23:48:48,2018-12-31 23:57:22,4386,514.0,624,Dearborn St & Van Buren St (*),44,State St & Randolph St,Subscriber,Female,1990.0
3603079,21742440,2018-12-31 23:50:09,2018-12-31 23:57:16,4927,427.0,41,Federal St & Polk St,52,Michigan Ave & Lake St,Subscriber,Female,1995.0
3603080,21742441,2018-12-31 23:55:04,2018-12-31 23:58:24,1350,200.0,141,Clark St & Lincoln Ave,118,Sedgwick St & North Ave,Subscriber,Male,1999.0
3603081,21742442,2018-12-31 23:59:18,2019-01-01 00:20:43,2006,"1,285.0",260,Kedzie Ave & Milwaukee Ave,166,Ashland Ave & Wrightwood Ave,Subscriber,Male,1990.0

In [13]:
df2 = pd.read_csv('Divvy 2019 merged nostation.csv').drop('Unnamed: 0',axis=1)

In [14]:
df2

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,21742443,2019-01-01 00:04:37,2019-01-01 00:11:07,2167,390.0,199,Wabash Ave & Grand Ave,84,Milwaukee Ave & Grand Ave,Subscriber,Male,1989.0
1,21742444,2019-01-01 00:08:13,2019-01-01 00:15:34,4386,441.0,44,State St & Randolph St,624,Dearborn St & Van Buren St (*),Subscriber,Female,1990.0
2,21742445,2019-01-01 00:13:23,2019-01-01 00:27:12,1524,829.0,15,Racine Ave & 18th St,644,Western Ave & Fillmore St (*),Subscriber,Female,1994.0
3,21742446,2019-01-01 00:13:45,2019-01-01 00:43:28,252,"1,783.0",123,California Ave & Milwaukee Ave,176,Clark St & Elm St,Subscriber,Male,1993.0
4,21742447,2019-01-01 00:14:52,2019-01-01 00:20:56,1170,364.0,173,Mies van der Rohe Way & Chicago Ave,35,Streeter Dr & Grand Ave,Subscriber,Male,1994.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3817999,25962900,2019-12-31 23:56:13,2020-01-01 00:15:45,2196,"1,172.0",112,Green St & Randolph St,225,Halsted St & Dickens Ave,Subscriber,Male,1981.0
3818000,25962901,2019-12-31 23:56:34,2020-01-01 00:22:08,4877,"1,533.0",90,Millennium Park,90,Millennium Park,Subscriber,Male,1992.0
3818001,25962902,2019-12-31 23:57:05,2020-01-01 00:05:46,863,520.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,Subscriber,Male,1967.0
3818002,25962903,2019-12-31 23:57:11,2020-01-01 00:05:45,2637,514.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,Subscriber,Female,1970.0
3818003,25962904,2019-12-31 23:57:17,2019-12-31 23:59:18,5930,120.0,256,Broadway & Sheridan Rd,240,Sheridan Rd & Irving Park Rd,Subscriber,Male,1982.0

In [15]:
merged2018_2019 = pd.concat([df1, df2], ignore_index=True)

In [16]:
merged2018_2019

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber,Male,1988.0
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber,Male,1984.0
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber,Male,1989.0
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber,Male,1983.0
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber,Male,1989.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7421081,25962900,2019-12-31 23:56:13,2020-01-01 00:15:45,2196,"1,172.0",112,Green St & Randolph St,225,Halsted St & Dickens Ave,Subscriber,Male,1981.0
7421082,25962901,2019-12-31 23:56:34,2020-01-01 00:22:08,4877,"1,533.0",90,Millennium Park,90,Millennium Park,Subscriber,Male,1992.0
7421083,25962902,2019-12-31 23:57:05,2020-01-01 00:05:46,863,520.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,Subscriber,Male,1967.0
7421084,25962903,2019-12-31 23:57:11,2020-01-01 00:05:45,2637,514.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,Subscriber,Female,1970.0
7421085,25962904,2019-12-31 23:57:17,2019-12-31 23:59:18,5930,120.0,256,Broadway & Sheridan Rd,240,Sheridan Rd & Irving Park Rd,Subscriber,Male,1982.0

In [17]:
# Tasks

# Check for nulls

# split start_time and end_time
# splitting start_time and end_time into two columns
# merged2018_2019[['start_date','start_time']] = merged2018_2019.start_time.str.split(" ",expand=True)
# merged2018_2019[['end_date','end_time']] = merged2018_2019.end_time.str.split(" ",expand=True)

# change usertype: Customer -> casual, Subscriber -> member
# merged2018_2019.loc[merged2018_2019['usertype'] == 'Customer', 'usertype'] = 'casual'
# merged2018_2019.loc[merged2018_2019['usertype'] == 'Subscriber', 'usertype'] = 'member'

In [18]:
merged2018_2019.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
7421081    False
7421082    False
7421083    False
7421084    False
7421085    False
Length: 7421086, dtype: bool

In [19]:
# checking for our previous problems station #1
print('California Ave & Augusta Blvd' in merged2018_2019['from_station_name'])
print('California Ave & Augusta Blvd' in merged2018_2019['to_station_name'])

# checking for our previous problems station #2
print('Humboldt Dr & Luis Munoz Marin Dr' in merged2018_2019['from_station_name'])
print('Humboldt Dr & Luis Munoz Marin Dr' in merged2018_2019['to_station_name'])

False
False
False
False

In [20]:
merged2018_2019.shape

(7421086, 12)

In [21]:
# remove duplicates
merged2018_2019.drop_duplicates()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber,Male,1988.0
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber,Male,1984.0
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber,Male,1989.0
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber,Male,1983.0
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber,Male,1989.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7421081,25962900,2019-12-31 23:56:13,2020-01-01 00:15:45,2196,"1,172.0",112,Green St & Randolph St,225,Halsted St & Dickens Ave,Subscriber,Male,1981.0
7421082,25962901,2019-12-31 23:56:34,2020-01-01 00:22:08,4877,"1,533.0",90,Millennium Park,90,Millennium Park,Subscriber,Male,1992.0
7421083,25962902,2019-12-31 23:57:05,2020-01-01 00:05:46,863,520.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,Subscriber,Male,1967.0
7421084,25962903,2019-12-31 23:57:11,2020-01-01 00:05:45,2637,514.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,Subscriber,Female,1970.0
7421085,25962904,2019-12-31 23:57:17,2019-12-31 23:59:18,5930,120.0,256,Broadway & Sheridan Rd,240,Sheridan Rd & Irving Park Rd,Subscriber,Male,1982.0

In [22]:
merged2018_2019.shape

(7421086, 12)

In [23]:
# remove duplicate trip_id
merged2018_2019.drop_duplicates(subset=['trip_id'])

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber,Male,1988.0
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber,Male,1984.0
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber,Male,1989.0
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber,Male,1983.0
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber,Male,1989.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7421081,25962900,2019-12-31 23:56:13,2020-01-01 00:15:45,2196,"1,172.0",112,Green St & Randolph St,225,Halsted St & Dickens Ave,Subscriber,Male,1981.0
7421082,25962901,2019-12-31 23:56:34,2020-01-01 00:22:08,4877,"1,533.0",90,Millennium Park,90,Millennium Park,Subscriber,Male,1992.0
7421083,25962902,2019-12-31 23:57:05,2020-01-01 00:05:46,863,520.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,Subscriber,Male,1967.0
7421084,25962903,2019-12-31 23:57:11,2020-01-01 00:05:45,2637,514.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,Subscriber,Female,1970.0
7421085,25962904,2019-12-31 23:57:17,2019-12-31 23:59:18,5930,120.0,256,Broadway & Sheridan Rd,240,Sheridan Rd & Irving Park Rd,Subscriber,Male,1982.0

In [24]:
# now we know all of our entries are unique, we can start performing data operations.

In [25]:
merged2018_2019.isnull().sum()

trip_id                    0
start_time                 0
end_time                   0
bikeid                     0
tripduration               0
from_station_id            0
from_station_name          0
to_station_id              0
to_station_name            0
usertype                   0
gender               1121711
birthyear            1093960
dtype: int64

In [26]:
# our values for gender and birthyear have many nulls, which is actually not a problem. we just need to make sure that
# all our nulls are casual riders and that there are no nulls in our member rider category.

# checking our entries for usertype


# change usertype: Customer -> casual, Subscriber -> member

merged2018_2019['usertype'].unique()

array(['Subscriber', 'Customer'], dtype=object)

In [27]:
# change usertype: Customer -> casual, Subscriber -> member

merged2018_2019.loc[merged2018_2019['usertype'] == 'Customer', 'usertype'] = 'casual'
merged2018_2019.loc[merged2018_2019['usertype'] == 'Subscriber', 'usertype'] = 'member'

In [28]:
merged2018_2019['usertype'].unique()

array(['member', 'casual'], dtype=object)

In [29]:
# now I need to make sure that the amount of null entries in gender == the amount in birthyear is true
# I will cast all the null values to 0.0 to make this easier for me
# Also, I will check to see if there are any 0.0 values for the birthdate so that I can remove them, as any that exist
# before I cast all the nulls == 0 are invalid birthyears

In [30]:
0.0 in merged2018_2019['birthyear'].values

False

In [31]:
#now we can move on to editing gender and birthyear rows

In [32]:
merged2018_2019['gender'].unique()

array(['Male', 'Female', nan], dtype=object)

In [33]:
merged2018_2019 = merged2018_2019.fillna(0)

In [34]:
merged2018_2019['gender'].unique()

array(['Male', 'Female', 0], dtype=object)

In [35]:
merged2018_2019['birthyear'].unique()

array([1988., 1984., 1989., 1983., 1994., 1998., 1990.,    0., 1992.,
       1985., 1993., 1979., 1981., 1986., 1991., 1978., 1982., 1987.,
       1962., 1960., 1980., 1959., 1972., 1966., 1975., 1974., 1976.,
       2000., 1969., 1971., 1965., 1996., 1961., 1995., 1973., 1951.,
       1940., 1970., 1967., 1953., 1950., 1963., 1997., 1977., 1955.,
       1946., 1964., 1968., 1957., 1954., 1958., 1956., 1952., 1944.,
       1999., 1918., 1948., 1949., 1921., 1939., 1906., 1942., 1923.,
       1943., 1945., 2003., 1934., 1947., 1899., 2001., 1900., 1930.,
       1916., 1931., 1941., 1933., 1938., 1901., 1909., 2002., 1922.,
       1929., 1895., 1937., 2005., 1935., 2014., 1912., 1936., 1759.,
       1790., 1911., 1905., 1904., 1910., 1928., 1888., 1889., 1920.,
       1925., 1890.])

In [36]:
merged2018_2019.dtypes

trip_id                int64
start_time            object
end_time              object
bikeid                 int64
tripduration          object
from_station_id        int64
from_station_name     object
to_station_id          int64
to_station_name       object
usertype              object
gender                object
birthyear            float64
dtype: object

In [37]:
# Will check for rows that have one or the other as 0 (between gender and birthyear) because casual should have 0,0 and member should have non-0 values
# all values that don't pass thhis test will be deleted

# Will edit seperate object first to make sure this works properly

check = merged2018_2019
index = merged2018_2019[(merged2018_2019['gender'] == 0.0) & (merged2018_2019['birthyear'] != 0.0)].index
check.drop(index, inplace=True)

In [38]:
check

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,member,Male,1988.0
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),member,Male,1984.0
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,member,Male,1989.0
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,member,Male,1983.0
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,member,Male,1989.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7421081,25962900,2019-12-31 23:56:13,2020-01-01 00:15:45,2196,"1,172.0",112,Green St & Randolph St,225,Halsted St & Dickens Ave,member,Male,1981.0
7421082,25962901,2019-12-31 23:56:34,2020-01-01 00:22:08,4877,"1,533.0",90,Millennium Park,90,Millennium Park,member,Male,1992.0
7421083,25962902,2019-12-31 23:57:05,2020-01-01 00:05:46,863,520.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,member,Male,1967.0
7421084,25962903,2019-12-31 23:57:11,2020-01-01 00:05:45,2637,514.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,member,Female,1970.0
7421085,25962904,2019-12-31 23:57:17,2019-12-31 23:59:18,5930,120.0,256,Broadway & Sheridan Rd,240,Sheridan Rd & Irving Park Rd,member,Male,1982.0

In [39]:
check[check['gender'] == 0].shape

(1093898, 12)

In [40]:
check[check['birthyear'] == 0].shape

(1093960, 12)

In [41]:
index2 = check[(merged2018_2019['gender'] != 0.0) & (check['birthyear'] == 0.0)].index
check.drop(index2, inplace=True)

In [42]:
check[check['gender'] == 0].shape

(1093898, 12)

In [43]:
check[check['birthyear'] == 0].shape

(1093898, 12)

In [44]:
check.isnull().sum()

trip_id              0
start_time           0
end_time             0
bikeid               0
tripduration         0
from_station_id      0
from_station_name    0
to_station_id        0
to_station_name      0
usertype             0
gender               0
birthyear            0
dtype: int64

In [45]:
merged2018_2019 = check

In [46]:
# Now that we know we have no rows left that provide incomplete information about our respective categories, we can move on
# to editting/adding rows and such

# splitting start_time and end_time into two columns
merged2018_2019[['start_date', 'start_time']] = merged2018_2019.start_time.str.split(" ", expand=True)
merged2018_2019[['end_date', 'end_time']] = merged2018_2019.end_time.str.split(" ", expand=True)

In [47]:
merged2018_2019

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear,start_date,end_date
0,17536702,00:12:00,00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,member,Male,1988.0,2018-01-01,2018-01-01
1,17536703,00:41:35,00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),member,Male,1984.0,2018-01-01,2018-01-01
2,17536704,00:44:46,01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,member,Male,1989.0,2018-01-01,2018-01-01
3,17536705,00:53:10,01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,member,Male,1983.0,2018-01-01,2018-01-01
4,17536706,00:53:37,00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,member,Male,1989.0,2018-01-01,2018-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7421081,25962900,23:56:13,00:15:45,2196,"1,172.0",112,Green St & Randolph St,225,Halsted St & Dickens Ave,member,Male,1981.0,2019-12-31,2020-01-01
7421082,25962901,23:56:34,00:22:08,4877,"1,533.0",90,Millennium Park,90,Millennium Park,member,Male,1992.0,2019-12-31,2020-01-01
7421083,25962902,23:57:05,00:05:46,863,520.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,member,Male,1967.0,2019-12-31,2020-01-01
7421084,25962903,23:57:11,00:05:45,2637,514.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,member,Female,1970.0,2019-12-31,2020-01-01
7421085,25962904,23:57:17,23:59:18,5930,120.0,256,Broadway & Sheridan Rd,240,Sheridan Rd & Irving Park Rd,member,Male,1982.0,2019-12-31,2019-12-31

In [48]:
# validate date formats
# now fix start_date and end_date so they are in a single format (and check to see if any values are invalid)
merged2018_2019['start_date'] = pd.to_datetime(merged2018_2019['start_date'])
merged2018_2019['end_date'] = pd.to_datetime(merged2018_2019['end_date'])

In [49]:
required_headers

Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'gender', 'birthyear', 'from_lat',
       'from_long', 'to_lat', 'to_long', 'rideable_type', 'from_city',
       'from_landmark', 'to_city', 'to_landmark', 'start_date', 'end_date',
       'from_dpcapacity', 'to_dpcapacity'],
      dtype='object')

In [50]:
merged2018_2019.columns

Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'gender', 'birthyear', 'start_date',
       'end_date'],
      dtype='object')

In [51]:
# 'from_lat', 'from_long', 'to_lat', 'to_long', 'rideable_type', 'from_city','from_landmark', 
# 'to_city', 'to_landmark'
# are all of our missing columns. To get these, we will merge with our from_city dataframe

In [52]:
merged2018_2019

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear,start_date,end_date
0,17536702,00:12:00,00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,member,Male,1988.0,2018-01-01,2018-01-01
1,17536703,00:41:35,00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),member,Male,1984.0,2018-01-01,2018-01-01
2,17536704,00:44:46,01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,member,Male,1989.0,2018-01-01,2018-01-01
3,17536705,00:53:10,01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,member,Male,1983.0,2018-01-01,2018-01-01
4,17536706,00:53:37,00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,member,Male,1989.0,2018-01-01,2018-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7421081,25962900,23:56:13,00:15:45,2196,"1,172.0",112,Green St & Randolph St,225,Halsted St & Dickens Ave,member,Male,1981.0,2019-12-31,2020-01-01
7421082,25962901,23:56:34,00:22:08,4877,"1,533.0",90,Millennium Park,90,Millennium Park,member,Male,1992.0,2019-12-31,2020-01-01
7421083,25962902,23:57:05,00:05:46,863,520.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,member,Male,1967.0,2019-12-31,2020-01-01
7421084,25962903,23:57:11,00:05:45,2637,514.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,member,Female,1970.0,2019-12-31,2020-01-01
7421085,25962904,23:57:17,23:59:18,5930,120.0,256,Broadway & Sheridan Rd,240,Sheridan Rd & Irving Park Rd,member,Male,1982.0,2019-12-31,2019-12-31

In [53]:
stations

,id,name,latitude,longitude,dpcapacity,landmark,city
0,5,State St & Harrison St,41.873958,-87.627739,19,30.0,Chicago
1,13,Wilton Ave & Diversey Pkwy,41.932500,-87.652681,19,66.0,Chicago
2,14,Morgan St & 18th St,41.858086,-87.651073,15,163.0,Chicago
3,15,Racine Ave & 18th St,41.858181,-87.656487,15,164.0,Chicago
4,16,Wood St & North Ave,41.910329,-87.672516,15,223.0,Chicago
...,...,...,...,...,...,...,...
581,622,California Ave & Cortez St,41.900363,-87.696704,0,0.0,Chicago
582,623,Michigan Ave & 8th St,41.872773,-87.623981,23,0.0,Chicago
583,624,Dearborn St & Van Buren St (*),41.876268,-87.629155,16,0.0,Chicago
584,625,Chicago Ave & Dempster St,42.041691,-87.680687,15,0.0,Evanston
585,626,Delano Ct & Roosevelt Rd,41.867491,-87.632190,19,0.0,Chicago

In [54]:
# 'from_lat', 'from_long', 'from_city','from_landmark',
from_city = stations.rename(columns={'id' : 'from_station_id', 'name' : 'from_name','city' : 'from_city', 'latitude' : 'from_lat', 'longitude' : 'from_long', 'landmark' : 'from_landmark',})

#'to_lat', 'to_long', 'to_city', 'to_landmark'
to_city = stations.rename(columns={'id' : 'to_station_id', 'name' : 'to_name','city' : 'to_city', 'latitude' : 'to_lat', 'longitude' : 'to_long', 'landmark' : 'to_landmark',})

#'rideable_type' will be added at the end

In [55]:
display(from_city.columns)
display(to_city.columns)

Index(['from_station_id', 'from_name', 'from_lat', 'from_long', 'dpcapacity',
       'from_landmark', 'from_city'],
      dtype='object')

Index(['to_station_id', 'to_name', 'to_lat', 'to_long', 'dpcapacity',
       'to_landmark', 'to_city'],
      dtype='object')

In [56]:
merged2018_2019

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear,start_date,end_date
0,17536702,00:12:00,00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,member,Male,1988.0,2018-01-01,2018-01-01
1,17536703,00:41:35,00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),member,Male,1984.0,2018-01-01,2018-01-01
2,17536704,00:44:46,01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,member,Male,1989.0,2018-01-01,2018-01-01
3,17536705,00:53:10,01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,member,Male,1983.0,2018-01-01,2018-01-01
4,17536706,00:53:37,00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,member,Male,1989.0,2018-01-01,2018-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7421081,25962900,23:56:13,00:15:45,2196,"1,172.0",112,Green St & Randolph St,225,Halsted St & Dickens Ave,member,Male,1981.0,2019-12-31,2020-01-01
7421082,25962901,23:56:34,00:22:08,4877,"1,533.0",90,Millennium Park,90,Millennium Park,member,Male,1992.0,2019-12-31,2020-01-01
7421083,25962902,23:57:05,00:05:46,863,520.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,member,Male,1967.0,2019-12-31,2020-01-01
7421084,25962903,23:57:11,00:05:45,2637,514.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,member,Female,1970.0,2019-12-31,2020-01-01
7421085,25962904,23:57:17,23:59:18,5930,120.0,256,Broadway & Sheridan Rd,240,Sheridan Rd & Irving Park Rd,member,Male,1982.0,2019-12-31,2019-12-31

In [57]:
k = pd.merge(merged2018_2019, from_city, on='from_station_id', how='left')

In [58]:
k

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear,start_date,end_date,from_name,from_lat,from_long,dpcapacity,from_landmark,from_city
0,17536702,00:12:00,00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,member,Male,1988.0,2018-01-01,2018-01-01,Damen Ave & Pierce Ave,41.909396,-87.677692,19.0,65.0,Chicago
1,17536703,00:41:35,00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),member,Male,1984.0,2018-01-01,2018-01-01,Clifton Ave & Lawrence Ave,41.968873,-87.658857,15.0,104.0,Chicago
2,17536704,00:44:46,01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,member,Male,1989.0,2018-01-01,2018-01-01,LaSalle St & Washington St,41.882664,-87.632530,15.0,6.0,Chicago
3,17536705,00:53:10,01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,member,Male,1983.0,2018-01-01,2018-01-01,Rush St & Hubbard St,41.890011,-87.626293,15.0,533.0,Chicago
4,17536706,00:53:37,00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,member,Male,1989.0,2018-01-01,2018-01-01,Blue Island Ave & 18th St,41.857556,-87.661535,15.0,135.0,Chicago
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393206,25962900,23:56:13,00:15:45,2196,"1,172.0",112,Green St & Randolph St,225,Halsted St & Dickens Ave,member,Male,1981.0,2019-12-31,2020-01-01,Green St & Randolph St,41.884078,-87.648684,15.0,53.0,Chicago
7393207,25962901,23:56:34,00:22:08,4877,"1,533.0",90,Millennium Park,90,Millennium Park,member,Male,1992.0,2019-12-31,2020-01-01,Millennium Park,41.881032,-87.624084,35.0,8.0,Chicago
7393208,25962902,23:57:05,00:05:46,863,520.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,member,Male,1967.0,2019-12-31,2020-01-01,Michigan Ave & 8th St,41.872773,-87.623981,23.0,0.0,Chicago
7393209,25962903,23:57:11,00:05:45,2637,514.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,member,Female,1970.0,2019-12-31,2020-01-01,Michigan Ave & 8th St,41.872773,-87.623981,23.0,0.0,Chicago
7393210,25962904,23:57:17,23:59:18,5930,120.0,256,Broadway & Sheridan Rd,240,Sheridan Rd & Irving Park Rd,member,Male,1982.0,2019-12-31,2019-12-31,Broadway & Sheridan Rd,41.952833,-87.649993,15.0,323.0,Chicago

In [59]:
k.isnull().sum()

trip_id                   0
start_time                0
end_time                  0
bikeid                    0
tripduration              0
from_station_id           0
from_station_name         0
to_station_id             0
to_station_name           0
usertype                  0
gender                    0
birthyear                 0
start_date                0
end_date                  0
from_name            147542
from_lat             147542
from_long            147542
dpcapacity           147542
from_landmark        147542
from_city            147542
dtype: int64

In [60]:
d = pd.merge(k, to_city, on='to_station_id', how='left')

In [61]:
d

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_name,to_lat,to_long,dpcapacity_y,to_landmark,to_city
0,17536702,00:12:00,00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,member,...,-87.677692,19.0,65.0,Chicago,Claremont Ave & Hirsch St,41.907781,-87.685854,11.0,245.0,Chicago
1,17536703,00:41:35,00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),member,...,-87.658857,15.0,104.0,Chicago,Clark St & Winnemac Ave,41.973385,-87.668365,15.0,392.0,Chicago
2,17536704,00:44:46,01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,member,...,-87.632530,15.0,6.0,Chicago,Troy St & North Ave,41.909769,-87.705280,15.0,653.0,Chicago
3,17536705,00:53:10,01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,member,...,-87.626293,15.0,533.0,Chicago,Larrabee St & Oak St,41.900219,-87.642985,15.0,527.0,Chicago
4,17536706,00:53:37,00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,member,...,-87.661535,15.0,135.0,Chicago,Paulina St & 18th St,41.857901,-87.668745,15.0,88.0,Chicago
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393206,25962900,23:56:13,00:15:45,2196,"1,172.0",112,Green St & Randolph St,225,Halsted St & Dickens Ave,member,...,-87.648684,15.0,53.0,Chicago,Halsted St & Dickens Ave,41.919936,-87.648830,15.0,192.0,Chicago
7393207,25962901,23:56:34,00:22:08,4877,"1,533.0",90,Millennium Park,90,Millennium Park,member,...,-87.624084,35.0,8.0,Chicago,Millennium Park,41.881032,-87.624084,35.0,8.0,Chicago
7393208,25962902,23:57:05,00:05:46,863,520.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,member,...,-87.623981,23.0,0.0,Chicago,Michigan Ave & Lake St,41.886058,-87.624289,23.0,43.0,Chicago
7393209,25962903,23:57:11,00:05:45,2637,514.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,member,...,-87.623981,23.0,0.0,Chicago,Michigan Ave & Lake St,41.886058,-87.624289,23.0,43.0,Chicago
7393210,25962904,23:57:17,23:59:18,5930,120.0,256,Broadway & Sheridan Rd,240,Sheridan Rd & Irving Park Rd,member,...,-87.649993,15.0,323.0,Chicago,Sheridan Rd & Irving Park Rd,41.954340,-87.654601,11.0,63.0,Chicago

In [62]:
d['rideable_type'] = 'classic_bike'

In [63]:
d.columns

Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'gender', 'birthyear', 'start_date',
       'end_date', 'from_name', 'from_lat', 'from_long', 'dpcapacity_x',
       'from_landmark', 'from_city', 'to_name', 'to_lat', 'to_long',
       'dpcapacity_y', 'to_landmark', 'to_city', 'rideable_type'],
      dtype='object')

In [64]:
required_headers

Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'gender', 'birthyear', 'from_lat',
       'from_long', 'to_lat', 'to_long', 'rideable_type', 'from_city',
       'from_landmark', 'to_city', 'to_landmark', 'start_date', 'end_date',
       'from_dpcapacity', 'to_dpcapacity'],
      dtype='object')

In [65]:
print(len(d.columns))
print(len(required_headers))

27
25

In [66]:
for i in range(len(d.columns)):
    if d.columns[i] not in required_headers:
        print(d.columns[i])

from_name
dpcapacity_x
to_name
dpcapacity_y

In [67]:
# we can drop from_name and to_name
d = d.drop(['from_name', 'to_name'],axis=1)

In [68]:
for i in range(len(d.columns)):
    if d.columns[i] not in required_headers:
        print(d.columns[i])

dpcapacity_x
dpcapacity_y

In [69]:
d

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
0,17536702,00:12:00,00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,member,...,-87.677692,19.0,65.0,Chicago,41.907781,-87.685854,11.0,245.0,Chicago,classic_bike
1,17536703,00:41:35,00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),member,...,-87.658857,15.0,104.0,Chicago,41.973385,-87.668365,15.0,392.0,Chicago,classic_bike
2,17536704,00:44:46,01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,member,...,-87.632530,15.0,6.0,Chicago,41.909769,-87.705280,15.0,653.0,Chicago,classic_bike
3,17536705,00:53:10,01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,member,...,-87.626293,15.0,533.0,Chicago,41.900219,-87.642985,15.0,527.0,Chicago,classic_bike
4,17536706,00:53:37,00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,member,...,-87.661535,15.0,135.0,Chicago,41.857901,-87.668745,15.0,88.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393206,25962900,23:56:13,00:15:45,2196,"1,172.0",112,Green St & Randolph St,225,Halsted St & Dickens Ave,member,...,-87.648684,15.0,53.0,Chicago,41.919936,-87.648830,15.0,192.0,Chicago,classic_bike
7393207,25962901,23:56:34,00:22:08,4877,"1,533.0",90,Millennium Park,90,Millennium Park,member,...,-87.624084,35.0,8.0,Chicago,41.881032,-87.624084,35.0,8.0,Chicago,classic_bike
7393208,25962902,23:57:05,00:05:46,863,520.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,member,...,-87.623981,23.0,0.0,Chicago,41.886058,-87.624289,23.0,43.0,Chicago,classic_bike
7393209,25962903,23:57:11,00:05:45,2637,514.0,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,member,...,-87.623981,23.0,0.0,Chicago,41.886058,-87.624289,23.0,43.0,Chicago,classic_bike
7393210,25962904,23:57:17,23:59:18,5930,120.0,256,Broadway & Sheridan Rd,240,Sheridan Rd & Irving Park Rd,member,...,-87.649993,15.0,323.0,Chicago,41.954340,-87.654601,11.0,63.0,Chicago,classic_bike

In [70]:
d.isnull().sum()

trip_id                   0
start_time                0
end_time                  0
bikeid                    0
tripduration              0
from_station_id           0
from_station_name         0
to_station_id             0
to_station_name           0
usertype                  0
gender                    0
birthyear                 0
start_date                0
end_date                  0
from_lat             147542
from_long            147542
dpcapacity_x         147542
from_landmark        147542
from_city            147542
to_lat               149108
to_long              149108
dpcapacity_y         149108
to_landmark          149108
to_city              149108
rideable_type             0
dtype: int64

In [71]:
merged2018_2019 = d

In [72]:
merged2018_2019.isnull().sum()

trip_id                   0
start_time                0
end_time                  0
bikeid                    0
tripduration              0
from_station_id           0
from_station_name         0
to_station_id             0
to_station_name           0
usertype                  0
gender                    0
birthyear                 0
start_date                0
end_date                  0
from_lat             147542
from_long            147542
dpcapacity_x         147542
from_landmark        147542
from_city            147542
to_lat               149108
to_long              149108
dpcapacity_y         149108
to_landmark          149108
to_city              149108
rideable_type             0
dtype: int64

In [73]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
33365,17579217,17:15:36,17:20:24,3887,288.0,360,DIVVY Map Frame B/C Station,285,Wood St & Hubbard St,member,...,NaN,NaN,NaN,NaN,41.891130,-87.672030,15.0,432.0,Chicago,classic_bike
76584,17631707,14:35:41,14:44:44,6417,543.0,360,DIVVY Map Frame B/C Station,360,DIVVY Map Frame B/C Station,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
112266,17673576,15:33:02,15:37:34,836,272.0,360,DIVVY Map Frame B/C Station,376,Artesian Ave & Hubbard St,member,...,NaN,NaN,NaN,NaN,41.889492,-87.688219,35.0,664.0,Chicago,classic_bike
123058,17687554,09:03:35,09:23:01,2922,"1,166.0",360,DIVVY Map Frame B/C Station,287,Franklin St & Monroe St,member,...,NaN,NaN,NaN,NaN,41.881131,-87.635185,23.0,57.0,Chicago,classic_bike
129197,17695601,10:23:30,10:32:03,5653,513.0,360,DIVVY Map Frame B/C Station,214,Damen Ave & Grand Ave,member,...,NaN,NaN,NaN,NaN,41.891220,-87.676860,15.0,141.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393106,25962789,21:27:23,21:29:37,389,133.0,627,LaSalle Dr & Huron St,110,Dearborn St & Erie St,member,...,NaN,NaN,NaN,NaN,41.893975,-87.628623,23.0,45.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike
7393203,25962897,23:51:19,23:55:33,5654,254.0,638,Clinton St & Jackson Blvd,134,Peoria St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877749,-87.649633,19.0,158.0,Chicago,classic_bike

In [74]:
merged2018_2019 = merged2018_2019.drop(merged2018_2019[merged2018_2019['from_station_name'] == 'DIVVY Map Frame B/C Station'].index)
merged2018_2019 = merged2018_2019.drop(merged2018_2019[merged2018_2019['to_station_name'] == 'DIVVY Map Frame B/C Station'].index)

In [75]:
merged2018_2019[merged2018_2019['from_long'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
207818,17788930,09:38:58,09:44:31,2351,333.0,512,BBB ~ Divvy Parts Testing,512,BBB ~ Divvy Parts Testing,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
207851,17788964,09:45:28,10:18:47,2351,"1,999.0",512,BBB ~ Divvy Parts Testing,512,BBB ~ Divvy Parts Testing,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
208648,17789882,12:13:15,12:15:09,2351,114.0,512,BBB ~ Divvy Parts Testing,512,BBB ~ Divvy Parts Testing,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
208812,17790072,12:40:57,12:47:05,1259,368.0,363,TS ~ DIVVY PARTS TESTING,512,BBB ~ Divvy Parts Testing,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
208845,17790107,12:48:20,13:05:44,1259,"1,044.0",512,BBB ~ Divvy Parts Testing,512,BBB ~ Divvy Parts Testing,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393106,25962789,21:27:23,21:29:37,389,133.0,627,LaSalle Dr & Huron St,110,Dearborn St & Erie St,member,...,NaN,NaN,NaN,NaN,41.893975,-87.628623,23.0,45.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike
7393203,25962897,23:51:19,23:55:33,5654,254.0,638,Clinton St & Jackson Blvd,134,Peoria St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877749,-87.649633,19.0,158.0,Chicago,classic_bike

In [76]:
merged2018_2019 = merged2018_2019.drop(merged2018_2019[merged2018_2019['from_station_name'] == 'BBB ~ Divvy Parts Testing'].index)
merged2018_2019 = merged2018_2019.drop(merged2018_2019[merged2018_2019['to_station_name'] == 'BBB ~ Divvy Parts Testing'].index)

In [77]:
merged2018_2019.isnull().sum()

trip_id                   0
start_time                0
end_time                  0
bikeid                    0
tripduration              0
from_station_id           0
from_station_name         0
to_station_id             0
to_station_name           0
usertype                  0
gender                    0
birthyear                 0
start_date                0
end_date                  0
from_lat             147436
from_long            147436
dpcapacity_x         147436
from_landmark        147436
from_city            147436
to_lat               148743
to_long              148743
dpcapacity_y         148743
to_landmark          148743
to_city              148743
rideable_type             0
dtype: int64

In [78]:
merged2018_2019[merged2018_2019['from_long'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
250958,17840267,15:47:51,15:57:38,1938,587.0,627,LaSalle Dr & Huron St (*),91,Clinton St & Washington Blvd,member,...,NaN,NaN,NaN,NaN,41.883380,-87.641170,31.0,10.0,Chicago,classic_bike
251697,17841115,17:04:55,17:14:10,3024,555.0,627,LaSalle Dr & Huron St (*),52,Michigan Ave & Lake St,member,...,NaN,NaN,NaN,NaN,41.886058,-87.624289,23.0,43.0,Chicago,classic_bike
251840,17841265,17:13:33,17:23:31,5218,598.0,627,LaSalle Dr & Huron St (*),66,Clinton St & Lake St,member,...,NaN,NaN,NaN,NaN,41.885833,-87.641382,19.0,21.0,Chicago,classic_bike
251969,17841402,17:20:59,17:30:47,3171,588.0,627,LaSalle Dr & Huron St (*),289,Wells St & Concord Ln,member,...,NaN,NaN,NaN,NaN,41.912202,-87.634664,19.0,182.0,Chicago,classic_bike
252092,17841544,17:30:25,17:38:25,3888,480.0,627,LaSalle Dr & Huron St (*),192,Canal St & Adams St,member,...,NaN,NaN,NaN,NaN,41.879230,-87.640015,27.0,11.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393106,25962789,21:27:23,21:29:37,389,133.0,627,LaSalle Dr & Huron St,110,Dearborn St & Erie St,member,...,NaN,NaN,NaN,NaN,41.893975,-87.628623,23.0,45.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike
7393203,25962897,23:51:19,23:55:33,5654,254.0,638,Clinton St & Jackson Blvd,134,Peoria St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877749,-87.649633,19.0,158.0,Chicago,classic_bike

In [79]:
merged2018_2019[merged2018_2019['from_station_id'] == 627]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
250958,17840267,15:47:51,15:57:38,1938,587.0,627,LaSalle Dr & Huron St (*),91,Clinton St & Washington Blvd,member,...,NaN,NaN,NaN,NaN,41.883380,-87.641170,31.0,10.0,Chicago,classic_bike
251697,17841115,17:04:55,17:14:10,3024,555.0,627,LaSalle Dr & Huron St (*),52,Michigan Ave & Lake St,member,...,NaN,NaN,NaN,NaN,41.886058,-87.624289,23.0,43.0,Chicago,classic_bike
251840,17841265,17:13:33,17:23:31,5218,598.0,627,LaSalle Dr & Huron St (*),66,Clinton St & Lake St,member,...,NaN,NaN,NaN,NaN,41.885833,-87.641382,19.0,21.0,Chicago,classic_bike
251969,17841402,17:20:59,17:30:47,3171,588.0,627,LaSalle Dr & Huron St (*),289,Wells St & Concord Ln,member,...,NaN,NaN,NaN,NaN,41.912202,-87.634664,19.0,182.0,Chicago,classic_bike
252092,17841544,17:30:25,17:38:25,3888,480.0,627,LaSalle Dr & Huron St (*),192,Canal St & Adams St,member,...,NaN,NaN,NaN,NaN,41.879230,-87.640015,27.0,11.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7392468,25962103,15:50:07,15:53:21,2076,193.0,627,LaSalle Dr & Huron St,140,Dearborn Pkwy & Delaware Pl,member,...,NaN,NaN,NaN,NaN,41.899007,-87.629928,19.0,173.0,Chicago,classic_bike
7393015,25962691,19:34:00,21:07:06,1034,"5,586.0",627,LaSalle Dr & Huron St,81,Daley Center Plaza,casual,...,NaN,NaN,NaN,NaN,41.884337,-87.630183,47.0,23.0,Chicago,classic_bike
7393071,25962752,20:31:30,20:58:24,389,"1,613.0",627,LaSalle Dr & Huron St,53,Wells St & Huron St,member,...,NaN,NaN,NaN,NaN,41.893832,-87.634195,19.0,64.0,Chicago,classic_bike
7393098,25962781,21:19:55,21:27:13,389,438.0,627,LaSalle Dr & Huron St,627,LaSalle Dr & Huron St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393106,25962789,21:27:23,21:29:37,389,133.0,627,LaSalle Dr & Huron St,110,Dearborn St & Erie St,member,...,NaN,NaN,NaN,NaN,41.893975,-87.628623,23.0,45.0,Chicago,classic_bike

In [80]:
set(merged2018_2019[merged2018_2019['from_station_id'] == 627]['from_long'].values)

{nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 ...}

In [81]:
merged2018_2019.loc[merged2018_2019['from_station_id'] == 627, 'from_lat'] = 41.894859
merged2018_2019.loc[merged2018_2019['from_station_id'] == 627, 'from_long'] = -87.632375
merged2018_2019.loc[merged2018_2019['from_station_id'] == 627, 'dpcapacity_x'] = 19
merged2018_2019.loc[merged2018_2019['from_station_id'] == 627, 'from_city'] = 'Chicago'

merged2018_2019.loc[merged2018_2019['to_station_id'] == 627, 'to_lat'] = 41.894859
merged2018_2019.loc[merged2018_2019['to_station_id'] == 627, 'to_long'] = -87.632375
merged2018_2019.loc[merged2018_2019['to_station_id'] == 627, 'dpcapacity_y'] = 19
merged2018_2019.loc[merged2018_2019['to_station_id'] == 627, 'to_city'] = 'Chicago'

In [82]:
merged2018_2019[merged2018_2019['from_station_id'] == 627]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
250958,17840267,15:47:51,15:57:38,1938,587.0,627,LaSalle Dr & Huron St (*),91,Clinton St & Washington Blvd,member,...,-87.632375,19.0,NaN,Chicago,41.883380,-87.641170,31.0,10.0,Chicago,classic_bike
251697,17841115,17:04:55,17:14:10,3024,555.0,627,LaSalle Dr & Huron St (*),52,Michigan Ave & Lake St,member,...,-87.632375,19.0,NaN,Chicago,41.886058,-87.624289,23.0,43.0,Chicago,classic_bike
251840,17841265,17:13:33,17:23:31,5218,598.0,627,LaSalle Dr & Huron St (*),66,Clinton St & Lake St,member,...,-87.632375,19.0,NaN,Chicago,41.885833,-87.641382,19.0,21.0,Chicago,classic_bike
251969,17841402,17:20:59,17:30:47,3171,588.0,627,LaSalle Dr & Huron St (*),289,Wells St & Concord Ln,member,...,-87.632375,19.0,NaN,Chicago,41.912202,-87.634664,19.0,182.0,Chicago,classic_bike
252092,17841544,17:30:25,17:38:25,3888,480.0,627,LaSalle Dr & Huron St (*),192,Canal St & Adams St,member,...,-87.632375,19.0,NaN,Chicago,41.879230,-87.640015,27.0,11.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7392468,25962103,15:50:07,15:53:21,2076,193.0,627,LaSalle Dr & Huron St,140,Dearborn Pkwy & Delaware Pl,member,...,-87.632375,19.0,NaN,Chicago,41.899007,-87.629928,19.0,173.0,Chicago,classic_bike
7393015,25962691,19:34:00,21:07:06,1034,"5,586.0",627,LaSalle Dr & Huron St,81,Daley Center Plaza,casual,...,-87.632375,19.0,NaN,Chicago,41.884337,-87.630183,47.0,23.0,Chicago,classic_bike
7393071,25962752,20:31:30,20:58:24,389,"1,613.0",627,LaSalle Dr & Huron St,53,Wells St & Huron St,member,...,-87.632375,19.0,NaN,Chicago,41.893832,-87.634195,19.0,64.0,Chicago,classic_bike
7393098,25962781,21:19:55,21:27:13,389,438.0,627,LaSalle Dr & Huron St,627,LaSalle Dr & Huron St,member,...,-87.632375,19.0,NaN,Chicago,41.894859,-87.632375,19.0,NaN,Chicago,classic_bike
7393106,25962789,21:27:23,21:29:37,389,133.0,627,LaSalle Dr & Huron St,110,Dearborn St & Erie St,member,...,-87.632375,19.0,NaN,Chicago,41.893975,-87.628623,23.0,45.0,Chicago,classic_bike

In [83]:
merged2018_2019[merged2018_2019['from_station_id'] == 627].isnull().sum()

trip_id                  0
start_time               0
end_time                 0
bikeid                   0
tripduration             0
from_station_id          0
from_station_name        0
to_station_id            0
to_station_name          0
usertype                 0
gender                   0
birthyear                0
start_date               0
end_date                 0
from_lat                 0
from_long                0
dpcapacity_x             0
from_landmark        18157
from_city                0
to_lat                 313
to_long                313
dpcapacity_y           313
to_landmark            791
to_city                313
rideable_type            0
dtype: int64

In [84]:
merged2018_2019.loc[merged2018_2019['from_station_id'] == 627, 'from_landmark'] = 0.0
merged2018_2019.loc[merged2018_2019['to_station_id'] == 627, 'to_landmark'] = 0.0

In [85]:
merged2018_2019.isnull().sum()

trip_id                   0
start_time                0
end_time                  0
bikeid                    0
tripduration              0
from_station_id           0
from_station_name         0
to_station_id             0
to_station_name           0
usertype                  0
gender                    0
birthyear                 0
start_date                0
end_date                  0
from_lat             129279
from_long            129279
dpcapacity_x         129279
from_landmark        129279
from_city            129279
to_lat               131967
to_long              131967
dpcapacity_y         131967
to_landmark          131967
to_city              131967
rideable_type             0
dtype: int64

In [86]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
579650,18233184,16:01:25,16:09:15,6454,470.0,621,Aberdeen St & Randolph St,350,Ashland Ave & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.895966,-87.667747,15.0,247.0,Chicago,classic_bike
581316,18235096,17:04:16,17:24:33,6417,"1,217.0",621,Aberdeen St & Randolph St,141,Clark St & Lincoln Ave,member,...,NaN,NaN,NaN,NaN,41.915689,-87.634600,19.0,179.0,Chicago,classic_bike
581417,18235212,17:06:34,17:21:51,2208,917.0,621,Aberdeen St & Randolph St,17,Honore St & Division St,member,...,NaN,NaN,NaN,NaN,41.903320,-87.672730,15.0,246.0,Chicago,classic_bike
582736,18236661,17:39:28,18:13:46,3119,"2,058.0",621,Aberdeen St & Randolph St,227,Southport Ave & Waveland Ave,member,...,NaN,NaN,NaN,NaN,41.948150,-87.663940,15.0,235.0,Chicago,classic_bike
582950,18236889,17:45:45,17:49:30,5926,225.0,621,Aberdeen St & Randolph St,21,Aberdeen St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877726,-87.654787,15.0,157.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393029,25962705,19:44:54,20:10:37,4767,"1,542.0",657,Wood St & Augusta Blvd,332,Burling St (Halsted) & Diversey Pkwy (Temp),member,...,NaN,NaN,NaN,NaN,41.933341,-87.648747,15.0,208.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike
7393203,25962897,23:51:19,23:55:33,5654,254.0,638,Clinton St & Jackson Blvd,134,Peoria St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877749,-87.649633,19.0,158.0,Chicago,classic_bike

In [87]:
# id 621: 15 dpcacpacity, 'Chicago', lat = 41.884100, long = -87.654286

merged2018_2019.loc[merged2018_2019['from_station_id'] == 621, 'from_lat'] = 41.884100
merged2018_2019.loc[merged2018_2019['from_station_id'] == 621, 'from_long'] = -87.654286
merged2018_2019.loc[merged2018_2019['from_station_id'] == 621, 'dpcapacity_x'] = 15
merged2018_2019.loc[merged2018_2019['from_station_id'] == 621, 'from_city'] = 'Chicago'

merged2018_2019.loc[merged2018_2019['to_station_id'] == 621, 'to_lat'] = 41.884100
merged2018_2019.loc[merged2018_2019['to_station_id'] == 621, 'to_long'] = -87.654286
merged2018_2019.loc[merged2018_2019['to_station_id'] == 621, 'dpcapacity_y'] = 15
merged2018_2019.loc[merged2018_2019['to_station_id'] == 621, 'to_city'] = 'Chicago'

merged2018_2019.loc[merged2018_2019['from_station_id'] == 621, 'from_landmark'] = 0.0
merged2018_2019.loc[merged2018_2019['to_station_id'] == 621, 'to_landmark'] = 0.0

In [88]:
merged2018_2019[merged2018_2019['from_station_id'] == 621]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
579650,18233184,16:01:25,16:09:15,6454,470.0,621,Aberdeen St & Randolph St,350,Ashland Ave & Chicago Ave,member,...,-87.654286,15.0,0.0,Chicago,41.895966,-87.667747,15.0,247.0,Chicago,classic_bike
581316,18235096,17:04:16,17:24:33,6417,"1,217.0",621,Aberdeen St & Randolph St,141,Clark St & Lincoln Ave,member,...,-87.654286,15.0,0.0,Chicago,41.915689,-87.634600,19.0,179.0,Chicago,classic_bike
581417,18235212,17:06:34,17:21:51,2208,917.0,621,Aberdeen St & Randolph St,17,Honore St & Division St,member,...,-87.654286,15.0,0.0,Chicago,41.903320,-87.672730,15.0,246.0,Chicago,classic_bike
582736,18236661,17:39:28,18:13:46,3119,"2,058.0",621,Aberdeen St & Randolph St,227,Southport Ave & Waveland Ave,member,...,-87.654286,15.0,0.0,Chicago,41.948150,-87.663940,15.0,235.0,Chicago,classic_bike
582950,18236889,17:45:45,17:49:30,5926,225.0,621,Aberdeen St & Randolph St,21,Aberdeen St & Jackson Blvd,member,...,-87.654286,15.0,0.0,Chicago,41.877726,-87.654787,15.0,157.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7392271,25961898,14:54:50,15:07:07,1048,737.0,621,Aberdeen St & Randolph St,50,Clark St & Ida B Wells Dr,member,...,-87.654286,15.0,0.0,Chicago,41.875933,-87.630585,27.0,9.0,Chicago,classic_bike
7392462,25962096,15:49:11,15:54:09,3794,297.0,621,Aberdeen St & Randolph St,346,Ada St & Washington Blvd,member,...,-87.654286,15.0,0.0,Chicago,41.882830,-87.661206,15.0,353.0,Chicago,classic_bike
7392810,25962466,17:29:56,17:34:37,3882,280.0,621,Aberdeen St & Randolph St,198,Green St & Madison St,member,...,-87.654286,15.0,0.0,Chicago,41.881750,-87.647800,19.0,159.0,Chicago,classic_bike
7392812,25962468,17:29:56,17:34:40,5010,283.0,621,Aberdeen St & Randolph St,198,Green St & Madison St,casual,...,-87.654286,15.0,0.0,Chicago,41.881750,-87.647800,19.0,159.0,Chicago,classic_bike
7392813,25962469,17:30:01,17:34:39,1438,278.0,621,Aberdeen St & Randolph St,198,Green St & Madison St,member,...,-87.654286,15.0,0.0,Chicago,41.881750,-87.647800,19.0,159.0,Chicago,classic_bike

In [89]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
988012,18709613,06:19:57,06:41:50,6222,"1,313.0",361,DIVVY CASSETTE REPAIR MOBILE STATION,77,Clinton St & Madison St,member,...,NaN,NaN,NaN,NaN,41.881582,-87.641277,23.0,301.0,Chicago,classic_bike
989304,18711125,07:45:56,08:13:31,4623,"1,655.0",361,DIVVY CASSETTE REPAIR MOBILE STATION,24,Fairbanks Ct & Grand Ave,member,...,NaN,NaN,NaN,NaN,41.891860,-87.620620,15.0,262.0,Chicago,classic_bike
1235969,19000213,00:21:17,00:27:26,6029,369.0,361,DIVVY CASSETTE REPAIR MOBILE STATION,44,State St & Randolph St,member,...,NaN,NaN,NaN,NaN,41.884730,-87.627734,27.0,2.0,Chicago,classic_bike
1238531,19003174,10:42:20,11:41:34,5743,"3,554.0",361,DIVVY CASSETTE REPAIR MOBILE STATION,35,Streeter Dr & Grand Ave,casual,...,NaN,NaN,NaN,NaN,41.891071,-87.612200,35.0,22.0,Chicago,classic_bike
1245338,19010926,17:42:41,17:57:41,5463,900.0,361,DIVVY CASSETTE REPAIR MOBILE STATION,301,Clark St & Schiller St,member,...,NaN,NaN,NaN,NaN,41.907993,-87.631501,19.0,200.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393029,25962705,19:44:54,20:10:37,4767,"1,542.0",657,Wood St & Augusta Blvd,332,Burling St (Halsted) & Diversey Pkwy (Temp),member,...,NaN,NaN,NaN,NaN,41.933341,-87.648747,15.0,208.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike
7393203,25962897,23:51:19,23:55:33,5654,254.0,638,Clinton St & Jackson Blvd,134,Peoria St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877749,-87.649633,19.0,158.0,Chicago,classic_bike

In [90]:
merged2018_2019[merged2018_2019['from_station_id'] == 361]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
988012,18709613,06:19:57,06:41:50,6222,"1,313.0",361,DIVVY CASSETTE REPAIR MOBILE STATION,77,Clinton St & Madison St,member,...,NaN,NaN,NaN,NaN,41.881582,-87.641277,23.0,301.0,Chicago,classic_bike
989304,18711125,07:45:56,08:13:31,4623,"1,655.0",361,DIVVY CASSETTE REPAIR MOBILE STATION,24,Fairbanks Ct & Grand Ave,member,...,NaN,NaN,NaN,NaN,41.891860,-87.620620,15.0,262.0,Chicago,classic_bike
1235969,19000213,00:21:17,00:27:26,6029,369.0,361,DIVVY CASSETTE REPAIR MOBILE STATION,44,State St & Randolph St,member,...,NaN,NaN,NaN,NaN,41.884730,-87.627734,27.0,2.0,Chicago,classic_bike
1238531,19003174,10:42:20,11:41:34,5743,"3,554.0",361,DIVVY CASSETTE REPAIR MOBILE STATION,35,Streeter Dr & Grand Ave,casual,...,NaN,NaN,NaN,NaN,41.891071,-87.612200,35.0,22.0,Chicago,classic_bike
1245338,19010926,17:42:41,17:57:41,5463,900.0,361,DIVVY CASSETTE REPAIR MOBILE STATION,301,Clark St & Schiller St,member,...,NaN,NaN,NaN,NaN,41.907993,-87.631501,19.0,200.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3222980,21296853,12:53:27,12:59:19,2332,352.0,361,DIVVY CASSETTE REPAIR MOBILE STATION,125,Rush St & Hubbard St,member,...,NaN,NaN,NaN,NaN,41.890011,-87.626293,15.0,533.0,Chicago,classic_bike
3567730,21707034,13:33:15,13:35:27,444,132.0,361,DIVVY CASSETTE REPAIR MOBILE STATION,215,Damen Ave & Madison St,member,...,NaN,NaN,NaN,NaN,41.881370,-87.674930,15.0,134.0,Chicago,classic_bike
4170681,22427587,10:42:14,10:44:03,5018,109.0,361,DIVVY CASSETTE REPAIR MOBILE STATION,361,DIVVY CASSETTE REPAIR MOBILE STATION,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4171907,22429216,13:23:58,13:35:41,5162,703.0,361,DIVVY CASSETTE REPAIR MOBILE STATION,426,Ellis Ave & 60th St,member,...,NaN,NaN,NaN,NaN,41.785097,-87.601073,19.0,481.0,Chicago,classic_bike
4440171,22748577,13:23:27,13:30:51,89,444.0,361,DIVVY CASSETTE REPAIR MOBILE STATION,111,Sedgwick St & Huron St,member,...,NaN,NaN,NaN,NaN,41.894666,-87.638437,19.0,52.0,Chicago,classic_bike

In [91]:
# id 621: 15 dpcacpacity, 'Chicago', lat = 41.880958 long = -87.616743

merged2018_2019.loc[merged2018_2019['from_station_id'] == 361, 'from_lat'] = 41.884100
merged2018_2019.loc[merged2018_2019['from_station_id'] == 361, 'from_long'] = -87.654286
merged2018_2019.loc[merged2018_2019['from_station_id'] == 361, 'dpcapacity_x'] = 0
merged2018_2019.loc[merged2018_2019['from_station_id'] == 361, 'from_city'] = 'Chicago'

merged2018_2019.loc[merged2018_2019['to_station_id'] == 361, 'to_lat'] = 41.884100
merged2018_2019.loc[merged2018_2019['to_station_id'] == 361, 'to_long'] = -87.654286
merged2018_2019.loc[merged2018_2019['to_station_id'] == 361, 'dpcapacity_y'] = 0
merged2018_2019.loc[merged2018_2019['to_station_id'] == 361, 'to_city'] = 'Chicago'

merged2018_2019.loc[merged2018_2019['from_station_id'] == 361, 'from_landmark'] = 0.0
merged2018_2019.loc[merged2018_2019['to_station_id'] == 361, 'to_landmark'] = 0.0

In [92]:
merged2018_2019.isnull().sum()

trip_id                   0
start_time                0
end_time                  0
bikeid                    0
tripduration              0
from_station_id           0
from_station_name         0
to_station_id             0
to_station_name           0
usertype                  0
gender                    0
birthyear                 0
start_date                0
end_date                  0
from_lat             112167
from_long            112167
dpcapacity_x         112167
from_landmark        112167
from_city            112167
to_lat               114550
to_long              114550
dpcapacity_y         114550
to_landmark          114550
to_city              114550
rideable_type             0
dtype: int64

In [93]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2461289,20413626,12:43:58,13:07:11,1733,"1,393.0",631,Malcolm X College,37,Dearborn St & Adams St,member,...,NaN,NaN,NaN,NaN,41.879356,-87.629791,19.0,20.0,Chicago,classic_bike
2461295,20413634,12:44:20,12:49:13,898,293.0,631,Malcolm X College,21,Aberdeen St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877726,-87.654787,15.0,157.0,Chicago,classic_bike
2461384,20413729,12:51:55,12:58:05,1740,370.0,631,Malcolm X College,631,Malcolm X College,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
2461731,20414169,13:24:20,13:40:52,1740,992.0,631,Malcolm X College,75,Canal St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.878114,-87.639971,35.0,138.0,Chicago,classic_bike
2461761,20414204,13:26:21,13:39:30,5087,789.0,631,Malcolm X College,631,Malcolm X College,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393029,25962705,19:44:54,20:10:37,4767,"1,542.0",657,Wood St & Augusta Blvd,332,Burling St (Halsted) & Diversey Pkwy (Temp),member,...,NaN,NaN,NaN,NaN,41.933341,-87.648747,15.0,208.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike
7393203,25962897,23:51:19,23:55:33,5654,254.0,638,Clinton St & Jackson Blvd,134,Peoria St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877749,-87.649633,19.0,158.0,Chicago,classic_bike

In [94]:
def fix_nulls(station_id=int,dpcapacity=int,lat_long=[],city=str,landmark=0):
    
    lat = lat_long[0]
    lng = lat_long[1]
    
    from_point = merged2018_2019['from_station_id'] == station_id
    to_point = merged2018_2019['to_station_id'] == station_id
    
    merged2018_2019.loc[from_point, 'from_lat'] = lat
    merged2018_2019.loc[from_point, 'from_long'] = lng
    merged2018_2019.loc[from_point, 'dpcapacity_x'] = dpcapacity
    merged2018_2019.loc[from_point, 'from_city'] = 'Chicago'
    merged2018_2019.loc[from_point, 'from_landmark'] = landmark
    
    merged2018_2019.loc[to_point, 'to_lat'] = lat
    merged2018_2019.loc[to_point, 'to_long'] = lng
    merged2018_2019.loc[to_point, 'dpcapacity_y'] = dpcapacity
    merged2018_2019.loc[to_point, 'to_city'] = 'Chicago'
    merged2018_2019.loc[to_point, 'to_landmark'] = landmark

    
fix_nulls(631, 17, [41.87763299333187, -87.67389247653337], 'Chicago')

In [95]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2550082,20516248,15:02:42,15:19:43,2459,"1,021.0",630,Kildare Ave & Montrose Ave,498,California Ave & Fletcher St,member,...,NaN,NaN,NaN,NaN,41.938429,-87.698008,19.0,642.0,Chicago,classic_bike
2553025,20519633,06:36:27,07:07:40,236,"1,873.0",630,Kildare Ave & Montrose Ave,307,Southport Ave & Clybourn Ave,member,...,NaN,NaN,NaN,NaN,41.921004,-87.663257,15.0,186.0,Chicago,classic_bike
2571563,20541321,08:19:21,08:24:46,4507,325.0,630,Kildare Ave & Montrose Ave,483,Avondale Ave & Irving Park Rd,member,...,NaN,NaN,NaN,NaN,41.953850,-87.732370,19.0,624.0,Chicago,classic_bike
2592257,20565763,21:43:13,22:06:26,1901,"1,393.0",630,Kildare Ave & Montrose Ave,326,Clark St & Leland Ave,member,...,NaN,NaN,NaN,NaN,41.967096,-87.667429,11.0,239.0,Chicago,classic_bike
2594501,20568301,07:42:01,07:47:11,2935,310.0,630,Kildare Ave & Montrose Ave,483,Avondale Ave & Irving Park Rd,member,...,NaN,NaN,NaN,NaN,41.953850,-87.732370,19.0,624.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393029,25962705,19:44:54,20:10:37,4767,"1,542.0",657,Wood St & Augusta Blvd,332,Burling St (Halsted) & Diversey Pkwy (Temp),member,...,NaN,NaN,NaN,NaN,41.933341,-87.648747,15.0,208.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike
7393203,25962897,23:51:19,23:55:33,5654,254.0,638,Clinton St & Jackson Blvd,134,Peoria St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877749,-87.649633,19.0,158.0,Chicago,classic_bike

In [96]:
fix_nulls(630, 15, [41.96109534681988, -87.73570245324244], 'Chicago')

In [97]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2673245,20659813,15:59:06,16:07:19,292,493.0,659,Leavitt St & Chicago Ave,213,Leavitt St & North Ave,member,...,NaN,NaN,NaN,NaN,41.910652,-87.682400,11.0,244.0,Chicago,classic_bike
2682729,20670211,06:18:29,06:29:56,156,687.0,657,Wood St & Augusta Blvd,71,Morgan St & Lake St,member,...,NaN,NaN,NaN,NaN,41.885483,-87.652305,15.0,72.0,Chicago,classic_bike
2683696,20671291,07:23:04,07:28:00,1446,296.0,657,Wood St & Augusta Blvd,210,Ashland Ave & Division St,member,...,NaN,NaN,NaN,NaN,41.903456,-87.667770,19.0,61.0,Chicago,classic_bike
2683757,20671366,07:26:10,07:30:44,1877,274.0,657,Wood St & Augusta Blvd,210,Ashland Ave & Division St,member,...,NaN,NaN,NaN,NaN,41.903456,-87.667770,19.0,61.0,Chicago,classic_bike
2684569,20672250,07:54:09,07:57:16,2806,187.0,657,Wood St & Augusta Blvd,210,Ashland Ave & Division St,member,...,NaN,NaN,NaN,NaN,41.903456,-87.667770,19.0,61.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393029,25962705,19:44:54,20:10:37,4767,"1,542.0",657,Wood St & Augusta Blvd,332,Burling St (Halsted) & Diversey Pkwy (Temp),member,...,NaN,NaN,NaN,NaN,41.933341,-87.648747,15.0,208.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike
7393203,25962897,23:51:19,23:55:33,5654,254.0,638,Clinton St & Jackson Blvd,134,Peoria St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877749,-87.649633,19.0,158.0,Chicago,classic_bike

In [98]:
merged2018_2019[merged2018_2019['from_station_name']=='Leavitt St & Chicago Ave']

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2673245,20659813,15:59:06,16:07:19,292,493.0,659,Leavitt St & Chicago Ave,213,Leavitt St & North Ave,member,...,NaN,NaN,NaN,NaN,41.910652,-87.682400,11.0,244.0,Chicago,classic_bike
2685746,20673622,08:30:16,08:58:05,4460,"1,669.0",659,Leavitt St & Chicago Ave,68,Clinton St & Tilden St,member,...,NaN,NaN,NaN,NaN,41.875885,-87.640795,23.0,37.0,Chicago,classic_bike
2688166,20676643,11:37:19,11:53:38,5344,979.0,659,Leavitt St & Chicago Ave,77,Clinton St & Madison St,member,...,NaN,NaN,NaN,NaN,41.881582,-87.641277,23.0,301.0,Chicago,classic_bike
2690388,20679124,14:37:06,14:44:48,4110,462.0,659,Leavitt St & Chicago Ave,17,Honore St & Division St,member,...,NaN,NaN,NaN,NaN,41.903320,-87.672730,15.0,246.0,Chicago,classic_bike
2692621,20681745,16:39:13,17:02:46,3469,"1,413.0",659,Leavitt St & Chicago Ave,75,Canal St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.878114,-87.639971,35.0,138.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7387864,25957289,06:06:39,06:21:59,2007,919.0,659,Leavitt St & Chicago Ave,211,St. Clair St & Erie St,member,...,NaN,NaN,NaN,NaN,41.894448,-87.622663,19.0,16.0,Chicago,classic_bike
7388292,25957734,08:17:01,08:22:21,719,319.0,659,Leavitt St & Chicago Ave,285,Wood St & Hubbard St,member,...,NaN,NaN,NaN,NaN,41.891130,-87.672030,15.0,432.0,Chicago,classic_bike
7391119,25960696,06:29:14,06:47:48,3739,"1,113.0",659,Leavitt St & Chicago Ave,211,St. Clair St & Erie St,member,...,NaN,NaN,NaN,NaN,41.894448,-87.622663,19.0,16.0,Chicago,classic_bike
7391177,25960756,07:11:09,07:35:42,3499,"1,473.0",659,Leavitt St & Chicago Ave,142,McClurg Ct & Erie St,member,...,NaN,NaN,NaN,NaN,41.894314,-87.617420,19.0,531.0,Chicago,classic_bike
7391354,25960942,08:28:46,08:47:15,2076,"1,108.0",659,Leavitt St & Chicago Ave,192,Canal St & Adams St,member,...,NaN,NaN,NaN,NaN,41.879230,-87.640015,27.0,11.0,Chicago,classic_bike

In [99]:
fix_nulls(659, 15, [41.895485, -87.682008], 'Chicago')

In [100]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2682729,20670211,06:18:29,06:29:56,156,687.0,657,Wood St & Augusta Blvd,71,Morgan St & Lake St,member,...,NaN,NaN,NaN,NaN,41.885483,-87.652305,15.0,72.0,Chicago,classic_bike
2683696,20671291,07:23:04,07:28:00,1446,296.0,657,Wood St & Augusta Blvd,210,Ashland Ave & Division St,member,...,NaN,NaN,NaN,NaN,41.903456,-87.667770,19.0,61.0,Chicago,classic_bike
2683757,20671366,07:26:10,07:30:44,1877,274.0,657,Wood St & Augusta Blvd,210,Ashland Ave & Division St,member,...,NaN,NaN,NaN,NaN,41.903456,-87.667770,19.0,61.0,Chicago,classic_bike
2684569,20672250,07:54:09,07:57:16,2806,187.0,657,Wood St & Augusta Blvd,210,Ashland Ave & Division St,member,...,NaN,NaN,NaN,NaN,41.903456,-87.667770,19.0,61.0,Chicago,classic_bike
2684783,20672490,08:00:36,08:12:00,3819,684.0,657,Wood St & Augusta Blvd,66,Clinton St & Lake St,member,...,NaN,NaN,NaN,NaN,41.885833,-87.641382,19.0,21.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393029,25962705,19:44:54,20:10:37,4767,"1,542.0",657,Wood St & Augusta Blvd,332,Burling St (Halsted) & Diversey Pkwy (Temp),member,...,NaN,NaN,NaN,NaN,41.933341,-87.648747,15.0,208.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike
7393203,25962897,23:51:19,23:55:33,5654,254.0,638,Clinton St & Jackson Blvd,134,Peoria St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877749,-87.649633,19.0,158.0,Chicago,classic_bike

In [101]:
fix_nulls(657, 15, [41.899168, -87.672199], 'Chicago')

In [102]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2763862,20762713,17:30:52,18:10:46,647,"2,394.0",628,Walsh Park,116,Western Ave & Winnebago Ave,casual,...,NaN,NaN,NaN,NaN,41.915533,-87.687051,15.0,68.0,Chicago,classic_bike
2763879,20762730,17:31:12,18:11:13,6374,"2,401.0",628,Walsh Park,116,Western Ave & Winnebago Ave,casual,...,NaN,NaN,NaN,NaN,41.915533,-87.687051,15.0,68.0,Chicago,classic_bike
2764855,20763759,17:55:41,20:17:38,4493,"8,517.0",628,Walsh Park,628,Walsh Park,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
2765841,20764849,18:24:43,18:37:00,637,737.0,628,Walsh Park,23,Orleans St & Elm St (*),member,...,NaN,NaN,NaN,NaN,41.902924,-87.637715,15.0,172.0,Chicago,classic_bike
2777116,20778007,15:03:37,15:12:15,1739,518.0,628,Walsh Park,309,Leavitt St & Armitage Ave,member,...,NaN,NaN,NaN,NaN,41.917805,-87.682437,11.0,286.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393001,25962677,19:23:38,19:29:31,3209,352.0,635,Fairbanks St & Superior St,26,McClurg Ct & Illinois St,member,...,NaN,NaN,NaN,NaN,41.891020,-87.617300,23.0,51.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike
7393203,25962897,23:51:19,23:55:33,5654,254.0,638,Clinton St & Jackson Blvd,134,Peoria St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877749,-87.649633,19.0,158.0,Chicago,classic_bike

In [103]:
fix_nulls(628, 24, [41.914543, -87.667983], 'Chicago')

In [104]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2777253,20778176,15:15:55,15:24:08,6439,493.0,639,Lakefront Trail & Wilson Ave,295,Broadway & Argyle St,member,...,NaN,NaN,NaN,NaN,41.972972,-87.659637,15.0,108.0,Chicago,classic_bike
2782968,20784605,18:40:35,18:57:19,5071,"1,004.0",636,Orleans St & Hubbard St (*),145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike
2783796,20785567,19:22:55,20:04:38,591,"2,503.0",639,Lakefront Trail & Wilson Ave,140,Dearborn Pkwy & Delaware Pl,member,...,NaN,NaN,NaN,NaN,41.899007,-87.629928,19.0,173.0,Chicago,classic_bike
2783906,20785690,19:30:14,19:45:45,2904,931.0,639,Lakefront Trail & Wilson Ave,34,Cannon Dr & Fullerton Ave,member,...,NaN,NaN,NaN,NaN,41.926756,-87.634429,15.0,124.0,Chicago,classic_bike
2784016,20785812,19:38:05,19:45:36,2365,451.0,636,Orleans St & Hubbard St (*),620,Orleans St & Chestnut St (NEXT Apts),member,...,NaN,NaN,NaN,NaN,41.898203,-87.637536,15.0,0.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393001,25962677,19:23:38,19:29:31,3209,352.0,635,Fairbanks St & Superior St,26,McClurg Ct & Illinois St,member,...,NaN,NaN,NaN,NaN,41.891020,-87.617300,23.0,51.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike
7393203,25962897,23:51:19,23:55:33,5654,254.0,638,Clinton St & Jackson Blvd,134,Peoria St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877749,-87.649633,19.0,158.0,Chicago,classic_bike

In [105]:
fix_nulls(639, 15, [41.965868, -87.645356], 'Chicago')

In [106]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2782968,20784605,18:40:35,18:57:19,5071,"1,004.0",636,Orleans St & Hubbard St (*),145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike
2784016,20785812,19:38:05,19:45:36,2365,451.0,636,Orleans St & Hubbard St (*),620,Orleans St & Chestnut St (NEXT Apts),member,...,NaN,NaN,NaN,NaN,41.898203,-87.637536,15.0,0.0,Chicago,classic_bike
2792449,20795767,12:54:21,13:06:02,5283,701.0,636,Orleans St & Hubbard St (*),289,Wells St & Concord Ln,member,...,NaN,NaN,NaN,NaN,41.912202,-87.634664,19.0,182.0,Chicago,classic_bike
2793076,20796514,13:47:56,13:56:33,5013,517.0,636,Orleans St & Hubbard St (*),283,LaSalle St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.878170,-87.631985,23.0,32.0,Chicago,classic_bike
2793764,20797370,14:51:56,15:01:59,4914,603.0,636,Orleans St & Hubbard St (*),176,Clark St & Elm St,member,...,NaN,NaN,NaN,NaN,41.903233,-87.631253,19.0,349.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393001,25962677,19:23:38,19:29:31,3209,352.0,635,Fairbanks St & Superior St,26,McClurg Ct & Illinois St,member,...,NaN,NaN,NaN,NaN,41.891020,-87.617300,23.0,51.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike
7393203,25962897,23:51:19,23:55:33,5654,254.0,638,Clinton St & Jackson Blvd,134,Peoria St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877749,-87.649633,19.0,158.0,Chicago,classic_bike

In [107]:
fix_nulls(636, 11, [41.890039, -87.63661894], 'Chicago')

In [108]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2795567,20799565,16:39:02,16:49:17,1200,615.0,635,Fairbanks St & Superior St (*),7,Field Blvd & South Water St,member,...,NaN,NaN,NaN,NaN,41.886349,-87.617517,19.0,534.0,Chicago,classic_bike
2798122,20802354,17:46:18,17:58:06,4122,708.0,635,Fairbanks St & Superior St (*),212,Wells St & Hubbard St,member,...,NaN,NaN,NaN,NaN,41.892238,-87.633985,19.0,264.0,Chicago,classic_bike
2807723,20813643,12:57:59,13:01:29,61,210.0,635,Fairbanks St & Superior St (*),24,Fairbanks Ct & Grand Ave,member,...,NaN,NaN,NaN,NaN,41.891860,-87.620620,15.0,262.0,Chicago,classic_bike
2809062,20815287,15:02:23,15:14:55,103,752.0,635,Fairbanks St & Superior St (*),50,Clark St & Congress Pkwy,member,...,NaN,NaN,NaN,NaN,41.875933,-87.630585,27.0,9.0,Chicago,classic_bike
2809776,20816150,15:52:51,16:09:13,3904,982.0,635,Fairbanks St & Superior St (*),192,Canal St & Adams St,member,...,NaN,NaN,NaN,NaN,41.879230,-87.640015,27.0,11.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393001,25962677,19:23:38,19:29:31,3209,352.0,635,Fairbanks St & Superior St,26,McClurg Ct & Illinois St,member,...,NaN,NaN,NaN,NaN,41.891020,-87.617300,23.0,51.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike
7393203,25962897,23:51:19,23:55:33,5654,254.0,638,Clinton St & Jackson Blvd,134,Peoria St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877749,-87.649633,19.0,158.0,Chicago,classic_bike

In [109]:
fix_nulls(635, 11, [41.895755, -87.620159], 'Chicago')

In [110]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2899026,20919068,16:01:54,16:06:52,6232,298.0,638,Clinton St & Jackson Blvd (*),96,Desplaines St & Randolph St,member,...,NaN,NaN,NaN,NaN,41.884616,-87.644571,23.0,535.0,Chicago,classic_bike
2900414,20920694,16:54:41,17:02:09,3735,448.0,638,Clinton St & Jackson Blvd (*),66,Clinton St & Lake St,member,...,NaN,NaN,NaN,NaN,41.885833,-87.641382,19.0,21.0,Chicago,classic_bike
2902317,20922703,17:39:29,17:56:40,3290,"1,031.0",638,Clinton St & Jackson Blvd (*),210,Ashland Ave & Division St,member,...,NaN,NaN,NaN,NaN,41.903456,-87.667770,19.0,61.0,Chicago,classic_bike
2902360,20922751,17:40:51,18:01:28,2638,"1,237.0",638,Clinton St & Jackson Blvd (*),69,Damen Ave & Pierce Ave,member,...,NaN,NaN,NaN,NaN,41.909396,-87.677692,19.0,65.0,Chicago,classic_bike
2902388,20922782,17:41:38,17:51:27,3134,589.0,638,Clinton St & Jackson Blvd (*),84,Milwaukee Ave & Grand Ave,member,...,NaN,NaN,NaN,NaN,41.891733,-87.648727,19.0,33.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7392987,25962662,19:11:29,19:27:05,4705,935.0,644,Western Ave & Fillmore St (*),659,Leavitt St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.895485,-87.682008,15.0,0.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike
7393203,25962897,23:51:19,23:55:33,5654,254.0,638,Clinton St & Jackson Blvd,134,Peoria St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877749,-87.649633,19.0,158.0,Chicago,classic_bike

In [111]:
fix_nulls(638, 31, [41.878432, -87.640989], 'Chicago')

In [112]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2924077,20947721,06:20:50,06:37:24,6379,994.0,637,Wood St & Chicago Ave (*),211,St. Clair St & Erie St,member,...,NaN,NaN,NaN,NaN,41.894448,-87.622663,19.0,16.0,Chicago,classic_bike
2924829,20948589,07:23:59,07:37:02,5666,783.0,637,Wood St & Chicago Ave (*),383,Ashland Ave & Harrison St,member,...,NaN,NaN,NaN,NaN,41.874291,-87.667246,23.0,669.0,Chicago,classic_bike
2924834,20948595,07:24:08,07:34:35,5534,627.0,637,Wood St & Chicago Ave (*),58,Marshfield Ave & Cortland St,member,...,NaN,NaN,NaN,NaN,41.917859,-87.668919,15.0,25.0,Chicago,classic_bike
2925869,20949731,08:05:27,08:22:36,4196,"1,029.0",637,Wood St & Chicago Ave (*),181,LaSalle St & Illinois St,member,...,NaN,NaN,NaN,NaN,41.890749,-87.632060,19.0,430.0,Chicago,classic_bike
2926099,20949992,08:14:20,08:34:25,5326,"1,205.0",643,Smith Park (*),161,Rush St & Superior St,member,...,NaN,NaN,NaN,NaN,41.895765,-87.625908,23.0,530.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7392972,25962647,19:02:59,19:11:56,5856,536.0,632,Clark St & Newport St,152,Lincoln Ave & Diversey Pkwy,casual,...,NaN,NaN,NaN,NaN,41.932225,-87.658617,15.0,226.0,Chicago,classic_bike
7392987,25962662,19:11:29,19:27:05,4705,935.0,644,Western Ave & Fillmore St (*),659,Leavitt St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.895485,-87.682008,15.0,0.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike

In [113]:
fix_nulls(637, 15, [41.895653, -87.672051], 'Chicago')

In [114]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2926099,20949992,08:14:20,08:34:25,5326,"1,205.0",643,Smith Park (*),161,Rush St & Superior St,member,...,NaN,NaN,NaN,NaN,41.895765,-87.625908,23.0,530.0,Chicago,classic_bike
2927797,20952133,09:39:52,09:59:01,2460,"1,149.0",643,Smith Park (*),192,Canal St & Adams St,member,...,NaN,NaN,NaN,NaN,41.879230,-87.640015,27.0,11.0,Chicago,classic_bike
2941065,20967707,14:39:32,15:02:11,1672,"1,359.0",643,Smith Park (*),309,Leavitt St & Armitage Ave,member,...,NaN,NaN,NaN,NaN,41.917805,-87.682437,11.0,286.0,Chicago,classic_bike
2957517,20986206,08:11:07,08:31:16,6315,"1,209.0",643,Smith Park (*),110,Dearborn St & Erie St,member,...,NaN,NaN,NaN,NaN,41.893975,-87.628623,23.0,45.0,Chicago,classic_bike
2959018,20988079,09:18:18,09:39:27,2056,"1,269.0",643,Smith Park (*),174,Canal St & Madison St,member,...,NaN,NaN,NaN,NaN,41.882091,-87.639833,23.0,341.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7392972,25962647,19:02:59,19:11:56,5856,536.0,632,Clark St & Newport St,152,Lincoln Ave & Diversey Pkwy,casual,...,NaN,NaN,NaN,NaN,41.932225,-87.658617,15.0,226.0,Chicago,classic_bike
7392987,25962662,19:11:29,19:27:05,4705,935.0,644,Western Ave & Fillmore St (*),659,Leavitt St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.895485,-87.682008,15.0,0.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike

In [115]:
fix_nulls(643, 16, [41.892003, -87.689397], 'Chicago')

In [116]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2976615,21008455,14:15:44,14:48:32,5884,"1,968.0",646,State St & 54th St,646,State St & 54th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
2992944,21027301,14:29:09,14:43:37,2331,868.0,641,Central Park Ave & Bloomingdale Ave,219,Damen Ave & Cortland St,member,...,NaN,NaN,NaN,NaN,41.916027,-87.677411,11.0,133.0,Chicago,classic_bike
2995979,21030907,17:09:26,17:28:28,57,"1,142.0",641,Central Park Ave & Bloomingdale Ave,590,Kilbourn Ave & Irving Park Rd,member,...,NaN,NaN,NaN,NaN,41.953733,-87.740569,15.0,0.0,Chicago,classic_bike
2998969,21034119,18:29:26,19:15:16,78,"2,750.0",641,Central Park Ave & Bloomingdale Ave,116,Western Ave & Winnebago Ave,member,...,NaN,NaN,NaN,NaN,41.915533,-87.687051,15.0,68.0,Chicago,classic_bike
2998977,21034128,18:29:57,19:15:26,2311,"2,729.0",641,Central Park Ave & Bloomingdale Ave,116,Western Ave & Winnebago Ave,member,...,NaN,NaN,NaN,NaN,41.915533,-87.687051,15.0,68.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7392972,25962647,19:02:59,19:11:56,5856,536.0,632,Clark St & Newport St,152,Lincoln Ave & Diversey Pkwy,casual,...,NaN,NaN,NaN,NaN,41.932225,-87.658617,15.0,226.0,Chicago,classic_bike
7392987,25962662,19:11:29,19:27:05,4705,935.0,644,Western Ave & Fillmore St (*),659,Leavitt St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.895485,-87.682008,15.0,0.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike
7393176,25962867,23:26:58,23:52:59,2609,"1,560.0",641,Central Park Ave & Bloomingdale Ave,641,Central Park Ave & Bloomingdale Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7393196,25962890,23:46:19,23:53:51,41,451.0,641,Central Park Ave & Bloomingdale Ave,259,California Ave & Francis Pl (Temp),member,...,NaN,NaN,NaN,NaN,41.918550,-87.697230,15.0,259.0,Chicago,classic_bike

In [117]:
fix_nulls(641, 11, [41.914151, -87.716788], 'Chicago')

In [118]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2976615,21008455,14:15:44,14:48:32,5884,"1,968.0",646,State St & 54th St,646,State St & 54th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3003236,21038942,07:23:01,07:29:19,3747,378.0,655,Hoyne Ave & Balmoral Ave,242,Damen Ave & Leland Ave,member,...,NaN,NaN,NaN,NaN,41.967094,-87.679028,15.0,93.0,Chicago,classic_bike
3010099,21047286,16:20:02,16:44:04,1374,"1,442.0",646,State St & 54th St,646,State St & 54th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3010987,21048355,16:55:58,17:12:21,3096,983.0,655,Hoyne Ave & Balmoral Ave,459,Lakefront Trail & Bryn Mawr Ave,member,...,NaN,NaN,NaN,NaN,41.984037,-87.652310,19.0,576.0,Chicago,classic_bike
3018187,21056726,11:38:40,11:45:57,995,437.0,660,Sheridan Rd & Columbia Ave,520,Greenview Ave & Jarvis Ave,member,...,NaN,NaN,NaN,NaN,42.015962,-87.668570,23.0,0.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7392818,25962475,17:33:07,17:54:09,5996,"1,261.0",673,Lincoln Park Conservatory,145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike
7392922,25962595,18:27:31,18:45:40,3647,"1,089.0",632,Clark St & Newport St,93,Sheffield Ave & Willow St,member,...,NaN,NaN,NaN,NaN,41.913688,-87.652855,15.0,190.0,Chicago,classic_bike
7392972,25962647,19:02:59,19:11:56,5856,536.0,632,Clark St & Newport St,152,Lincoln Ave & Diversey Pkwy,casual,...,NaN,NaN,NaN,NaN,41.932225,-87.658617,15.0,226.0,Chicago,classic_bike
7392987,25962662,19:11:29,19:27:05,4705,935.0,644,Western Ave & Fillmore St (*),659,Leavitt St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.895485,-87.682008,15.0,0.0,Chicago,classic_bike
7393155,25962845,23:05:47,23:16:54,4877,666.0,644,Western Ave & Fillmore St (*),22,May St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869482,-87.655486,15.0,160.0,Chicago,classic_bike

In [119]:
fix_nulls(644, 12, [41.868629, -87.686244], 'Chicago')

In [120]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2976615,21008455,14:15:44,14:48:32,5884,"1,968.0",646,State St & 54th St,646,State St & 54th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3003236,21038942,07:23:01,07:29:19,3747,378.0,655,Hoyne Ave & Balmoral Ave,242,Damen Ave & Leland Ave,member,...,NaN,NaN,NaN,NaN,41.967094,-87.679028,15.0,93.0,Chicago,classic_bike
3010099,21047286,16:20:02,16:44:04,1374,"1,442.0",646,State St & 54th St,646,State St & 54th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3010987,21048355,16:55:58,17:12:21,3096,983.0,655,Hoyne Ave & Balmoral Ave,459,Lakefront Trail & Bryn Mawr Ave,member,...,NaN,NaN,NaN,NaN,41.984037,-87.652310,19.0,576.0,Chicago,classic_bike
3018187,21056726,11:38:40,11:45:57,995,437.0,660,Sheridan Rd & Columbia Ave,520,Greenview Ave & Jarvis Ave,member,...,NaN,NaN,NaN,NaN,42.015962,-87.668570,23.0,0.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7392748,25962400,17:06:06,17:17:15,1408,669.0,672,Franklin St & Illinois St,654,Racine Ave & Washington Blvd (*),member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7392787,25962443,17:21:25,17:25:45,6439,260.0,632,Clark St & Newport St,226,Racine Ave & Belmont Ave,member,...,NaN,NaN,NaN,NaN,41.939743,-87.658865,15.0,230.0,Chicago,classic_bike
7392818,25962475,17:33:07,17:54:09,5996,"1,261.0",673,Lincoln Park Conservatory,145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike
7392922,25962595,18:27:31,18:45:40,3647,"1,089.0",632,Clark St & Newport St,93,Sheffield Ave & Willow St,member,...,NaN,NaN,NaN,NaN,41.913688,-87.652855,15.0,190.0,Chicago,classic_bike
7392972,25962647,19:02:59,19:11:56,5856,536.0,632,Clark St & Newport St,152,Lincoln Ave & Diversey Pkwy,casual,...,NaN,NaN,NaN,NaN,41.932225,-87.658617,15.0,226.0,Chicago,classic_bike

In [121]:
fix_nulls(632, 15, [41.944586, -87.654675], 'Chicago')

In [122]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2976615,21008455,14:15:44,14:48:32,5884,"1,968.0",646,State St & 54th St,646,State St & 54th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3003236,21038942,07:23:01,07:29:19,3747,378.0,655,Hoyne Ave & Balmoral Ave,242,Damen Ave & Leland Ave,member,...,NaN,NaN,NaN,NaN,41.967094,-87.679028,15.0,93.0,Chicago,classic_bike
3010099,21047286,16:20:02,16:44:04,1374,"1,442.0",646,State St & 54th St,646,State St & 54th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3010987,21048355,16:55:58,17:12:21,3096,983.0,655,Hoyne Ave & Balmoral Ave,459,Lakefront Trail & Bryn Mawr Ave,member,...,NaN,NaN,NaN,NaN,41.984037,-87.652310,19.0,576.0,Chicago,classic_bike
3018187,21056726,11:38:40,11:45:57,995,437.0,660,Sheridan Rd & Columbia Ave,520,Greenview Ave & Jarvis Ave,member,...,NaN,NaN,NaN,NaN,42.015962,-87.668570,23.0,0.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7392582,25962227,16:22:15,16:25:09,6274,173.0,672,Franklin St & Illinois St,31,Franklin St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.896802,-87.635638,23.0,17.0,Chicago,classic_bike
7392639,25962287,16:34:54,16:41:41,1328,407.0,672,Franklin St & Illinois St,191,Canal St & Monroe St,member,...,NaN,NaN,NaN,NaN,41.880700,-87.639470,23.0,56.0,Chicago,classic_bike
7392656,25962304,16:39:36,16:46:34,5703,418.0,656,Damen Ave & Walnut (Lake) St (*),659,Leavitt St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.895485,-87.682008,15.0,0.0,Chicago,classic_bike
7392748,25962400,17:06:06,17:17:15,1408,669.0,672,Franklin St & Illinois St,654,Racine Ave & Washington Blvd (*),member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7392818,25962475,17:33:07,17:54:09,5996,"1,261.0",673,Lincoln Park Conservatory,145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike

In [123]:
fix_nulls(672, 9, [41.89103, -87.63548], 'Chicago')

In [124]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2976615,21008455,14:15:44,14:48:32,5884,"1,968.0",646,State St & 54th St,646,State St & 54th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3003236,21038942,07:23:01,07:29:19,3747,378.0,655,Hoyne Ave & Balmoral Ave,242,Damen Ave & Leland Ave,member,...,NaN,NaN,NaN,NaN,41.967094,-87.679028,15.0,93.0,Chicago,classic_bike
3010099,21047286,16:20:02,16:44:04,1374,"1,442.0",646,State St & 54th St,646,State St & 54th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3010987,21048355,16:55:58,17:12:21,3096,983.0,655,Hoyne Ave & Balmoral Ave,459,Lakefront Trail & Bryn Mawr Ave,member,...,NaN,NaN,NaN,NaN,41.984037,-87.652310,19.0,576.0,Chicago,classic_bike
3018187,21056726,11:38:40,11:45:57,995,437.0,660,Sheridan Rd & Columbia Ave,520,Greenview Ave & Jarvis Ave,member,...,NaN,NaN,NaN,NaN,42.015962,-87.668570,23.0,0.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7391832,25961435,12:17:03,12:32:50,1884,947.0,673,Lincoln Park Conservatory,48,Larrabee St & Kingsbury St,member,...,NaN,NaN,NaN,NaN,41.897764,-87.642884,27.0,12.0,Chicago,classic_bike
7392272,25961899,14:55:21,15:26:43,2249,"1,882.0",640,Bernard St & Elston Ave,94,Clark St & Armitage Ave,member,...,NaN,NaN,NaN,NaN,41.918273,-87.638116,19.0,146.0,Chicago,classic_bike
7392570,25962215,16:19:30,16:38:05,5883,"1,115.0",660,Sheridan Rd & Columbia Ave,325,Clark St & Winnemac Ave,member,...,NaN,NaN,NaN,NaN,41.973385,-87.668365,15.0,392.0,Chicago,classic_bike
7392656,25962304,16:39:36,16:46:34,5703,418.0,656,Damen Ave & Walnut (Lake) St (*),659,Leavitt St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.895485,-87.682008,15.0,0.0,Chicago,classic_bike
7392818,25962475,17:33:07,17:54:09,5996,"1,261.0",673,Lincoln Park Conservatory,145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike

In [125]:
fix_nulls(660, 15, [42.00459, -87.66141], 'Chicago')

In [126]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2976615,21008455,14:15:44,14:48:32,5884,"1,968.0",646,State St & 54th St,646,State St & 54th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3003236,21038942,07:23:01,07:29:19,3747,378.0,655,Hoyne Ave & Balmoral Ave,242,Damen Ave & Leland Ave,member,...,NaN,NaN,NaN,NaN,41.967094,-87.679028,15.0,93.0,Chicago,classic_bike
3010099,21047286,16:20:02,16:44:04,1374,"1,442.0",646,State St & 54th St,646,State St & 54th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3010987,21048355,16:55:58,17:12:21,3096,983.0,655,Hoyne Ave & Balmoral Ave,459,Lakefront Trail & Bryn Mawr Ave,member,...,NaN,NaN,NaN,NaN,41.984037,-87.652310,19.0,576.0,Chicago,classic_bike
3028408,21068557,11:43:23,11:57:03,5952,820.0,655,Hoyne Ave & Balmoral Ave,459,Lakefront Trail & Bryn Mawr Ave,member,...,NaN,NaN,NaN,NaN,41.984037,-87.652310,19.0,576.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7391649,25961245,11:02:41,11:20:10,3309,"1,049.0",646,State St & 54th St,407,State St & Pershing Rd,member,...,NaN,NaN,NaN,NaN,41.823015,-87.626568,19.0,449.0,Chicago,classic_bike
7391832,25961435,12:17:03,12:32:50,1884,947.0,673,Lincoln Park Conservatory,48,Larrabee St & Kingsbury St,member,...,NaN,NaN,NaN,NaN,41.897764,-87.642884,27.0,12.0,Chicago,classic_bike
7392272,25961899,14:55:21,15:26:43,2249,"1,882.0",640,Bernard St & Elston Ave,94,Clark St & Armitage Ave,member,...,NaN,NaN,NaN,NaN,41.918273,-87.638116,19.0,146.0,Chicago,classic_bike
7392656,25962304,16:39:36,16:46:34,5703,418.0,656,Damen Ave & Walnut (Lake) St (*),659,Leavitt St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.895485,-87.682008,15.0,0.0,Chicago,classic_bike
7392818,25962475,17:33:07,17:54:09,5996,"1,261.0",673,Lincoln Park Conservatory,145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike

In [127]:
fix_nulls(655, 14, [41.97991, -87.68193], 'Chicago')

In [128]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
2976615,21008455,14:15:44,14:48:32,5884,"1,968.0",646,State St & 54th St,646,State St & 54th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3010099,21047286,16:20:02,16:44:04,1374,"1,442.0",646,State St & 54th St,646,State St & 54th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3033107,21073837,18:47:50,19:26:50,1374,"2,340.0",646,State St & 54th St,646,State St & 54th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3064537,21110294,12:06:19,12:41:33,1374,"2,114.0",646,State St & 54th St,193,State St & 29th St,member,...,NaN,NaN,NaN,NaN,41.841707,-87.626938,15.0,213.0,Chicago,classic_bike
3117429,21172079,09:39:33,09:52:42,1374,789.0,646,State St & 54th St,423,University Ave & 57th St,member,...,NaN,NaN,NaN,NaN,41.791476,-87.599414,19.0,478.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7391649,25961245,11:02:41,11:20:10,3309,"1,049.0",646,State St & 54th St,407,State St & Pershing Rd,member,...,NaN,NaN,NaN,NaN,41.823015,-87.626568,19.0,449.0,Chicago,classic_bike
7391832,25961435,12:17:03,12:32:50,1884,947.0,673,Lincoln Park Conservatory,48,Larrabee St & Kingsbury St,member,...,NaN,NaN,NaN,NaN,41.897764,-87.642884,27.0,12.0,Chicago,classic_bike
7392272,25961899,14:55:21,15:26:43,2249,"1,882.0",640,Bernard St & Elston Ave,94,Clark St & Armitage Ave,member,...,NaN,NaN,NaN,NaN,41.918273,-87.638116,19.0,146.0,Chicago,classic_bike
7392656,25962304,16:39:36,16:46:34,5703,418.0,656,Damen Ave & Walnut (Lake) St (*),659,Leavitt St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.895485,-87.682008,15.0,0.0,Chicago,classic_bike
7392818,25962475,17:33:07,17:54:09,5996,"1,261.0",673,Lincoln Park Conservatory,145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike

In [129]:
fix_nulls(646, 11, [41.79708, -87.62596], 'Chicago')

In [130]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3132718,21189770,17:29:07,17:49:54,5722,"1,247.0",640,Bernard St & Elston Ave,239,Western Ave & Leland Ave,member,...,NaN,NaN,NaN,NaN,41.966555,-87.688487,15.0,112.0,Chicago,classic_bike
3159034,21220891,22:45:22,22:53:53,1587,511.0,654,Racine Ave & Washington Blvd (*),350,Ashland Ave & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.895966,-87.667747,15.0,247.0,Chicago,classic_bike
3159398,21221306,06:07:09,06:10:48,5904,219.0,654,Racine Ave & Washington Blvd (*),112,Green St & Randolph St,member,...,NaN,NaN,NaN,NaN,41.884078,-87.648684,15.0,53.0,Chicago,classic_bike
3163754,21226669,12:33:09,12:49:28,6072,979.0,654,Racine Ave & Washington Blvd (*),31,Franklin St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.896802,-87.635638,23.0,17.0,Chicago,classic_bike
3164129,21227132,13:15:47,13:24:49,5251,542.0,654,Racine Ave & Washington Blvd (*),133,Kingsbury St & Kinzie St,member,...,NaN,NaN,NaN,NaN,41.889177,-87.638506,27.0,532.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7391574,25961169,10:13:43,10:23:26,363,582.0,664,Leavitt St & Belmont Ave (*),117,Wilton Ave & Belmont Ave,casual,...,NaN,NaN,NaN,NaN,41.940180,-87.653040,23.0,69.0,Chicago,classic_bike
7391832,25961435,12:17:03,12:32:50,1884,947.0,673,Lincoln Park Conservatory,48,Larrabee St & Kingsbury St,member,...,NaN,NaN,NaN,NaN,41.897764,-87.642884,27.0,12.0,Chicago,classic_bike
7392272,25961899,14:55:21,15:26:43,2249,"1,882.0",640,Bernard St & Elston Ave,94,Clark St & Armitage Ave,member,...,NaN,NaN,NaN,NaN,41.918273,-87.638116,19.0,146.0,Chicago,classic_bike
7392656,25962304,16:39:36,16:46:34,5703,418.0,656,Damen Ave & Walnut (Lake) St (*),659,Leavitt St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.895485,-87.682008,15.0,0.0,Chicago,classic_bike
7392818,25962475,17:33:07,17:54:09,5996,"1,261.0",673,Lincoln Park Conservatory,145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike

In [131]:
fix_nulls(654, 11, [41.88368, -87.65704], 'Chicago')

In [132]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3132718,21189770,17:29:07,17:49:54,5722,"1,247.0",640,Bernard St & Elston Ave,239,Western Ave & Leland Ave,member,...,NaN,NaN,NaN,NaN,41.966555,-87.688487,15.0,112.0,Chicago,classic_bike
3167839,21231740,17:21:07,17:26:20,1813,313.0,640,Bernard St & Elston Ave,497,Kimball Ave & Belmont Ave,member,...,NaN,NaN,NaN,NaN,41.939392,-87.712241,23.0,641.0,Chicago,classic_bike
3182837,21249648,10:20:41,10:34:32,6348,831.0,640,Bernard St & Elston Ave,258,Logan Blvd & Elston Ave,member,...,NaN,NaN,NaN,NaN,41.930584,-87.685126,19.0,145.0,Chicago,classic_bike
3193096,21261665,19:04:26,19:22:50,2003,"1,104.0",640,Bernard St & Elston Ave,226,Racine Ave & Belmont Ave,member,...,NaN,NaN,NaN,NaN,41.939743,-87.658865,15.0,230.0,Chicago,classic_bike
3204568,21275195,18:42:22,18:55:58,95,816.0,649,Stewart Ave & 63rd St (*),428,Dorchester Ave & 63rd St,member,...,NaN,NaN,NaN,NaN,41.780406,-87.591416,15.0,484.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7391574,25961169,10:13:43,10:23:26,363,582.0,664,Leavitt St & Belmont Ave (*),117,Wilton Ave & Belmont Ave,casual,...,NaN,NaN,NaN,NaN,41.940180,-87.653040,23.0,69.0,Chicago,classic_bike
7391832,25961435,12:17:03,12:32:50,1884,947.0,673,Lincoln Park Conservatory,48,Larrabee St & Kingsbury St,member,...,NaN,NaN,NaN,NaN,41.897764,-87.642884,27.0,12.0,Chicago,classic_bike
7392272,25961899,14:55:21,15:26:43,2249,"1,882.0",640,Bernard St & Elston Ave,94,Clark St & Armitage Ave,member,...,NaN,NaN,NaN,NaN,41.918273,-87.638116,19.0,146.0,Chicago,classic_bike
7392656,25962304,16:39:36,16:46:34,5703,418.0,656,Damen Ave & Walnut (Lake) St (*),659,Leavitt St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.895485,-87.682008,15.0,0.0,Chicago,classic_bike
7392818,25962475,17:33:07,17:54:09,5996,"1,261.0",673,Lincoln Park Conservatory,145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike

In [133]:
fix_nulls(640, 10, [41.95049, -87.713906], 'Chicago')

In [134]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3204568,21275195,18:42:22,18:55:58,95,816.0,649,Stewart Ave & 63rd St (*),428,Dorchester Ave & 63rd St,member,...,NaN,NaN,NaN,NaN,41.780406,-87.591416,15.0,484.0,Chicago,classic_bike
3218005,21290972,21:51:39,23:33:58,1979,"6,139.0",649,Stewart Ave & 63rd St (*),392,Perry Ave & 69th St,member,...,NaN,NaN,NaN,NaN,41.769293,-87.628196,15.0,598.0,Chicago,classic_bike
3228058,21302740,18:53:51,18:57:28,4044,217.0,650,Eggleston Ave & 69th St (*),392,Perry Ave & 69th St,member,...,NaN,NaN,NaN,NaN,41.769293,-87.628196,15.0,598.0,Chicago,classic_bike
3233579,21309441,11:40:49,12:05:23,4715,"1,474.0",656,Damen Ave & Walnut (Lake) St (*),656,Damen Ave & Walnut (Lake) St (*),casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3233765,21309690,12:05:45,12:35:32,4715,"1,787.0",656,Damen Ave & Walnut (Lake) St (*),286,Franklin St & Quincy St,casual,...,NaN,NaN,NaN,NaN,41.878724,-87.634793,15.0,7.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7391556,25961151,10:02:01,10:22:15,2690,"1,213.0",673,Lincoln Park Conservatory,232,Pine Grove Ave & Waveland Ave,member,...,NaN,NaN,NaN,NaN,41.947836,-87.645416,15.0,273.0,Chicago,classic_bike
7391574,25961169,10:13:43,10:23:26,363,582.0,664,Leavitt St & Belmont Ave (*),117,Wilton Ave & Belmont Ave,casual,...,NaN,NaN,NaN,NaN,41.940180,-87.653040,23.0,69.0,Chicago,classic_bike
7391832,25961435,12:17:03,12:32:50,1884,947.0,673,Lincoln Park Conservatory,48,Larrabee St & Kingsbury St,member,...,NaN,NaN,NaN,NaN,41.897764,-87.642884,27.0,12.0,Chicago,classic_bike
7392656,25962304,16:39:36,16:46:34,5703,418.0,656,Damen Ave & Walnut (Lake) St (*),659,Leavitt St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.895485,-87.682008,15.0,0.0,Chicago,classic_bike
7392818,25962475,17:33:07,17:54:09,5996,"1,261.0",673,Lincoln Park Conservatory,145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike

In [135]:
fix_nulls(649, 11, [41.78035, -87.63490], 'Chicago')

In [136]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3228058,21302740,18:53:51,18:57:28,4044,217.0,650,Eggleston Ave & 69th St (*),392,Perry Ave & 69th St,member,...,NaN,NaN,NaN,NaN,41.769293,-87.628196,15.0,598.0,Chicago,classic_bike
3233579,21309441,11:40:49,12:05:23,4715,"1,474.0",656,Damen Ave & Walnut (Lake) St (*),656,Damen Ave & Walnut (Lake) St (*),casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3233765,21309690,12:05:45,12:35:32,4715,"1,787.0",656,Damen Ave & Walnut (Lake) St (*),286,Franklin St & Quincy St,casual,...,NaN,NaN,NaN,NaN,41.878724,-87.634793,15.0,7.0,Chicago,classic_bike
3234671,21310809,14:09:01,14:20:15,1326,674.0,656,Damen Ave & Walnut (Lake) St (*),61,Wood St & Milwaukee Ave,member,...,NaN,NaN,NaN,NaN,41.907655,-87.672552,15.0,221.0,Chicago,classic_bike
3236129,21312663,16:35:09,16:52:45,3481,"1,056.0",658,Leavitt St & Division St (*),317,Wood St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869154,-87.671045,15.0,285.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7391556,25961151,10:02:01,10:22:15,2690,"1,213.0",673,Lincoln Park Conservatory,232,Pine Grove Ave & Waveland Ave,member,...,NaN,NaN,NaN,NaN,41.947836,-87.645416,15.0,273.0,Chicago,classic_bike
7391574,25961169,10:13:43,10:23:26,363,582.0,664,Leavitt St & Belmont Ave (*),117,Wilton Ave & Belmont Ave,casual,...,NaN,NaN,NaN,NaN,41.940180,-87.653040,23.0,69.0,Chicago,classic_bike
7391832,25961435,12:17:03,12:32:50,1884,947.0,673,Lincoln Park Conservatory,48,Larrabee St & Kingsbury St,member,...,NaN,NaN,NaN,NaN,41.897764,-87.642884,27.0,12.0,Chicago,classic_bike
7392656,25962304,16:39:36,16:46:34,5703,418.0,656,Damen Ave & Walnut (Lake) St (*),659,Leavitt St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.895485,-87.682008,15.0,0.0,Chicago,classic_bike
7392818,25962475,17:33:07,17:54:09,5996,"1,261.0",673,Lincoln Park Conservatory,145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike

In [137]:
fix_nulls(656, 15, [41.88646, -87.67701], 'Chicago')

In [138]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3228058,21302740,18:53:51,18:57:28,4044,217.0,650,Eggleston Ave & 69th St (*),392,Perry Ave & 69th St,member,...,NaN,NaN,NaN,NaN,41.769293,-87.628196,15.0,598.0,Chicago,classic_bike
3236129,21312663,16:35:09,16:52:45,3481,"1,056.0",658,Leavitt St & Division St (*),317,Wood St & Taylor St,member,...,NaN,NaN,NaN,NaN,41.869154,-87.671045,15.0,285.0,Chicago,classic_bike
3239389,21316238,19:09:48,19:16:45,6262,417.0,658,Leavitt St & Division St (*),210,Ashland Ave & Division St,member,...,NaN,NaN,NaN,NaN,41.903456,-87.667770,19.0,61.0,Chicago,classic_bike
3242674,21320055,08:17:21,08:35:23,4105,"1,082.0",658,Leavitt St & Division St (*),66,Clinton St & Lake St,member,...,NaN,NaN,NaN,NaN,41.885833,-87.641382,19.0,21.0,Chicago,classic_bike
3245013,21323177,12:26:00,12:49:54,3956,"1,434.0",648,Carpenter St & 63rd St,428,Dorchester Ave & 63rd St,casual,...,NaN,NaN,NaN,NaN,41.780406,-87.591416,15.0,484.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7391369,25960957,08:34:07,08:45:11,5544,664.0,658,Leavitt St & Division St (*),276,California Ave & North Ave,member,...,NaN,NaN,NaN,NaN,41.910440,-87.697200,11.0,258.0,Chicago,classic_bike
7391556,25961151,10:02:01,10:22:15,2690,"1,213.0",673,Lincoln Park Conservatory,232,Pine Grove Ave & Waveland Ave,member,...,NaN,NaN,NaN,NaN,41.947836,-87.645416,15.0,273.0,Chicago,classic_bike
7391574,25961169,10:13:43,10:23:26,363,582.0,664,Leavitt St & Belmont Ave (*),117,Wilton Ave & Belmont Ave,casual,...,NaN,NaN,NaN,NaN,41.940180,-87.653040,23.0,69.0,Chicago,classic_bike
7391832,25961435,12:17:03,12:32:50,1884,947.0,673,Lincoln Park Conservatory,48,Larrabee St & Kingsbury St,member,...,NaN,NaN,NaN,NaN,41.897764,-87.642884,27.0,12.0,Chicago,classic_bike
7392818,25962475,17:33:07,17:54:09,5996,"1,261.0",673,Lincoln Park Conservatory,145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike

In [139]:
fix_nulls(658, 15, [41.90367, -87.68387], 'Chicago')

In [140]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3228058,21302740,18:53:51,18:57:28,4044,217.0,650,Eggleston Ave & 69th St (*),392,Perry Ave & 69th St,member,...,NaN,NaN,NaN,NaN,41.769293,-87.628196,15.0,598.0,Chicago,classic_bike
3245013,21323177,12:26:00,12:49:54,3956,"1,434.0",648,Carpenter St & 63rd St,428,Dorchester Ave & 63rd St,casual,...,NaN,NaN,NaN,NaN,41.780406,-87.591416,15.0,484.0,Chicago,classic_bike
3287465,21372707,23:04:17,23:49:09,5012,"2,692.0",650,Eggleston Ave & 69th St (*),649,Stewart Ave & 63rd St (*),member,...,NaN,NaN,NaN,NaN,41.780350,-87.634900,11.0,0.0,Chicago,classic_bike
3296921,21383705,18:05:41,18:20:31,5674,890.0,662,Dodge Ave & Mulford St,625,Chicago Ave & Dempster St,casual,...,NaN,NaN,NaN,NaN,42.041691,-87.680687,15.0,0.0,Evanston,classic_bike
3297421,21384265,18:37:05,18:42:52,5085,347.0,661,Evanston Civic Center,601,Central St Metra,member,...,NaN,NaN,NaN,NaN,42.063598,-87.698730,15.0,0.0,Evanston,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7389095,25958562,12:21:35,12:48:07,2546,"1,592.0",673,Lincoln Park Conservatory,6,Dusable Harbor,member,...,NaN,NaN,NaN,NaN,41.885042,-87.612795,31.0,548.0,Chicago,classic_bike
7391556,25961151,10:02:01,10:22:15,2690,"1,213.0",673,Lincoln Park Conservatory,232,Pine Grove Ave & Waveland Ave,member,...,NaN,NaN,NaN,NaN,41.947836,-87.645416,15.0,273.0,Chicago,classic_bike
7391574,25961169,10:13:43,10:23:26,363,582.0,664,Leavitt St & Belmont Ave (*),117,Wilton Ave & Belmont Ave,casual,...,NaN,NaN,NaN,NaN,41.940180,-87.653040,23.0,69.0,Chicago,classic_bike
7391832,25961435,12:17:03,12:32:50,1884,947.0,673,Lincoln Park Conservatory,48,Larrabee St & Kingsbury St,member,...,NaN,NaN,NaN,NaN,41.897764,-87.642884,27.0,12.0,Chicago,classic_bike
7392818,25962475,17:33:07,17:54:09,5996,"1,261.0",673,Lincoln Park Conservatory,145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike

In [141]:
fix_nulls(673, 31, [41.92412, -87.63590], 'Chicago')

In [142]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3228058,21302740,18:53:51,18:57:28,4044,217.0,650,Eggleston Ave & 69th St (*),392,Perry Ave & 69th St,member,...,NaN,NaN,NaN,NaN,41.769293,-87.628196,15.0,598.0,Chicago,classic_bike
3245013,21323177,12:26:00,12:49:54,3956,"1,434.0",648,Carpenter St & 63rd St,428,Dorchester Ave & 63rd St,casual,...,NaN,NaN,NaN,NaN,41.780406,-87.591416,15.0,484.0,Chicago,classic_bike
3287465,21372707,23:04:17,23:49:09,5012,"2,692.0",650,Eggleston Ave & 69th St (*),649,Stewart Ave & 63rd St (*),member,...,NaN,NaN,NaN,NaN,41.780350,-87.634900,11.0,0.0,Chicago,classic_bike
3296921,21383705,18:05:41,18:20:31,5674,890.0,662,Dodge Ave & Mulford St,625,Chicago Ave & Dempster St,casual,...,NaN,NaN,NaN,NaN,42.041691,-87.680687,15.0,0.0,Evanston,classic_bike
3297421,21384265,18:37:05,18:42:52,5085,347.0,661,Evanston Civic Center,601,Central St Metra,member,...,NaN,NaN,NaN,NaN,42.063598,-87.698730,15.0,0.0,Evanston,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7385414,25954673,13:23:26,13:45:00,693,"1,294.0",664,Leavitt St & Belmont Ave (*),331,Halsted St & Clybourn Ave,member,...,NaN,NaN,NaN,NaN,41.908540,-87.648568,19.0,176.0,Chicago,classic_bike
7386004,25955291,14:41:12,15:08:54,2059,"1,662.0",653,Cornell Dr & Hayes Dr,580,Exchange Ave & 79th St,member,...,NaN,NaN,NaN,NaN,41.751731,-87.552812,15.0,0.0,Chicago,classic_bike
7388405,25957852,08:35:15,08:40:15,347,299.0,663,Lincolnwood Dr & Central St,601,Central St Metra,member,...,NaN,NaN,NaN,NaN,42.063598,-87.698730,15.0,0.0,Evanston,classic_bike
7388951,25958416,11:40:13,11:48:50,6105,517.0,661,Evanston Civic Center,596,Benson Ave & Church St,member,...,NaN,NaN,NaN,NaN,42.048214,-87.683485,15.0,0.0,Evanston,classic_bike
7391574,25961169,10:13:43,10:23:26,363,582.0,664,Leavitt St & Belmont Ave (*),117,Wilton Ave & Belmont Ave,casual,...,NaN,NaN,NaN,NaN,41.940180,-87.653040,23.0,69.0,Chicago,classic_bike

In [143]:
fix_nulls(650, 11, [41.76950, -87.63583], 'Chicago')

In [144]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3245013,21323177,12:26:00,12:49:54,3956,"1,434.0",648,Carpenter St & 63rd St,428,Dorchester Ave & 63rd St,casual,...,NaN,NaN,NaN,NaN,41.780406,-87.591416,15.0,484.0,Chicago,classic_bike
3296921,21383705,18:05:41,18:20:31,5674,890.0,662,Dodge Ave & Mulford St,625,Chicago Ave & Dempster St,casual,...,NaN,NaN,NaN,NaN,42.041691,-87.680687,15.0,0.0,Evanston,classic_bike
3297421,21384265,18:37:05,18:42:52,5085,347.0,661,Evanston Civic Center,601,Central St Metra,member,...,NaN,NaN,NaN,NaN,42.063598,-87.698730,15.0,0.0,Evanston,classic_bike
3299659,21386818,06:39:43,06:47:44,2532,481.0,663,Lincolnwood Dr & Central St,601,Central St Metra,member,...,NaN,NaN,NaN,NaN,42.063598,-87.698730,15.0,0.0,Evanston,classic_bike
3307309,21396230,17:34:31,17:39:12,2036,281.0,661,Evanston Civic Center,596,Benson Ave & Church St,member,...,NaN,NaN,NaN,NaN,42.048214,-87.683485,15.0,0.0,Evanston,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7385414,25954673,13:23:26,13:45:00,693,"1,294.0",664,Leavitt St & Belmont Ave (*),331,Halsted St & Clybourn Ave,member,...,NaN,NaN,NaN,NaN,41.908540,-87.648568,19.0,176.0,Chicago,classic_bike
7386004,25955291,14:41:12,15:08:54,2059,"1,662.0",653,Cornell Dr & Hayes Dr,580,Exchange Ave & 79th St,member,...,NaN,NaN,NaN,NaN,41.751731,-87.552812,15.0,0.0,Chicago,classic_bike
7388405,25957852,08:35:15,08:40:15,347,299.0,663,Lincolnwood Dr & Central St,601,Central St Metra,member,...,NaN,NaN,NaN,NaN,42.063598,-87.698730,15.0,0.0,Evanston,classic_bike
7388951,25958416,11:40:13,11:48:50,6105,517.0,661,Evanston Civic Center,596,Benson Ave & Church St,member,...,NaN,NaN,NaN,NaN,42.048214,-87.683485,15.0,0.0,Evanston,classic_bike
7391574,25961169,10:13:43,10:23:26,363,582.0,664,Leavitt St & Belmont Ave (*),117,Wilton Ave & Belmont Ave,casual,...,NaN,NaN,NaN,NaN,41.940180,-87.653040,23.0,69.0,Chicago,classic_bike

In [145]:
fix_nulls(653, 10, [41.78061, -87.58484], 'Chicago')

In [146]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3245013,21323177,12:26:00,12:49:54,3956,"1,434.0",648,Carpenter St & 63rd St,428,Dorchester Ave & 63rd St,casual,...,NaN,NaN,NaN,NaN,41.780406,-87.591416,15.0,484.0,Chicago,classic_bike
3296921,21383705,18:05:41,18:20:31,5674,890.0,662,Dodge Ave & Mulford St,625,Chicago Ave & Dempster St,casual,...,NaN,NaN,NaN,NaN,42.041691,-87.680687,15.0,0.0,Evanston,classic_bike
3297421,21384265,18:37:05,18:42:52,5085,347.0,661,Evanston Civic Center,601,Central St Metra,member,...,NaN,NaN,NaN,NaN,42.063598,-87.698730,15.0,0.0,Evanston,classic_bike
3299659,21386818,06:39:43,06:47:44,2532,481.0,663,Lincolnwood Dr & Central St,601,Central St Metra,member,...,NaN,NaN,NaN,NaN,42.063598,-87.698730,15.0,0.0,Evanston,classic_bike
3307309,21396230,17:34:31,17:39:12,2036,281.0,661,Evanston Civic Center,596,Benson Ave & Church St,member,...,NaN,NaN,NaN,NaN,42.048214,-87.683485,15.0,0.0,Evanston,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7384310,25953495,10:25:23,10:57:01,1443,"1,898.0",662,Dodge Ave & Mulford St,662,Dodge Ave & Mulford St,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7385414,25954673,13:23:26,13:45:00,693,"1,294.0",664,Leavitt St & Belmont Ave (*),331,Halsted St & Clybourn Ave,member,...,NaN,NaN,NaN,NaN,41.908540,-87.648568,19.0,176.0,Chicago,classic_bike
7388405,25957852,08:35:15,08:40:15,347,299.0,663,Lincolnwood Dr & Central St,601,Central St Metra,member,...,NaN,NaN,NaN,NaN,42.063598,-87.698730,15.0,0.0,Evanston,classic_bike
7388951,25958416,11:40:13,11:48:50,6105,517.0,661,Evanston Civic Center,596,Benson Ave & Church St,member,...,NaN,NaN,NaN,NaN,42.048214,-87.683485,15.0,0.0,Evanston,classic_bike
7391574,25961169,10:13:43,10:23:26,363,582.0,664,Leavitt St & Belmont Ave (*),117,Wilton Ave & Belmont Ave,casual,...,NaN,NaN,NaN,NaN,41.940180,-87.653040,23.0,69.0,Chicago,classic_bike

In [147]:
fix_nulls(661, 13, [41.78061, -87.58484], 'Chicago')

In [148]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3245013,21323177,12:26:00,12:49:54,3956,"1,434.0",648,Carpenter St & 63rd St,428,Dorchester Ave & 63rd St,casual,...,NaN,NaN,NaN,NaN,41.780406,-87.591416,15.0,484.0,Chicago,classic_bike
3296921,21383705,18:05:41,18:20:31,5674,890.0,662,Dodge Ave & Mulford St,625,Chicago Ave & Dempster St,casual,...,NaN,NaN,NaN,NaN,42.041691,-87.680687,15.0,0.0,Evanston,classic_bike
3299659,21386818,06:39:43,06:47:44,2532,481.0,663,Lincolnwood Dr & Central St,601,Central St Metra,member,...,NaN,NaN,NaN,NaN,42.063598,-87.698730,15.0,0.0,Evanston,classic_bike
3308549,21397555,18:40:53,18:58:32,823,"1,059.0",663,Lincolnwood Dr & Central St,603,Chicago Ave & Sheridan Rd,member,...,NaN,NaN,NaN,NaN,42.050491,-87.677821,15.0,0.0,Evanston,classic_bike
3310590,21399908,06:51:02,06:56:56,4517,354.0,663,Lincolnwood Dr & Central St,601,Central St Metra,member,...,NaN,NaN,NaN,NaN,42.063598,-87.698730,15.0,0.0,Evanston,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7383506,25952631,18:41:08,19:12:18,549,"1,869.0",664,Leavitt St & Belmont Ave (*),112,Green St & Randolph St,casual,...,NaN,NaN,NaN,NaN,41.884078,-87.648684,15.0,53.0,Chicago,classic_bike
7384310,25953495,10:25:23,10:57:01,1443,"1,898.0",662,Dodge Ave & Mulford St,662,Dodge Ave & Mulford St,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7385414,25954673,13:23:26,13:45:00,693,"1,294.0",664,Leavitt St & Belmont Ave (*),331,Halsted St & Clybourn Ave,member,...,NaN,NaN,NaN,NaN,41.908540,-87.648568,19.0,176.0,Chicago,classic_bike
7388405,25957852,08:35:15,08:40:15,347,299.0,663,Lincolnwood Dr & Central St,601,Central St Metra,member,...,NaN,NaN,NaN,NaN,42.063598,-87.698730,15.0,0.0,Evanston,classic_bike
7391574,25961169,10:13:43,10:23:26,363,582.0,664,Leavitt St & Belmont Ave (*),117,Wilton Ave & Belmont Ave,casual,...,NaN,NaN,NaN,NaN,41.940180,-87.653040,23.0,69.0,Chicago,classic_bike

In [149]:
fix_nulls(663, 11, [42.06545, -87.71529], 'Evanston')

In [150]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3245013,21323177,12:26:00,12:49:54,3956,"1,434.0",648,Carpenter St & 63rd St,428,Dorchester Ave & 63rd St,casual,...,NaN,NaN,NaN,NaN,41.780406,-87.591416,15.0,484.0,Chicago,classic_bike
3296921,21383705,18:05:41,18:20:31,5674,890.0,662,Dodge Ave & Mulford St,625,Chicago Ave & Dempster St,casual,...,NaN,NaN,NaN,NaN,42.041691,-87.680687,15.0,0.0,Evanston,classic_bike
3337078,21431519,17:21:38,17:30:19,929,521.0,662,Dodge Ave & Mulford St,467,Western Ave & Lunt Ave,member,...,NaN,NaN,NaN,NaN,42.008594,-87.690492,15.0,584.0,Chicago,classic_bike
3340403,21435173,07:29:48,07:44:17,6158,869.0,662,Dodge Ave & Mulford St,432,Clark St & Lunt Ave,member,...,NaN,NaN,NaN,NaN,42.009069,-87.673711,15.0,563.0,Chicago,classic_bike
3350746,21447587,08:44:07,08:52:51,1392,524.0,662,Dodge Ave & Mulford St,467,Western Ave & Lunt Ave,member,...,NaN,NaN,NaN,NaN,42.008594,-87.690492,15.0,584.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7382832,25951910,15:16:54,15:22:55,6075,361.0,666,Cherry Ave & Blackhawk St,93,Sheffield Ave & Willow St,member,...,NaN,NaN,NaN,NaN,41.913688,-87.652855,15.0,190.0,Chicago,classic_bike
7383506,25952631,18:41:08,19:12:18,549,"1,869.0",664,Leavitt St & Belmont Ave (*),112,Green St & Randolph St,casual,...,NaN,NaN,NaN,NaN,41.884078,-87.648684,15.0,53.0,Chicago,classic_bike
7384310,25953495,10:25:23,10:57:01,1443,"1,898.0",662,Dodge Ave & Mulford St,662,Dodge Ave & Mulford St,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7385414,25954673,13:23:26,13:45:00,693,"1,294.0",664,Leavitt St & Belmont Ave (*),331,Halsted St & Clybourn Ave,member,...,NaN,NaN,NaN,NaN,41.908540,-87.648568,19.0,176.0,Chicago,classic_bike
7391574,25961169,10:13:43,10:23:26,363,582.0,664,Leavitt St & Belmont Ave (*),117,Wilton Ave & Belmont Ave,casual,...,NaN,NaN,NaN,NaN,41.940180,-87.653040,23.0,69.0,Chicago,classic_bike

In [151]:
fix_nulls(662, 15, [42.02378, -87.69959], 'Chicago')

In [152]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3245013,21323177,12:26:00,12:49:54,3956,"1,434.0",648,Carpenter St & 63rd St,428,Dorchester Ave & 63rd St,casual,...,NaN,NaN,NaN,NaN,41.780406,-87.591416,15.0,484.0,Chicago,classic_bike
3374394,21476278,16:26:32,16:39:52,1673,800.0,648,Carpenter St & 63rd St,427,Cottage Grove Ave & 63rd St,member,...,NaN,NaN,NaN,NaN,41.780599,-87.606112,19.0,482.0,Chicago,classic_bike
3437697,21553073,12:21:39,12:48:31,6282,"1,612.0",651,Michigan Ave & 71st St,558,Ashland Ave & Garfield Blvd,casual,...,NaN,NaN,NaN,NaN,41.792822,-87.664429,11.0,0.0,Chicago,classic_bike
3531887,21665619,11:58:30,12:07:37,5985,547.0,664,Leavitt St & Belmont Ave (*),307,Southport Ave & Clybourn Ave,member,...,NaN,NaN,NaN,NaN,41.921004,-87.663257,15.0,186.0,Chicago,classic_bike
3535353,21669884,22:04:01,22:12:55,6357,534.0,664,Leavitt St & Belmont Ave (*),243,Lincoln Ave & Sunnyside Ave,member,...,NaN,NaN,NaN,NaN,41.962391,-87.684146,15.0,126.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7380085,25949026,16:54:19,17:20:02,2538,"1,542.0",666,Cherry Ave & Blackhawk St,304,Broadway & Waveland Ave,member,...,NaN,NaN,NaN,NaN,41.949333,-87.649634,15.0,325.0,Chicago,classic_bike
7382832,25951910,15:16:54,15:22:55,6075,361.0,666,Cherry Ave & Blackhawk St,93,Sheffield Ave & Willow St,member,...,NaN,NaN,NaN,NaN,41.913688,-87.652855,15.0,190.0,Chicago,classic_bike
7383506,25952631,18:41:08,19:12:18,549,"1,869.0",664,Leavitt St & Belmont Ave (*),112,Green St & Randolph St,casual,...,NaN,NaN,NaN,NaN,41.884078,-87.648684,15.0,53.0,Chicago,classic_bike
7385414,25954673,13:23:26,13:45:00,693,"1,294.0",664,Leavitt St & Belmont Ave (*),331,Halsted St & Clybourn Ave,member,...,NaN,NaN,NaN,NaN,41.908540,-87.648568,19.0,176.0,Chicago,classic_bike
7391574,25961169,10:13:43,10:23:26,363,582.0,664,Leavitt St & Belmont Ave (*),117,Wilton Ave & Belmont Ave,casual,...,NaN,NaN,NaN,NaN,41.940180,-87.653040,23.0,69.0,Chicago,classic_bike

In [153]:
fix_nulls(664, 15, [41.93996, -87.68341], 'Chicago')

In [154]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3245013,21323177,12:26:00,12:49:54,3956,"1,434.0",648,Carpenter St & 63rd St,428,Dorchester Ave & 63rd St,casual,...,NaN,NaN,NaN,NaN,41.780406,-87.591416,15.0,484.0,Chicago,classic_bike
3374394,21476278,16:26:32,16:39:52,1673,800.0,648,Carpenter St & 63rd St,427,Cottage Grove Ave & 63rd St,member,...,NaN,NaN,NaN,NaN,41.780599,-87.606112,19.0,482.0,Chicago,classic_bike
3437697,21553073,12:21:39,12:48:31,6282,"1,612.0",651,Michigan Ave & 71st St,558,Ashland Ave & Garfield Blvd,casual,...,NaN,NaN,NaN,NaN,41.792822,-87.664429,11.0,0.0,Chicago,classic_bike
3647196,21801831,10:34:19,10:35:56,5148,97.0,645,Archer (Damen) Ave & 37th St (*),9,Leavitt St & Archer Ave,member,...,NaN,NaN,NaN,NaN,41.828792,-87.680604,19.0,695.0,Chicago,classic_bike
3654364,21810465,06:55:30,07:29:24,1806,"2,034.0",645,Archer (Damen) Ave & 37th St (*),146,Loomis St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877945,-87.662007,11.0,206.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7371636,25940118,06:44:41,07:18:22,4924,"2,020.0",645,Archer (Damen) Ave & 37th St,107,Desplaines St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.878287,-87.643909,23.0,539.0,Chicago,classic_bike
7377463,25946271,07:08:02,07:38:36,6423,"1,833.0",645,Archer (Damen) Ave & 37th St,107,Desplaines St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.878287,-87.643909,23.0,539.0,Chicago,classic_bike
7378549,25947417,11:56:55,12:13:23,5973,987.0,666,Cherry Ave & Blackhawk St,145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike
7380085,25949026,16:54:19,17:20:02,2538,"1,542.0",666,Cherry Ave & Blackhawk St,304,Broadway & Waveland Ave,member,...,NaN,NaN,NaN,NaN,41.949333,-87.649634,15.0,325.0,Chicago,classic_bike
7382832,25951910,15:16:54,15:22:55,6075,361.0,666,Cherry Ave & Blackhawk St,93,Sheffield Ave & Willow St,member,...,NaN,NaN,NaN,NaN,41.913688,-87.652855,15.0,190.0,Chicago,classic_bike

In [155]:
fix_nulls(648, 7, [41.78041, -87.65074], 'Chicago')

In [156]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3437697,21553073,12:21:39,12:48:31,6282,"1,612.0",651,Michigan Ave & 71st St,558,Ashland Ave & Garfield Blvd,casual,...,NaN,NaN,NaN,NaN,41.792822,-87.664429,11.0,0.0,Chicago,classic_bike
3647196,21801831,10:34:19,10:35:56,5148,97.0,645,Archer (Damen) Ave & 37th St (*),9,Leavitt St & Archer Ave,member,...,NaN,NaN,NaN,NaN,41.828792,-87.680604,19.0,695.0,Chicago,classic_bike
3654364,21810465,06:55:30,07:29:24,1806,"2,034.0",645,Archer (Damen) Ave & 37th St (*),146,Loomis St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877945,-87.662007,11.0,206.0,Chicago,classic_bike
3659493,21816442,06:59:59,07:31:17,4804,"1,878.0",645,Archer (Damen) Ave & 37th St (*),146,Loomis St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877945,-87.662007,11.0,206.0,Chicago,classic_bike
3664757,21822487,06:59:23,07:32:56,6139,"2,013.0",645,Archer (Damen) Ave & 37th St (*),146,Loomis St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.877945,-87.662007,11.0,206.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7371636,25940118,06:44:41,07:18:22,4924,"2,020.0",645,Archer (Damen) Ave & 37th St,107,Desplaines St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.878287,-87.643909,23.0,539.0,Chicago,classic_bike
7377463,25946271,07:08:02,07:38:36,6423,"1,833.0",645,Archer (Damen) Ave & 37th St,107,Desplaines St & Jackson Blvd,member,...,NaN,NaN,NaN,NaN,41.878287,-87.643909,23.0,539.0,Chicago,classic_bike
7378549,25947417,11:56:55,12:13:23,5973,987.0,666,Cherry Ave & Blackhawk St,145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike
7380085,25949026,16:54:19,17:20:02,2538,"1,542.0",666,Cherry Ave & Blackhawk St,304,Broadway & Waveland Ave,member,...,NaN,NaN,NaN,NaN,41.949333,-87.649634,15.0,325.0,Chicago,classic_bike
7382832,25951910,15:16:54,15:22:55,6075,361.0,666,Cherry Ave & Blackhawk St,93,Sheffield Ave & Willow St,member,...,NaN,NaN,NaN,NaN,41.913688,-87.652855,15.0,190.0,Chicago,classic_bike

In [157]:
fix_nulls(645, 11, [41.82729, -87.68310], 'Chicago')

In [158]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3437697,21553073,12:21:39,12:48:31,6282,"1,612.0",651,Michigan Ave & 71st St,558,Ashland Ave & Garfield Blvd,casual,...,NaN,NaN,NaN,NaN,41.792822,-87.664429,11.0,0.0,Chicago,classic_bike
3864491,22067517,20:42:57,21:12:14,1123,"1,757.0",647,Elizabeth St & 59th St,562,Racine Ave & 61st St,casual,...,NaN,NaN,NaN,NaN,41.783189,-87.654372,11.0,0.0,Chicago,classic_bike
3898777,22107937,11:26:22,13:00:08,4909,"5,626.0",665,South Chicago Ave & Elliot Ave,665,South Chicago Ave & Elliot Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3982538,22206498,18:14:48,19:13:38,5943,"3,530.0",642,Latrobe Ave & Chicago Ave,534,Karlov Ave & Madison St,member,...,NaN,NaN,NaN,NaN,41.880827,-87.726279,15.0,0.0,Chicago,classic_bike
3997075,22224084,19:56:25,20:27:12,5943,"1,847.0",642,Latrobe Ave & Chicago Ave,535,Pulaski Rd & Congress Pkwy,member,...,NaN,NaN,NaN,NaN,41.874325,-87.725704,15.0,0.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7351509,25918809,17:17:50,17:40:42,1196,"1,371.0",666,Cherry Ave & Blackhawk St,299,Halsted St & Roscoe St,member,...,NaN,NaN,NaN,NaN,41.943662,-87.648917,15.0,127.0,Chicago,classic_bike
7356089,25923604,18:29:16,18:39:48,4847,632.0,666,Cherry Ave & Blackhawk St,315,Elston Ave & Wabansia Ave,member,...,NaN,NaN,NaN,NaN,41.906717,-87.682779,11.0,255.0,Chicago,classic_bike
7378549,25947417,11:56:55,12:13:23,5973,987.0,666,Cherry Ave & Blackhawk St,145,Mies van der Rohe Way & Chestnut St,member,...,NaN,NaN,NaN,NaN,41.898587,-87.621915,19.0,529.0,Chicago,classic_bike
7380085,25949026,16:54:19,17:20:02,2538,"1,542.0",666,Cherry Ave & Blackhawk St,304,Broadway & Waveland Ave,member,...,NaN,NaN,NaN,NaN,41.949333,-87.649634,15.0,325.0,Chicago,classic_bike
7382832,25951910,15:16:54,15:22:55,6075,361.0,666,Cherry Ave & Blackhawk St,93,Sheffield Ave & Willow St,member,...,NaN,NaN,NaN,NaN,41.913688,-87.652855,15.0,190.0,Chicago,classic_bike

In [159]:
fix_nulls(666, 15, [41.90773, -87.65557], 'Chicago')

In [160]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3437697,21553073,12:21:39,12:48:31,6282,"1,612.0",651,Michigan Ave & 71st St,558,Ashland Ave & Garfield Blvd,casual,...,NaN,NaN,NaN,NaN,41.792822,-87.664429,11.0,0.0,Chicago,classic_bike
3864491,22067517,20:42:57,21:12:14,1123,"1,757.0",647,Elizabeth St & 59th St,562,Racine Ave & 61st St,casual,...,NaN,NaN,NaN,NaN,41.783189,-87.654372,11.0,0.0,Chicago,classic_bike
3898777,22107937,11:26:22,13:00:08,4909,"5,626.0",665,South Chicago Ave & Elliot Ave,665,South Chicago Ave & Elliot Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3982538,22206498,18:14:48,19:13:38,5943,"3,530.0",642,Latrobe Ave & Chicago Ave,534,Karlov Ave & Madison St,member,...,NaN,NaN,NaN,NaN,41.880827,-87.726279,15.0,0.0,Chicago,classic_bike
3997075,22224084,19:56:25,20:27:12,5943,"1,847.0",642,Latrobe Ave & Chicago Ave,535,Pulaski Rd & Congress Pkwy,member,...,NaN,NaN,NaN,NaN,41.874325,-87.725704,15.0,0.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7203104,25760622,18:25:24,18:53:26,1870,"1,682.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),126,Clark St & North Ave,member,...,NaN,NaN,NaN,NaN,41.911791,-87.631841,15.0,128.0,Chicago,classic_bike
7227335,25786606,15:58:23,16:31:10,1798,"1,967.0",651,Michigan Ave & 71st St,336,Cottage Grove Ave & 47th St,member,...,NaN,NaN,NaN,NaN,41.809855,-87.606755,15.0,422.0,Chicago,classic_bike
7253340,25814510,17:16:43,17:39:50,2608,"1,386.0",651,Michigan Ave & 71st St,651,Michigan Ave & 71st St,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7280054,25843111,07:52:40,08:07:10,3836,870.0,652,Rhodes Ave & 71st St,422,DuSable Museum,casual,...,NaN,NaN,NaN,NaN,41.791568,-87.607852,14.0,477.0,Chicago,classic_bike
7287808,25851347,23:37:28,23:49:02,555,694.0,651,Michigan Ave & 71st St,571,Vernon Ave & 75th St,casual,...,NaN,NaN,NaN,NaN,41.758361,-87.614138,11.0,0.0,Chicago,classic_bike

In [161]:
fix_nulls(651, 15, [41.76531, -87.62174], 'Chicago')

In [162]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3864491,22067517,20:42:57,21:12:14,1123,"1,757.0",647,Elizabeth St & 59th St,562,Racine Ave & 61st St,casual,...,NaN,NaN,NaN,NaN,41.783189,-87.654372,11.0,0.0,Chicago,classic_bike
3898777,22107937,11:26:22,13:00:08,4909,"5,626.0",665,South Chicago Ave & Elliot Ave,665,South Chicago Ave & Elliot Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
3982538,22206498,18:14:48,19:13:38,5943,"3,530.0",642,Latrobe Ave & Chicago Ave,534,Karlov Ave & Madison St,member,...,NaN,NaN,NaN,NaN,41.880827,-87.726279,15.0,0.0,Chicago,classic_bike
3997075,22224084,19:56:25,20:27:12,5943,"1,847.0",642,Latrobe Ave & Chicago Ave,535,Pulaski Rd & Congress Pkwy,member,...,NaN,NaN,NaN,NaN,41.874325,-87.725704,15.0,0.0,Chicago,classic_bike
4006448,22234710,18:40:25,19:24:53,2605,"2,668.0",642,Latrobe Ave & Chicago Ave,535,Pulaski Rd & Congress Pkwy,member,...,NaN,NaN,NaN,NaN,41.874325,-87.725704,15.0,0.0,Chicago,classic_bike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7150761,25704962,18:11:24,18:35:43,5598,"1,459.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),163,Damen Ave & Clybourn Ave,member,...,NaN,NaN,NaN,NaN,41.931860,-87.670790,15.0,271.0,Chicago,classic_bike
7184520,25740734,12:40:26,12:51:48,4345,681.0,652,Rhodes Ave & 71st St,422,DuSable Museum,casual,...,NaN,NaN,NaN,NaN,41.791568,-87.607852,14.0,477.0,Chicago,classic_bike
7195187,25752130,18:20:40,18:53:39,3204,"1,978.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),239,Western Ave & Leland Ave,member,...,NaN,NaN,NaN,NaN,41.966555,-87.688487,15.0,112.0,Chicago,classic_bike
7203104,25760622,18:25:24,18:53:26,1870,"1,682.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),126,Clark St & North Ave,member,...,NaN,NaN,NaN,NaN,41.911791,-87.631841,15.0,128.0,Chicago,classic_bike
7280054,25843111,07:52:40,08:07:10,3836,870.0,652,Rhodes Ave & 71st St,422,DuSable Museum,casual,...,NaN,NaN,NaN,NaN,41.791568,-87.607852,14.0,477.0,Chicago,classic_bike

In [163]:
fix_nulls(642, 7, [41.89472, -87.75688], 'Chicago')

In [164]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3864491,22067517,20:42:57,21:12:14,1123,"1,757.0",647,Elizabeth St & 59th St,562,Racine Ave & 61st St,casual,...,NaN,NaN,NaN,NaN,41.783189,-87.654372,11.0,0.0,Chicago,classic_bike
3898777,22107937,11:26:22,13:00:08,4909,"5,626.0",665,South Chicago Ave & Elliot Ave,665,South Chicago Ave & Elliot Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4152143,22405667,17:27:56,18:17:32,4526,"2,976.0",652,Rhodes Ave & 71st St,652,Rhodes Ave & 71st St,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4152296,22405828,17:31:13,18:17:39,5429,"2,786.0",652,Rhodes Ave & 71st St,652,Rhodes Ave & 71st St,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4317247,22601910,00:24:38,00:30:47,6282,369.0,647,Elizabeth St & 59th St,559,Racine Ave & Garfield Blvd,member,...,NaN,NaN,NaN,NaN,41.794694,-87.654947,11.0,0.0,Chicago,classic_bike
4440317,22748777,14:01:05,14:10:20,1741,555.0,1,Special Events,1,Special Events,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4506479,22826016,20:01:30,21:09:27,4526,"4,077.0",652,Rhodes Ave & 71st St,652,Rhodes Ave & 71st St,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4524589,22847328,11:46:06,12:41:19,5429,"3,313.0",652,Rhodes Ave & 71st St,652,Rhodes Ave & 71st St,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4545386,22873019,14:53:14,16:03:32,5429,"4,218.0",652,Rhodes Ave & 71st St,652,Rhodes Ave & 71st St,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4622597,22962577,13:33:41,14:40:31,1727,"4,010.0",647,Elizabeth St & 59th St,559,Racine Ave & Garfield Blvd,member,...,NaN,NaN,NaN,NaN,41.794694,-87.654947,11.0,0.0,Chicago,classic_bike
4642813,22986278,18:07:15,18:22:57,2236,942.0,647,Elizabeth St & 59th St,559,Racine Ave & Garfield Blvd,member,...,NaN,NaN,NaN,NaN,41.794694,-87.654947,11.0,0.0,Chicago,classic_bike
4685840,23036848,10:42:11,10:51:37,2139,566.0,647,Elizabeth St & 59th St,559,Racine Ave & Garfield Blvd,member,...,NaN,NaN,NaN,NaN,41.794694,-87.654947,11.0,0.0,Chicago,classic_bike
4727058,23084552,20:51:06,21:41:08,990,"3,002.0",647,Elizabeth St & 59th St,647,Elizabeth St & 59th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4832700,23207817,13:54:49,13:57:19,6206,150.0,669,LBS - BBB La Magie,669,LBS - BBB La Magie,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4847466,23225304,12:52:38,13:14:00,4823,"1,282.0",647,Elizabeth St & 59th St,647,Elizabeth St & 59th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4902476,23290237,19:44:06,08:56:38,4526,"1,170,750.0",652,Rhodes Ave & 71st St,429,Cottage Grove Ave & 67th St,casual,...,NaN,NaN,NaN,NaN,41.773721,-87.605635,15.0,485.0,Chicago,classic_bike
5319142,23775344,14:27:52,14:31:10,2540,198.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5322880,23779268,17:15:28,20:26:23,3990,"11,455.0",665,South Chicago Ave & Elliot Ave,665,South Chicago Ave & Elliot Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5322890,23779279,17:15:40,20:26:31,359,"11,451.0",665,South Chicago Ave & Elliot Ave,665,South Chicago Ave & Elliot Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5404190,23865161,17:47:14,19:08:06,5578,"4,852.0",652,Rhodes Ave & 71st St,76,Lake Shore Dr & Monroe St,casual,...,NaN,NaN,NaN,NaN,41.881050,-87.616970,11.0,300.0,Chicago,classic_bike
5419450,23881473,20:12:46,20:41:01,4988,"1,695.0",652,Rhodes Ave & 71st St,385,Princeton Ave & Garfield Blvd,member,...,NaN,NaN,NaN,NaN,41.794982,-87.633124,15.0,592.0,Chicago,classic_bike
5452340,23916262,16:52:58,16:57:05,4198,247.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5637916,24113003,03:40:28,04:43:38,3990,"3,789.0",665,South Chicago Ave & Elliot Ave,588,South Chicago Ave & 83rd St,casual,...,NaN,NaN,NaN,NaN,41.743921,-87.575225,11.0,0.0,Chicago,classic_bike
5693602,24172268,15:42:51,20:37:47,4909,"17,696.0",665,South Chicago Ave & Elliot Ave,585,Cottage Grove Ave & 83rd St,casual,...,NaN,NaN,NaN,NaN,41.744053,-87.604786,11.0,0.0,Chicago,classic_bike
5693620,24172289,15:43:34,20:37:55,6276,"17,661.0",665,South Chicago Ave & Elliot Ave,585,Cottage Grove Ave & 83rd St,casual,...,NaN,NaN,NaN,NaN,41.744053,-87.604786,11.0,0.0,Chicago,classic_bike
5783238,24266678,21:41:30,21:53:40,5429,730.0,652,Rhodes Ave & 71st St,392,Perry Ave & 69th St,member,...,NaN,NaN,NaN,NaN,41.769293,-87.628196,15.0,598.0,Chicago,classic_bike
5783647,24267109,22:13:36,22:44:28,2736,"1,852.0",665,South Chicago Ave & Elliot Ave,200,MLK Jr Dr & 47th St,casual,...,NaN,NaN,NaN,NaN,41.809851,-87.616279,11.0,90.0,Chicago,classic_bike
5895422,24385416,03:20:34,05:34:22,3509,"8,027.0",652,Rhodes Ave & 71st St,573,State St & 79th St,member,...,NaN,NaN,NaN,NaN,41.750794,-87.624424,15.0,0.0,Chicago,classic_bike
5931358,24423222,18:15:00,18:20:27,1404,326.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),119,Ashland Ave & Lake St,member,...,NaN,NaN,NaN,NaN,41.885410,-87.667320,19.0,73.0,Chicago,classic_bike
6009558,24506080,16:04:53,16:10:55,4835,361.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),119,Ashland Ave & Lake St,member,...,NaN,NaN,NaN,NaN,41.885410,-87.667320,19.0,73.0,Chicago,classic_bike
6057227,24556354,19:03:03,19:05:28,4295,145.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),214,Damen Ave & Grand Ave,member,...,NaN,NaN,NaN,NaN,41.891220,-87.676860,15.0,141.0,Chicago,classic_bike
6058675,24557892,20:33:02,14:39:56,1822,"65,214.0",665,South Chicago Ave & Elliot Ave,581,Commercial Ave & 83rd St,casual,...,NaN,NaN,NaN,NaN,41.744607,-87.551201,15.0,0.0,Chicago,classic_bike
6106963,24608963,18:11:38,18:40:23,5677,"1,725.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),486,Oakley Ave & Irving Park Rd,member,...,NaN,NaN,NaN,NaN,41.954341,-87.686080,15.0,627.0,Chicago,classic_bike
6144665,24648419,18:32:53,18:36:21,6258,208.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),656,Damen Ave & Walnut (Lake) St (*),member,...,NaN,NaN,NaN,NaN,41.886460,-87.677010,15.0,0.0,Chicago,classic_bike
6195095,24701472,14:21:01,15:35:02,767,"4,441.0",665,South Chicago Ave & Elliot Ave,588,South Chicago Ave & 83rd St,casual,...,NaN,NaN,NaN,NaN,41.743921,-87.575225,11.0,0.0,Chicago,classic_bike
6579817,25104174,11:51:08,12:00:14,2514,546.0,652,Rhodes Ave & 71st St,574,Vernon Ave & 79th St,casual,...,NaN,NaN,NaN,NaN,41.750951,-87.613783,11.0,0.0,Chicago,classic_bike
6681106,25209965,11:00:39,11:26:29,3750,"1,549.0",665,South Chicago Ave & Elliot Ave,665,South Chicago Ave & Elliot Ave,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
6681364,25210248,11:27:41,11:48:25,3750,"1,243.0",665,South Chicago Ave & Elliot Ave,583,Stony Island Ave & 82nd St,member,...,NaN,NaN,NaN,NaN,41.746559,-87.586005,11.0,0.0,Chicago,classic_bike
6752886,25285641,08:02:35,08:29:49,6151,"1,634.0",652,Rhodes Ave & 71st St,422,DuSable Museum,casual,...,NaN,NaN,NaN,NaN,41.791568,-87.607852,14.0,477.0,Chicago,classic_bike
6811026,25346695,06:26:02,15:00:17,6184,"2,367,255.0",665,South Chicago Ave & Elliot Ave,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
6815619,25351470,10:26:36,10:48:58,3904,"1,341.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),337,Clark St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.896544,-87.630931,19.0,303.0,Chicago,classic_bike
6818911,25354941,15:19:10,15:27:18,4345,488.0,652,Rhodes Ave & 71st St,652,Rhodes Ave & 71st St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
6883907,25422958,22:31:51,23:15:43,6306,"2,632.0",665,South Chicago Ave & Elliot Ave,569,Woodlawn Ave & 75th St,casual,...,NaN,NaN,NaN,NaN,41.759160,-87.595751,15.0,0.0,Chicago,classic_bike
6916337,25456596,14:18:34,14:47:15,1519,"1,721.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),486,Oakley Ave & Irving Park Rd,member,...,NaN,NaN,NaN,NaN,41.954341,-87.686080,15.0,627.0,Chicago,classic_bike
6965591,25508190,11:24:08,12:17:30,2532,"3,202.0",652,Rhodes Ave & 71st St,429,Cottage Grove Ave & 67th St,casual,...,NaN,NaN,NaN,NaN,41.773721,-87.605635,15.0,485.0,Chicago,classic_bike
6990773,25534747,15:04:59,17:53:35,4451,"10,116.0",652,Rhodes Ave & 71st St,200,MLK Jr Dr & 47th St,casual,...,NaN,NaN,NaN,NaN,41.809851,-87.616279,11.0,90.0,Chicago,classic_bike
7069278,25618689,18:00:39,18:27:09,3172,"1,590.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),486,Oakley Ave & Irving Park Rd,member,...,NaN,NaN,NaN,NaN,41.954341,-87.686080,15.0,627.0,Chicago,classic_bike
7096926,25647964,11:46:09,11:54:01,1667,471.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7127364,25680015,09:57:49,10:06:23,4175,514.0,647,Elizabeth St & 59th St,559,Racine Ave & Garfield Blvd,member,...,NaN,NaN,NaN,NaN,41.794694,-87.654947,11.0,0.0,Chicago,classic_bike
7150761,25704962,18:11:24,18:35:43,5598,"1,459.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),163,Damen Ave & Clybourn Ave,member,...,NaN,NaN,NaN,NaN,41.931860,-87.670790,15.0,271.0,Chicago,classic_bike
7184520,25740734,12:40:26,12:51:48,4345,681.0,652,Rhodes Ave & 71st St,422,DuSable Museum,casual,...,NaN,NaN,NaN,NaN,41.791568,-87.607852,14.0,477.0,Chicago,classic_bike
7195187,25752130,18:20:40,18:53:39,3204,"1,978.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),239,Western Ave & Leland Ave,member,...,NaN,NaN,NaN,NaN,41.966555,-87.688487,15.0,112.0,Chicago,classic_bike
7203104,25760622,18:25:24,18:53:26,1870,"1,682.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),126,Clark St & North Ave,member,...,NaN,NaN,NaN,NaN,41.911791,-87.631841,15.0,128.0,Chicago,classic_bike
7280054,25843111,07:52:40,08:07:10,3836,870.0,652,Rhodes Ave & 71st St,422,DuSable Museum,casual,...,NaN,NaN,NaN,NaN,41.791568,-87.607852,14.0,477.0,Chicago,classic_bike

In [165]:
fix_nulls(652, 11, [41.76602, -87.61173], 'Chicago')

In [166]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3864491,22067517,20:42:57,21:12:14,1123,"1,757.0",647,Elizabeth St & 59th St,562,Racine Ave & 61st St,casual,...,NaN,NaN,NaN,NaN,41.783189,-87.654372,11.0,0.0,Chicago,classic_bike
3898777,22107937,11:26:22,13:00:08,4909,"5,626.0",665,South Chicago Ave & Elliot Ave,665,South Chicago Ave & Elliot Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4317247,22601910,00:24:38,00:30:47,6282,369.0,647,Elizabeth St & 59th St,559,Racine Ave & Garfield Blvd,member,...,NaN,NaN,NaN,NaN,41.794694,-87.654947,11.0,0.0,Chicago,classic_bike
4440317,22748777,14:01:05,14:10:20,1741,555.0,1,Special Events,1,Special Events,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4622597,22962577,13:33:41,14:40:31,1727,"4,010.0",647,Elizabeth St & 59th St,559,Racine Ave & Garfield Blvd,member,...,NaN,NaN,NaN,NaN,41.794694,-87.654947,11.0,0.0,Chicago,classic_bike
4642813,22986278,18:07:15,18:22:57,2236,942.0,647,Elizabeth St & 59th St,559,Racine Ave & Garfield Blvd,member,...,NaN,NaN,NaN,NaN,41.794694,-87.654947,11.0,0.0,Chicago,classic_bike
4685840,23036848,10:42:11,10:51:37,2139,566.0,647,Elizabeth St & 59th St,559,Racine Ave & Garfield Blvd,member,...,NaN,NaN,NaN,NaN,41.794694,-87.654947,11.0,0.0,Chicago,classic_bike
4727058,23084552,20:51:06,21:41:08,990,"3,002.0",647,Elizabeth St & 59th St,647,Elizabeth St & 59th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4832700,23207817,13:54:49,13:57:19,6206,150.0,669,LBS - BBB La Magie,669,LBS - BBB La Magie,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4847466,23225304,12:52:38,13:14:00,4823,"1,282.0",647,Elizabeth St & 59th St,647,Elizabeth St & 59th St,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5319142,23775344,14:27:52,14:31:10,2540,198.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5322880,23779268,17:15:28,20:26:23,3990,"11,455.0",665,South Chicago Ave & Elliot Ave,665,South Chicago Ave & Elliot Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5322890,23779279,17:15:40,20:26:31,359,"11,451.0",665,South Chicago Ave & Elliot Ave,665,South Chicago Ave & Elliot Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5452340,23916262,16:52:58,16:57:05,4198,247.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5637916,24113003,03:40:28,04:43:38,3990,"3,789.0",665,South Chicago Ave & Elliot Ave,588,South Chicago Ave & 83rd St,casual,...,NaN,NaN,NaN,NaN,41.743921,-87.575225,11.0,0.0,Chicago,classic_bike
5693602,24172268,15:42:51,20:37:47,4909,"17,696.0",665,South Chicago Ave & Elliot Ave,585,Cottage Grove Ave & 83rd St,casual,...,NaN,NaN,NaN,NaN,41.744053,-87.604786,11.0,0.0,Chicago,classic_bike
5693620,24172289,15:43:34,20:37:55,6276,"17,661.0",665,South Chicago Ave & Elliot Ave,585,Cottage Grove Ave & 83rd St,casual,...,NaN,NaN,NaN,NaN,41.744053,-87.604786,11.0,0.0,Chicago,classic_bike
5783647,24267109,22:13:36,22:44:28,2736,"1,852.0",665,South Chicago Ave & Elliot Ave,200,MLK Jr Dr & 47th St,casual,...,NaN,NaN,NaN,NaN,41.809851,-87.616279,11.0,90.0,Chicago,classic_bike
5931358,24423222,18:15:00,18:20:27,1404,326.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),119,Ashland Ave & Lake St,member,...,NaN,NaN,NaN,NaN,41.885410,-87.667320,19.0,73.0,Chicago,classic_bike
6009558,24506080,16:04:53,16:10:55,4835,361.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),119,Ashland Ave & Lake St,member,...,NaN,NaN,NaN,NaN,41.885410,-87.667320,19.0,73.0,Chicago,classic_bike
6057227,24556354,19:03:03,19:05:28,4295,145.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),214,Damen Ave & Grand Ave,member,...,NaN,NaN,NaN,NaN,41.891220,-87.676860,15.0,141.0,Chicago,classic_bike
6058675,24557892,20:33:02,14:39:56,1822,"65,214.0",665,South Chicago Ave & Elliot Ave,581,Commercial Ave & 83rd St,casual,...,NaN,NaN,NaN,NaN,41.744607,-87.551201,15.0,0.0,Chicago,classic_bike
6106963,24608963,18:11:38,18:40:23,5677,"1,725.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),486,Oakley Ave & Irving Park Rd,member,...,NaN,NaN,NaN,NaN,41.954341,-87.686080,15.0,627.0,Chicago,classic_bike
6144665,24648419,18:32:53,18:36:21,6258,208.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),656,Damen Ave & Walnut (Lake) St (*),member,...,NaN,NaN,NaN,NaN,41.886460,-87.677010,15.0,0.0,Chicago,classic_bike
6195095,24701472,14:21:01,15:35:02,767,"4,441.0",665,South Chicago Ave & Elliot Ave,588,South Chicago Ave & 83rd St,casual,...,NaN,NaN,NaN,NaN,41.743921,-87.575225,11.0,0.0,Chicago,classic_bike
6681106,25209965,11:00:39,11:26:29,3750,"1,549.0",665,South Chicago Ave & Elliot Ave,665,South Chicago Ave & Elliot Ave,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
6681364,25210248,11:27:41,11:48:25,3750,"1,243.0",665,South Chicago Ave & Elliot Ave,583,Stony Island Ave & 82nd St,member,...,NaN,NaN,NaN,NaN,41.746559,-87.586005,11.0,0.0,Chicago,classic_bike
6811026,25346695,06:26:02,15:00:17,6184,"2,367,255.0",665,South Chicago Ave & Elliot Ave,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
6815619,25351470,10:26:36,10:48:58,3904,"1,341.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),337,Clark St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.896544,-87.630931,19.0,303.0,Chicago,classic_bike
6883907,25422958,22:31:51,23:15:43,6306,"2,632.0",665,South Chicago Ave & Elliot Ave,569,Woodlawn Ave & 75th St,casual,...,NaN,NaN,NaN,NaN,41.759160,-87.595751,15.0,0.0,Chicago,classic_bike
6916337,25456596,14:18:34,14:47:15,1519,"1,721.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),486,Oakley Ave & Irving Park Rd,member,...,NaN,NaN,NaN,NaN,41.954341,-87.686080,15.0,627.0,Chicago,classic_bike
7069278,25618689,18:00:39,18:27:09,3172,"1,590.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),486,Oakley Ave & Irving Park Rd,member,...,NaN,NaN,NaN,NaN,41.954341,-87.686080,15.0,627.0,Chicago,classic_bike
7096926,25647964,11:46:09,11:54:01,1667,471.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7127364,25680015,09:57:49,10:06:23,4175,514.0,647,Elizabeth St & 59th St,559,Racine Ave & Garfield Blvd,member,...,NaN,NaN,NaN,NaN,41.794694,-87.654947,11.0,0.0,Chicago,classic_bike
7150761,25704962,18:11:24,18:35:43,5598,"1,459.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),163,Damen Ave & Clybourn Ave,member,...,NaN,NaN,NaN,NaN,41.931860,-87.670790,15.0,271.0,Chicago,classic_bike
7195187,25752130,18:20:40,18:53:39,3204,"1,978.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),239,Western Ave & Leland Ave,member,...,NaN,NaN,NaN,NaN,41.966555,-87.688487,15.0,112.0,Chicago,classic_bike
7203104,25760622,18:25:24,18:53:26,1870,"1,682.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),126,Clark St & North Ave,member,...,NaN,NaN,NaN,NaN,41.911791,-87.631841,15.0,128.0,Chicago,classic_bike

In [167]:
fix_nulls(647, 7, [41.78974, -87.65469], 'Chicago')

In [168]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
3898777,22107937,11:26:22,13:00:08,4909,"5,626.0",665,South Chicago Ave & Elliot Ave,665,South Chicago Ave & Elliot Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4440317,22748777,14:01:05,14:10:20,1741,555.0,1,Special Events,1,Special Events,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4832700,23207817,13:54:49,13:57:19,6206,150.0,669,LBS - BBB La Magie,669,LBS - BBB La Magie,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5319142,23775344,14:27:52,14:31:10,2540,198.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5322880,23779268,17:15:28,20:26:23,3990,"11,455.0",665,South Chicago Ave & Elliot Ave,665,South Chicago Ave & Elliot Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5322890,23779279,17:15:40,20:26:31,359,"11,451.0",665,South Chicago Ave & Elliot Ave,665,South Chicago Ave & Elliot Ave,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5452340,23916262,16:52:58,16:57:05,4198,247.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5637916,24113003,03:40:28,04:43:38,3990,"3,789.0",665,South Chicago Ave & Elliot Ave,588,South Chicago Ave & 83rd St,casual,...,NaN,NaN,NaN,NaN,41.743921,-87.575225,11.0,0.0,Chicago,classic_bike
5693602,24172268,15:42:51,20:37:47,4909,"17,696.0",665,South Chicago Ave & Elliot Ave,585,Cottage Grove Ave & 83rd St,casual,...,NaN,NaN,NaN,NaN,41.744053,-87.604786,11.0,0.0,Chicago,classic_bike
5693620,24172289,15:43:34,20:37:55,6276,"17,661.0",665,South Chicago Ave & Elliot Ave,585,Cottage Grove Ave & 83rd St,casual,...,NaN,NaN,NaN,NaN,41.744053,-87.604786,11.0,0.0,Chicago,classic_bike
5783647,24267109,22:13:36,22:44:28,2736,"1,852.0",665,South Chicago Ave & Elliot Ave,200,MLK Jr Dr & 47th St,casual,...,NaN,NaN,NaN,NaN,41.809851,-87.616279,11.0,90.0,Chicago,classic_bike
5931358,24423222,18:15:00,18:20:27,1404,326.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),119,Ashland Ave & Lake St,member,...,NaN,NaN,NaN,NaN,41.885410,-87.667320,19.0,73.0,Chicago,classic_bike
6009558,24506080,16:04:53,16:10:55,4835,361.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),119,Ashland Ave & Lake St,member,...,NaN,NaN,NaN,NaN,41.885410,-87.667320,19.0,73.0,Chicago,classic_bike
6057227,24556354,19:03:03,19:05:28,4295,145.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),214,Damen Ave & Grand Ave,member,...,NaN,NaN,NaN,NaN,41.891220,-87.676860,15.0,141.0,Chicago,classic_bike
6058675,24557892,20:33:02,14:39:56,1822,"65,214.0",665,South Chicago Ave & Elliot Ave,581,Commercial Ave & 83rd St,casual,...,NaN,NaN,NaN,NaN,41.744607,-87.551201,15.0,0.0,Chicago,classic_bike
6106963,24608963,18:11:38,18:40:23,5677,"1,725.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),486,Oakley Ave & Irving Park Rd,member,...,NaN,NaN,NaN,NaN,41.954341,-87.686080,15.0,627.0,Chicago,classic_bike
6144665,24648419,18:32:53,18:36:21,6258,208.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),656,Damen Ave & Walnut (Lake) St (*),member,...,NaN,NaN,NaN,NaN,41.886460,-87.677010,15.0,0.0,Chicago,classic_bike
6195095,24701472,14:21:01,15:35:02,767,"4,441.0",665,South Chicago Ave & Elliot Ave,588,South Chicago Ave & 83rd St,casual,...,NaN,NaN,NaN,NaN,41.743921,-87.575225,11.0,0.0,Chicago,classic_bike
6681106,25209965,11:00:39,11:26:29,3750,"1,549.0",665,South Chicago Ave & Elliot Ave,665,South Chicago Ave & Elliot Ave,member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
6681364,25210248,11:27:41,11:48:25,3750,"1,243.0",665,South Chicago Ave & Elliot Ave,583,Stony Island Ave & 82nd St,member,...,NaN,NaN,NaN,NaN,41.746559,-87.586005,11.0,0.0,Chicago,classic_bike
6811026,25346695,06:26:02,15:00:17,6184,"2,367,255.0",665,South Chicago Ave & Elliot Ave,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
6815619,25351470,10:26:36,10:48:58,3904,"1,341.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),337,Clark St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.896544,-87.630931,19.0,303.0,Chicago,classic_bike
6883907,25422958,22:31:51,23:15:43,6306,"2,632.0",665,South Chicago Ave & Elliot Ave,569,Woodlawn Ave & 75th St,casual,...,NaN,NaN,NaN,NaN,41.759160,-87.595751,15.0,0.0,Chicago,classic_bike
6916337,25456596,14:18:34,14:47:15,1519,"1,721.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),486,Oakley Ave & Irving Park Rd,member,...,NaN,NaN,NaN,NaN,41.954341,-87.686080,15.0,627.0,Chicago,classic_bike
7069278,25618689,18:00:39,18:27:09,3172,"1,590.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),486,Oakley Ave & Irving Park Rd,member,...,NaN,NaN,NaN,NaN,41.954341,-87.686080,15.0,627.0,Chicago,classic_bike
7096926,25647964,11:46:09,11:54:01,1667,471.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7150761,25704962,18:11:24,18:35:43,5598,"1,459.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),163,Damen Ave & Clybourn Ave,member,...,NaN,NaN,NaN,NaN,41.931860,-87.670790,15.0,271.0,Chicago,classic_bike
7195187,25752130,18:20:40,18:53:39,3204,"1,978.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),239,Western Ave & Leland Ave,member,...,NaN,NaN,NaN,NaN,41.966555,-87.688487,15.0,112.0,Chicago,classic_bike
7203104,25760622,18:25:24,18:53:26,1870,"1,682.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),126,Clark St & North Ave,member,...,NaN,NaN,NaN,NaN,41.911791,-87.631841,15.0,128.0,Chicago,classic_bike

In [169]:
fix_nulls(665, 7, [41.74734, -87.58003], 'Chicago')

In [170]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
4440317,22748777,14:01:05,14:10:20,1741,555.0,1,Special Events,1,Special Events,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
4832700,23207817,13:54:49,13:57:19,6206,150.0,669,LBS - BBB La Magie,669,LBS - BBB La Magie,casual,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5319142,23775344,14:27:52,14:31:10,2540,198.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5452340,23916262,16:52:58,16:57:05,4198,247.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
5931358,24423222,18:15:00,18:20:27,1404,326.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),119,Ashland Ave & Lake St,member,...,NaN,NaN,NaN,NaN,41.885410,-87.667320,19.0,73.0,Chicago,classic_bike
6009558,24506080,16:04:53,16:10:55,4835,361.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),119,Ashland Ave & Lake St,member,...,NaN,NaN,NaN,NaN,41.885410,-87.667320,19.0,73.0,Chicago,classic_bike
6057227,24556354,19:03:03,19:05:28,4295,145.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),214,Damen Ave & Grand Ave,member,...,NaN,NaN,NaN,NaN,41.891220,-87.676860,15.0,141.0,Chicago,classic_bike
6106963,24608963,18:11:38,18:40:23,5677,"1,725.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),486,Oakley Ave & Irving Park Rd,member,...,NaN,NaN,NaN,NaN,41.954341,-87.686080,15.0,627.0,Chicago,classic_bike
6144665,24648419,18:32:53,18:36:21,6258,208.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),656,Damen Ave & Walnut (Lake) St (*),member,...,NaN,NaN,NaN,NaN,41.886460,-87.677010,15.0,0.0,Chicago,classic_bike
6815619,25351470,10:26:36,10:48:58,3904,"1,341.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),337,Clark St & Chicago Ave,member,...,NaN,NaN,NaN,NaN,41.896544,-87.630931,19.0,303.0,Chicago,classic_bike
6916337,25456596,14:18:34,14:47:15,1519,"1,721.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),486,Oakley Ave & Irving Park Rd,member,...,NaN,NaN,NaN,NaN,41.954341,-87.686080,15.0,627.0,Chicago,classic_bike
7069278,25618689,18:00:39,18:27:09,3172,"1,590.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),486,Oakley Ave & Irving Park Rd,member,...,NaN,NaN,NaN,NaN,41.954341,-87.686080,15.0,627.0,Chicago,classic_bike
7096926,25647964,11:46:09,11:54:01,1667,471.0,671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),member,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,classic_bike
7150761,25704962,18:11:24,18:35:43,5598,"1,459.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),163,Damen Ave & Clybourn Ave,member,...,NaN,NaN,NaN,NaN,41.931860,-87.670790,15.0,271.0,Chicago,classic_bike
7195187,25752130,18:20:40,18:53:39,3204,"1,978.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),239,Western Ave & Leland Ave,member,...,NaN,NaN,NaN,NaN,41.966555,-87.688487,15.0,112.0,Chicago,classic_bike
7203104,25760622,18:25:24,18:53:26,1870,"1,682.0",671,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),126,Clark St & North Ave,member,...,NaN,NaN,NaN,NaN,41.911791,-87.631841,15.0,128.0,Chicago,classic_bike

In [171]:
# Now delete all of these

merged2018_2019 = merged2018_2019.drop(merged2018_2019[merged2018_2019['from_station_name'] == 'HUBBARD ST BIKE CHECKING (LBS-WH-TEST)'].index)
merged2018_2019 = merged2018_2019.drop(merged2018_2019[merged2018_2019['to_station_name'] == 'HUBBARD ST BIKE CHECKING (LBS-WH-TEST)'].index)

merged2018_2019 = merged2018_2019.drop(merged2018_2019[merged2018_2019['from_station_name'] == 'Special Events'].index)
merged2018_2019 = merged2018_2019.drop(merged2018_2019[merged2018_2019['to_station_name'] == 'Special Events'].index)

merged2018_2019 = merged2018_2019.drop(merged2018_2019[merged2018_2019['from_station_name'] == 'LBS - BBB La Magie'].index)
merged2018_2019 = merged2018_2019.drop(merged2018_2019[merged2018_2019['to_station_name'] == 'LBS - BBB La Magie'].index)

In [172]:
merged2018_2019[merged2018_2019['from_lat'].isnull()]

Empty DataFrame
Columns: [trip_id, start_time, end_time, bikeid, tripduration, from_station_id, from_station_name, to_station_id, to_station_name, usertype, gender, birthyear, start_date, end_date, from_lat, from_long, dpcapacity_x, from_landmark, from_city, to_lat, to_long, dpcapacity_y, to_landmark, to_city, rideable_type]
Index: []

[0 rows x 25 columns]

In [173]:
merged2018_2019[merged2018_2019['to_lat'].isnull()]

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,from_long,dpcapacity_x,from_landmark,from_city,to_lat,to_long,dpcapacity_y,to_landmark,to_city,rideable_type
4417203,22721057,10:27:00,10:39:03,2191,723.0,410,Prairie Ave & 43rd St,363,TS ~ DIVVY PARTS TESTING,casual,...,-87.619412,19.0,452.0,Chicago,NaN,NaN,NaN,NaN,NaN,classic_bike
4417328,22721199,10:43:33,10:48:51,4732,318.0,279,Halsted St & 35th St (*),363,TS ~ DIVVY PARTS TESTING,member,...,-87.647172,15.0,413.0,Chicago,NaN,NaN,NaN,NaN,NaN,classic_bike

In [174]:
merged2018_2019 = merged2018_2019.drop(merged2018_2019[merged2018_2019['from_station_name'] == 'TS ~ DIVVY PARTS TESTING'].index)
merged2018_2019 = merged2018_2019.drop(merged2018_2019[merged2018_2019['to_station_name'] == 'TS ~ DIVVY PARTS TESTING'].index)

In [175]:
merged2018_2019[merged2018_2019['to_lat'].isnull()]

Empty DataFrame
Columns: [trip_id, start_time, end_time, bikeid, tripduration, from_station_id, from_station_name, to_station_id, to_station_name, usertype, gender, birthyear, start_date, end_date, from_lat, from_long, dpcapacity_x, from_landmark, from_city, to_lat, to_long, dpcapacity_y, to_landmark, to_city, rideable_type]
Index: []

[0 rows x 25 columns]

In [176]:
merged2018_2019.isnull().sum()

trip_id              0
start_time           0
end_time             0
bikeid               0
tripduration         0
from_station_id      0
from_station_name    0
to_station_id        0
to_station_name      0
usertype             0
gender               0
birthyear            0
start_date           0
end_date             0
from_lat             0
from_long            0
dpcapacity_x         0
from_landmark        0
from_city            0
to_lat               0
to_long              0
dpcapacity_y         0
to_landmark          0
to_city              0
rideable_type        0
dtype: int64

In [177]:
merged2018_2019.shape

(7392597, 25)

In [178]:
# making sure no test Values are left
merged2018_2019 = merged2018_2019.drop(merged2018_2019[merged2018_2019['from_station_name'].str.lower().str.contains("test", regex=False, na=False) == True].index)
merged2018_2019 = merged2018_2019.drop(merged2018_2019[merged2018_2019['to_station_name'].str.lower().str.contains("test", regex=False, na=False) == True].index)

In [179]:
merged2018_2019.shape

(7392597, 25)

In [180]:
hi = sorted(list(set(merged2018_2019['from_station_name'].values)))

for i in range(len(hi)):
    print(hi[i])

2112 W Peterson Ave
63rd St Beach
900 W Harrison St
Aberdeen St & Jackson Blvd
Aberdeen St & Monroe St
Aberdeen St & Randolph St
Ada St & Washington Blvd
Adler Planetarium
Albany Ave & 26th St
Albany Ave & Bloomingdale Ave
Albany Ave & Montrose Ave
Archer (Damen) Ave & 37th St
Archer (Damen) Ave & 37th St (*)
Artesian Ave & Hubbard St
Ashland Ave & 13th St
Ashland Ave & 21st St
Ashland Ave & 50th St
Ashland Ave & 63rd St
Ashland Ave & 66th St
Ashland Ave & 69th St
Ashland Ave & Archer Ave
Ashland Ave & Augusta Blvd
Ashland Ave & Belle Plaine Ave
Ashland Ave & Blackhawk St
Ashland Ave & Chicago Ave
Ashland Ave & Division St
Ashland Ave & Garfield Blvd
Ashland Ave & Grace St
Ashland Ave & Grand Ave
Ashland Ave & Harrison St
Ashland Ave & Lake St
Ashland Ave & Lake St (Temp)
Ashland Ave & McDowell Ave
Ashland Ave & Pershing Rd
Ashland Ave & Wellington Ave
Ashland Ave & Wrightwood Ave
Austin Blvd & Chicago Ave
Austin Blvd & Lake St
Austin Blvd & Madison St
Avers Ave & Belmont Ave
Avondale Ave & Irving Park Rd
Bennett Ave & 79th St
Benson Ave & Church St
Bernard St & Elston Ave
Bissell St & Armitage Ave
Blackstone Ave & Hyde Park Blvd
Blue Island Ave & 18th St
Bosworth Ave & Howard St
Broadway & Argyle St
Broadway & Barry Ave
Broadway & Belmont Ave
Broadway & Berwyn Ave
Broadway & Cornelia Ave
Broadway & Granville Ave
Broadway & Ridge Ave
Broadway & Sheridan Rd
Broadway & Thorndale Ave
Broadway & Waveland Ave
Broadway & Wilson Ave
Buckingham Fountain
Buckingham Fountain (Temp)
Budlong Woods Library
Burling St (Halsted) & Diversey Pkwy (Temp)
Burnham Harbor
California Ave & 21st St
California Ave & 23rd Pl
California Ave & 26th St
California Ave & Altgeld St
California Ave & Byron St
California Ave & Cortez St
California Ave & Division St
California Ave & Fletcher St
California Ave & Francis Pl
California Ave & Francis Pl (Temp)
California Ave & Lake St
California Ave & Milwaukee Ave
California Ave & Montrose Ave
California Ave & North Ave
Calumet Ave & 18th St
Calumet Ave & 21st St
Calumet Ave & 33rd St
Calumet Ave & 35th St
Calumet Ave & 51st St
Calumet Ave & 71st St
Campbell Ave & Fullerton Ave
Campbell Ave & Montrose Ave
Campbell Ave & North Ave
Canal St & Adams St
Canal St & Harrison St
Canal St & Jackson Blvd
Canal St & Madison St
Canal St & Monroe St
Canal St & Monroe St (*)
Canal St & Taylor St
Cannon Dr & Fullerton Ave
Carpenter St & 63rd St
Carpenter St & Huron St
Central Ave & Chicago Ave
Central Ave & Harrison St
Central Ave & Lake St
Central Ave & Madison St
Central Park Ave & 24th St
Central Park Ave & Bloomingdale Ave
Central Park Ave & Elbridge Ave
Central Park Ave & North Ave
Central Park Ave & Ogden Ave
Central Park Blvd & 5th Ave
Central St & Girard Ave
Central St Metra
Cherry Ave & Blackhawk St
Chicago Ave & Dempster St
Chicago Ave & Sheridan Rd
Chicago Ave & Washington St
Christiana Ave & Lawrence Ave
Cicero Ave & Flournoy St
Cicero Ave & Lake St
Cicero Ave & Quincy St
Cityfront Plaza Dr & Pioneer Ct
Claremont Ave & Hirsch St
Clarendon Ave & Gordon Ter
Clarendon Ave & Junior Ter
Clarendon Ave & Leland Ave
Clark St & 9th St (AMLI)
Clark St & Armitage Ave
Clark St & Berwyn Ave
Clark St & Bryn Mawr Ave
Clark St & Chicago Ave
Clark St & Columbia Ave
Clark St & Congress Pkwy
Clark St & Drummond Pl
Clark St & Elm St
Clark St & Elmdale Ave
Clark St & Grace St
Clark St & Ida B Wells Dr
Clark St & Jarvis Ave
Clark St & Lake St
Clark St & Leland Ave
Clark St & Lincoln Ave
Clark St & Lunt Ave
Clark St & Montrose Ave
Clark St & Newport St
Clark St & North Ave
Clark St & Randolph St
Clark St & Schiller St
Clark St & Schreiber Ave
Clark St & Touhy Ave
Clark St & Wellington Ave
Clark St & Winnemac Ave
Clark St & Winnemac Ave (Temp)
Clark St & Wrightwood Ave
Clifton Ave & Armitage Ave
Clinton St & 18th St
Clinton St & Jackson Blvd
Clinton St & Jackson Blvd (*)
Clinton St & Lake St
Clinton St & Madison St
Clinton St & Polk St
Clinton St & Polk St (*)
Clinton St & Roosevelt Rd
Clinton St & Tilden St
Clinton St & Washington Blvd
Clybourn Ave & Division St
Columbus Dr & Randolph St
Commercial Ave & 83rd St
Conservatory Dr & Lake St
Cornell Ave & Hyde Park Blvd
Cornell Dr & Hayes Dr
Cottage Grove Ave & 43rd St
Cottage Grove Ave & 47th St
Cottage Grove Ave & 51st St
Cottage Grove Ave & 63rd St
Cottage Grove Ave & 67th St
Cottage Grove Ave & 71st St
Cottage Grove Ave & 78th St
Cottage Grove Ave & 83rd St
Cottage Grove Ave & Oakwood Blvd
Cuyler Ave & Augusta St
DIVVY CASSETTE REPAIR MOBILE STATION
Daley Center Plaza
Damen Ave & 51st St
Damen Ave & 59th St
Damen Ave & Charleston St
Damen Ave & Chicago Ave
Damen Ave & Clybourn Ave
Damen Ave & Cortland St
Damen Ave & Coulter St
Damen Ave & Cullerton St
Damen Ave & Division St
Damen Ave & Foster Ave
Damen Ave & Grand Ave
Damen Ave & Leland Ave
Damen Ave & Madison St
Damen Ave & Melrose Ave
Damen Ave & Pershing Rd
Damen Ave & Pierce Ave
Damen Ave & Sunnyside Ave
Damen Ave & Thomas St (Augusta Blvd)
Damen Ave & Walnut (Lake) St (*)
Damen Ave & Wellington Ave
Dayton St & North Ave
Dearborn Pkwy & Delaware Pl
Dearborn St & Adams St
Dearborn St & Erie St
Dearborn St & Monroe St
Dearborn St & Van Buren St
Dearborn St & Van Buren St (*)
Delano Ct & Roosevelt Rd
Desplaines St & Jackson Blvd
Desplaines St & Kinzie St
Desplaines St & Randolph St
Dodge Ave & Church St
Dodge Ave & Mulford St
Dorchester Ave & 49th St
Dorchester Ave & 63rd St
Drake Ave & Addison St
Drake Ave & Fullerton Ave
Drake Ave & Montrose Ave
DuSable Museum
Dusable Harbor
East Ave & Garfield St
East Ave & Madison St
Eastlake Ter & Rogers Ave
Eberhart (Vernon) Ave & 79th St
Eberhart Ave & 61st St
Eckhart Park
Eggleston Ave & 69th St (*)
Elizabeth (May) St & Fulton St
Elizabeth St & 47th St
Elizabeth St & 59th St
Ellis Ave & 53rd St
Ellis Ave & 55th St
Ellis Ave & 58th St
Ellis Ave & 60th St
Ellis Ave & 83rd St
Elmwood Ave & Austin St
Elston Ave & Wabansia Ave
Emerald Ave & 28th St
Emerald Ave & 31st St
Evans Ave & 75th St
Evanston Civic Center
Exchange Ave & 79th St
Fairbanks Ct & Grand Ave
Fairbanks St & Superior St
Fairbanks St & Superior St (*)
Fairfield Ave & Roosevelt Rd
Federal St & Polk St
Field Blvd & South Water St
Field Museum
Financial Pl & Congress Pkwy (Temp)
Financial Pl & Ida B Wells Dr
Financial Pl & Ida B Wells Dr (Temp)
Forest Ave & Chicago Ave
Forest Ave & Lake St
Fort Dearborn Dr & 31st St
Francisco Ave & Foster Ave
Franklin St & Adams St (Temp)
Franklin St & Chicago Ave
Franklin St & Chicago Ave (Temp)
Franklin St & Illinois St
Franklin St & Jackson Blvd
Franklin St & Lake St
Franklin St & Monroe St
Franklin St & Quincy St
Glenwood Ave & Morse Ave
Glenwood Ave & Touhy Ave
Green St & Madison St
Green St & Randolph St
Greenview Ave & Diversey Pkwy
Greenview Ave & Fullerton Ave
Greenview Ave & Jarvis Ave
Greenwood Ave & 47th St
Greenwood Ave & 79th St
Halsted St & 18th St
Halsted St & 21st St
Halsted St & 35th St
Halsted St & 35th St (*)
Halsted St & 37th St
Halsted St & 47th Pl
Halsted St & 51st St
Halsted St & 56th St
Halsted St & 59th St
Halsted St & 63rd St
Halsted St & 69th St
Halsted St & Archer Ave
Halsted St & Clybourn Ave
Halsted St & Clybourn Ave (*)
Halsted St & Dickens Ave
Halsted St & Maxwell St
Halsted St & North Branch St
Halsted St & Polk St
Halsted St & Roosevelt Rd
Halsted St & Roscoe St
Halsted St & Willow St
Halsted St & Wrightwood Ave
Harper Ave & 59th St
Hermitage Ave & Polk St
Honore St & Division St
Hoyne Ave & 47th St
Hoyne Ave & Balmoral Ave
Humboldt Blvd & Armitage Ave
Humphrey Ave & Ontario St
Indiana Ave & 26th St
Indiana Ave & 31st St
Indiana Ave & 40th St
Indiana Ave & Roosevelt Rd
Jefferson St & Monroe St
Jeffery Blvd & 67th St
Jeffery Blvd & 71st St
Jeffery Blvd & 76th St
Karlov Ave & Madison St
Kedzie Ave & 21st St
Kedzie Ave & 24th St
Kedzie Ave & Bryn Mawr Ave
Kedzie Ave & Chicago Ave
Kedzie Ave & Foster Ave
Kedzie Ave & Harrison St
Kedzie Ave & Lake St
Kedzie Ave & Leland Ave
Kedzie Ave & Milwaukee Ave
Kedzie Ave & Palmer Ct
Kedzie Ave & Roosevelt Rd
Kenton Ave & Madison St
Keystone Ave & Fullerton Ave
Keystone Ave & Montrose Ave
Kilbourn Ave & Irving Park Rd
Kilbourn Ave & Milwaukee Ave
Kildare Ave & Montrose Ave
Kimball Ave & Belmont Ave
Kimbark Ave & 53rd St
Kingsbury St & Erie St
Kingsbury St & Kinzie St
Knox Ave & Montrose Ave
Kosciuszko Park
Kostner Ave & Adams St
Kostner Ave & Lake St
LaSalle Dr & Huron St
LaSalle Dr & Huron St (*)
LaSalle St & Adams St
LaSalle St & Illinois St
LaSalle St & Jackson Blvd
LaSalle St & Washington St
Lake Park Ave & 35th St
Lake Park Ave & 47th St
Lake Park Ave & 53rd St
Lake Park Ave & 56th St
Lake Shore Dr & Belmont Ave
Lake Shore Dr & Diversey Pkwy
Lake Shore Dr & Monroe St
Lake Shore Dr & North Blvd
Lake Shore Dr & Ohio St
Lake Shore Dr & Wellington Ave
Lakefront Trail & Bryn Mawr Ave
Lakefront Trail & Wilson Ave
Lakeview Ave & Fullerton Pkwy
Laramie Ave & Gladys Ave
Laramie Ave & Kinzie St
Laramie Ave & Madison St
Larrabee St & Armitage Ave
Larrabee St & Division St
Larrabee St & Kingsbury St
Larrabee St & Menomonee St
Larrabee St & North Ave
Larrabee St & Oak St
Larrabee St & Webster Ave
Latrobe Ave & Chicago Ave
Leavitt St & Addison St
Leavitt St & Archer Ave
Leavitt St & Armitage Ave
Leavitt St & Belmont Ave (*)
Leavitt St & Chicago Ave
Leavitt St & Division St (*)
Leavitt St & Lawrence Ave
Leavitt St & North Ave
Lincoln Ave & Addison St
Lincoln Ave & Belle Plaine Ave
Lincoln Ave & Belmont Ave
Lincoln Ave & Diversey Pkwy
Lincoln Ave & Fullerton Ave
Lincoln Ave & Leavitt St
Lincoln Ave & Roscoe St
Lincoln Ave & Sunnyside Ave
Lincoln Ave & Waveland Ave
Lincoln Ave & Winona St
Lincoln Park Conservatory
Lincolnwood Dr & Central St
Logan Blvd & Elston Ave
Lombard Ave & Garfield St
Lombard Ave & Madison St
Loomis St & Archer Ave
Loomis St & Jackson Blvd
Loomis St & Lexington St
Loomis St & Taylor St (*)
MLK Jr Dr & 29th St
MLK Jr Dr & 47th St
MLK Jr Dr & 56th St
MLK Jr Dr & 56th St (*)
MLK Jr Dr & 63rd St
MLK Jr Dr & 83rd St
MLK Jr Dr & Pershing Rd
Malcolm X College
Manor Ave & Leland Ave
Maplewood Ave & Peterson Ave
Marine Dr & Ainslie St
Marion St & South Blvd
Marshfield Ave & 44th St
Marshfield Ave & 59th St
Marshfield Ave & Cortland St
May St & 69th St
May St & Cullerton St
May St & Taylor St
McClurg Ct & Erie St
McClurg Ct & Illinois St
McCormick Place
Michigan Ave & 14th St
Michigan Ave & 18th St
Michigan Ave & 71st St
Michigan Ave & 8th St
Michigan Ave & Congress Pkwy
Michigan Ave & Ida B Wells Dr
Michigan Ave & Jackson Blvd
Michigan Ave & Lake St
Michigan Ave & Madison St
Michigan Ave & Oak St
Michigan Ave & Pearson St
Michigan Ave & Washington St
Mies van der Rohe Way & Chestnut St
Mies van der Rohe Way & Chicago Ave
Millard Ave & 26th St
Millennium Park
Milwaukee Ave & Cuyler Ave
Milwaukee Ave & Grand Ave
Milwaukee Ave & Rockwell St
Milwaukee Ave & Wabansia Ave
Monticello Ave & Irving Park Rd
Montrose Harbor
Morgan Ave & 14th Pl
Morgan St & 18th St
Morgan St & 31st St
Morgan St & Lake St
Morgan St & Pershing Rd
Morgan St & Polk St
Museum of Science and Industry
Noble St & Milwaukee Ave
Normal Ave & 72nd St
Normal Ave & Archer Ave
Oak Park Ave & Harrison St
Oak Park Ave & South Blvd
Oakley Ave & Irving Park Rd
Oakley Ave & Touhy Ave
Ogden Ave & Chicago Ave
Ogden Ave & Congress Pkwy
Ogden Ave & Race Ave
Ogden Ave & Roosevelt Rd
Orleans St & Chestnut St (NEXT Apts)
Orleans St & Elm St
Orleans St & Elm St (*)
Orleans St & Hubbard St
Orleans St & Hubbard St (*)
Orleans St & Merchandise Mart Plaza
Paulina Ave & North Ave
Paulina St & 18th St
Paulina St & Flournoy St
Paulina St & Howard St
Paulina St & Montrose Ave
Peoria St & Jackson Blvd
Perry Ave & 69th St
Phillips Ave & 79th St
Phillips Ave & 83rd St
Pine Grove Ave & Irving Park Rd
Pine Grove Ave & Waveland Ave
Prairie Ave & 43rd St
Prairie Ave & Garfield Blvd
Princeton Ave & 47th St
Princeton Ave & Garfield Blvd
Pulaski Rd & Congress Pkwy
Pulaski Rd & Eddy St (Temp)
Pulaski Rd & Lake St
Racine Ave & 13th St
Racine Ave & 15th St
Racine Ave & 18th St
Racine Ave & 35th St
Racine Ave & 61st St
Racine Ave & 65th St
Racine Ave & Belmont Ave
Racine Ave & Congress Pkwy
Racine Ave & Fullerton Ave
Racine Ave & Garfield Blvd
Racine Ave & Randolph St
Racine Ave & Washington Blvd (*)
Racine Ave & Wrightwood Ave
Racine Ave (May St) & Fulton St
Rainbow Beach
Ravenswood Ave & Berteau Ave
Ravenswood Ave & Irving Park Rd
Ravenswood Ave & Lawrence Ave
Rhodes Ave & 32nd St
Rhodes Ave & 71st St
Richmond St & Diversey Ave
Ridge Blvd & Howard St
Ridge Blvd & Touhy Ave
Ridgeland Ave & Lake St
Ritchie Ct & Banks St
Rockwell St & Eastwood Ave
Rush St & Cedar St
Rush St & Hubbard St
Rush St & Superior St
Sacramento Blvd & Franklin Blvd
Saginaw Ave & Exchange Ave
Sangamon St & Washington Blvd
Sangamon St & Washington Blvd (*)
Sawyer Ave & Irving Park Rd
Sedgwick St & Huron St
Sedgwick St & North Ave
Sedgwick St & Schiller St
Sedgwick St & Webster Ave
Seeley Ave & Garfield Blvd
Seeley Ave & Roscoe St
Shedd Aquarium
Sheffield Ave & Fullerton Ave
Sheffield Ave & Kingsbury St
Sheffield Ave & Waveland Ave
Sheffield Ave & Webster Ave
Sheffield Ave & Wellington Ave
Sheffield Ave & Willow St
Sheffield Ave & Wrightwood Ave
Sheridan Rd & Buena Ave
Sheridan Rd & Columbia Ave
Sheridan Rd & Greenleaf Ave
Sheridan Rd & Irving Park Rd
Sheridan Rd & Lawrence Ave
Sheridan Rd & Loyola Ave
Sheridan Rd & Montrose Ave
Sheridan Rd & Noyes St (NU)
Shields Ave & 28th Pl
Shields Ave & 31st St
Shields Ave & 43rd St
Shore Dr & 55th St
Smith Park (*)
South Chicago Ave & 83rd St
South Chicago Ave & Elliot Ave
South Shore Dr & 67th St
South Shore Dr & 71st St
South Shore Dr & 74th St
Southport Ave & Belmont Ave
Southport Ave & Clark St
Southport Ave & Clybourn Ave
Southport Ave & Irving Park Rd
Southport Ave & Roscoe St
Southport Ave & Waveland Ave
Southport Ave & Wellington Ave
Southport Ave & Wrightwood Ave
Spaulding Ave & Armitage Ave
Spaulding Ave & Division St
St. Clair St & Erie St
St. Louis Ave & Balmoral Ave
State St & 19th St
State St & 29th St
State St & 33rd St
State St & 35th St
State St & 54th St
State St & 76th St
State St & 79th St
State St & Harrison St
State St & Kinzie St
State St & Pearson St
State St & Pershing Rd
State St & Randolph St
State St & Van Buren St
Stave St & Armitage Ave
Stetson Ave & South Water St
Stewart Ave & 63rd St (*)
Stockton Dr & Wrightwood Ave
Stony Island Ave & 64th St
Stony Island Ave & 67th St
Stony Island Ave & 71st St
Stony Island Ave & 75th St
Stony Island Ave & 82nd St
Stony Island Ave & South Chicago Ave
Streeter Dr & Grand Ave
Talman Ave & Addison St
Theater on the Lake
Throop (Loomis) St & Taylor St
Throop St & 52nd St
Troy St & Elston Ave
Troy St & North Ave
Union Ave & Root St
University Ave & 57th St
University Library (NU)
Valli Produce - Evanston Plaza
Vernon Ave & 75th St
Vernon Ave & 79th St
Vincennes Ave & 75th St
Wabash Ave & 16th St
Wabash Ave & 83rd St
Wabash Ave & 87th St
Wabash Ave & 9th St
Wabash Ave & Adams St
Wabash Ave & Cermak Rd
Wabash Ave & Grand Ave
Wabash Ave & Roosevelt Rd
Wabash Ave & Wacker Pl
Wacker Dr & Washington St
Wallace St & 35th St
Walsh Park
Warren Park East
Warren Park West
Washtenaw Ave & Lawrence Ave
Washtenaw Ave & Ogden Ave
Washtenaw Ave & Ogden Ave (*)
Wells St & 19th St
Wells St & Concord Ln
Wells St & Elm St
Wells St & Evergreen Ave
Wells St & Hubbard St
Wells St & Huron St
Wells St & Polk St
Wells St & Walton St
Wentworth Ave & 24th St
Wentworth Ave & 24th St (Temp)
Wentworth Ave & 33rd St
Wentworth Ave & 35th St
Wentworth Ave & 63rd St
Wentworth Ave & Cermak Rd (Temp)
Western Ave & 21st St
Western Ave & 24th St
Western Ave & 28th St
Western Ave & Congress Pkwy
Western Ave & Division St
Western Ave & Fillmore St (*)
Western Ave & Granville Ave
Western Ave & Howard St
Western Ave & Leland Ave
Western Ave & Lunt Ave
Western Ave & Monroe St
Western Ave & Roscoe St
Western Ave & Walton St
Western Ave & Winnebago Ave
Western Blvd & 48th Pl
Wilton Ave & Belmont Ave
Wilton Ave & Diversey Pkwy
Winchester (Ravenswood) Ave & Balmoral Ave
Winchester Ave & Elston Ave
Winthrop Ave & Lawrence Ave
Wisconsin Ave & Madison St (Temp)
Wolcott (Ravenswood) Ave & Montrose Ave
Wolcott (Ravenswood) Ave & Montrose Ave (*)
Wolcott Ave & Fargo Ave
Wolcott Ave & Polk St
Wood St & 35th St
Wood St & Augusta Blvd
Wood St & Chicago Ave (*)
Wood St & Hubbard St
Wood St & Milwaukee Ave
Wood St & Taylor St
Woodlawn Ave & 55th St
Woodlawn Ave & 75th St
Woodlawn Ave & Lake Park Ave
Yates Blvd & 75th St

In [181]:
# DIVVY CASSETTE REPAIR MOBILE STATION , 

merged2018_2019 = merged2018_2019.drop(merged2018_2019[merged2018_2019['from_station_name'] == 'TS ~ DIVVY PARTS TESTING'].index)
merged2018_2019 = merged2018_2019.drop(merged2018_2019[merged2018_2019['to_station_name'] == 'TS ~ DIVVY PARTS TESTING'].index)

# some values with (Temp) or (*) at the end of the station names can be combined with non-temp or non-* values, will keep this
# in mind for later during final cleaning.

In [182]:
l1 = list(merged2018_2019[merged2018_2019['from_station_name'] == 'DIVVY CASSETTE REPAIR MOBILE STATION'].index)
l2 = list(merged2018_2019[merged2018_2019['to_station_name'] == 'DIVVY CASSETTE REPAIR MOBILE STATION'].index)

overlap = list(set(l1) & set(l2))
merged2018_2019 = merged2018_2019.drop(overlap)

In [183]:
merged2018_2019 = merged2018_2019.reset_index()

In [ ]:
merged2018_2019.to_csv('merged2018_2019.csv')