In [1]:
import pandas as pd

df1 = pd.read_csv('Divvy 2020 merged nostation.csv')

C:\Users\vitzj\AppData\Local\Temp\ipykernel_19600\380970896.py:3: DtypeWarning: Columns (6,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('Divvy 2020 merged nostation.csv')

# Data Cleaning for 2020-2022

# 2020 Seperate

In [2]:
df1.dtypes

Unnamed: 0             int64
ride_id               object
rideable_type         object
start_time            object
end_time              object
from_station_name     object
from_station_id       object
to_station_name       object
end_station_id        object
start_lat            float64
start_lng            float64
end_lat              float64
end_lng              float64
usertype              object
dtype: object

In [3]:
df1.isnull().sum()

Unnamed: 0                0
ride_id                   0
rideable_type             0
start_time                0
end_time                  0
from_station_name     94656
from_station_id       95282
to_station_name      110881
end_station_id       111342
start_lat                 0
start_lng                 0
end_lat                4255
end_lng                4255
usertype                  0
dtype: int64

In [4]:
# in order to fix our station name/id situation, we need to use start_lat and start_lng values, so I need to investigate where
# the nulls of end_lat and end_lng are so that I can either delete them (in cases if both are null) or retain them (to salvage)

null_lats = list(df1[df1['end_lat'].isnull()].index)
null_lngs = list(df1[df1['end_lng'].isnull()].index)

In [5]:
# Finding out if all of the index positions overlap
set(df1[df1['end_lat'].isnull()].index == df1[df1['end_lng'].isnull()].index)

{True}

In [6]:
# Because all of the index positions overlap, this means we can simply delete these rows by using only one condition
df1.drop(df1[df1['end_lat'].isnull()].index, inplace=True)

In [7]:
df1.isnull().sum()

Unnamed: 0                0
ride_id                   0
rideable_type             0
start_time                0
end_time                  0
from_station_name     94656
from_station_id       95282
to_station_name      106626
end_station_id       107087
start_lat                 0
start_lng                 0
end_lat                   0
end_lng                   0
usertype                  0
dtype: int64

In [8]:
display(df1)

,Unnamed: 0,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
0,0,EACB19130B0CDA4A,docked_bike,2020-01-21 20:06:59,2020-01-21 20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,41.967100,-87.667400,member
1,1,8FED874C809DC021,docked_bike,2020-01-30 14:22:39,2020-01-30 14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,41.954200,-87.664400,member
2,2,789F3C21E472CA96,docked_bike,2020-01-09 19:29:26,2020-01-09 19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,41.940200,-87.653000,member
3,3,C9A388DAC6ABF313,docked_bike,2020-01-06 16:17:07,2020-01-06 16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,41.891800,-87.620600,member
4,4,943BC3CBECCFD662,docked_bike,2020-01-30 08:37:16,2020-01-30 08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,41.889900,-87.634300,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3541678,3541678,4631EE956BCEA738,classic_bike,2020-12-19 13:59:33,2020-12-19 14:03:21,Rhodes Ave & 32nd St,13215,Indiana Ave & 31st St,TA1308000036,41.836208,-87.613533,41.838842,-87.621857,casual
3541679,3541679,D17CBEDEA8DBDFF6,electric_bike,2020-12-20 15:48:41,2020-12-20 15:52:14,Rhodes Ave & 32nd St,13215,Indiana Ave & 31st St,TA1308000036,41.836723,-87.613365,41.838723,-87.621854,member
3541680,3541680,447A6C67E9AF962E,docked_bike,2020-12-02 16:59:58,2020-12-02 17:08:28,Rhodes Ave & 32nd St,13215,Indiana Ave & 31st St,TA1308000036,41.836208,-87.613533,41.838842,-87.621857,member
3541681,3541681,F558C17E95751C62,electric_bike,2020-12-20 18:06:52,2020-12-20 18:09:53,Rhodes Ave & 32nd St,13215,Indiana Ave & 31st St,TA1308000036,41.836734,-87.613394,41.838749,-87.621862,member
3541682,3541682,E1888F4B274EEA12,electric_bike,2020-12-03 09:43:42,2020-12-03 09:47:14,Rhodes Ave & 32nd St,13215,Indiana Ave & 31st St,TA1308000036,41.836766,-87.613366,41.838681,-87.621854,member

In [9]:
df1 = df1.drop('Unnamed: 0',axis=1)
df1 = df1.drop_duplicates()
df1 = df1.drop_duplicates(subset=['ride_id']).reset_index()

In [10]:
# In previous iterations, I tried to salvage values. Doing this requires hardware I don't have access to and knowledge that I
# don't currently have access to. The biggest challenge is determining what to do with overlaps, and how likely it is that
# one station is a better pick than another over the course of a ride. I'm sure that if I had a month to take the time to figure
# this out, as well as access to geo-location searches and a hyper-fast computer beyond the realms of home PC enthusiast level,
# that I could design a system to fill in the blanks. However, for the sake of expediency, I will simply delete the values
# that are missing both station_name and station_id

In [11]:
df1

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
0,0,EACB19130B0CDA4A,docked_bike,2020-01-21 20:06:59,2020-01-21 20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,41.967100,-87.667400,member
1,1,8FED874C809DC021,docked_bike,2020-01-30 14:22:39,2020-01-30 14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,41.954200,-87.664400,member
2,2,789F3C21E472CA96,docked_bike,2020-01-09 19:29:26,2020-01-09 19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,41.940200,-87.653000,member
3,3,C9A388DAC6ABF313,docked_bike,2020-01-06 16:17:07,2020-01-06 16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,41.891800,-87.620600,member
4,4,943BC3CBECCFD662,docked_bike,2020-01-30 08:37:16,2020-01-30 08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,41.889900,-87.634300,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3537215,3541678,4631EE956BCEA738,classic_bike,2020-12-19 13:59:33,2020-12-19 14:03:21,Rhodes Ave & 32nd St,13215,Indiana Ave & 31st St,TA1308000036,41.836208,-87.613533,41.838842,-87.621857,casual
3537216,3541679,D17CBEDEA8DBDFF6,electric_bike,2020-12-20 15:48:41,2020-12-20 15:52:14,Rhodes Ave & 32nd St,13215,Indiana Ave & 31st St,TA1308000036,41.836723,-87.613365,41.838723,-87.621854,member
3537217,3541680,447A6C67E9AF962E,docked_bike,2020-12-02 16:59:58,2020-12-02 17:08:28,Rhodes Ave & 32nd St,13215,Indiana Ave & 31st St,TA1308000036,41.836208,-87.613533,41.838842,-87.621857,member
3537218,3541681,F558C17E95751C62,electric_bike,2020-12-20 18:06:52,2020-12-20 18:09:53,Rhodes Ave & 32nd St,13215,Indiana Ave & 31st St,TA1308000036,41.836734,-87.613394,41.838749,-87.621862,member
3537219,3541682,E1888F4B274EEA12,electric_bike,2020-12-03 09:43:42,2020-12-03 09:47:14,Rhodes Ave & 32nd St,13215,Indiana Ave & 31st St,TA1308000036,41.836766,-87.613366,41.838681,-87.621854,member

In [12]:
null_from_names = df1.iloc[df1[df1['from_station_name'].isnull()].index]
null_from_id = df1.iloc[df1[df1['from_station_id'].isnull()].index]

In [13]:
# This function drops rows with nulls from the subset if more than one column has a null. In this case, we only have two columns
# and this means that if both are null, the value is dropped, however if only one is null, the row is not dropped
df1 = df1.dropna(subset=['from_station_name', 'from_station_id'], thresh=1)

# Will do the same for to_station_name and end_station_id
df1 = df1.dropna(subset=['to_station_name', 'end_station_id'], thresh=1)

In [14]:
df1.isnull().sum()

index                  0
ride_id                0
rideable_type          0
start_time             0
end_time               0
from_station_name      0
from_station_id      524
to_station_name        0
end_station_id       404
start_lat              0
start_lng              0
end_lat                0
end_lng                0
usertype               0
dtype: int64

In [15]:
df1[df1['from_station_id'].isnull()]

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
1182613,1183690,248BC2E2842C3468,electric_bike,2020-07-30 16:39:55,2020-07-30 16:40:33,hubbard_test_lws,NaN,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671.0,41.89,-87.68,41.889975,-87.680321,casual
1607481,1609140,87604F9E0202C24C,electric_bike,2020-08-28 08:29:35,2020-08-28 09:18:49,W Oakdale Ave & N Broadway,NaN,W Oakdale Ave & N Broadway,NaN,41.94,-87.64,41.940000,-87.640000,casual
1607854,1609513,7E1268F06DB1E8ED,electric_bike,2020-08-22 14:25:05,2020-08-22 14:32:07,W Oakdale Ave & N Broadway,NaN,Clark St & Wrightwood Ave,340.0,41.94,-87.64,41.929563,-87.643578,casual
1609231,1610890,ED4D2E4B2B836445,electric_bike,2020-08-22 14:25:28,2020-08-22 14:32:10,W Oakdale Ave & N Broadway,NaN,Clark St & Wrightwood Ave,340.0,41.94,-87.64,41.929554,-87.643613,casual
1609244,1610903,54A93E5423F9B0E4,electric_bike,2020-08-22 14:17:21,2020-08-22 14:25:15,W Oakdale Ave & N Broadway,NaN,Racine Ave & Belmont Ave,226.0,41.94,-87.64,41.939654,-87.658884,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3364198,3368284,D6DE4B1BDBB42009,electric_bike,2020-11-08 13:27:09,2020-11-08 13:43:26,W Oakdale Ave & N Broadway,NaN,Damen Ave & Clybourn Ave,163.0,41.94,-87.64,41.931882,-87.677793,member
3364199,3368285,A781FD09251C80CD,electric_bike,2020-11-08 13:26:28,2020-11-08 13:26:44,W Oakdale Ave & N Broadway,NaN,W Oakdale Ave & N Broadway,NaN,41.94,-87.64,41.940000,-87.640000,member
3375393,3379500,DAE7E54F9A80C7CF,electric_bike,2020-11-13 10:43:28,2020-11-13 10:50:25,W Oakdale Ave & N Broadway,NaN,Southport Ave & Roscoe St,229.0,41.94,-87.64,41.943624,-87.664002,member
3383613,3387736,84E9039AD0B2F387,electric_bike,2020-11-06 17:11:02,2020-11-06 17:20:38,W Oakdale Ave & N Broadway,NaN,Clark St & North Ave,126.0,41.94,-87.64,41.912034,-87.631915,member
3404772,3408914,BB91520BFF2BD1F8,electric_bike,2020-11-08 11:59:03,2020-11-08 12:17:15,W Oakdale Ave & N Broadway,NaN,Franklin St & Chicago Ave,31.0,41.94,-87.64,41.897095,-87.635825,member

In [16]:
# fixing one station at a time from here out
df1.loc[df1['from_station_name'] == 'W Oakdale Ave & N Broadway', 'from_station_id'] = '20252.0'

In [17]:
df1[df1['from_station_id'].isnull()]

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
1182613,1183690,248BC2E2842C3468,electric_bike,2020-07-30 16:39:55,2020-07-30 16:40:33,hubbard_test_lws,NaN,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671.0,41.89,-87.68,41.889975,-87.680321,casual
1613025,1614684,4D9CCC0EDC37A8CD,electric_bike,2020-08-23 15:34:56,2020-08-23 16:14:42,W Armitage Ave & N Sheffield Ave,NaN,Calumet Ave & 18th St,338.0,41.92,-87.65,41.857656,-87.619272,casual
1615588,1617247,74F7C9FB57E3C1B2,electric_bike,2020-08-30 06:19:38,2020-08-30 06:21:01,W Armitage Ave & N Sheffield Ave,NaN,W Armitage Ave & N Sheffield Ave,NaN,41.92,-87.65,41.920000,-87.650000,casual
1617728,1619387,B12C0A27D55DC96F,electric_bike,2020-08-13 16:32:55,2020-08-13 16:33:08,W Armitage Ave & N Sheffield Ave,NaN,W Armitage Ave & N Sheffield Ave,NaN,41.92,-87.65,41.920000,-87.650000,casual
1619334,1620993,A69C76CF7E0B60F0,electric_bike,2020-08-30 13:09:44,2020-08-30 13:15:03,W Armitage Ave & N Sheffield Ave,NaN,Clifton Ave & Armitage Ave,223.0,41.92,-87.65,41.918184,-87.657018,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3160709,3164569,083B47675BFA7372,electric_bike,2020-11-07 18:51:09,2020-11-07 18:56:12,W Armitage Ave & N Sheffield Ave,NaN,Halsted St & Wrightwood Ave,349.0,41.92,-87.65,41.929150,-87.649206,casual
3160906,3164766,540A1AA801E745FA,electric_bike,2020-11-11 17:45:43,2020-11-11 18:10:55,W Armitage Ave & N Sheffield Ave,NaN,Daley Center Plaza,81.0,41.92,-87.65,41.884172,-87.629186,casual
3202062,3205934,049F2BBABEACA493,electric_bike,2020-11-06 07:42:48,2020-11-06 07:51:57,W Armitage Ave & N Sheffield Ave,NaN,Lake Shore Dr & Diversey Pkwy,329.0,41.92,-87.65,41.932834,-87.636649,member
3223086,3226988,A25B7D5B317983C5,electric_bike,2020-11-27 10:19:38,2020-11-27 10:26:39,W Armitage Ave & N Sheffield Ave,NaN,Southport Ave & Wrightwood Ave,190.0,41.92,-87.65,41.928880,-87.663797,member
3225078,3228982,49D53BDE01DB9FAA,electric_bike,2020-11-01 13:04:31,2020-11-01 13:08:29,W Armitage Ave & N Sheffield Ave,NaN,Sheffield Ave & Wrightwood Ave,302.0,41.92,-87.65,41.928387,-87.653833,member

In [18]:
df1[df1['from_station_name'] == 'W Armitage Ave & N Sheffield Ave']

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
1613025,1614684,4D9CCC0EDC37A8CD,electric_bike,2020-08-23 15:34:56,2020-08-23 16:14:42,W Armitage Ave & N Sheffield Ave,NaN,Calumet Ave & 18th St,338.0,41.92,-87.65,41.857656,-87.619272,casual
1615588,1617247,74F7C9FB57E3C1B2,electric_bike,2020-08-30 06:19:38,2020-08-30 06:21:01,W Armitage Ave & N Sheffield Ave,NaN,W Armitage Ave & N Sheffield Ave,NaN,41.92,-87.65,41.920000,-87.650000,casual
1617728,1619387,B12C0A27D55DC96F,electric_bike,2020-08-13 16:32:55,2020-08-13 16:33:08,W Armitage Ave & N Sheffield Ave,NaN,W Armitage Ave & N Sheffield Ave,NaN,41.92,-87.65,41.920000,-87.650000,casual
1619334,1620993,A69C76CF7E0B60F0,electric_bike,2020-08-30 13:09:44,2020-08-30 13:15:03,W Armitage Ave & N Sheffield Ave,NaN,Clifton Ave & Armitage Ave,223.0,41.92,-87.65,41.918184,-87.657018,casual
1620664,1622323,69320923D1AE603A,electric_bike,2020-08-26 22:00:47,2020-08-26 22:34:16,W Armitage Ave & N Sheffield Ave,NaN,Wells St & Polk St,175.0,41.92,-87.65,41.872297,-87.633103,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3461827,3466088,724CAABCBF093487,electric_bike,2020-12-05 16:58:06,2020-12-05 17:07:57,W Armitage Ave & N Sheffield Ave,20254.0,Damen Ave & Cortland St,13133,41.92,-87.65,41.915979,-87.677132,member
3471347,3475623,D98E43B296F48790,electric_bike,2020-12-05 17:34:50,2020-12-05 17:47:31,W Armitage Ave & N Sheffield Ave,20254.0,Wells St & Huron St,TA1306000012,41.92,-87.65,41.894995,-87.634321,member
3478367,3482656,F0F76E1C64D69679,electric_bike,2020-12-14 13:50:19,2020-12-14 13:53:45,W Armitage Ave & N Sheffield Ave,20254.0,Sheffield Ave & Fullerton Ave,TA1306000016,41.92,-87.65,41.925507,-87.653717,member
3504177,3508507,EAE1F6134BE03E6C,electric_bike,2020-12-08 09:18:34,2020-12-08 09:33:04,W Armitage Ave & N Sheffield Ave,20254.0,LaSalle Dr & Huron St,KP1705001026,41.92,-87.65,41.895034,-87.632505,casual
3522394,3526823,743A6AB46FA3C47A,electric_bike,2020-12-09 16:17:35,2020-12-09 16:25:09,W Armitage Ave & N Sheffield Ave,20254.0,Clark St & Wrightwood Ave,TA1305000014,41.92,-87.65,41.929585,-87.643345,casual

In [19]:
df1.loc[df1['from_station_name'] == 'W Armitage Ave & N Sheffield Ave', 'from_station_id'] = '20254.0'

In [20]:
df1[df1['from_station_id'].isnull()]

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
1182613,1183690,248BC2E2842C3468,electric_bike,2020-07-30 16:39:55,2020-07-30 16:40:33,hubbard_test_lws,NaN,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671.0,41.89,-87.68,41.889975,-87.680321,casual

In [21]:
df1[df1['from_station_name'] == 'hubbard_test_lws']

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
1182613,1183690,248BC2E2842C3468,electric_bike,2020-07-30 16:39:55,2020-07-30 16:40:33,hubbard_test_lws,NaN,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671.0,41.89,-87.68,41.889975,-87.680321,casual

In [22]:
# Now that we have observed that there are values that include "test", we can assume that we should remove these values from the
# dataframe. I will go through all of them at the end to determine this. For now, I will delete this row.

In [23]:
df1 = df1.drop(1182613)

In [24]:
df1.isnull().sum()

index                  0
ride_id                0
rideable_type          0
start_time             0
end_time               0
from_station_name      0
from_station_id        0
to_station_name        0
end_station_id       404
start_lat              0
start_lng              0
end_lat                0
end_lng                0
usertype               0
dtype: int64

In [25]:
# now to investigate end_station_id

In [26]:
df1[df1['end_station_id'].isnull()]

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
1605826,1607485,427ED3D8BD480E4B,electric_bike,2020-08-29 23:02:04,2020-08-29 23:25:43,Broadway & Granville Ave,454.0,W Oakdale Ave & N Broadway,NaN,41.994839,-87.660244,41.94,-87.64,casual
1605873,1607532,F3A221B47D3A479A,electric_bike,2020-08-29 22:31:43,2020-08-29 22:41:58,Pine Grove Ave & Waveland Ave,232.0,W Oakdale Ave & N Broadway,NaN,41.949315,-87.646370,41.94,-87.64,casual
1606829,1608488,082313F9D5DC4A13,electric_bike,2020-08-31 15:50:27,2020-08-31 16:04:18,Clark St & Armitage Ave,94.0,W Oakdale Ave & N Broadway,NaN,41.918296,-87.636336,41.94,-87.64,casual
1606874,1608533,FDE9F1A39375EE33,electric_bike,2020-08-27 09:27:10,2020-08-27 09:48:31,Wells St & Hubbard St,212.0,W Oakdale Ave & N Broadway,NaN,41.889840,-87.634320,41.94,-87.64,casual
1607078,1608737,C6D3109E1569A3B8,electric_bike,2020-08-16 16:15:09,2020-08-16 16:22:48,Clark St & Armitage Ave,94.0,W Oakdale Ave & N Broadway,NaN,41.918386,-87.636411,41.94,-87.64,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3364199,3368285,A781FD09251C80CD,electric_bike,2020-11-08 13:26:28,2020-11-08 13:26:44,W Oakdale Ave & N Broadway,20252.0,W Oakdale Ave & N Broadway,NaN,41.940000,-87.640000,41.94,-87.64,member
3371194,3375289,008955EFCA1CF51B,electric_bike,2020-11-17 15:00:11,2020-11-17 15:06:11,Lakeview Ave & Fullerton Pkwy,313.0,W Oakdale Ave & N Broadway,NaN,41.925879,-87.639162,41.94,-87.64,member
3375401,3379508,9EEAB641C0FC8A7C,electric_bike,2020-11-28 15:27:53,2020-11-28 15:33:57,Racine Ave & Belmont Ave,226.0,W Oakdale Ave & N Broadway,NaN,41.939675,-87.658842,41.94,-87.64,member
3379022,3383137,273D3DFFDA195C7C,electric_bike,2020-11-04 12:38:16,2020-11-04 12:42:09,Lake Shore Dr & Belmont Ave,334.0,W Oakdale Ave & N Broadway,NaN,41.940687,-87.639184,41.94,-87.64,member
3381822,3385942,42F093E4358E79F0,electric_bike,2020-11-01 16:38:00,2020-11-01 17:01:32,Wood St & Milwaukee Ave,61.0,W Oakdale Ave & N Broadway,NaN,41.907575,-87.672474,41.94,-87.64,member

In [27]:
df1.loc[df1['to_station_name'] == 'W Oakdale Ave & N Broadway', 'end_station_id'] = '20252.0'

In [28]:
df1[df1['end_station_id'].isnull()]

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
1608987,1610646,FEE5F6365A9B42AE,electric_bike,2020-08-15 09:48:44,2020-08-15 10:03:32,Clark St & Elm St,176.0,W Armitage Ave & N Sheffield Ave,NaN,41.902854,-87.631760,41.92,-87.65,casual
1610104,1611763,9BA05D744F2430B6,electric_bike,2020-08-17 11:57:07,2020-08-17 12:22:25,Green St & Madison St,198.0,W Armitage Ave & N Sheffield Ave,NaN,41.882013,-87.648975,41.92,-87.65,casual
1615588,1617247,74F7C9FB57E3C1B2,electric_bike,2020-08-30 06:19:38,2020-08-30 06:21:01,W Armitage Ave & N Sheffield Ave,20254.0,W Armitage Ave & N Sheffield Ave,NaN,41.920000,-87.650000,41.92,-87.65,casual
1617518,1619177,BF0DFA178923F1EB,electric_bike,2020-08-26 18:44:47,2020-08-26 19:35:36,Kimbark Ave & 53rd St,322.0,W Armitage Ave & N Sheffield Ave,NaN,41.799625,-87.594797,41.92,-87.65,casual
1617728,1619387,B12C0A27D55DC96F,electric_bike,2020-08-13 16:32:55,2020-08-13 16:33:08,W Armitage Ave & N Sheffield Ave,20254.0,W Armitage Ave & N Sheffield Ave,NaN,41.920000,-87.650000,41.92,-87.65,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2940057,2943596,F5344999C2763FE4,electric_bike,2020-10-18 09:50:31,2020-10-18 09:50:42,W Armitage Ave & N Sheffield Ave,20254.0,W Armitage Ave & N Sheffield Ave,NaN,41.920000,-87.650000,41.92,-87.65,member
2940364,2943904,367FD84357CEC604,electric_bike,2020-10-08 19:32:27,2020-10-08 19:41:10,Sheffield Ave & Wellington Ave,115.0,W Armitage Ave & N Sheffield Ave,NaN,41.936356,-87.652900,41.92,-87.65,member
2951290,2954840,A7BB79F54B4F619A,electric_bike,2020-10-02 16:37:37,2020-10-02 16:50:54,Kingsbury St & Erie St,74.0,W Armitage Ave & N Sheffield Ave,NaN,41.894019,-87.641917,41.92,-87.65,member
3035179,3038862,49F6DEE3FD2BC50B,electric_bike,2020-10-13 17:03:07,2020-10-13 17:19:12,Clark St & Newport St,632.0,W Armitage Ave & N Sheffield Ave,NaN,41.944564,-87.654732,41.92,-87.65,member
3142967,3146824,FC43F3E7D8B1FF74,electric_bike,2020-10-03 19:33:39,2020-10-03 19:38:03,Sheffield Ave & Fullerton Ave,67.0,W Armitage Ave & N Sheffield Ave,NaN,41.925535,-87.653694,41.92,-87.65,member

In [29]:
df1.loc[df1['to_station_name'] == 'W Armitage Ave & N Sheffield Ave', 'end_station_id'] = '20254.0'

In [30]:
df1[df1['end_station_id'].isnull()]

Empty DataFrame
Columns: [index, ride_id, rideable_type, start_time, end_time, from_station_name, from_station_id, to_station_name, end_station_id, start_lat, start_lng, end_lat, end_lng, usertype]
Index: []

# 2021 Seperate

In [31]:
# Now to rinse and repeat with the other datasets.

In [32]:
df2 = pd.read_csv('Divvy 2021 merged nostation.csv')

In [33]:
df2

,Unnamed: 0,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
0,0,E19E6F1B8D4C42ED,electric_bike,2021-01-23 16:14:19,2021-01-23 16:24:44,California Ave & Cortez St,17660,NaN,NaN,41.900341,-87.696743,41.890000,-87.720000,member
1,1,DC88F20C2C55F27F,electric_bike,2021-01-27 18:43:08,2021-01-27 18:47:12,California Ave & Cortez St,17660,NaN,NaN,41.900333,-87.696707,41.900000,-87.690000,member
2,2,EC45C94683FE3F27,electric_bike,2021-01-21 22:35:54,2021-01-21 22:37:14,California Ave & Cortez St,17660,NaN,NaN,41.900313,-87.696643,41.900000,-87.700000,member
3,3,4FA453A75AE377DB,electric_bike,2021-01-07 13:31:13,2021-01-07 13:42:55,California Ave & Cortez St,17660,NaN,NaN,41.900399,-87.696662,41.920000,-87.690000,member
4,4,BE5E8EB4E7263A0B,electric_bike,2021-01-23 02:24:02,2021-01-23 02:24:45,California Ave & Cortez St,17660,NaN,NaN,41.900326,-87.696697,41.900000,-87.700000,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5595058,5595058,847431F3D5353AB7,electric_bike,2021-12-12 13:36:55,2021-12-12 13:56:08,Canal St & Madison St,13341,NaN,NaN,41.882289,-87.639752,41.890000,-87.610000,casual
5595059,5595059,CF407BBC3B9FAD63,electric_bike,2021-12-06 19:37:50,2021-12-06 19:44:51,Canal St & Madison St,13341,Kingsbury St & Kinzie St,KA1503000043,41.882123,-87.640053,41.889106,-87.638862,member
5595060,5595060,60BB69EBF5440E92,electric_bike,2021-12-02 08:57:04,2021-12-02 09:05:21,Canal St & Madison St,13341,Dearborn St & Monroe St,TA1305000006,41.881956,-87.639955,41.880254,-87.629603,member
5595061,5595061,C414F654A28635B8,electric_bike,2021-12-13 09:00:26,2021-12-13 09:14:39,Lawndale Ave & 16th St,362.0,NaN,NaN,41.860000,-87.720000,41.850000,-87.710000,member
5595062,5595062,37AC57E34B2E7E97,classic_bike,2021-12-13 08:45:32,2021-12-13 08:49:09,Michigan Ave & Jackson Blvd,TA1309000002,Dearborn St & Monroe St,TA1305000006,41.877850,-87.624080,41.881320,-87.629521,member

In [34]:
df2.isnull().sum()

Unnamed: 0                0
ride_id                   0
rideable_type             0
start_time                0
end_time                  0
from_station_name    690809
from_station_id      690806
to_station_name      739170
end_station_id       739170
start_lat                 0
start_lng                 0
end_lat                4771
end_lng                4771
usertype                  0
dtype: int64

In [35]:
null_lats2 = list(df2[df2['end_lat'].isnull()].index)
null_lngs2 = list(df2[df2['end_lng'].isnull()].index)
set(df2[df2['end_lat'].isnull()].index == df2[df2['end_lng'].isnull()].index)

{True}

In [36]:
df2.drop(df2[df2['end_lat'].isnull()].index, inplace=True)

In [37]:
df2.isnull().sum()

Unnamed: 0                0
ride_id                   0
rideable_type             0
start_time                0
end_time                  0
from_station_name    690809
from_station_id      690806
to_station_name      734399
end_station_id       734399
start_lat                 0
start_lng                 0
end_lat                   0
end_lng                   0
usertype                  0
dtype: int64

In [38]:
# Again, if I had the time and it would benefit a company that was employing me, I would try to see how many of these I could
# fix before deletion. However, I don't have access to a supercomputer and don't have a database of the station information that
# is comprehensive enough to be able to do so.

# Dropping columns with dual nulls
df2 = df2.dropna(subset=['from_station_name', 'from_station_id'], thresh=1)

# Will do the same for to_station_name and end_station_id
df2 = df2.dropna(subset=['to_station_name', 'end_station_id'], thresh=1)

In [39]:
df2.isnull().sum()

Unnamed: 0           0
ride_id              0
rideable_type        0
start_time           0
end_time             0
from_station_name    1
from_station_id      0
to_station_name      0
end_station_id       0
start_lat            0
start_lng            0
end_lat              0
end_lng              0
usertype             0
dtype: int64

In [40]:
df2[df2['from_station_name'].isnull()]

,Unnamed: 0,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
3668173,3668173,DE82A15026BA3056,electric_bike,2021-09-21 18:18:59,2021-09-21 18:21:48,NaN,20215,Hegewisch Metra Station,20215,41.6485,-87.546089,41.648589,-87.54625,casual

In [41]:
df2[df2['from_station_id'] == '20215']

,Unnamed: 0,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
16893,16893,F355A001C7552ADD,classic_bike,2021-01-21 14:18:53,2021-01-21 14:45:50,Hegewisch Metra Station,20215,Burnham Greenway & 105th St,20222,41.648501,-87.546090,41.704575,-87.528232,member
334646,334646,23FE33AEC9C13C9C,classic_bike,2021-03-05 10:53:14,2021-03-05 11:16:26,Hegewisch Metra Station,20215,Burnham Greenway & 105th St,20222,41.648501,-87.546090,41.704575,-87.528232,member
334667,334667,0744ADDD14D52471,classic_bike,2021-03-10 11:01:20,2021-03-10 11:23:47,Hegewisch Metra Station,20215,Burnham Greenway & 105th St,20222,41.648501,-87.546090,41.704575,-87.528232,member
364275,364275,4640F42D34E739E9,classic_bike,2021-03-13 16:12:25,2021-03-13 16:46:01,Hegewisch Metra Station,20215,Ewing Ave & Burnham Greenway,20223,41.648501,-87.546090,41.712749,-87.534814,member
368683,368683,218643C9083A6E9D,classic_bike,2021-03-28 12:40:45,2021-03-28 12:49:16,Hegewisch Metra Station,20215,Hegewisch Metra Station,20215,41.648501,-87.546090,41.648501,-87.546090,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4567438,4567438,28B71034C924011A,classic_bike,2021-10-11 13:45:16,2021-10-11 14:32:31,Hegewisch Metra Station,20215,Cottage Grove Ave & 111th Pl,20131,41.648501,-87.546090,41.691710,-87.610002,casual
4994644,4994644,4F6FB68D0D4CD300,electric_bike,2021-11-03 01:28:18,2021-11-03 01:33:32,Hegewisch Metra Station,20215,Commercial Ave & 130th St,20213,41.648591,-87.546205,41.659156,-87.550754,casual
4994661,4994661,8D392BC915B708F2,classic_bike,2021-11-04 15:07:43,2021-11-04 15:16:59,Hegewisch Metra Station,20215,Commercial Ave & 130th St,20213,41.648501,-87.546090,41.659150,-87.550762,casual
4994697,4994697,AD090077C2C9D53B,electric_bike,2021-11-09 21:52:42,2021-11-09 21:58:15,Hegewisch Metra Station,20215,Commercial Ave & 130th St,20213,41.648562,-87.546206,41.659135,-87.550712,casual
5349753,5349753,1E1BD7E3EA47A2B0,electric_bike,2021-12-01 13:16:39,2021-12-01 13:24:48,Hegewisch Metra Station,20215,Commercial Ave & 130th St,20213,41.648538,-87.546191,41.659109,-87.550655,casual

In [42]:
df2.loc[df2['from_station_id'] == '20215', 'from_station_name'] = 'Hegewisch Metra Station'

In [43]:
df2.isnull().sum()

Unnamed: 0           0
ride_id              0
rideable_type        0
start_time           0
end_time             0
from_station_name    0
from_station_id      0
to_station_name      0
end_station_id       0
start_lat            0
start_lng            0
end_lat              0
end_lng              0
usertype             0
dtype: int64

In [44]:
df2.shape

(4588303, 14)

In [45]:
df2.drop_duplicates()
df2.drop_duplicates(subset=['ride_id'])
df2.shape

(4588303, 14)

In [46]:
df2 = df2.drop('Unnamed: 0',axis=1)

In [47]:
df2

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
9,B9F73448DFBE0D45,classic_bike,2021-01-24 19:15:38,2021-01-24 19:22:51,California Ave & Cortez St,17660,Wood St & Augusta Blvd,657,41.900363,-87.696704,41.899181,-87.672200,member
10,457C7F4B5D3DA135,electric_bike,2021-01-23 12:57:38,2021-01-23 13:02:10,California Ave & Cortez St,17660,California Ave & North Ave,13258,41.900406,-87.696733,41.910435,-87.696890,member
11,57C750326F9FDABE,electric_bike,2021-01-09 15:28:04,2021-01-09 15:37:51,California Ave & Cortez St,17660,Wood St & Augusta Blvd,657,41.900374,-87.696688,41.899180,-87.672178,casual
12,4D518C65E338D070,electric_bike,2021-01-09 15:28:57,2021-01-09 15:37:54,California Ave & Cortez St,17660,Wood St & Augusta Blvd,657,41.900379,-87.696716,41.899149,-87.672177,casual
13,9D08A3AFF410474D,classic_bike,2021-01-24 15:56:59,2021-01-24 16:07:08,California Ave & Cortez St,17660,Wood St & Augusta Blvd,657,41.900363,-87.696704,41.899181,-87.672200,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5595051,E06135F650553F21,electric_bike,2021-12-07 15:55:37,2021-12-07 16:00:17,Canal St & Madison St,13341,Desplaines St & Kinzie St,TA1306000003,41.881372,-87.640042,41.888456,-87.644336,casual
5595055,8DF0DBB049906332,electric_bike,2021-12-01 16:50:52,2021-12-01 16:55:18,Canal St & Madison St,13341,Desplaines St & Kinzie St,TA1306000003,41.881999,-87.639265,41.888415,-87.644342,casual
5595059,CF407BBC3B9FAD63,electric_bike,2021-12-06 19:37:50,2021-12-06 19:44:51,Canal St & Madison St,13341,Kingsbury St & Kinzie St,KA1503000043,41.882123,-87.640053,41.889106,-87.638862,member
5595060,60BB69EBF5440E92,electric_bike,2021-12-02 08:57:04,2021-12-02 09:05:21,Canal St & Madison St,13341,Dearborn St & Monroe St,TA1305000006,41.881956,-87.639955,41.880254,-87.629603,member
5595062,37AC57E34B2E7E97,classic_bike,2021-12-13 08:45:32,2021-12-13 08:49:09,Michigan Ave & Jackson Blvd,TA1309000002,Dearborn St & Monroe St,TA1305000006,41.877850,-87.624080,41.881320,-87.629521,member

# 2022 Seperate

In [48]:
# Now to rinse and repeat 2022 dataset.

df3 = pd.read_csv('Divvy 2022 merged nostation.csv')
df3

,Unnamed: 0,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
0,0,C2F7DD78E82EC875,electric_bike,2022-01-13 11:59:47,2022-01-13 12:02:44,Glenwood Ave & Touhy Ave,525,Clark St & Touhy Ave,RP-007,42.012800,-87.665906,42.012560,-87.674367,casual
1,1,A6CF8980A652D272,electric_bike,2022-01-10 08:41:56,2022-01-10 08:46:17,Glenwood Ave & Touhy Ave,525,Clark St & Touhy Ave,RP-007,42.012763,-87.665967,42.012560,-87.674367,casual
2,2,BD0F91DFF741C66D,classic_bike,2022-01-25 04:53:40,2022-01-25 04:58:01,Sheffield Ave & Fullerton Ave,TA1306000016,Greenview Ave & Fullerton Ave,TA1307000001,41.925602,-87.653708,41.925330,-87.665800,member
3,3,CBB80ED419105406,classic_bike,2022-01-04 00:18:04,2022-01-04 00:33:00,Clark St & Bryn Mawr Ave,KA1504000151,Paulina St & Montrose Ave,TA1309000021,41.983593,-87.669154,41.961507,-87.671387,casual
4,4,DDC963BFDDA51EEA,classic_bike,2022-01-20 01:31:10,2022-01-20 01:37:12,Michigan Ave & Jackson Blvd,TA1309000002,State St & Randolph St,TA1305000029,41.877850,-87.624080,41.884621,-87.627834,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5148171,5148171,BC3BFA659C9AB6F1,classic_bike,2022-10-30 01:41:29,2022-10-30 01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,41.943350,-87.670668,casual
5148172,5148172,ACD65450291CF95F,classic_bike,2022-10-30 01:41:54,2022-10-30 01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,41.943350,-87.670668,casual
5148173,5148173,4AAC03D1438E97CA,classic_bike,2022-10-15 09:34:11,2022-10-15 10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,-87.638677,41.891466,-87.626761,casual
5148174,5148174,8E6F3F29785E5D40,classic_bike,2022-10-09 10:21:34,2022-10-09 10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,-87.638677,41.931931,-87.677856,member
5148175,5148175,8D14CBE672431920,docked_bike,2022-10-22 13:17:13,2022-10-22 13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,-87.636282,41.891466,-87.626761,casual

In [49]:
df3.isnull().sum()

Unnamed: 0                0
ride_id                   0
rideable_type             0
start_time                0
end_time                  0
from_station_name    751824
from_station_id      751824
to_station_name      807325
end_station_id       807325
start_lat                 0
start_lng                 0
end_lat                5500
end_lng                5500
usertype                  0
dtype: int64

In [50]:
set(df3[df3['end_lat'].isnull()].index == df3[df3['end_lng'].isnull()].index)

{True}

In [51]:
df3.drop(df3[df3['end_lat'].isnull()].index, inplace=True)

In [52]:
df3 = df3.drop('Unnamed: 0', axis=1)

In [53]:
df3.isnull().sum()

ride_id                   0
rideable_type             0
start_time                0
end_time                  0
from_station_name    751824
from_station_id      751824
to_station_name      801825
end_station_id       801825
start_lat                 0
start_lng                 0
end_lat                   0
end_lng                   0
usertype                  0
dtype: int64

In [54]:
df3 = df3.dropna(subset=['from_station_name', 'from_station_id'], thresh=1)

# Will do the same for to_station_name and end_station_id
df3 = df3.dropna(subset=['to_station_name', 'end_station_id'], thresh=1)

In [55]:
df3.isnull().sum()

ride_id              0
rideable_type        0
start_time           0
end_time             0
from_station_name    0
from_station_id      0
to_station_name      0
end_station_id       0
start_lat            0
start_lng            0
end_lat              0
end_lng              0
usertype             0
dtype: int64

In [56]:
df3.shape

(3978163, 13)

In [57]:
df3.drop_duplicates()
df3.drop_duplicates(subset=['ride_id'])
df3.shape

(3978163, 13)

# Combining Dataframes

In [58]:
merged2020_2022 = pd.concat([df1, df2, df3], ignore_index=True)

In [59]:
merged2020_2022 = merged2020_2022.drop('index', axis=1)

In [60]:
merged2020_2022.drop_duplicates()
merged2020_2022.drop_duplicates(subset=['ride_id'])
merged2020_2022

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
0,EACB19130B0CDA4A,docked_bike,2020-01-21 20:06:59,2020-01-21 20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,41.967100,-87.667400,member
1,8FED874C809DC021,docked_bike,2020-01-30 14:22:39,2020-01-30 14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,41.954200,-87.664400,member
2,789F3C21E472CA96,docked_bike,2020-01-09 19:29:26,2020-01-09 19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,41.940200,-87.653000,member
3,C9A388DAC6ABF313,docked_bike,2020-01-06 16:17:07,2020-01-06 16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,41.891800,-87.620600,member
4,943BC3CBECCFD662,docked_bike,2020-01-30 08:37:16,2020-01-30 08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,41.889900,-87.634300,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11956505,BC3BFA659C9AB6F1,classic_bike,2022-10-30 01:41:29,2022-10-30 01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,41.943350,-87.670668,casual
11956506,ACD65450291CF95F,classic_bike,2022-10-30 01:41:54,2022-10-30 01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,41.943350,-87.670668,casual
11956507,4AAC03D1438E97CA,classic_bike,2022-10-15 09:34:11,2022-10-15 10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,-87.638677,41.891466,-87.626761,casual
11956508,8E6F3F29785E5D40,classic_bike,2022-10-09 10:21:34,2022-10-09 10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,-87.638677,41.931931,-87.677856,member
11956509,8D14CBE672431920,docked_bike,2022-10-22 13:17:13,2022-10-22 13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,-87.636282,41.891466,-87.626761,casual

In [61]:
merged2020_2022[merged2020_2022['from_station_name'] == 'DIVVY CASSETTE REPAIR MOBILE STATION']

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
5131038,04B18873381AACA9,classic_bike,2021-07-07 11:01:33,2021-07-07 11:14:59,DIVVY CASSETTE REPAIR MOBILE STATION,DIVVY CASSETTE REPAIR MOBILE STATION,Field Museum,13029,41.880958,-87.616743,41.865312,-87.617867,casual
5217433,A4354906AD557A6C,electric_bike,2021-07-07 11:06:50,2021-07-07 13:06:50,DIVVY CASSETTE REPAIR MOBILE STATION,DIVVY CASSETTE REPAIR MOBILE STATION,Lake Shore Dr & Monroe St,13300,41.881039,-87.616730,41.881225,-87.616750,casual
5510826,74B6C966F82A9FD5,electric_bike,2021-07-07 11:06:19,2021-07-07 13:06:49,DIVVY CASSETTE REPAIR MOBILE STATION,DIVVY CASSETTE REPAIR MOBILE STATION,Lake Shore Dr & Monroe St,13300,41.881051,-87.616766,41.881165,-87.616763,casual
5510955,C0D3A64896642496,classic_bike,2021-07-07 11:03:00,2021-07-07 13:06:22,DIVVY CASSETTE REPAIR MOBILE STATION,DIVVY CASSETTE REPAIR MOBILE STATION,Lake Shore Dr & Monroe St,13300,41.880958,-87.616743,41.880958,-87.616743,casual

In [62]:
# Remember, we don't want test values to obscure our actualy data. This means that all values with 'test' in the station names
# need to be found and deleted.

merged2020_2022[merged2020_2022['from_station_name'].str.lower().str.contains("test", regex=False, na=False) == True]

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
77901,7A46E4BD3F074400,docked_bike,2020-01-30 16:59:14,2020-01-30 17:26:42,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671.0,Lincoln Ave & Belle Plaine Ave,298.0,41.890000,-87.680700,41.956000,-87.680300,member
148557,B869D5896CB1BE5F,docked_bike,2020-02-21 17:09:01,2020-02-21 17:35:25,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671.0,Oakley Ave & Irving Park Rd,486.0,41.890000,-87.680700,41.954300,-87.686100,member
371556,A4E016418635549A,docked_bike,2020-03-31 17:15:48,2020-03-31 17:45:19,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671.0,Oakley Ave & Irving Park Rd,486.0,41.890000,-87.680700,41.954300,-87.686100,member
372682,73D0B881C63D1736,docked_bike,2020-03-26 17:30:02,2020-03-26 17:53:42,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671.0,Lincoln Ave & Waveland Ave,257.0,41.890000,-87.680700,41.948800,-87.675300,member
436240,01FD073BD38D7552,docked_bike,2020-04-24 17:35:34,2020-04-24 17:35:39,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671.0,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671.0,41.890000,-87.680700,41.890000,-87.680700,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3121165,35708F6806F43F9C,electric_bike,2020-11-09 11:39:26,2020-11-09 11:43:32,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671.0,Wood St & Chicago Ave,637.0,41.889949,-87.680233,41.895539,-87.672092,member
3264119,7B23D12183D82FE1,electric_bike,2020-11-15 14:08:06,2020-11-15 14:11:04,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671.0,Artesian Ave & Hubbard St,376.0,41.889961,-87.680281,41.889528,-87.688076,member
3264122,AB50D5777D630144,electric_bike,2020-11-08 14:02:30,2020-11-08 14:05:46,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),671.0,Artesian Ave & Hubbard St,376.0,41.889984,-87.680237,41.889509,-87.688109,member
3295010,FED70F7BEAEF5E70,electric_bike,2020-12-04 12:20:23,2020-12-04 12:22:33,HUBBARD ST BIKE CHECKING (LBS-WH-TEST),Hubbard Bike-checking (LBS-WH-TEST),HUBBARD ST BIKE CHECKING (LBS-WH-TEST),Hubbard Bike-checking (LBS-WH-TEST),41.889935,-87.680188,41.889949,-87.680265,member
7989869,3327172413547F64,electric_bike,2022-01-14 11:13:15,2022-01-14 11:15:50,Pawel Bialowas - Test- PBSC charging station,Pawel Bialowas - Test- PBSC charging station,Pawel Bialowas - Test- PBSC charging station,Pawel Bialowas - Test- PBSC charging station,45.635034,-73.796477,41.864600,-87.681000,casual

In [63]:
merged2020_2022.shape

(11956510, 13)

In [64]:
merged2020_2022.drop(merged2020_2022[merged2020_2022['from_station_name'].str.lower().str.contains("test", regex=False, na=False) == True].index)

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
0,EACB19130B0CDA4A,docked_bike,2020-01-21 20:06:59,2020-01-21 20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,41.967100,-87.667400,member
1,8FED874C809DC021,docked_bike,2020-01-30 14:22:39,2020-01-30 14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,41.954200,-87.664400,member
2,789F3C21E472CA96,docked_bike,2020-01-09 19:29:26,2020-01-09 19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,41.940200,-87.653000,member
3,C9A388DAC6ABF313,docked_bike,2020-01-06 16:17:07,2020-01-06 16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,41.891800,-87.620600,member
4,943BC3CBECCFD662,docked_bike,2020-01-30 08:37:16,2020-01-30 08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,41.889900,-87.634300,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11956505,BC3BFA659C9AB6F1,classic_bike,2022-10-30 01:41:29,2022-10-30 01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,41.943350,-87.670668,casual
11956506,ACD65450291CF95F,classic_bike,2022-10-30 01:41:54,2022-10-30 01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,41.943350,-87.670668,casual
11956507,4AAC03D1438E97CA,classic_bike,2022-10-15 09:34:11,2022-10-15 10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,-87.638677,41.891466,-87.626761,casual
11956508,8E6F3F29785E5D40,classic_bike,2022-10-09 10:21:34,2022-10-09 10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,-87.638677,41.931931,-87.677856,member
11956509,8D14CBE672431920,docked_bike,2022-10-22 13:17:13,2022-10-22 13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,-87.636282,41.891466,-87.626761,casual

In [65]:
# so we can delete all rows with occurances of the phrase
merged2020_2022 = merged2020_2022.drop(merged2020_2022[merged2020_2022['from_station_name'].str.lower().str.contains("test", regex=False, na=False) == True].index)
# now repeat for to_station_names
merged2020_2022 = merged2020_2022.drop(merged2020_2022[merged2020_2022['to_station_name'].str.lower().str.contains("test", regex=False, na=False) == True].index)

In [66]:
merged2020_2022.isnull().sum()

ride_id              0
rideable_type        0
start_time           0
end_time             0
from_station_name    0
from_station_id      0
to_station_name      0
end_station_id       0
start_lat            0
start_lng            0
end_lat              0
end_lng              0
usertype             0
dtype: int64

In [67]:
# I will need to remain concious of this going forward, when I do the final data cleaning on all of the data at once. I will
# make sure to do a comprehensive over-view of all of the names that are assigned to station id's in the final dataset, to
# correct inconsistencies as well as delete any more of these types of entries that involve company testing/facilities

In [68]:
merged2020_2022 = merged2020_2022.reset_index()

In [69]:
merged2020_2022

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype
0,0,EACB19130B0CDA4A,docked_bike,2020-01-21 20:06:59,2020-01-21 20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,41.967100,-87.667400,member
1,1,8FED874C809DC021,docked_bike,2020-01-30 14:22:39,2020-01-30 14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,41.954200,-87.664400,member
2,2,789F3C21E472CA96,docked_bike,2020-01-09 19:29:26,2020-01-09 19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,41.940200,-87.653000,member
3,3,C9A388DAC6ABF313,docked_bike,2020-01-06 16:17:07,2020-01-06 16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,41.891800,-87.620600,member
4,4,943BC3CBECCFD662,docked_bike,2020-01-30 08:37:16,2020-01-30 08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,41.889900,-87.634300,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11952925,11956505,BC3BFA659C9AB6F1,classic_bike,2022-10-30 01:41:29,2022-10-30 01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,41.943350,-87.670668,casual
11952926,11956506,ACD65450291CF95F,classic_bike,2022-10-30 01:41:54,2022-10-30 01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,41.943350,-87.670668,casual
11952927,11956507,4AAC03D1438E97CA,classic_bike,2022-10-15 09:34:11,2022-10-15 10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,-87.638677,41.891466,-87.626761,casual
11952928,11956508,8E6F3F29785E5D40,classic_bike,2022-10-09 10:21:34,2022-10-09 10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,-87.638677,41.931931,-87.677856,member
11952929,11956509,8D14CBE672431920,docked_bike,2022-10-22 13:17:13,2022-10-22 13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,-87.636282,41.891466,-87.626761,casual

In [70]:
# Now to split time columns

merged2020_2022[['start_date', 'start_time']] = merged2020_2022.start_time.str.split(" ", expand=True)
merged2020_2022[['end_date', 'end_time']] = merged2020_2022.end_time.str.split(" ", expand=True)
merged2020_2022

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype,start_date,end_date
0,0,EACB19130B0CDA4A,docked_bike,20:06:59,20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,41.967100,-87.667400,member,2020-01-21,2020-01-21
1,1,8FED874C809DC021,docked_bike,14:22:39,14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,41.954200,-87.664400,member,2020-01-30,2020-01-30
2,2,789F3C21E472CA96,docked_bike,19:29:26,19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,41.940200,-87.653000,member,2020-01-09,2020-01-09
3,3,C9A388DAC6ABF313,docked_bike,16:17:07,16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,41.891800,-87.620600,member,2020-01-06,2020-01-06
4,4,943BC3CBECCFD662,docked_bike,08:37:16,08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,41.889900,-87.634300,member,2020-01-30,2020-01-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11952925,11956505,BC3BFA659C9AB6F1,classic_bike,01:41:29,01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,41.943350,-87.670668,casual,2022-10-30,2022-10-30
11952926,11956506,ACD65450291CF95F,classic_bike,01:41:54,01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,41.943350,-87.670668,casual,2022-10-30,2022-10-30
11952927,11956507,4AAC03D1438E97CA,classic_bike,09:34:11,10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,-87.638677,41.891466,-87.626761,casual,2022-10-15,2022-10-15
11952928,11956508,8E6F3F29785E5D40,classic_bike,10:21:34,10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,-87.638677,41.931931,-87.677856,member,2022-10-09,2022-10-09
11952929,11956509,8D14CBE672431920,docked_bike,13:17:13,13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,-87.636282,41.891466,-87.626761,casual,2022-10-22,2022-10-22

In [71]:
merged2020_2022 = merged2020_2022.drop('index', axis=1)

In [72]:
merged2020_2022

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype,start_date,end_date
0,EACB19130B0CDA4A,docked_bike,20:06:59,20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,41.967100,-87.667400,member,2020-01-21,2020-01-21
1,8FED874C809DC021,docked_bike,14:22:39,14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,41.954200,-87.664400,member,2020-01-30,2020-01-30
2,789F3C21E472CA96,docked_bike,19:29:26,19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,41.940200,-87.653000,member,2020-01-09,2020-01-09
3,C9A388DAC6ABF313,docked_bike,16:17:07,16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,41.891800,-87.620600,member,2020-01-06,2020-01-06
4,943BC3CBECCFD662,docked_bike,08:37:16,08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,41.889900,-87.634300,member,2020-01-30,2020-01-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11952925,BC3BFA659C9AB6F1,classic_bike,01:41:29,01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,41.943350,-87.670668,casual,2022-10-30,2022-10-30
11952926,ACD65450291CF95F,classic_bike,01:41:54,01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,41.943350,-87.670668,casual,2022-10-30,2022-10-30
11952927,4AAC03D1438E97CA,classic_bike,09:34:11,10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,-87.638677,41.891466,-87.626761,casual,2022-10-15,2022-10-15
11952928,8E6F3F29785E5D40,classic_bike,10:21:34,10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,-87.638677,41.931931,-87.677856,member,2022-10-09,2022-10-09
11952929,8D14CBE672431920,docked_bike,13:17:13,13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,-87.636282,41.891466,-87.626761,casual,2022-10-22,2022-10-22

# Stations merge for landmark and dpcapcity data

In [73]:
# I am now going to merge this dataset with the 'stations_master_list' data, because we can add to/from landmark columns, as
# well as to/from city columns.
stations = pd.read_csv('master_station_list.csv')
stations = stations.drop(['Unnamed: 0'], axis=1)

In [74]:
stations

,id,name,latitude,longitude,dpcapacity,landmark,city
0,5,State St & Harrison St,41.873958,-87.627739,19,30.0,Chicago
1,13,Wilton Ave & Diversey Pkwy,41.932500,-87.652681,19,66.0,Chicago
2,14,Morgan St & 18th St,41.858086,-87.651073,15,163.0,Chicago
3,15,Racine Ave & 18th St,41.858181,-87.656487,15,164.0,Chicago
4,16,Wood St & North Ave,41.910329,-87.672516,15,223.0,Chicago
...,...,...,...,...,...,...,...
581,622,California Ave & Cortez St,41.900363,-87.696704,0,0.0,Chicago
582,623,Michigan Ave & 8th St,41.872773,-87.623981,23,0.0,Chicago
583,624,Dearborn St & Van Buren St (*),41.876268,-87.629155,16,0.0,Chicago
584,625,Chicago Ave & Dempster St,42.041691,-87.680687,15,0.0,Evanston
585,626,Delano Ct & Roosevelt Rd,41.867491,-87.632190,19,0.0,Chicago

In [75]:
stations.dtypes

id              int64
name           object
latitude      float64
longitude     float64
dpcapacity      int64
landmark      float64
city           object
dtype: object

In [76]:
stations = stations.astype({'id' : 'float'})
stations = stations.astype({'id' : 'string'})

In [77]:
stations

,id,name,latitude,longitude,dpcapacity,landmark,city
0,5.0,State St & Harrison St,41.873958,-87.627739,19,30.0,Chicago
1,13.0,Wilton Ave & Diversey Pkwy,41.932500,-87.652681,19,66.0,Chicago
2,14.0,Morgan St & 18th St,41.858086,-87.651073,15,163.0,Chicago
3,15.0,Racine Ave & 18th St,41.858181,-87.656487,15,164.0,Chicago
4,16.0,Wood St & North Ave,41.910329,-87.672516,15,223.0,Chicago
...,...,...,...,...,...,...,...
581,622.0,California Ave & Cortez St,41.900363,-87.696704,0,0.0,Chicago
582,623.0,Michigan Ave & 8th St,41.872773,-87.623981,23,0.0,Chicago
583,624.0,Dearborn St & Van Buren St (*),41.876268,-87.629155,16,0.0,Chicago
584,625.0,Chicago Ave & Dempster St,42.041691,-87.680687,15,0.0,Evanston
585,626.0,Delano Ct & Roosevelt Rd,41.867491,-87.632190,19,0.0,Chicago

In [78]:
# I will drop latitude and longitude, since we already have these. I will include dpcapcity, but only for now. Merging on 'id'

In [79]:
stations = stations.drop(['latitude', 'longitude', 'name'], axis=1)

# 'from_city','from_landmark',
from_city = stations.rename(columns={'id' : 'from_station_id', 'city' : 'from_city', 'landmark' : 'from_landmark', 'dpcapacity' : 'from_dpcapacity'})

# 'to_city', 'to_landmark'
to_city = stations.rename(columns={'id' : 'end_station_id', 'city' : 'to_city', 'landmark' : 'to_landmark', 'dpcapacity' : 'to_dpcapacity'})

In [80]:
from_city

    from_station_id  from_dpcapacity  from_landmark from_city
0               5.0               19           30.0   Chicago
1              13.0               19           66.0   Chicago
2              14.0               15          163.0   Chicago
3              15.0               15          164.0   Chicago
4              16.0               15          223.0   Chicago
..              ...              ...            ...       ...
581           622.0                0            0.0   Chicago
582           623.0               23            0.0   Chicago
583           624.0               16            0.0   Chicago
584           625.0               15            0.0  Evanston
585           626.0               19            0.0   Chicago

[586 rows x 4 columns]

In [81]:
to_city

    end_station_id  to_dpcapacity  to_landmark   to_city
0              5.0             19         30.0   Chicago
1             13.0             19         66.0   Chicago
2             14.0             15        163.0   Chicago
3             15.0             15        164.0   Chicago
4             16.0             15        223.0   Chicago
..             ...            ...          ...       ...
581          622.0              0          0.0   Chicago
582          623.0             23          0.0   Chicago
583          624.0             16          0.0   Chicago
584          625.0             15          0.0  Evanston
585          626.0             19          0.0   Chicago

[586 rows x 4 columns]

In [82]:
to_city

    end_station_id  to_dpcapacity  to_landmark   to_city
0              5.0             19         30.0   Chicago
1             13.0             19         66.0   Chicago
2             14.0             15        163.0   Chicago
3             15.0             15        164.0   Chicago
4             16.0             15        223.0   Chicago
..             ...            ...          ...       ...
581          622.0              0          0.0   Chicago
582          623.0             23          0.0   Chicago
583          624.0             16          0.0   Chicago
584          625.0             15          0.0  Evanston
585          626.0             19          0.0   Chicago

[586 rows x 4 columns]

In [83]:
k = pd.merge(merged2020_2022, from_city, on='from_station_id', how='left')

In [84]:
k

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city
0,EACB19130B0CDA4A,docked_bike,20:06:59,20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,41.967100,-87.667400,member,2020-01-21,2020-01-21,NaN,NaN,NaN
1,8FED874C809DC021,docked_bike,14:22:39,14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,41.954200,-87.664400,member,2020-01-30,2020-01-30,NaN,NaN,NaN
2,789F3C21E472CA96,docked_bike,19:29:26,19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,41.940200,-87.653000,member,2020-01-09,2020-01-09,NaN,NaN,NaN
3,C9A388DAC6ABF313,docked_bike,16:17:07,16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,41.891800,-87.620600,member,2020-01-06,2020-01-06,NaN,NaN,NaN
4,943BC3CBECCFD662,docked_bike,08:37:16,08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,41.889900,-87.634300,member,2020-01-30,2020-01-30,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11952925,BC3BFA659C9AB6F1,classic_bike,01:41:29,01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,41.943350,-87.670668,casual,2022-10-30,2022-10-30,NaN,NaN,NaN
11952926,ACD65450291CF95F,classic_bike,01:41:54,01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,41.943350,-87.670668,casual,2022-10-30,2022-10-30,NaN,NaN,NaN
11952927,4AAC03D1438E97CA,classic_bike,09:34:11,10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,-87.638677,41.891466,-87.626761,casual,2022-10-15,2022-10-15,NaN,NaN,NaN
11952928,8E6F3F29785E5D40,classic_bike,10:21:34,10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,-87.638677,41.931931,-87.677856,member,2022-10-09,2022-10-09,NaN,NaN,NaN
11952929,8D14CBE672431920,docked_bike,13:17:13,13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,-87.636282,41.891466,-87.626761,casual,2022-10-22,2022-10-22,NaN,NaN,NaN

In [85]:
k_final = pd.merge(k, to_city, on='end_station_id', how='left')

In [86]:
k_final

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,...,end_lng,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city
0,EACB19130B0CDA4A,docked_bike,20:06:59,20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,...,-87.667400,member,2020-01-21,2020-01-21,NaN,NaN,NaN,NaN,NaN,NaN
1,8FED874C809DC021,docked_bike,14:22:39,14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,...,-87.664400,member,2020-01-30,2020-01-30,NaN,NaN,NaN,NaN,NaN,NaN
2,789F3C21E472CA96,docked_bike,19:29:26,19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,...,-87.653000,member,2020-01-09,2020-01-09,NaN,NaN,NaN,NaN,NaN,NaN
3,C9A388DAC6ABF313,docked_bike,16:17:07,16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,...,-87.620600,member,2020-01-06,2020-01-06,NaN,NaN,NaN,NaN,NaN,NaN
4,943BC3CBECCFD662,docked_bike,08:37:16,08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,...,-87.634300,member,2020-01-30,2020-01-30,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11952925,BC3BFA659C9AB6F1,classic_bike,01:41:29,01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,-87.670668,casual,2022-10-30,2022-10-30,NaN,NaN,NaN,NaN,NaN,NaN
11952926,ACD65450291CF95F,classic_bike,01:41:54,01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,-87.670668,casual,2022-10-30,2022-10-30,NaN,NaN,NaN,NaN,NaN,NaN
11952927,4AAC03D1438E97CA,classic_bike,09:34:11,10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,-87.638677,...,-87.626761,casual,2022-10-15,2022-10-15,NaN,NaN,NaN,NaN,NaN,NaN
11952928,8E6F3F29785E5D40,classic_bike,10:21:34,10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,-87.638677,...,-87.677856,member,2022-10-09,2022-10-09,NaN,NaN,NaN,NaN,NaN,NaN
11952929,8D14CBE672431920,docked_bike,13:17:13,13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,-87.636282,...,-87.626761,casual,2022-10-22,2022-10-22,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
k_final.isnull().sum()

ride_id                     0
rideable_type               0
start_time                  0
end_time                    0
from_station_name           0
from_station_id             0
to_station_name             0
end_station_id              0
start_lat                   0
start_lng                   0
end_lat                     0
end_lng                     0
usertype                    0
start_date                  0
end_date                    0
from_dpcapacity      11946646
from_landmark        11946646
from_city            11946646
to_dpcapacity        11946875
to_landmark          11946875
to_city              11946875
dtype: int64

In [88]:
stations

        id  dpcapacity  landmark      city
0      5.0          19      30.0   Chicago
1     13.0          19      66.0   Chicago
2     14.0          15     163.0   Chicago
3     15.0          15     164.0   Chicago
4     16.0          15     223.0   Chicago
..     ...         ...       ...       ...
581  622.0           0       0.0   Chicago
582  623.0          23       0.0   Chicago
583  624.0          16       0.0   Chicago
584  625.0          15       0.0  Evanston
585  626.0          19       0.0   Chicago

[586 rows x 4 columns]

In [89]:
stations_and_landmarks = {}
ids = stations['id'].values
landmarks = stations['landmark'].values

for i in range(len(ids)):
    stations_and_landmarks[f'{ids[i]}'] = landmarks[i]
stations_and_landmarks

{'5.0': 30.0,
 '13.0': 66.0,
 '14.0': 163.0,
 '15.0': 164.0,
 '16.0': 223.0,
 '17.0': 246.0,
 '19.0': 139.0,
 '20.0': 154.0,
 '21.0': 157.0,
 '22.0': 160.0,
 '23.0': 172.0,
 '24.0': 262.0,
 '25.0': 34.0,
 '26.0': 51.0,
 '27.0': 174.0,
 '28.0': 282.0,
 '29.0': 290.0,
 '30.0': 248.0,
 '31.0': 17.0,
 '32.0': 76.0,
 '33.0': 3.0,
 '34.0': 124.0,
 '35.0': 22.0,
 '36.0': 19.0,
 '37.0': 20.0,
 '42.0': 170.0,
 '43.0': 1.0,
 '44.0': 2.0,
 '45.0': 40.0,
 '46.0': 46.0,
 '47.0': 50.0,
 '48.0': 12.0,
 '49.0': 49.0,
 '50.0': 9.0,
 '51.0': 5.0,
 '52.0': 43.0,
 '53.0': 64.0,
 '54.0': 44.0,
 '55.0': 166.0,
 '56.0': 39.0,
 '57.0': 327.0,
 '58.0': 25.0,
 '59.0': 31.0,
 '60.0': 58.0,
 '61.0': 221.0,
 '62.0': 106.0,
 '66.0': 21.0,
 '67.0': 60.0,
 '68.0': 37.0,
 '69.0': 65.0,
 '71.0': 72.0,
 '72.0': 148.0,
 '73.0': 38.0,
 '74.0': 265.0,
 '75.0': 138.0,
 '76.0': 300.0,
 '77.0': 301.0,
 '80.0': 156.0,
 '81.0': 23.0,
 '84.0': 33.0,
 '85.0': 42.0,
 '86.0': 289.0,
 '87.0': 189.0,
 '88.0': 155.0,
 '90.0': 8.0,
 '91.0': 10.0,
 '92.0': 196.0,
 '93.0': 190.0,
 '94.0': 146.0,
 '97.0': 29.0,
 '98.0': 6.0,
 '99.0': 337.0,
 '100.0': 13.0,
 '106.0': 14.0,
 '108.0': 27.0,
 '109.0': 28.0,
 '110.0': 45.0,
 '111.0': 52.0,
 '112.0': 53.0,
 '113.0': 59.0,
 '114.0': 62.0,
 '115.0': 67.0,
 '116.0': 68.0,
 '117.0': 69.0,
 '118.0': 70.0,
 '119.0': 73.0,
 '120.0': 75.0,
 '121.0': 398.0,
 '122.0': 81.0,
 '123.0': 84.0,
 '124.0': 89.0,
 '126.0': 128.0,
 '127.0': 131.0,
 '128.0': 132.0,
 '129.0': 135.0,
 '130.0': 136.0,
 '131.0': 140.0,
 '132.0': 149.0,
 '134.0': 158.0,
 '135.0': 162.0,
 '136.0': 165.0,
 '137.0': 169.0,
 '138.0': 171.0,
 '140.0': 173.0,
 '141.0': 179.0,
 '143.0': 191.0,
 '144.0': 193.0,
 '146.0': 206.0,
 '147.0': 212.0,
 '148.0': 216.0,
 '149.0': 217.0,
 '150.0': 220.0,
 '152.0': 226.0,
 '153.0': 228.0,
 '154.0': 229.0,
 '156.0': 232.0,
 '157.0': 234.0,
 '158.0': 243.0,
 '159.0': 245.0,
 '160.0': 257.0,
 '162.0': 268.0,
 '163.0': 271.0,
 '164.0': 272.0,
 '165.0': 275.0,
 '166.0': 296.0,
 '167.0': 306.0,
 '168.0': 310.0,
 '169.0': 326.0,
 '170.0': 329.0,
 '171.0': 331.0,
 '173.0': 338.0,
 '174.0': 341.0,
 '175.0': 344.0,
 '176.0': 349.0,
 '177.0': 350.0,
 '178.0': 408.0,
 '179.0': 420.0,
 '181.0': 430.0,
 '183.0': 142.0,
 '184.0': 82.0,
 '185.0': 266.0,
 '186.0': 194.0,
 '188.0': 295.0,
 '190.0': 298.0,
 '191.0': 56.0,
 '192.0': 11.0,
 '193.0': 213.0,
 '194.0': 339.0,
 '195.0': 263.0,
 '196.0': 427.0,
 '197.0': 36.0,
 '198.0': 159.0,
 '199.0': 4.0,
 '200.0': 90.0,
 '201.0': 83.0,
 '202.0': 99.0,
 '203.0': 91.0,
 '204.0': 101.0,
 '205.0': 88.0,
 '206.0': 98.0,
 '207.0': 399.0,
 '208.0': 307.0,
 '209.0': 308.0,
 '210.0': 61.0,
 '211.0': 16.0,
 '212.0': 264.0,
 '213.0': 244.0,
 '214.0': 141.0,
 '215.0': 134.0,
 '216.0': 256.0,
 '217.0': 197.0,
 '218.0': 180.0,
 '219.0': 133.0,
 '220.0': 123.0,
 '222.0': 242.0,
 '223.0': 185.0,
 '224.0': 181.0,
 '225.0': 192.0,
 '226.0': 230.0,
 '227.0': 235.0,
 '228.0': 143.0,
 '229.0': 71.0,
 '230.0': 78.0,
 '231.0': 130.0,
 '232.0': 273.0,
 '233.0': 409.0,
 '234.0': 316.0,
 '236.0': 410.0,
 '237.0': 214.0,
 '238.0': 92.0,
 '239.0': 112.0,
 '240.0': 63.0,
 '241.0': 168.0,
 '242.0': 93.0,
 '243.0': 126.0,
 '244.0': 87.0,
 '245.0': 389.0,
 '246.0': 249.0,
 '247.0': 361.0,
 '248.0': 362.0,
 '249.0': 388.0,
 '250.0': 269.0,
 '251.0': 385.0,
 '252.0': 396.0,
 '253.0': 104.0,
 '254.0': 324.0,
 '255.0': 309.0,
 '256.0': 323.0,
 '257.0': 253.0,
 '258.0': 145.0,
 '259.0': 259.0,
 '260.0': 85.0,
 '261.0': 80.0,
 '262.0': 414.0,
 '263.0': 215.0,
 '264.0': 48.0,
 '265.0': 346.0,
 '267.0': 117.0,
 '268.0': 328.0,
 '271.0': 86.0,
 '272.0': 219.0,
 '273.0': 150.0,
 '274.0': 304.0,
 '275.0': 354.0,
 '276.0': 258.0,
 '277.0': 434.0,
 '278.0': 417.0,
 '279.0': 413.0,
 '280.0': 97.0,
 '281.0': 393.0,
 '282.0': 161.0,
 '283.0': 32.0,
 '284.0': 340.0,
 '285.0': 432.0,
 '286.0': 7.0,
 '287.0': 57.0,
 '288.0': 184.0,
 '289.0': 182.0,
 '290.0': 292.0,
 '291.0': 302.0,
 '292.0': 317.0,
 '293.0': 74.0,
 '294.0': 109.0,
 '295.0': 108.0,
 '296.0': 277.0,
 '297.0': 250.0,
 '298.0': 252.0,
 '299.0': 127.0,
 '300.0': 137.0,
 '301.0': 200.0,
 '302.0': 211.0,
 '303.0': 278.0,
 '304.0': 325.0,
 '305.0': 241.0,
 '306.0': 374.0,
 '307.0': 186.0,
 '308.0': 144.0,
 '309.0': 286.0,
 '310.0': 288.0,
 '311.0': 237.0,
 '312.0': 379.0,
 '313.0': 147.0,
 '314.0': 251.0,
 '315.0': 255.0,
 '316.0': 315.0,
 '317.0': 285.0,
 '318.0': 321.0,
 '319.0': 294.0,
 '320.0': 332.0,
 '321.0': 54.0,
 '322.0': 397.0,
 '323.0': 384.0,
 '324.0': 276.0,
 '325.0': 392.0,
 '326.0': 239.0,
 '327.0': 188.0,
 '328.0': 365.0,
 '329.0': 347.0,
 '330.0': 77.0,
 '331.0': 176.0,
 '332.0': 208.0,
 '333.0': 224.0,
 '334.0': 233.0,
 '335.0': 345.0,
 '336.0': 422.0,
 '337.0': 303.0,
 '338.0': 102.0,
 '339.0': 404.0,
 '340.0': 209.0,
 '341.0': 431.0,
 '342.0': 284.0,
 '343.0': 297.0,
 '344.0': 26.0,
 '345.0': 119.0,
 '346.0': 353.0,
 '347.0': 319.0,
 '348.0': 96.0,
 '349.0': 210.0,
 '350.0': 247.0,
 '351.0': 440.0,
 '2.0': 541.0,
 '3.0': 544.0,
 '4.0': 545.0,
 '6.0': 548.0,
 '7.0': 534.0,
 '9.0': 695.0,
 '11.0': 496.0,
 '12.0': 497.0,
 '18.0': 536.0,
 '38.0': 547.0,
 '39.0': 538.0,
 '40.0': 537.0,
 '41.0': 543.0,
 '89.0': 540.0,
 '95.0': 490.0,
 '96.0': 535.0,
 '101.0': 491.0,
 '102.0': 492.0,
 '103.0': 542.0,
 '107.0': 539.0,
 '125.0': 533.0,
 '133.0': 532.0,
 '142.0': 531.0,
 '145.0': 529.0,
 '161.0': 530.0,
 '172.0': 525.0,
 '180.0': 523.0,
 '182.0': 522.0,
 '270.0': 498.0,
 '352.0': 493.0,
 '353.0': 561.0,
 '354.0': 562.0,
 '355.0': 494.0,
 '356.0': 495.0,
 '359.0': 524.0,
 '364.0': 527.0,
 '365.0': 528.0,
 '366.0': 441.0,
 '367.0': 446.0,
 '368.0': 442.0,
 '369.0': 694.0,
 '370.0': 546.0,
 '372.0': 660.0,
 '373.0': 661.0,
 '374.0': 662.0,
 '375.0': 663.0,
 '376.0': 664.0,
 '377.0': 665.0,
 '378.0': 666.0,
 '381.0': 667.0,
 '382.0': 668.0,
 '383.0': 669.0,
 '384.0': 591.0,
 '385.0': 592.0,
 '386.0': 593.0,
 '388.0': 595.0,
 '390.0': 596.0,
 '391.0': 597.0,
 '392.0': 598.0,
 '393.0': 599.0,
 '395.0': 499.0,
 '396.0': 500.0,
 '397.0': 501.0,
 '398.0': 502.0,
 '399.0': 506.0,
 '400.0': 507.0,
 '401.0': 443.0,
 '402.0': 444.0,
 '403.0': 445.0,
 '406.0': 448.0,
 '407.0': 449.0,
 '408.0': 450.0,
 '409.0': 451.0,
 '410.0': 452.0,
 '411.0': 453.0,
 '412.0': 454.0,
 '413.0': 455.0,
 '414.0': 456.0,
 '415.0': 470.0,
 '416.0': 471.0,
 '417.0': 472.0,
 '418.0': 473.0,
 '419.0': 474.0,
 '420.0': 475.0,
 '421.0': 476.0,
 '422.0': 477.0,
 '423.0': 478.0,
 '424.0': 479.0,
 '425.0': 480.0,
 '426.0': 481.0,
 '427.0': 482.0,
 '428.0': 484.0,
 '429.0': 485.0,
 '430.0': 486.0,
 '431.0': 487.0,
 '432.0': 563.0,
 '433.0': 680.0,
 '434.0': 681.0,
 '435.0': 682.0,
 '436.0': 683.0,
 '437.0': 684.0,
 '438.0': 685.0,
 '439.0': 686.0,
 '440.0': 687.0,
 '441.0': 688.0,
 '442.0': 689.0,
 '443.0': 690.0,
 '444.0': 691.0,
 '445.0': 692.0,
 '446.0': 693.0,
 '447.0': 564.0,
 '448.0': 565.0,
 '449.0': 566.0,
 '450.0': 567.0,
 '451.0': 568.0,
 '452.0': 569.0,
 '453.0': 570.0,
 '454.0': 571.0,
 '455.0': 572.0,
 '456.0': 573.0,
 '457.0': 574.0,
 '458.0': 575.0,
 '459.0': 576.0,
 '460.0': 577.0,
 '461.0': 578.0,
 '462.0': 579.0,
 '463.0': 580.0,
 '464.0': 581.0,
 '465.0': 582.0,
 '466.0': 583.0,
 '467.0': 584.0,
 '468.0': 585.0,
 '469.0': 611.0,
 '470.0': 612.0,
 '471.0': 613.0,
 '472.0': 614.0,
 '474.0': 615.0,
 '475.0': 616.0,
 '476.0': 617.0,
 '477.0': 618.0,
 '478.0': 619.0,
 '479.0': 620.0,
 '480.0': 621.0,
 '481.0': 622.0,
 '482.0': 623.0,
 '483.0': 624.0,
 '484.0': 625.0,
 '485.0': 626.0,
 '486.0': 627.0,
 '487.0': 628.0,
 '488.0': 629.0,
 '489.0': 630.0,
 '490.0': 631.0,
 '491.0': 632.0,
 '492.0': 633.0,
 '493.0': 634.0,
 '494.0': 635.0,
 '495.0': 636.0,
 '496.0': 640.0,
 '497.0': 641.0,
 '498.0': 642.0,
 '499.0': 643.0,
 '500.0': 644.0,
 '501.0': 645.0,
 '502.0': 646.0,
 '503.0': 647.0,
 '504.0': 648.0,
 '505.0': 649.0,
 '506.0': 650.0,
 '507.0': 651.0,
 '508.0': 652.0,
 '509.0': 653.0,
 '510.0': 654.0,
 '511.0': 655.0,
 '555.0': 0.0,
 '563.0': 0.0,
 '565.0': 0.0,
 '566.0': 0.0,
 '558.0': 0.0,
 '552.0': 0.0,
 '547.0': 0.0,
 '532.0': 0.0,
 '541.0': 0.0,
 '542.0': 0.0,
 '533.0': 0.0,
 '538.0': 0.0,
 '529.0': 0.0,
 '539.0': 0.0,
 '394.0': 0.0,
 '518.0': 0.0,
 '554.0': 0.0,
 '561.0': 0.0,
 '557.0': 0.0,
 '546.0': 0.0,
 '553.0': 0.0,
 '570.0': 0.0,
 '593.0': 0.0,
 '551.0': 0.0,
 '537.0': 0.0,
 '545.0': 0.0,
 '536.0': 0.0,
 '543.0': 0.0,
 '530.0': 0.0,
 '540.0': 0.0,
 '549.0': 0.0,
 '560.0': 0.0,
 '544.0': 0.0,
 '567.0': 0.0,
 '548.0': 0.0,
 '568.0': 0.0,
 '535.0': 0.0,
 '528.0': 0.0,
 '534.0': 0.0,
 '562.0': 0.0,
 '564.0': 0.0,
 '559.0': 0.0,
 '572.0': 0.0,
 '556.0': 0.0,
 '594.0': 0.0,
 '569.0': 0.0,
 '596.0': 0.0,
 '601.0': 0.0,
 '597.0': 0.0,
 '600.0': 0.0,
 '607.0': 0.0,
 '617.0': 0.0,
 '614.0': 0.0,
 '609.0': 0.0,
 '608.0': 0.0,
 '618.0': 0.0,
 '615.0': 0.0,
 '610.0': 0.0,
 '616.0': 0.0,
 '611.0': 0.0,
 '613.0': 0.0,
 '524.0': 0.0,
 '522.0': 0.0,
 '550.0': 0.0,
 '531.0': 0.0,
 '602.0': 0.0,
 '578.0': 0.0,
 '603.0': 0.0,
 '517.0': 0.0,
 '581.0': 0.0,
 '575.0': 0.0,
 '585.0': 0.0,
 '523.0': 0.0,
 '584.0': 0.0,
 '598.0': 0.0,
 '580.0': 0.0,
 '606.0': 0.0,
 '525.0': 0.0,
 '520.0': 0.0,
 '576.0': 0.0,
 '619.0': 0.0,
 '590.0': 0.0,
 '591.0': 0.0,
 '592.0': 0.0,
 '589.0': 0.0,
 '586.0': 0.0,
 '526.0': 0.0,
 '620.0': 0.0,
 '515.0': 0.0,
 '579.0': 0.0,
 '582.0': 0.0,
 '514.0': 0.0,
 '612.0': 0.0,
 '604.0': 0.0,
 '588.0': 0.0,
 '573.0': 0.0,
 '583.0': 0.0,
 '577.0': 0.0,
 '605.0': 0.0,
 '599.0': 0.0,
 '571.0': 0.0,
 '574.0': 0.0,
 '587.0': 0.0,
 '595.0': 0.0,
 '405.0': 0.0,
 '527.0': 0.0,
 '519.0': 0.0,
 '622.0': 0.0,
 '623.0': 0.0,
 '624.0': 0.0,
 '625.0': 0.0,
 '626.0': 0.0}

In [90]:
new_column_from_station = []
run_ids_from = k_final['from_station_id'].values


for i in range(len(run_ids_from)):
    try:
        new_column_from_station.append(stations_and_landmarks[f'{run_ids_from[i]}'])
    except KeyError:
        new_column_from_station.append(0.0)
        pass
    
    
    
new_column_from_station

[112.0,
 316.0,
 277.0,
 5.0,
 21.0,
 264.0,
 535.0,
 535.0,
 264.0,
 547.0,
 69.0,
 430.0,
 10.0,
 10.0,
 84.0,
 19.0,
 66.0,
 19.0,
 226.0,
 532.0,
 300.0,
 11.0,
 309.0,
 323.0,
 539.0,
 11.0,
 241.0,
 19.0,
 45.0,
 19.0,
 208.0,
 66.0,
 0.0,
 145.0,
 243.0,
 353.0,
 186.0,
 171.0,
 12.0,
 33.0,
 63.0,
 39.0,
 21.0,
 197.0,
 196.0,
 78.0,
 141.0,
 310.0,
 310.0,
 622.0,
 141.0,
 141.0,
 374.0,
 53.0,
 353.0,
 277.0,
 353.0,
 23.0,
 341.0,
 57.0,
 263.0,
 339.0,
 263.0,
 145.0,
 145.0,
 4.0,
 194.0,
 22.0,
 263.0,
 145.0,
 263.0,
 263.0,
 4.0,
 263.0,
 61.0,
 241.0,
 21.0,
 408.0,
 456.0,
 408.0,
 1.0,
 456.0,
 456.0,
 534.0,
 148.0,
 263.0,
 263.0,
 232.0,
 112.0,
 85.0,
 643.0,
 6.0,
 275.0,
 26.0,
 85.0,
 643.0,
 140.0,
 66.0,
 524.0,
 211.0,
 1.0,
 10.0,
 211.0,
 10.0,
 210.0,
 210.0,
 137.0,
 527.0,
 210.0,
 52.0,
 475.0,
 480.0,
 475.0,
 1.0,
 448.0,
 1.0,
 43.0,
 5.0,
 0.0,
 168.0,
 681.0,
 168.0,
 0.0,
 354.0,
 0.0,
 385.0,
 72.0,
 409.0,
 345.0,
 448.0,
 420.0,
 83.0,
 266.0,
 0.0,
 71.0,
 228.0,
 323.0,
 0.0,
 0.0,
 11.0,
 11.0,
 10.0,
 11.0,
 61.0,
 246.0,
 532.0,
 241.0,
 662.0,
 662.0,
 321.0,
 63.0,
 51.0,
 208.0,
 538.0,
 332.0,
 339.0,
 37.0,
 33.0,
 11.0,
 5.0,
 23.0,
 200.0,
 209.0,
 0.0,
 209.0,
 71.0,
 200.0,
 64.0,
 137.0,
 0.0,
 123.0,
 200.0,
 226.0,
 209.0,
 32.0,
 23.0,
 23.0,
 32.0,
 32.0,
 32.0,
 531.0,
 309.0,
 0.0,
 0.0,
 12.0,
 25.0,
 12.0,
 12.0,
 301.0,
 137.0,
 667.0,
 12.0,
 42.0,
 126.0,
 300.0,
 2.0,
 69.0,
 561.0,
 0.0,
 0.0,
 0.0,
 273.0,
 481.0,
 252.0,
 273.0,
 69.0,
 273.0,
 235.0,
 21.0,
 57.0,
 57.0,
 323.0,
 522.0,
 70.0,
 76.0,
 160.0,
 59.0,
 349.0,
 12.0,
 25.0,
 25.0,
 12.0,
 12.0,
 25.0,
 12.0,
 25.0,
 650.0,
 49.0,
 644.0,
 5.0,
 650.0,
 292.0,
 243.0,
 0.0,
 57.0,
 60.0,
 66.0,
 176.0,
 87.0,
 234.0,
 272.0,
 431.0,
 272.0,
 10.0,
 272.0,
 272.0,
 577.0,
 263.0,
 53.0,
 60.0,
 522.0,
 522.0,
 349.0,
 50.0,
 522.0,
 53.0,
 46.0,
 0.0,
 232.0,
 154.0,
 642.0,
 522.0,
 12.0,
 59.0,
 99.0,
 246.0,
 0.0,
 289.0,
 135.0,
 300.0,
 430.0,
 430.0,
 3.0,
 36.0,
 309.0,
 36.0,
 0.0,
 0.0,
 54.0,
 327.0,
 36.0,
 430.0,
 48.0,
 2.0,
 51.0,
 0.0,
 13.0,
 32.0,
 12.0,
 78.0,
 392.0,
 232.0,
 398.0,
 361.0,
 123.0,
 277.0,
 209.0,
 276.0,
 147.0,
 276.0,
 546.0,
 0.0,
 0.0,
 276.0,
 68.0,
 655.0,
 0.0,
 68.0,
 173.0,
 0.0,
 68.0,
 655.0,
 61.0,
 262.0,
 243.0,
 242.0,
 4.0,
 85.0,
 33.0,
 532.0,
 262.0,
 13.0,
 262.0,
 13.0,
 262.0,
 0.0,
 21.0,
 0.0,
 0.0,
 536.0,
 21.0,
 21.0,
 536.0,
 0.0,
 21.0,
 10.0,
 13.0,
 0.0,
 10.0,
 0.0,
 243.0,
 265.0,
 21.0,
 0.0,
 10.0,
 21.0,
 297.0,
 186.0,
 0.0,
 297.0,
 186.0,
 297.0,
 186.0,
 298.0,
 28.0,
 173.0,
 56.0,
 173.0,
 341.0,
 173.0,
 324.0,
 278.0,
 12.0,
 441.0,
 32.0,
 441.0,
 379.0,
 64.0,
 273.0,
 242.0,
 259.0,
 301.0,
 527.0,
 190.0,
 146.0,
 527.0,
 8.0,
 338.0,
 45.0,
 338.0,
 349.0,
 45.0,
 10.0,
 301.0,
 282.0,
 174.0,
 282.0,
 282.0,
 527.0,
 282.0,
 524.0,
 128.0,
 42.0,
 0.0,
 0.0,
 10.0,
 45.0,
 52.0,
 191.0,
 208.0,
 338.0,
 56.0,
 338.0,
 56.0,
 338.0,
 253.0,
 6.0,
 5.0,
 29.0,
 49.0,
 536.0,
 6.0,
 92.0,
 651.0,
 19.0,
 154.0,
 93.0,
 194.0,
 194.0,
 14.0,
 74.0,
 194.0,
 669.0,
 3.0,
 536.0,
 228.0,
 135.0,
 3.0,
 327.0,
 32.0,
 427.0,
 579.0,
 93.0,
 93.0,
 396.0,
 396.0,
 43.0,
 1.0,
 536.0,
 328.0,
 328.0,
 2.0,
 578.0,
 209.0,
 228.0,
 301.0,
 301.0,
 301.0,
 80.0,
 301.0,
 127.0,
 303.0,
 10.0,
 10.0,
 173.0,
 10.0,
 303.0,
 10.0,
 43.0,
 19.0,
 221.0,
 275.0,
 133.0,
 150.0,
 32.0,
 148.0,
 27.0,
 39.0,
 23.0,
 344.0,
 344.0,
 26.0,
 623.0,
 112.0,
 620.0,
 32.0,
 148.0,
 353.0,
 32.0,
 150.0,
 32.0,
 148.0,
 32.0,
 7.0,
 148.0,
 327.0,
 148.0,
 7.0,
 148.0,
 353.0,
 32.0,
 148.0,
 32.0,
 148.0,
 11.0,
 13.0,
 31.0,
 148.0,
 36.0,
 301.0,
 49.0,
 536.0,
 544.0,
 53.0,
 651.0,
 522.0,
 10.0,
 43.0,
 525.0,
 43.0,
 43.0,
 10.0,
 522.0,
 651.0,
 544.0,
 8.0,
 80.0,
 10.0,
 80.0,
 10.0,
 51.0,
 160.0,
 51.0,
 11.0,
 1.0,
 189.0,
 613.0,
 544.0,
 8.0,
 10.0,
 1.0,
 10.0,
 1.0,
 265.0,
 286.0,
 286.0,
 265.0,
 286.0,
 52.0,
 286.0,
 564.0,
 243.0,
 564.0,
 577.0,
 577.0,
 578.0,
 160.0,
 51.0,
 50.0,
 168.0,
 160.0,
 51.0,
 50.0,
 76.0,
 28.0,
 627.0,
 85.0,
 642.0,
 625.0,
 642.0,
 85.0,
 642.0,
 253.0,
 85.0,
 669.0,
 392.0,
 112.0,
 92.0,
 5.0,
 316.0,
 74.0,
 295.0,
 23.0,
 523.0,
 544.0,
 347.0,
 23.0,
 276.0,
 347.0,
 23.0,
 347.0,
 276.0,
 134.0,
 374.0,
 273.0,
 273.0,
 481.0,
 226.0,
 181.0,
 145.0,
 192.0,
 273.0,
 533.0,
 5.0,
 159.0,
 159.0,
 193.0,
 523.0,
 208.0,
 277.0,
 69.0,
 11.0,
 56.0,
 148.0,
 31.0,
 11.0,
 11.0,
 246.0,
 0.0,
 221.0,
 0.0,
 432.0,
 0.0,
 432.0,
 21.0,
 0.0,
 166.0,
 148.0,
 23.0,
 432.0,
 0.0,
 43.0,
 4.0,
 6.0,
 481.0,
 30.0,
 165.0,
 165.0,
 30.0,
 93.0,
 579.0,
 262.0,
 326.0,
 326.0,
 150.0,
 262.0,
 39.0,
 61.0,
 106.0,
 49.0,
 39.0,
 532.0,
 23.0,
 72.0,
 10.0,
 173.0,
 10.0,
 72.0,
 535.0,
 16.0,
 241.0,
 68.0,
 650.0,
 68.0,
 45.0,
 269.0,
 275.0,
 265.0,
 339.0,
 78.0,
 650.0,
 182.0,
 269.0,
 650.0,
 434.0,
 0.0,
 208.0,
 578.0,
 13.0,
 11.0,
 11.0,
 13.0,
 45.0,
 532.0,
 11.0,
 13.0,
 22.0,
 13.0,
 10.0,
 13.0,
 11.0,
 473.0,
 365.0,
 397.0,
 39.0,
 72.0,
 5.0,
 137.0,
 0.0,
 397.0,
 475.0,
 473.0,
 478.0,
 397.0,
 344.0,
 344.0,
 189.0,
 21.0,
 344.0,
 0.0,
 344.0,
 344.0,
 615.0,
 615.0,
 615.0,
 617.0,
 615.0,
 159.0,
 615.0,
 615.0,
 56.0,
 263.0,
 0.0,
 532.0,
 45.0,
 321.0,
 317.0,
 179.0,
 182.0,
 128.0,
 181.0,
 181.0,
 0.0,
 257.0,
 257.0,
 21.0,
 176.0,
 221.0,
 323.0,
 85.0,
 266.0,
 74.0,
 146.0,
 536.0,
 84.0,
 536.0,
 0.0,
 169.0,
 531.0,
 531.0,
 302.0,
 69.0,
 61.0,
 8.0,
 19.0,
 156.0,
 156.0,
 531.0,
 531.0,
 44.0,
 32.0,
 6.0,
 522.0,
 6.0,
 296.0,
 192.0,
 235.0,
 531.0,
 16.0,
 146.0,
 301.0,
 209.0,
 209.0,
 146.0,
 525.0,
 108.0,
 226.0,
 0.0,
 26.0,
 392.0,
 26.0,
 26.0,
 392.0,
 392.0,
 26.0,
 0.0,
 392.0,
 301.0,
 25.0,
 247.0,
 537.0,
 247.0,
 20.0,
 289.0,
 44.0,
 20.0,
 6.0,
 397.0,
 480.0,
 43.0,
 157.0,
 85.0,
 17.0,
 319.0,
 319.0,
 87.0,
 321.0,
 17.0,
 321.0,
 232.0,
 319.0,
 221.0,
 475.0,
 155.0,
 296.0,
 296.0,
 191.0,
 576.0,
 191.0,
 662.0,
 43.0,
 39.0,
 33.0,
 10.0,
 532.0,
 33.0,
 532.0,
 33.0,
 532.0,
 57.0,
 33.0,
 63.0,
 39.0,
 33.0,
 57.0,
 63.0,
 67.0,
 67.0,
 70.0,
 0.0,
 0.0,
 73.0,
 141.0,
 141.0,
 158.0,
 158.0,
 158.0,
 141.0,
 158.0,
 141.0,
 536.0,
 154.0,
 242.0,
 48.0,
 43.0,
 17.0,
 10.0,
 16.0,
 530.0,
 17.0,
 532.0,
 21.0,
 172.0,
 17.0,
 23.0,
 262.0,
 249.0,
 14.0,
 209.0,
 146.0,
 303.0,
 303.0,
 303.0,
 303.0,
 272.0,
 21.0,
 0.0,
 0.0,
 0.0,
 10.0,
 532.0,
 265.0,
 185.0,
 547.0,
 248.0,
 0.0,
 11.0,
 379.0,
 385.0,
 582.0,
 575.0,
 106.0,
 0.0,
 76.0,
 57.0,
 544.0,
 301.0,
 53.0,
 71.0,
 10.0,
 19.0,
 341.0,
 5.0,
 5.0,
 341.0,
 5.0,
 341.0,
 341.0,
 10.0,
 5.0,
 301.0,
 341.0,
 5.0,
 5.0,
 341.0,
 5.0,
 214.0,
 298.0,
 212.0,
 170.0,
 538.0,
 547.0,
 0.0,
 69.0,
 277.0,
 50.0,
 532.0,
 39.0,
 61.0,
 13.0,
 33.0,
 65.0,
 65.0,
 65.0,
 139.0,
 472.0,
 263.0,
 397.0,
 478.0,
 317.0,
 2.0,
 63.0,
 48.0,
 17.0,
 57.0,
 34.0,
 72.0,
 72.0,
 264.0,
 72.0,
 189.0,
 145.0,
 191.0,
 182.0,
 8.0,
 300.0,
 8.0,
 8.0,
 300.0,
 1.0,
 0.0,
 0.0,
 0.0,
 478.0,
 384.0,
 474.0,
 474.0,
 478.0,
 538.0,
 474.0,
 538.0,
 478.0,
 474.0,
 71.0,
 71.0,
 71.0,
 26.0,
 109.0,
 1.0,
 11.0,
 26.0,
 26.0,
 262.0,
 56.0,
 216.0,
 216.0,
 434.0,
 630.0,
 45.0,
 13.0,
 45.0,
 45.0,
 13.0,
 45.0,
 45.0,
 45.0,
 264.0,
 13.0,
 13.0,
 45.0,
 323.0,
 5.0,
 21.0,
 0.0,
 194.0,
 65.0,
 133.0,
 290.0,
 194.0,
 91.0,
 ...]

In [91]:
len(new_column_from_station)

11952930

In [92]:
k_final.shape

(11952930, 21)

In [93]:
k_final

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,...,end_lng,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city
0,EACB19130B0CDA4A,docked_bike,20:06:59,20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,...,-87.667400,member,2020-01-21,2020-01-21,NaN,NaN,NaN,NaN,NaN,NaN
1,8FED874C809DC021,docked_bike,14:22:39,14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,...,-87.664400,member,2020-01-30,2020-01-30,NaN,NaN,NaN,NaN,NaN,NaN
2,789F3C21E472CA96,docked_bike,19:29:26,19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,...,-87.653000,member,2020-01-09,2020-01-09,NaN,NaN,NaN,NaN,NaN,NaN
3,C9A388DAC6ABF313,docked_bike,16:17:07,16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,...,-87.620600,member,2020-01-06,2020-01-06,NaN,NaN,NaN,NaN,NaN,NaN
4,943BC3CBECCFD662,docked_bike,08:37:16,08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,...,-87.634300,member,2020-01-30,2020-01-30,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11952925,BC3BFA659C9AB6F1,classic_bike,01:41:29,01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,-87.670668,casual,2022-10-30,2022-10-30,NaN,NaN,NaN,NaN,NaN,NaN
11952926,ACD65450291CF95F,classic_bike,01:41:54,01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,-87.670668,casual,2022-10-30,2022-10-30,NaN,NaN,NaN,NaN,NaN,NaN
11952927,4AAC03D1438E97CA,classic_bike,09:34:11,10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,-87.638677,...,-87.626761,casual,2022-10-15,2022-10-15,NaN,NaN,NaN,NaN,NaN,NaN
11952928,8E6F3F29785E5D40,classic_bike,10:21:34,10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,-87.638677,...,-87.677856,member,2022-10-09,2022-10-09,NaN,NaN,NaN,NaN,NaN,NaN
11952929,8D14CBE672431920,docked_bike,13:17:13,13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,-87.636282,...,-87.626761,casual,2022-10-22,2022-10-22,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
k_final['from_landmark'] = new_column_from_station

In [95]:
k_final

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,...,end_lng,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city
0,EACB19130B0CDA4A,docked_bike,20:06:59,20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,...,-87.667400,member,2020-01-21,2020-01-21,NaN,112.0,NaN,NaN,NaN,NaN
1,8FED874C809DC021,docked_bike,14:22:39,14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,...,-87.664400,member,2020-01-30,2020-01-30,NaN,316.0,NaN,NaN,NaN,NaN
2,789F3C21E472CA96,docked_bike,19:29:26,19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,...,-87.653000,member,2020-01-09,2020-01-09,NaN,277.0,NaN,NaN,NaN,NaN
3,C9A388DAC6ABF313,docked_bike,16:17:07,16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,...,-87.620600,member,2020-01-06,2020-01-06,NaN,5.0,NaN,NaN,NaN,NaN
4,943BC3CBECCFD662,docked_bike,08:37:16,08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,...,-87.634300,member,2020-01-30,2020-01-30,NaN,21.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11952925,BC3BFA659C9AB6F1,classic_bike,01:41:29,01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,-87.670668,casual,2022-10-30,2022-10-30,NaN,0.0,NaN,NaN,NaN,NaN
11952926,ACD65450291CF95F,classic_bike,01:41:54,01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,-87.670668,casual,2022-10-30,2022-10-30,NaN,0.0,NaN,NaN,NaN,NaN
11952927,4AAC03D1438E97CA,classic_bike,09:34:11,10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,-87.638677,...,-87.626761,casual,2022-10-15,2022-10-15,NaN,0.0,NaN,NaN,NaN,NaN
11952928,8E6F3F29785E5D40,classic_bike,10:21:34,10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,-87.638677,...,-87.677856,member,2022-10-09,2022-10-09,NaN,0.0,NaN,NaN,NaN,NaN
11952929,8D14CBE672431920,docked_bike,13:17:13,13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,-87.636282,...,-87.626761,casual,2022-10-22,2022-10-22,NaN,0.0,NaN,NaN,NaN,NaN

In [96]:
new_column_to_station = []
run_ids_to = k_final['end_station_id'].values


for i in range(len(run_ids_to)):
    try:
        new_column_to_station.append(stations_and_landmarks[f'{run_ids_to[i]}'])
    except KeyError:
        new_column_to_station.append(0.0)
        pass
new_column_to_station

[239.0,
 321.0,
 69.0,
 262.0,
 264.0,
 535.0,
 264.0,
 264.0,
 535.0,
 13.0,
 0.0,
 10.0,
 430.0,
 430.0,
 25.0,
 226.0,
 19.0,
 226.0,
 19.0,
 303.0,
 1.0,
 1.0,
 11.0,
 63.0,
 1.0,
 539.0,
 432.0,
 344.0,
 7.0,
 159.0,
 0.0,
 210.0,
 66.0,
 276.0,
 142.0,
 53.0,
 12.0,
 186.0,
 186.0,
 21.0,
 321.0,
 196.0,
 196.0,
 196.0,
 21.0,
 273.0,
 623.0,
 534.0,
 534.0,
 642.0,
 623.0,
 353.0,
 273.0,
 353.0,
 53.0,
 123.0,
 23.0,
 353.0,
 36.0,
 263.0,
 4.0,
 263.0,
 4.0,
 20.0,
 4.0,
 145.0,
 524.0,
 534.0,
 4.0,
 78.0,
 4.0,
 4.0,
 43.0,
 4.0,
 241.0,
 6.0,
 531.0,
 456.0,
 408.0,
 456.0,
 534.0,
 408.0,
 408.0,
 2.0,
 456.0,
 4.0,
 4.0,
 67.0,
 616.0,
 643.0,
 85.0,
 64.0,
 232.0,
 275.0,
 643.0,
 85.0,
 211.0,
 532.0,
 275.0,
 52.0,
 301.0,
 1.0,
 52.0,
 1.0,
 210.0,
 137.0,
 210.0,
 52.0,
 527.0,
 210.0,
 480.0,
 475.0,
 480.0,
 10.0,
 90.0,
 0.0,
 0.0,
 0.0,
 547.0,
 0.0,
 168.0,
 0.0,
 354.0,
 0.0,
 4.0,
 384.0,
 0.0,
 11.0,
 448.0,
 420.0,
 448.0,
 448.0,
 0.0,
 266.0,
 229.0,
 154.0,
 235.0,
 0.0,
 0.0,
 33.0,
 10.0,
 11.0,
 37.0,
 430.0,
 430.0,
 246.0,
 65.0,
 65.0,
 65.0,
 325.0,
 321.0,
 10.0,
 323.0,
 49.0,
 10.0,
 332.0,
 11.0,
 141.0,
 37.0,
 11.0,
 9.0,
 235.0,
 64.0,
 522.0,
 52.0,
 209.0,
 71.0,
 522.0,
 275.0,
 137.0,
 137.0,
 66.0,
 209.0,
 182.0,
 23.0,
 32.0,
 32.0,
 23.0,
 23.0,
 23.0,
 5.0,
 0.0,
 344.0,
 309.0,
 21.0,
 12.0,
 10.0,
 21.0,
 12.0,
 209.0,
 301.0,
 134.0,
 278.0,
 315.0,
 300.0,
 21.0,
 78.0,
 0.0,
 0.0,
 0.0,
 0.0,
 137.0,
 478.0,
 273.0,
 69.0,
 273.0,
 235.0,
 324.0,
 536.0,
 148.0,
 150.0,
 275.0,
 0.0,
 302.0,
 160.0,
 76.0,
 522.0,
 4.0,
 25.0,
 12.0,
 12.0,
 0.0,
 21.0,
 12.0,
 25.0,
 12.0,
 84.0,
 644.0,
 650.0,
 432.0,
 292.0,
 650.0,
 650.0,
 0.0,
 256.0,
 276.0,
 276.0,
 160.0,
 26.0,
 350.0,
 159.0,
 8.0,
 159.0,
 535.0,
 159.0,
 159.0,
 570.0,
 341.0,
 0.0,
 59.0,
 0.0,
 264.0,
 50.0,
 53.0,
 46.0,
 154.0,
 522.0,
 522.0,
 349.0,
 232.0,
 154.0,
 264.0,
 17.0,
 12.0,
 61.0,
 61.0,
 130.0,
 194.0,
 72.0,
 309.0,
 36.0,
 36.0,
 430.0,
 430.0,
 537.0,
 430.0,
 309.0,
 309.0,
 57.0,
 31.0,
 430.0,
 36.0,
 45.0,
 2.0,
 13.0,
 51.0,
 265.0,
 32.0,
 193.0,
 392.0,
 232.0,
 78.0,
 361.0,
 398.0,
 277.0,
 123.0,
 277.0,
 276.0,
 147.0,
 147.0,
 163.0,
 276.0,
 276.0,
 147.0,
 655.0,
 68.0,
 0.0,
 243.0,
 0.0,
 0.0,
 243.0,
 68.0,
 0.0,
 13.0,
 36.0,
 243.0,
 13.0,
 242.0,
 262.0,
 33.0,
 264.0,
 262.0,
 13.0,
 262.0,
 264.0,
 301.0,
 0.0,
 10.0,
 21.0,
 13.0,
 0.0,
 52.0,
 13.0,
 341.0,
 0.0,
 0.0,
 0.0,
 301.0,
 0.0,
 21.0,
 243.0,
 21.0,
 532.0,
 21.0,
 13.0,
 0.0,
 186.0,
 297.0,
 31.0,
 186.0,
 66.0,
 186.0,
 297.0,
 186.0,
 166.0,
 341.0,
 173.0,
 341.0,
 173.0,
 341.0,
 278.0,
 324.0,
 540.0,
 138.0,
 441.0,
 32.0,
 63.0,
 155.0,
 323.0,
 259.0,
 242.0,
 44.0,
 338.0,
 146.0,
 190.0,
 338.0,
 527.0,
 349.0,
 349.0,
 173.0,
 430.0,
 349.0,
 0.0,
 284.0,
 12.0,
 12.0,
 12.0,
 12.0,
 282.0,
 12.0,
 12.0,
 200.0,
 200.0,
 10.0,
 171.0,
 0.0,
 17.0,
 265.0,
 193.0,
 137.0,
 56.0,
 338.0,
 56.0,
 338.0,
 56.0,
 78.0,
 32.0,
 536.0,
 309.0,
 341.0,
 5.0,
 32.0,
 252.0,
 19.0,
 154.0,
 651.0,
 26.0,
 72.0,
 72.0,
 301.0,
 26.0,
 72.0,
 241.0,
 536.0,
 3.0,
 67.0,
 327.0,
 135.0,
 3.0,
 135.0,
 310.0,
 93.0,
 579.0,
 579.0,
 119.0,
 362.0,
 138.0,
 1.0,
 1.0,
 578.0,
 578.0,
 328.0,
 209.0,
 5.0,
 60.0,
 285.0,
 284.0,
 80.0,
 301.0,
 284.0,
 323.0,
 34.0,
 173.0,
 173.0,
 301.0,
 173.0,
 10.0,
 173.0,
 7.0,
 2.0,
 288.0,
 63.0,
 221.0,
 326.0,
 148.0,
 57.0,
 39.0,
 27.0,
 344.0,
 456.0,
 456.0,
 126.0,
 26.0,
 615.0,
 112.0,
 148.0,
 57.0,
 148.0,
 148.0,
 102.0,
 148.0,
 57.0,
 148.0,
 327.0,
 19.0,
 148.0,
 20.0,
 353.0,
 57.0,
 148.0,
 148.0,
 19.0,
 148.0,
 57.0,
 13.0,
 11.0,
 148.0,
 31.0,
 301.0,
 536.0,
 301.0,
 49.0,
 48.0,
 10.0,
 84.0,
 10.0,
 522.0,
 525.0,
 43.0,
 45.0,
 4.0,
 522.0,
 10.0,
 84.0,
 8.0,
 531.0,
 301.0,
 80.0,
 168.0,
 80.0,
 264.0,
 332.0,
 264.0,
 263.0,
 11.0,
 60.0,
 613.0,
 31.0,
 531.0,
 1.0,
 10.0,
 1.0,
 10.0,
 16.0,
 21.0,
 286.0,
 16.0,
 61.0,
 16.0,
 61.0,
 577.0,
 0.0,
 0.0,
 578.0,
 578.0,
 577.0,
 166.0,
 264.0,
 51.0,
 166.0,
 166.0,
 264.0,
 51.0,
 166.0,
 76.0,
 85.0,
 642.0,
 87.0,
 85.0,
 85.0,
 642.0,
 253.0,
 85.0,
 642.0,
 134.0,
 112.0,
 392.0,
 74.0,
 523.0,
 74.0,
 74.0,
 59.0,
 523.0,
 5.0,
 54.0,
 547.0,
 347.0,
 5.0,
 5.0,
 276.0,
 5.0,
 5.0,
 246.0,
 273.0,
 278.0,
 0.0,
 478.0,
 273.0,
 192.0,
 273.0,
 226.0,
 145.0,
 301.0,
 159.0,
 6.0,
 5.0,
 523.0,
 193.0,
 127.0,
 278.0,
 277.0,
 148.0,
 50.0,
 56.0,
 56.0,
 148.0,
 148.0,
 0.0,
 539.0,
 0.0,
 432.0,
 0.0,
 536.0,
 0.0,
 17.0,
 432.0,
 56.0,
 166.0,
 31.0,
 0.0,
 432.0,
 16.0,
 43.0,
 32.0,
 119.0,
 165.0,
 30.0,
 30.0,
 165.0,
 579.0,
 93.0,
 33.0,
 150.0,
 150.0,
 326.0,
 39.0,
 262.0,
 33.0,
 529.0,
 200.0,
 532.0,
 39.0,
 538.0,
 23.0,
 173.0,
 10.0,
 173.0,
 16.0,
 16.0,
 535.0,
 669.0,
 650.0,
 68.0,
 650.0,
 52.0,
 233.0,
 230.0,
 43.0,
 265.0,
 271.0,
 68.0,
 66.0,
 182.0,
 68.0,
 269.0,
 0.0,
 577.0,
 208.0,
 11.0,
 13.0,
 13.0,
 11.0,
 532.0,
 6.0,
 13.0,
 11.0,
 138.0,
 11.0,
 11.0,
 10.0,
 13.0,
 475.0,
 473.0,
 473.0,
 339.0,
 39.0,
 169.0,
 127.0,
 26.0,
 473.0,
 473.0,
 362.0,
 473.0,
 473.0,
 456.0,
 272.0,
 298.0,
 344.0,
 21.0,
 0.0,
 456.0,
 23.0,
 635.0,
 635.0,
 635.0,
 635.0,
 635.0,
 13.0,
 635.0,
 635.0,
 263.0,
 56.0,
 562.0,
 196.0,
 16.0,
 128.0,
 128.0,
 321.0,
 181.0,
 321.0,
 255.0,
 181.0,
 257.0,
 68.0,
 68.0,
 221.0,
 221.0,
 176.0,
 130.0,
 84.0,
 84.0,
 239.0,
 59.0,
 1.0,
 243.0,
 1.0,
 0.0,
 166.0,
 302.0,
 302.0,
 531.0,
 176.0,
 246.0,
 19.0,
 263.0,
 532.0,
 532.0,
 532.0,
 532.0,
 338.0,
 11.0,
 349.0,
 5.0,
 349.0,
 60.0,
 235.0,
 337.0,
 192.0,
 338.0,
 123.0,
 1.0,
 146.0,
 146.0,
 209.0,
 427.0,
 392.0,
 173.0,
 50.0,
 392.0,
 26.0,
 392.0,
 392.0,
 26.0,
 26.0,
 392.0,
 50.0,
 108.0,
 159.0,
 681.0,
 49.0,
 247.0,
 20.0,
 0.0,
 2.0,
 0.0,
 44.0,
 1.0,
 472.0,
 397.0,
 11.0,
 39.0,
 665.0,
 10.0,
 321.0,
 321.0,
 250.0,
 235.0,
 10.0,
 319.0,
 192.0,
 69.0,
 61.0,
 362.0,
 649.0,
 60.0,
 60.0,
 576.0,
 191.0,
 188.0,
 221.0,
 0.0,
 33.0,
 57.0,
 39.0,
 33.0,
 532.0,
 33.0,
 532.0,
 6.0,
 33.0,
 532.0,
 325.0,
 57.0,
 39.0,
 33.0,
 645.0,
 67.0,
 70.0,
 208.0,
 0.0,
 340.0,
 141.0,
 73.0,
 73.0,
 0.0,
 0.0,
 0.0,
 73.0,
 0.0,
 73.0,
 262.0,
 191.0,
 85.0,
 547.0,
 547.0,
 531.0,
 532.0,
 530.0,
 0.0,
 172.0,
 301.0,
 532.0,
 17.0,
 172.0,
 11.0,
 9.0,
 26.0,
 4.0,
 58.0,
 70.0,
 272.0,
 272.0,
 272.0,
 272.0,
 303.0,
 0.0,
 21.0,
 243.0,
 10.0,
 0.0,
 138.0,
 532.0,
 184.0,
 132.0,
 136.0,
 176.0,
 200.0,
 385.0,
 379.0,
 325.0,
 570.0,
 337.0,
 49.0,
 32.0,
 158.0,
 310.0,
 159.0,
 11.0,
 319.0,
 19.0,
 341.0,
 5.0,
 10.0,
 10.0,
 5.0,
 10.0,
 5.0,
 5.0,
 5.0,
 10.0,
 5.0,
 5.0,
 10.0,
 10.0,
 5.0,
 10.0,
 217.0,
 25.0,
 170.0,
 212.0,
 538.0,
 11.0,
 159.0,
 278.0,
 69.0,
 532.0,
 50.0,
 13.0,
 13.0,
 33.0,
 662.0,
 25.0,
 25.0,
 25.0,
 284.0,
 473.0,
 22.0,
 481.0,
 119.0,
 63.0,
 43.0,
 317.0,
 2.0,
 12.0,
 72.0,
 11.0,
 57.0,
 57.0,
 34.0,
 57.0,
 145.0,
 189.0,
 70.0,
 191.0,
 300.0,
 8.0,
 300.0,
 300.0,
 8.0,
 300.0,
 0.0,
 0.0,
 0.0,
 472.0,
 26.0,
 362.0,
 362.0,
 474.0,
 301.0,
 362.0,
 341.0,
 474.0,
 362.0,
 58.0,
 58.0,
 58.0,
 109.0,
 26.0,
 11.0,
 263.0,
 315.0,
 315.0,
 11.0,
 263.0,
 216.0,
 149.0,
 264.0,
 631.0,
 10.0,
 533.0,
 10.0,
 10.0,
 533.0,
 10.0,
 10.0,
 10.0,
 301.0,
 533.0,
 50.0,
 301.0,
 325.0,
 43.0,
 263.0,
 0.0,
 136.0,
 25.0,
 65.0,
 194.0,
 154.0,
 327.0,
 ...]

In [97]:
k_final['to_landmark'] = new_column_to_station

In [98]:
k_final.isnull().sum()

ride_id                     0
rideable_type               0
start_time                  0
end_time                    0
from_station_name           0
from_station_id             0
to_station_name             0
end_station_id              0
start_lat                   0
start_lng                   0
end_lat                     0
end_lng                     0
usertype                    0
start_date                  0
end_date                    0
from_dpcapacity      11946646
from_landmark               0
from_city            11946646
to_dpcapacity        11946875
to_landmark                 0
to_city              11946875
dtype: int64

In [99]:
landmarks_and_city = {}
city = stations['city'].values
landmarks = stations['landmark'].values

for i in range(len(ids)):
    landmarks_and_city[f'{landmarks[i]}'] = city[i]
landmarks_and_city

{'30.0': 'Chicago',
 '66.0': 'Chicago',
 '163.0': 'Chicago',
 '164.0': 'Chicago',
 '223.0': 'Chicago',
 '246.0': 'Chicago',
 '139.0': 'Chicago',
 '154.0': 'Chicago',
 '157.0': 'Chicago',
 '160.0': 'Chicago',
 '172.0': 'Chicago',
 '262.0': 'Chicago',
 '34.0': 'Chicago',
 '51.0': 'Chicago',
 '174.0': 'Chicago',
 '282.0': 'Chicago',
 '290.0': 'Chicago',
 '248.0': 'Chicago',
 '17.0': 'Chicago',
 '76.0': 'Chicago',
 '3.0': 'Chicago',
 '124.0': 'Chicago',
 '22.0': 'Chicago',
 '19.0': 'Chicago',
 '20.0': 'Chicago',
 '170.0': 'Chicago',
 '1.0': 'Chicago',
 '2.0': 'Chicago',
 '40.0': 'Chicago',
 '46.0': 'Chicago',
 '50.0': 'Chicago',
 '12.0': 'Chicago',
 '49.0': 'Chicago',
 '9.0': 'Chicago',
 '5.0': 'Chicago',
 '43.0': 'Chicago',
 '64.0': 'Chicago',
 '44.0': 'Chicago',
 '166.0': 'Chicago',
 '39.0': 'Chicago',
 '327.0': 'Chicago',
 '25.0': 'Chicago',
 '31.0': 'Chicago',
 '58.0': 'Chicago',
 '221.0': 'Chicago',
 '106.0': 'Chicago',
 '21.0': 'Chicago',
 '60.0': 'Chicago',
 '37.0': 'Chicago',
 '65.0': 'Chicago',
 '72.0': 'Chicago',
 '148.0': 'Chicago',
 '38.0': 'Chicago',
 '265.0': 'Chicago',
 '138.0': 'Chicago',
 '300.0': 'Chicago',
 '301.0': 'Chicago',
 '156.0': 'Chicago',
 '23.0': 'Chicago',
 '33.0': 'Chicago',
 '42.0': 'Chicago',
 '289.0': 'Chicago',
 '189.0': 'Chicago',
 '155.0': 'Chicago',
 '8.0': 'Chicago',
 '10.0': 'Chicago',
 '196.0': 'Chicago',
 '190.0': 'Chicago',
 '146.0': 'Chicago',
 '29.0': 'Chicago',
 '6.0': 'Chicago',
 '337.0': 'Chicago',
 '13.0': 'Chicago',
 '14.0': 'Chicago',
 '27.0': 'Chicago',
 '28.0': 'Chicago',
 '45.0': 'Chicago',
 '52.0': 'Chicago',
 '53.0': 'Chicago',
 '59.0': 'Chicago',
 '62.0': 'Chicago',
 '67.0': 'Chicago',
 '68.0': 'Chicago',
 '69.0': 'Chicago',
 '70.0': 'Chicago',
 '73.0': 'Chicago',
 '75.0': 'Chicago',
 '398.0': 'Chicago',
 '81.0': 'Chicago',
 '84.0': 'Chicago',
 '89.0': 'Chicago',
 '128.0': 'Chicago',
 '131.0': 'Chicago',
 '132.0': 'Chicago',
 '135.0': 'Chicago',
 '136.0': 'Chicago',
 '140.0': 'Chicago',
 '149.0': 'Chicago',
 '158.0': 'Chicago',
 '162.0': 'Chicago',
 '165.0': 'Chicago',
 '169.0': 'Chicago',
 '171.0': 'Chicago',
 '173.0': 'Chicago',
 '179.0': 'Chicago',
 '191.0': 'Chicago',
 '193.0': 'Chicago',
 '206.0': 'Chicago',
 '212.0': 'Chicago',
 '216.0': 'Chicago',
 '217.0': 'Chicago',
 '220.0': 'Chicago',
 '226.0': 'Chicago',
 '228.0': 'Chicago',
 '229.0': 'Chicago',
 '232.0': 'Chicago',
 '234.0': 'Chicago',
 '243.0': 'Chicago',
 '245.0': 'Chicago',
 '257.0': 'Chicago',
 '268.0': 'Chicago',
 '271.0': 'Chicago',
 '272.0': 'Chicago',
 '275.0': 'Chicago',
 '296.0': 'Chicago',
 '306.0': 'Chicago',
 '310.0': 'Chicago',
 '326.0': 'Chicago',
 '329.0': 'Chicago',
 '331.0': 'Chicago',
 '338.0': 'Chicago',
 '341.0': 'Chicago',
 '344.0': 'Chicago',
 '349.0': 'Chicago',
 '350.0': 'Chicago',
 '408.0': 'Chicago',
 '420.0': 'Chicago',
 '430.0': 'Chicago',
 '142.0': 'Chicago',
 '82.0': 'Chicago',
 '266.0': 'Chicago',
 '194.0': 'Chicago',
 '295.0': 'Chicago',
 '298.0': 'Chicago',
 '56.0': 'Chicago',
 '11.0': 'Chicago',
 '213.0': 'Chicago',
 '339.0': 'Chicago',
 '263.0': 'Chicago',
 '427.0': 'Chicago',
 '36.0': 'Chicago',
 '159.0': 'Chicago',
 '4.0': 'Chicago',
 '90.0': 'Chicago',
 '83.0': 'Chicago',
 '99.0': 'Chicago',
 '91.0': 'Chicago',
 '101.0': 'Chicago',
 '88.0': 'Chicago',
 '98.0': 'Chicago',
 '399.0': 'Chicago',
 '307.0': 'Chicago',
 '308.0': 'Chicago',
 '61.0': 'Chicago',
 '16.0': 'Chicago',
 '264.0': 'Chicago',
 '244.0': 'Chicago',
 '141.0': 'Chicago',
 '134.0': 'Chicago',
 '256.0': 'Chicago',
 '197.0': 'Chicago',
 '180.0': 'Chicago',
 '133.0': 'Chicago',
 '123.0': 'Chicago',
 '242.0': 'Chicago',
 '185.0': 'Chicago',
 '181.0': 'Chicago',
 '192.0': 'Chicago',
 '230.0': 'Chicago',
 '235.0': 'Chicago',
 '143.0': 'Chicago',
 '71.0': 'Chicago',
 '78.0': 'Chicago',
 '130.0': 'Chicago',
 '273.0': 'Chicago',
 '409.0': 'Chicago',
 '316.0': 'Chicago',
 '410.0': 'Chicago',
 '214.0': 'Chicago',
 '92.0': 'Chicago',
 '112.0': 'Chicago',
 '63.0': 'Chicago',
 '168.0': 'Chicago',
 '93.0': 'Chicago',
 '126.0': 'Chicago',
 '87.0': 'Chicago',
 '389.0': 'Chicago',
 '249.0': 'Chicago',
 '361.0': 'Chicago',
 '362.0': 'Chicago',
 '388.0': 'Chicago',
 '269.0': 'Chicago',
 '385.0': 'Chicago',
 '396.0': 'Chicago',
 '104.0': 'Chicago',
 '324.0': 'Chicago',
 '309.0': 'Chicago',
 '323.0': 'Chicago',
 '253.0': 'Chicago',
 '145.0': 'Chicago',
 '259.0': 'Chicago',
 '85.0': 'Chicago',
 '80.0': 'Chicago',
 '414.0': 'Chicago',
 '215.0': 'Chicago',
 '48.0': 'Chicago',
 '346.0': 'Chicago',
 '117.0': 'Chicago',
 '328.0': 'Chicago',
 '86.0': 'Chicago',
 '219.0': 'Chicago',
 '150.0': 'Chicago',
 '304.0': 'Chicago',
 '354.0': 'Chicago',
 '258.0': 'Chicago',
 '434.0': 'Chicago',
 '417.0': 'Chicago',
 '413.0': 'Chicago',
 '97.0': 'Chicago',
 '393.0': 'Chicago',
 '161.0': 'Chicago',
 '32.0': 'Chicago',
 '340.0': 'Chicago',
 '432.0': 'Chicago',
 '7.0': 'Chicago',
 '57.0': 'Chicago',
 '184.0': 'Chicago',
 '182.0': 'Chicago',
 '292.0': 'Chicago',
 '302.0': 'Chicago',
 '317.0': 'Chicago',
 '74.0': 'Chicago',
 '109.0': 'Chicago',
 '108.0': 'Chicago',
 '277.0': 'Chicago',
 '250.0': 'Chicago',
 '252.0': 'Chicago',
 '127.0': 'Chicago',
 '137.0': 'Chicago',
 '200.0': 'Chicago',
 '211.0': 'Chicago',
 '278.0': 'Chicago',
 '325.0': 'Chicago',
 '241.0': 'Chicago',
 '374.0': 'Chicago',
 '186.0': 'Chicago',
 '144.0': 'Chicago',
 '286.0': 'Chicago',
 '288.0': 'Chicago',
 '237.0': 'Chicago',
 '379.0': 'Chicago',
 '147.0': 'Chicago',
 '251.0': 'Chicago',
 '255.0': 'Chicago',
 '315.0': 'Chicago',
 '285.0': 'Chicago',
 '321.0': 'Chicago',
 '294.0': 'Chicago',
 '332.0': 'Chicago',
 '54.0': 'Chicago',
 '397.0': 'Chicago',
 '384.0': 'Chicago',
 '276.0': 'Chicago',
 '392.0': 'Chicago',
 '239.0': 'Chicago',
 '188.0': 'Chicago',
 '365.0': 'Chicago',
 '347.0': 'Chicago',
 '77.0': 'Chicago',
 '176.0': 'Chicago',
 '208.0': 'Chicago',
 '224.0': 'Chicago',
 '233.0': 'Chicago',
 '345.0': 'Chicago',
 '422.0': 'Chicago',
 '303.0': 'Chicago',
 '102.0': 'Chicago',
 '404.0': 'Chicago',
 '209.0': 'Chicago',
 '431.0': 'Chicago',
 '284.0': 'Chicago',
 '297.0': 'Chicago',
 '26.0': 'Chicago',
 '119.0': 'Chicago',
 '353.0': 'Chicago',
 '319.0': 'Chicago',
 '96.0': 'Chicago',
 '210.0': 'Chicago',
 '247.0': 'Chicago',
 '440.0': 'Chicago',
 '541.0': 'Chicago',
 '544.0': 'Chicago',
 '545.0': 'Chicago',
 '548.0': 'Chicago',
 '534.0': 'Chicago',
 '695.0': 'Chicago',
 '496.0': 'Chicago',
 '497.0': 'Chicago',
 '536.0': 'Chicago',
 '547.0': 'Chicago',
 '538.0': 'Chicago',
 '537.0': 'Chicago',
 '543.0': 'Chicago',
 '540.0': 'Chicago',
 '490.0': 'Chicago',
 '535.0': 'Chicago',
 '491.0': 'Chicago',
 '492.0': 'Chicago',
 '542.0': 'Chicago',
 '539.0': 'Chicago',
 '533.0': 'Chicago',
 '532.0': 'Chicago',
 '531.0': 'Chicago',
 '529.0': 'Chicago',
 '530.0': 'Chicago',
 '525.0': 'Chicago',
 '523.0': 'Chicago',
 '522.0': 'Chicago',
 '498.0': 'Chicago',
 '493.0': 'Chicago',
 '561.0': 'Chicago',
 '562.0': 'Chicago',
 '494.0': 'Chicago',
 '495.0': 'Chicago',
 '524.0': 'Chicago',
 '527.0': 'Chicago',
 '528.0': 'Chicago',
 '441.0': 'Chicago',
 '446.0': 'Chicago',
 '442.0': 'Chicago',
 '694.0': 'Chicago',
 '546.0': 'Chicago',
 '660.0': 'Chicago',
 '661.0': 'Chicago',
 '662.0': 'Chicago',
 '663.0': 'Chicago',
 '664.0': 'Chicago',
 '665.0': 'Chicago',
 '666.0': 'Chicago',
 '667.0': 'Chicago',
 '668.0': 'Chicago',
 '669.0': 'Chicago',
 '591.0': 'Chicago',
 '592.0': 'Chicago',
 '593.0': 'Chicago',
 '595.0': 'Chicago',
 '596.0': 'Chicago',
 '597.0': 'Chicago',
 '598.0': 'Chicago',
 '599.0': 'Chicago',
 '499.0': 'Chicago',
 '500.0': 'Chicago',
 '501.0': 'Chicago',
 '502.0': 'Chicago',
 '506.0': 'Chicago',
 '507.0': 'Chicago',
 '443.0': 'Chicago',
 '444.0': 'Chicago',
 '445.0': 'Chicago',
 '448.0': 'Chicago',
 '449.0': 'Chicago',
 '450.0': 'Chicago',
 '451.0': 'Chicago',
 '452.0': 'Chicago',
 '453.0': 'Chicago',
 '454.0': 'Chicago',
 '455.0': 'Chicago',
 '456.0': 'Chicago',
 '470.0': 'Chicago',
 '471.0': 'Chicago',
 '472.0': 'Chicago',
 '473.0': 'Chicago',
 '474.0': 'Chicago',
 '475.0': 'Chicago',
 '476.0': 'Chicago',
 '477.0': 'Chicago',
 '478.0': 'Chicago',
 '479.0': 'Chicago',
 '480.0': 'Chicago',
 '481.0': 'Chicago',
 '482.0': 'Chicago',
 '484.0': 'Chicago',
 '485.0': 'Chicago',
 '486.0': 'Chicago',
 '487.0': 'Chicago',
 '563.0': 'Chicago',
 '680.0': 'Chicago',
 '681.0': 'Chicago',
 '682.0': 'Chicago',
 '683.0': 'Chicago',
 '684.0': 'Chicago',
 '685.0': 'Chicago',
 '686.0': 'Chicago',
 '687.0': 'Chicago',
 '688.0': 'Chicago',
 '689.0': 'Chicago',
 '690.0': 'Chicago',
 '691.0': 'Chicago',
 '692.0': 'Chicago',
 '693.0': 'Chicago',
 '564.0': 'Chicago',
 '565.0': 'Chicago',
 '566.0': 'Chicago',
 '567.0': 'Chicago',
 '568.0': 'Chicago',
 '569.0': 'Chicago',
 '570.0': 'Chicago',
 '571.0': 'Chicago',
 '572.0': 'Chicago',
 '573.0': 'Chicago',
 '574.0': 'Chicago',
 '575.0': 'Chicago',
 '576.0': 'Chicago',
 '577.0': 'Chicago',
 '578.0': 'Chicago',
 '579.0': 'Chicago',
 '580.0': 'Chicago',
 '581.0': 'Chicago',
 '582.0': 'Chicago',
 '583.0': 'Chicago',
 '584.0': 'Chicago',
 '585.0': 'Chicago',
 '611.0': 'Chicago',
 '612.0': 'Chicago',
 '613.0': 'Chicago',
 '614.0': 'Chicago',
 '615.0': 'Chicago',
 '616.0': 'Chicago',
 '617.0': 'Chicago',
 '618.0': 'Chicago',
 '619.0': 'Chicago',
 '620.0': 'Chicago',
 '621.0': 'Chicago',
 '622.0': 'Chicago',
 '623.0': 'Chicago',
 '624.0': 'Chicago',
 '625.0': 'Chicago',
 '626.0': 'Chicago',
 '627.0': 'Chicago',
 '628.0': 'Chicago',
 '629.0': 'Chicago',
 '630.0': 'Chicago',
 '631.0': 'Chicago',
 '632.0': 'Chicago',
 '633.0': 'Chicago',
 '634.0': 'Chicago',
 '635.0': 'Chicago',
 '636.0': 'Chicago',
 '640.0': 'Chicago',
 '641.0': 'Chicago',
 '642.0': 'Chicago',
 '643.0': 'Chicago',
 '644.0': 'Chicago',
 '645.0': 'Chicago',
 '646.0': 'Chicago',
 '647.0': 'Chicago',
 '648.0': 'Chicago',
 '649.0': 'Chicago',
 '650.0': 'Chicago',
 '651.0': 'Chicago',
 '652.0': 'Chicago',
 '653.0': 'Chicago',
 '654.0': 'Chicago',
 '655.0': 'Chicago',
 '0.0': 'Chicago'}

In [100]:
new_column_from_city = []
run_ids_from2 = k_final['from_landmark'].values


for i in range(len(run_ids_from2)):
    try:
        new_column_from_city.append(landmarks_and_city[f'{run_ids_from2[i]}'])
    except KeyError:
        new_column_from_city.append(0.0)
        pass
new_column_from_city

['Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 ...]

In [101]:
set(new_column_from_city)

{'Chicago'}

In [102]:
k_final['from_city'] = new_column_from_city

In [103]:
new_column_to_city = []
run_ids_to3 = k_final['to_landmark'].values


for i in range(len(run_ids_to3)):
    try:
        new_column_to_city.append(landmarks_and_city[f'{run_ids_to3[i]}'])
    except KeyError:
        new_column_to_city.append(0.0)
        pass
new_column_to_city

['Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 'Chicago',
 ...]

In [104]:
set(new_column_to_city)

{'Chicago'}

In [105]:
k_final['to_city'] = new_column_to_city

In [106]:
k_final.isnull().sum()

ride_id                     0
rideable_type               0
start_time                  0
end_time                    0
from_station_name           0
from_station_id             0
to_station_name             0
end_station_id              0
start_lat                   0
start_lng                   0
end_lat                     0
end_lng                     0
usertype                    0
start_date                  0
end_date                    0
from_dpcapacity      11946646
from_landmark               0
from_city                   0
to_dpcapacity        11946875
to_landmark                 0
to_city                     0
dtype: int64

In [107]:
k_final

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,...,end_lng,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city
0,EACB19130B0CDA4A,docked_bike,20:06:59,20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,...,-87.667400,member,2020-01-21,2020-01-21,NaN,112.0,Chicago,NaN,239.0,Chicago
1,8FED874C809DC021,docked_bike,14:22:39,14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,...,-87.664400,member,2020-01-30,2020-01-30,NaN,316.0,Chicago,NaN,321.0,Chicago
2,789F3C21E472CA96,docked_bike,19:29:26,19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,...,-87.653000,member,2020-01-09,2020-01-09,NaN,277.0,Chicago,NaN,69.0,Chicago
3,C9A388DAC6ABF313,docked_bike,16:17:07,16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,...,-87.620600,member,2020-01-06,2020-01-06,NaN,5.0,Chicago,NaN,262.0,Chicago
4,943BC3CBECCFD662,docked_bike,08:37:16,08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,...,-87.634300,member,2020-01-30,2020-01-30,NaN,21.0,Chicago,NaN,264.0,Chicago
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11952925,BC3BFA659C9AB6F1,classic_bike,01:41:29,01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,-87.670668,casual,2022-10-30,2022-10-30,NaN,0.0,Chicago,NaN,0.0,Chicago
11952926,ACD65450291CF95F,classic_bike,01:41:54,01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,-87.670668,casual,2022-10-30,2022-10-30,NaN,0.0,Chicago,NaN,0.0,Chicago
11952927,4AAC03D1438E97CA,classic_bike,09:34:11,10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,-87.638677,...,-87.626761,casual,2022-10-15,2022-10-15,NaN,0.0,Chicago,NaN,0.0,Chicago
11952928,8E6F3F29785E5D40,classic_bike,10:21:34,10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,-87.638677,...,-87.677856,member,2022-10-09,2022-10-09,NaN,0.0,Chicago,NaN,0.0,Chicago
11952929,8D14CBE672431920,docked_bike,13:17:13,13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,-87.636282,...,-87.626761,casual,2022-10-22,2022-10-22,NaN,0.0,Chicago,NaN,0.0,Chicago

In [108]:
k_final.isnull().sum()

ride_id                     0
rideable_type               0
start_time                  0
end_time                    0
from_station_name           0
from_station_id             0
to_station_name             0
end_station_id              0
start_lat                   0
start_lng                   0
end_lat                     0
end_lng                     0
usertype                    0
start_date                  0
end_date                    0
from_dpcapacity      11946646
from_landmark               0
from_city                   0
to_dpcapacity        11946875
to_landmark                 0
to_city                     0
dtype: int64

In [109]:
station_id_and_dpcapacity = {}
station_id = stations['id'].values
dpcapacity = stations['dpcapacity'].values

for i in range(len(ids)):
    station_id_and_dpcapacity[f'{station_id[i]}'] = dpcapacity[i]
station_id_and_dpcapacity

{'5.0': 19,
 '13.0': 19,
 '14.0': 15,
 '15.0': 15,
 '16.0': 15,
 '17.0': 15,
 '19.0': 15,
 '20.0': 15,
 '21.0': 15,
 '22.0': 15,
 '23.0': 15,
 '24.0': 15,
 '25.0': 23,
 '26.0': 23,
 '27.0': 19,
 '28.0': 15,
 '29.0': 15,
 '30.0': 15,
 '31.0': 23,
 '32.0': 19,
 '33.0': 27,
 '34.0': 15,
 '35.0': 35,
 '36.0': 27,
 '37.0': 19,
 '42.0': 15,
 '43.0': 43,
 '44.0': 27,
 '45.0': 15,
 '46.0': 19,
 '47.0': 15,
 '48.0': 27,
 '49.0': 23,
 '50.0': 27,
 '51.0': 31,
 '52.0': 23,
 '53.0': 19,
 '54.0': 19,
 '55.0': 15,
 '56.0': 19,
 '57.0': 15,
 '58.0': 15,
 '59.0': 19,
 '60.0': 19,
 '61.0': 15,
 '62.0': 15,
 '66.0': 19,
 '67.0': 15,
 '68.0': 23,
 '69.0': 19,
 '71.0': 15,
 '72.0': 15,
 '73.0': 19,
 '74.0': 23,
 '75.0': 35,
 '76.0': 11,
 '77.0': 23,
 '80.0': 19,
 '81.0': 47,
 '84.0': 19,
 '85.0': 15,
 '86.0': 15,
 '87.0': 19,
 '88.0': 15,
 '90.0': 35,
 '91.0': 31,
 '92.0': 19,
 '93.0': 15,
 '94.0': 19,
 '97.0': 19,
 '98.0': 15,
 '99.0': 19,
 '100.0': 23,
 '106.0': 27,
 '108.0': 19,
 '109.0': 19,
 '110.0': 23,
 '111.0': 19,
 '112.0': 15,
 '113.0': 15,
 '114.0': 27,
 '115.0': 23,
 '116.0': 15,
 '117.0': 23,
 '118.0': 19,
 '119.0': 19,
 '120.0': 15,
 '121.0': 15,
 '122.0': 15,
 '123.0': 15,
 '124.0': 15,
 '126.0': 15,
 '127.0': 15,
 '128.0': 15,
 '129.0': 15,
 '130.0': 15,
 '131.0': 15,
 '132.0': 15,
 '134.0': 19,
 '135.0': 11,
 '136.0': 15,
 '137.0': 15,
 '138.0': 15,
 '140.0': 19,
 '141.0': 19,
 '143.0': 15,
 '144.0': 15,
 '146.0': 11,
 '147.0': 15,
 '148.0': 11,
 '149.0': 11,
 '150.0': 11,
 '152.0': 15,
 '153.0': 19,
 '154.0': 15,
 '156.0': 15,
 '157.0': 15,
 '158.0': 15,
 '159.0': 11,
 '160.0': 15,
 '162.0': 15,
 '163.0': 15,
 '164.0': 23,
 '165.0': 19,
 '166.0': 15,
 '167.0': 11,
 '168.0': 19,
 '169.0': 15,
 '170.0': 15,
 '171.0': 11,
 '173.0': 15,
 '174.0': 23,
 '175.0': 19,
 '176.0': 19,
 '177.0': 15,
 '178.0': 15,
 '179.0': 15,
 '181.0': 19,
 '183.0': 15,
 '184.0': 19,
 '185.0': 11,
 '186.0': 15,
 '188.0': 15,
 '190.0': 15,
 '191.0': 23,
 '192.0': 27,
 '193.0': 15,
 '194.0': 11,
 '195.0': 23,
 '196.0': 19,
 '197.0': 19,
 '198.0': 19,
 '199.0': 15,
 '200.0': 11,
 '201.0': 15,
 '202.0': 15,
 '203.0': 15,
 '204.0': 15,
 '205.0': 15,
 '206.0': 15,
 '207.0': 15,
 '208.0': 15,
 '209.0': 11,
 '210.0': 19,
 '211.0': 19,
 '212.0': 19,
 '213.0': 11,
 '214.0': 15,
 '215.0': 15,
 '216.0': 15,
 '217.0': 15,
 '218.0': 11,
 '219.0': 11,
 '220.0': 19,
 '222.0': 19,
 '223.0': 15,
 '224.0': 19,
 '225.0': 15,
 '226.0': 15,
 '227.0': 15,
 '228.0': 11,
 '229.0': 19,
 '230.0': 19,
 '231.0': 15,
 '232.0': 15,
 '233.0': 15,
 '234.0': 19,
 '236.0': 15,
 '237.0': 15,
 '238.0': 15,
 '239.0': 15,
 '240.0': 11,
 '241.0': 15,
 '242.0': 15,
 '243.0': 15,
 '244.0': 19,
 '245.0': 15,
 '246.0': 11,
 '247.0': 15,
 '248.0': 15,
 '249.0': 15,
 '250.0': 19,
 '251.0': 15,
 '252.0': 15,
 '253.0': 15,
 '254.0': 15,
 '255.0': 19,
 '256.0': 15,
 '257.0': 15,
 '258.0': 19,
 '259.0': 15,
 '260.0': 19,
 '261.0': 15,
 '262.0': 11,
 '263.0': 11,
 '264.0': 19,
 '265.0': 15,
 '267.0': 15,
 '268.0': 15,
 '271.0': 11,
 '272.0': 11,
 '273.0': 15,
 '274.0': 15,
 '275.0': 15,
 '276.0': 11,
 '277.0': 15,
 '278.0': 15,
 '279.0': 15,
 '280.0': 11,
 '281.0': 15,
 '282.0': 15,
 '283.0': 23,
 '284.0': 23,
 '285.0': 15,
 '286.0': 15,
 '287.0': 23,
 '288.0': 11,
 '289.0': 19,
 '290.0': 15,
 '291.0': 19,
 '292.0': 11,
 '293.0': 19,
 '294.0': 15,
 '295.0': 15,
 '296.0': 15,
 '297.0': 15,
 '298.0': 15,
 '299.0': 15,
 '300.0': 15,
 '301.0': 19,
 '302.0': 19,
 '303.0': 15,
 '304.0': 15,
 '305.0': 15,
 '306.0': 15,
 '307.0': 15,
 '308.0': 11,
 '309.0': 11,
 '310.0': 11,
 '311.0': 15,
 '312.0': 15,
 '313.0': 19,
 '314.0': 15,
 '315.0': 11,
 '316.0': 19,
 '317.0': 15,
 '318.0': 15,
 '319.0': 15,
 '320.0': 15,
 '321.0': 19,
 '322.0': 15,
 '323.0': 15,
 '324.0': 15,
 '325.0': 15,
 '326.0': 11,
 '327.0': 19,
 '328.0': 15,
 '329.0': 15,
 '330.0': 19,
 '331.0': 19,
 '332.0': 15,
 '333.0': 15,
 '334.0': 19,
 '335.0': 15,
 '336.0': 15,
 '337.0': 19,
 '338.0': 15,
 '339.0': 11,
 '340.0': 15,
 '341.0': 19,
 '342.0': 15,
 '343.0': 15,
 '344.0': 15,
 '345.0': 15,
 '346.0': 15,
 '347.0': 15,
 '348.0': 15,
 '349.0': 15,
 '350.0': 15,
 '351.0': 15,
 '2.0': 35,
 '3.0': 31,
 '4.0': 23,
 '6.0': 31,
 '7.0': 19,
 '9.0': 19,
 '11.0': 11,
 '12.0': 15,
 '18.0': 19,
 '38.0': 27,
 '39.0': 23,
 '40.0': 15,
 '41.0': 19,
 '89.0': 31,
 '95.0': 15,
 '96.0': 23,
 '101.0': 23,
 '102.0': 11,
 '103.0': 15,
 '107.0': 23,
 '125.0': 15,
 '133.0': 27,
 '142.0': 19,
 '145.0': 19,
 '161.0': 23,
 '172.0': 11,
 '180.0': 15,
 '182.0': 23,
 '270.0': 15,
 '352.0': 15,
 '353.0': 15,
 '354.0': 15,
 '355.0': 19,
 '356.0': 11,
 '359.0': 19,
 '364.0': 15,
 '365.0': 15,
 '366.0': 15,
 '367.0': 15,
 '368.0': 19,
 '369.0': 11,
 '370.0': 15,
 '372.0': 19,
 '373.0': 15,
 '374.0': 15,
 '375.0': 15,
 '376.0': 35,
 '377.0': 19,
 '378.0': 15,
 '381.0': 15,
 '382.0': 19,
 '383.0': 23,
 '384.0': 15,
 '385.0': 15,
 '386.0': 15,
 '388.0': 15,
 '390.0': 15,
 '391.0': 15,
 '392.0': 15,
 '393.0': 15,
 '395.0': 15,
 '396.0': 11,
 '397.0': 11,
 '398.0': 19,
 '399.0': 11,
 '400.0': 19,
 '401.0': 11,
 '402.0': 15,
 '403.0': 15,
 '406.0': 19,
 '407.0': 19,
 '408.0': 15,
 '409.0': 15,
 '410.0': 19,
 '411.0': 11,
 '412.0': 19,
 '413.0': 15,
 '414.0': 15,
 '415.0': 19,
 '416.0': 15,
 '417.0': 19,
 '418.0': 11,
 '419.0': 15,
 '420.0': 19,
 '421.0': 15,
 '422.0': 14,
 '423.0': 19,
 '424.0': 27,
 '425.0': 15,
 '426.0': 19,
 '427.0': 19,
 '428.0': 15,
 '429.0': 15,
 '430.0': 15,
 '431.0': 15,
 '432.0': 15,
 '433.0': 15,
 '434.0': 19,
 '435.0': 15,
 '436.0': 15,
 '437.0': 19,
 '438.0': 19,
 '439.0': 15,
 '440.0': 15,
 '441.0': 15,
 '442.0': 15,
 '443.0': 15,
 '444.0': 19,
 '445.0': 19,
 '446.0': 15,
 '447.0': 15,
 '448.0': 15,
 '449.0': 15,
 '450.0': 15,
 '451.0': 15,
 '452.0': 15,
 '453.0': 15,
 '454.0': 15,
 '455.0': 15,
 '456.0': 15,
 '457.0': 19,
 '458.0': 19,
 '459.0': 19,
 '460.0': 15,
 '461.0': 15,
 '462.0': 15,
 '463.0': 19,
 '464.0': 15,
 '465.0': 23,
 '466.0': 15,
 '467.0': 15,
 '468.0': 15,
 '469.0': 15,
 '470.0': 15,
 '471.0': 15,
 '472.0': 15,
 '474.0': 15,
 '475.0': 15,
 '476.0': 15,
 '477.0': 11,
 '478.0': 15,
 '479.0': 11,
 '480.0': 15,
 '481.0': 15,
 '482.0': 15,
 '483.0': 19,
 '484.0': 15,
 '485.0': 15,
 '486.0': 15,
 '487.0': 19,
 '488.0': 15,
 '489.0': 23,
 '490.0': 15,
 '491.0': 15,
 '492.0': 15,
 '493.0': 15,
 '494.0': 15,
 '495.0': 15,
 '496.0': 19,
 '497.0': 23,
 '498.0': 19,
 '499.0': 15,
 '500.0': 15,
 '501.0': 15,
 '502.0': 19,
 '503.0': 15,
 '504.0': 15,
 '505.0': 15,
 '506.0': 15,
 '507.0': 19,
 '508.0': 15,
 '509.0': 15,
 '510.0': 15,
 '511.0': 15,
 '555.0': 11,
 '563.0': 15,
 '565.0': 11,
 '566.0': 11,
 '558.0': 11,
 '552.0': 11,
 '547.0': 11,
 '532.0': 15,
 '541.0': 15,
 '542.0': 15,
 '533.0': 15,
 '538.0': 15,
 '529.0': 15,
 '539.0': 15,
 '394.0': 15,
 '518.0': 15,
 '554.0': 11,
 '561.0': 11,
 '557.0': 11,
 '546.0': 11,
 '553.0': 11,
 '570.0': 11,
 '593.0': 11,
 '551.0': 11,
 '537.0': 15,
 '545.0': 15,
 '536.0': 15,
 '543.0': 15,
 '530.0': 15,
 '540.0': 15,
 '549.0': 11,
 '560.0': 11,
 '544.0': 15,
 '567.0': 11,
 '548.0': 11,
 '568.0': 11,
 '535.0': 15,
 '528.0': 15,
 '534.0': 15,
 '562.0': 11,
 '564.0': 11,
 '559.0': 11,
 '572.0': 11,
 '556.0': 11,
 '594.0': 15,
 '569.0': 15,
 '596.0': 15,
 '601.0': 15,
 '597.0': 15,
 '600.0': 15,
 '607.0': 11,
 '617.0': 19,
 '614.0': 15,
 '609.0': 15,
 '608.0': 11,
 '618.0': 19,
 '615.0': 15,
 '610.0': 19,
 '616.0': 19,
 '611.0': 19,
 '613.0': 11,
 '524.0': 11,
 '522.0': 15,
 '550.0': 11,
 '531.0': 15,
 '602.0': 15,
 '578.0': 11,
 '603.0': 15,
 '517.0': 15,
 '581.0': 15,
 '575.0': 11,
 '585.0': 11,
 '523.0': 15,
 '584.0': 15,
 '598.0': 15,
 '580.0': 15,
 '606.0': 19,
 '525.0': 15,
 '520.0': 23,
 '576.0': 15,
 '619.0': 15,
 '590.0': 15,
 '591.0': 23,
 '592.0': 15,
 '589.0': 15,
 '586.0': 11,
 '526.0': 15,
 '620.0': 15,
 '515.0': 23,
 '579.0': 11,
 '582.0': 11,
 '514.0': 15,
 '612.0': 15,
 '604.0': 15,
 '588.0': 11,
 '573.0': 15,
 '583.0': 11,
 '577.0': 11,
 '605.0': 15,
 '599.0': 15,
 '571.0': 11,
 '574.0': 11,
 '587.0': 11,
 '595.0': 15,
 '405.0': 15,
 '527.0': 19,
 '519.0': 11,
 '622.0': 0,
 '623.0': 23,
 '624.0': 16,
 '625.0': 15,
 '626.0': 19}

In [110]:
new_column_dpcapacity_from = []
run_ids_to4 = k_final['from_station_id'].values


for i in range(len(run_ids_to4)):
    try:
        new_column_dpcapacity_from.append(station_id_and_dpcapacity[f'{run_ids_to4[i]}'])
    except KeyError:
        new_column_dpcapacity_from.append(0)
        pass
new_column_dpcapacity_from

[15,
 19,
 15,
 31,
 19,
 19,
 23,
 23,
 19,
 27,
 23,
 19,
 31,
 31,
 15,
 27,
 19,
 27,
 15,
 27,
 11,
 27,
 19,
 15,
 23,
 27,
 15,
 27,
 23,
 27,
 15,
 19,
 0,
 19,
 15,
 15,
 15,
 15,
 27,
 19,
 11,
 19,
 19,
 15,
 19,
 19,
 15,
 19,
 19,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 47,
 23,
 23,
 23,
 11,
 23,
 19,
 19,
 15,
 15,
 35,
 23,
 19,
 23,
 23,
 15,
 23,
 19,
 15,
 19,
 15,
 15,
 15,
 43,
 15,
 15,
 19,
 15,
 23,
 23,
 15,
 15,
 19,
 15,
 15,
 19,
 15,
 19,
 15,
 15,
 19,
 19,
 19,
 43,
 31,
 19,
 31,
 15,
 15,
 15,
 15,
 15,
 19,
 19,
 15,
 19,
 43,
 19,
 43,
 23,
 31,
 0,
 15,
 19,
 15,
 0,
 15,
 0,
 15,
 15,
 15,
 15,
 19,
 15,
 15,
 11,
 0,
 19,
 19,
 15,
 15,
 15,
 27,
 27,
 31,
 27,
 19,
 15,
 27,
 15,
 15,
 15,
 15,
 11,
 23,
 15,
 23,
 15,
 11,
 23,
 19,
 27,
 31,
 47,
 19,
 15,
 0,
 15,
 19,
 19,
 19,
 15,
 0,
 19,
 19,
 15,
 15,
 23,
 47,
 47,
 23,
 23,
 23,
 19,
 19,
 0,
 0,
 27,
 15,
 27,
 27,
 23,
 15,
 15,
 27,
 15,
 15,
 11,
 27,
 23,
 15,
 15,
 15,
 15,
 15,
 19,
 15,
 15,
 23,
 15,
 15,
 19,
 23,
 23,
 15,
 23,
 19,
 19,
 15,
 15,
 19,
 27,
 15,
 15,
 27,
 27,
 15,
 27,
 15,
 15,
 23,
 15,
 31,
 15,
 15,
 15,
 23,
 23,
 15,
 19,
 19,
 19,
 15,
 23,
 19,
 23,
 31,
 23,
 23,
 15,
 23,
 15,
 15,
 23,
 23,
 19,
 15,
 23,
 15,
 19,
 15,
 15,
 15,
 19,
 23,
 27,
 15,
 15,
 15,
 0,
 15,
 15,
 11,
 19,
 19,
 27,
 19,
 19,
 19,
 0,
 23,
 19,
 15,
 19,
 19,
 19,
 27,
 23,
 0,
 23,
 23,
 27,
 19,
 15,
 15,
 15,
 15,
 19,
 15,
 15,
 15,
 19,
 15,
 15,
 0,
 0,
 15,
 15,
 15,
 0,
 15,
 19,
 0,
 15,
 15,
 19,
 15,
 15,
 19,
 15,
 19,
 19,
 27,
 15,
 23,
 15,
 23,
 15,
 0,
 19,
 0,
 0,
 19,
 19,
 19,
 19,
 0,
 19,
 31,
 23,
 0,
 31,
 0,
 15,
 23,
 19,
 0,
 31,
 19,
 15,
 15,
 16,
 15,
 15,
 15,
 15,
 15,
 19,
 19,
 23,
 19,
 23,
 19,
 15,
 15,
 27,
 15,
 23,
 15,
 15,
 19,
 15,
 19,
 15,
 23,
 15,
 15,
 19,
 15,
 35,
 15,
 23,
 15,
 19,
 23,
 31,
 23,
 15,
 19,
 15,
 15,
 15,
 15,
 19,
 15,
 15,
 0,
 0,
 31,
 23,
 19,
 15,
 15,
 15,
 23,
 15,
 23,
 15,
 15,
 15,
 31,
 19,
 23,
 19,
 15,
 15,
 19,
 27,
 15,
 15,
 15,
 15,
 27,
 19,
 15,
 23,
 27,
 19,
 19,
 15,
 27,
 15,
 23,
 19,
 15,
 15,
 15,
 15,
 15,
 23,
 43,
 19,
 15,
 15,
 27,
 15,
 15,
 19,
 23,
 23,
 23,
 15,
 23,
 15,
 19,
 31,
 31,
 19,
 31,
 19,
 31,
 23,
 27,
 15,
 19,
 11,
 15,
 23,
 15,
 19,
 19,
 47,
 19,
 19,
 15,
 15,
 15,
 11,
 23,
 15,
 15,
 23,
 15,
 23,
 15,
 23,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 23,
 15,
 23,
 15,
 27,
 23,
 19,
 15,
 19,
 23,
 23,
 19,
 31,
 15,
 19,
 23,
 31,
 23,
 11,
 23,
 23,
 31,
 23,
 19,
 31,
 35,
 15,
 31,
 15,
 31,
 23,
 15,
 23,
 27,
 43,
 19,
 15,
 31,
 35,
 31,
 43,
 31,
 43,
 23,
 11,
 11,
 23,
 11,
 19,
 11,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 23,
 15,
 15,
 15,
 23,
 15,
 19,
 19,
 15,
 19,
 19,
 15,
 19,
 19,
 19,
 15,
 19,
 23,
 15,
 15,
 15,
 31,
 19,
 19,
 15,
 47,
 15,
 31,
 15,
 47,
 15,
 15,
 47,
 15,
 15,
 15,
 15,
 15,
 15,
 19,
 15,
 19,
 19,
 15,
 15,
 15,
 31,
 19,
 19,
 15,
 15,
 15,
 15,
 23,
 27,
 23,
 15,
 19,
 27,
 27,
 15,
 0,
 15,
 0,
 15,
 0,
 15,
 19,
 0,
 15,
 15,
 47,
 15,
 0,
 23,
 15,
 15,
 19,
 19,
 15,
 15,
 19,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 19,
 19,
 15,
 23,
 19,
 27,
 47,
 15,
 31,
 19,
 31,
 15,
 23,
 19,
 15,
 15,
 15,
 15,
 23,
 19,
 19,
 23,
 11,
 19,
 15,
 19,
 19,
 15,
 15,
 15,
 15,
 15,
 23,
 27,
 27,
 23,
 23,
 27,
 27,
 23,
 35,
 23,
 31,
 23,
 27,
 11,
 15,
 15,
 19,
 15,
 31,
 15,
 0,
 15,
 19,
 11,
 19,
 15,
 19,
 19,
 19,
 19,
 19,
 15,
 19,
 19,
 15,
 15,
 15,
 15,
 15,
 19,
 15,
 15,
 23,
 23,
 15,
 27,
 23,
 15,
 11,
 19,
 19,
 15,
 19,
 19,
 0,
 15,
 15,
 19,
 19,
 15,
 15,
 19,
 11,
 19,
 19,
 19,
 15,
 19,
 15,
 15,
 19,
 19,
 19,
 23,
 19,
 35,
 27,
 19,
 19,
 19,
 19,
 19,
 23,
 15,
 23,
 15,
 15,
 15,
 15,
 19,
 19,
 19,
 23,
 15,
 15,
 19,
 11,
 15,
 15,
 0,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 0,
 15,
 23,
 15,
 15,
 15,
 15,
 19,
 15,
 19,
 19,
 15,
 15,
 15,
 23,
 15,
 19,
 23,
 15,
 15,
 19,
 15,
 23,
 15,
 15,
 15,
 15,
 19,
 15,
 15,
 15,
 15,
 19,
 15,
 15,
 23,
 19,
 19,
 31,
 27,
 19,
 27,
 19,
 27,
 23,
 19,
 11,
 19,
 19,
 23,
 11,
 23,
 23,
 19,
 15,
 23,
 19,
 15,
 15,
 19,
 19,
 19,
 15,
 19,
 15,
 19,
 15,
 19,
 19,
 23,
 23,
 31,
 19,
 23,
 23,
 27,
 19,
 15,
 23,
 47,
 15,
 11,
 27,
 15,
 19,
 19,
 19,
 19,
 19,
 23,
 19,
 0,
 0,
 0,
 31,
 27,
 23,
 15,
 27,
 15,
 0,
 27,
 15,
 15,
 23,
 19,
 15,
 0,
 19,
 23,
 31,
 23,
 15,
 19,
 31,
 27,
 23,
 31,
 31,
 23,
 31,
 23,
 23,
 31,
 31,
 23,
 23,
 31,
 31,
 23,
 31,
 15,
 15,
 15,
 15,
 23,
 27,
 0,
 23,
 15,
 15,
 27,
 19,
 19,
 23,
 19,
 19,
 19,
 19,
 15,
 19,
 23,
 15,
 19,
 11,
 27,
 11,
 19,
 23,
 23,
 23,
 15,
 15,
 19,
 15,
 19,
 19,
 15,
 19,
 35,
 11,
 35,
 35,
 11,
 43,
 15,
 15,
 15,
 19,
 15,
 15,
 15,
 19,
 23,
 15,
 23,
 19,
 15,
 19,
 19,
 19,
 15,
 15,
 43,
 27,
 15,
 15,
 15,
 23,
 11,
 11,
 15,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 19,
 23,
 23,
 23,
 15,
 31,
 19,
 15,
 15,
 19,
 11,
 15,
 15,
 15,
 ...]

In [111]:
stations

        id  dpcapacity  landmark      city
0      5.0          19      30.0   Chicago
1     13.0          19      66.0   Chicago
2     14.0          15     163.0   Chicago
3     15.0          15     164.0   Chicago
4     16.0          15     223.0   Chicago
..     ...         ...       ...       ...
581  622.0           0       0.0   Chicago
582  623.0          23       0.0   Chicago
583  624.0          16       0.0   Chicago
584  625.0          15       0.0  Evanston
585  626.0          19       0.0   Chicago

[586 rows x 4 columns]

In [112]:
# Checking we added actual values instead of just 0.0
max(new_column_dpcapacity_from)

47

In [113]:
k_final['from_dpcapacity'] = new_column_dpcapacity_from

In [114]:
k_final.isnull().sum()

ride_id                     0
rideable_type               0
start_time                  0
end_time                    0
from_station_name           0
from_station_id             0
to_station_name             0
end_station_id              0
start_lat                   0
start_lng                   0
end_lat                     0
end_lng                     0
usertype                    0
start_date                  0
end_date                    0
from_dpcapacity             0
from_landmark               0
from_city                   0
to_dpcapacity        11946875
to_landmark                 0
to_city                     0
dtype: int64

In [115]:
new_column_dpcapacity_to = []
run_ids_to5 = k_final['end_station_id'].values


for i in range(len(run_ids_to4)):
    try:
        new_column_dpcapacity_to.append(station_id_and_dpcapacity[f'{run_ids_to5[i]}'])
    except KeyError:
        new_column_dpcapacity_to.append(0)
        pass
new_column_dpcapacity_to

[11,
 15,
 23,
 15,
 19,
 23,
 19,
 19,
 23,
 23,
 0,
 31,
 19,
 19,
 15,
 15,
 27,
 15,
 27,
 19,
 43,
 43,
 27,
 11,
 43,
 23,
 15,
 19,
 15,
 19,
 0,
 15,
 19,
 15,
 15,
 15,
 27,
 15,
 15,
 19,
 15,
 19,
 19,
 19,
 19,
 15,
 15,
 19,
 19,
 19,
 15,
 15,
 15,
 15,
 15,
 19,
 47,
 15,
 19,
 23,
 15,
 23,
 15,
 19,
 15,
 19,
 19,
 19,
 15,
 19,
 15,
 15,
 23,
 15,
 15,
 15,
 19,
 15,
 15,
 15,
 19,
 15,
 15,
 27,
 15,
 15,
 15,
 23,
 15,
 15,
 19,
 19,
 15,
 19,
 15,
 19,
 19,
 27,
 19,
 19,
 23,
 43,
 19,
 43,
 15,
 15,
 15,
 19,
 15,
 15,
 15,
 19,
 15,
 31,
 11,
 0,
 0,
 0,
 27,
 0,
 15,
 0,
 15,
 0,
 15,
 15,
 0,
 27,
 19,
 15,
 19,
 19,
 0,
 11,
 15,
 15,
 15,
 15,
 15,
 19,
 31,
 27,
 23,
 19,
 19,
 15,
 19,
 19,
 19,
 15,
 15,
 31,
 15,
 23,
 31,
 15,
 27,
 15,
 23,
 27,
 27,
 15,
 19,
 23,
 19,
 15,
 19,
 23,
 19,
 15,
 15,
 19,
 15,
 19,
 47,
 23,
 23,
 47,
 47,
 47,
 31,
 0,
 19,
 19,
 19,
 27,
 31,
 19,
 27,
 15,
 23,
 15,
 15,
 19,
 11,
 19,
 19,
 15,
 23,
 23,
 23,
 15,
 19,
 15,
 23,
 15,
 15,
 15,
 19,
 15,
 15,
 19,
 15,
 19,
 15,
 19,
 23,
 15,
 15,
 27,
 27,
 0,
 19,
 27,
 15,
 27,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 19,
 15,
 15,
 15,
 15,
 15,
 15,
 19,
 35,
 19,
 23,
 19,
 19,
 15,
 23,
 0,
 15,
 15,
 19,
 15,
 15,
 19,
 15,
 23,
 23,
 19,
 15,
 15,
 19,
 23,
 27,
 19,
 19,
 15,
 15,
 15,
 19,
 19,
 19,
 19,
 19,
 15,
 19,
 19,
 19,
 23,
 19,
 19,
 19,
 23,
 27,
 23,
 23,
 23,
 23,
 15,
 15,
 15,
 19,
 15,
 15,
 15,
 19,
 15,
 15,
 19,
 19,
 15,
 15,
 15,
 19,
 15,
 15,
 0,
 15,
 0,
 0,
 15,
 15,
 0,
 23,
 19,
 15,
 23,
 19,
 15,
 19,
 19,
 15,
 23,
 15,
 19,
 23,
 0,
 31,
 19,
 23,
 0,
 19,
 23,
 23,
 0,
 0,
 0,
 23,
 0,
 19,
 15,
 19,
 27,
 19,
 23,
 0,
 15,
 15,
 19,
 15,
 19,
 15,
 15,
 15,
 15,
 23,
 19,
 23,
 19,
 23,
 15,
 15,
 31,
 35,
 15,
 23,
 11,
 15,
 15,
 15,
 19,
 19,
 15,
 19,
 15,
 15,
 15,
 19,
 19,
 19,
 19,
 19,
 0,
 15,
 27,
 27,
 27,
 27,
 15,
 27,
 27,
 19,
 19,
 31,
 15,
 0,
 23,
 23,
 15,
 15,
 23,
 15,
 23,
 15,
 23,
 19,
 23,
 19,
 19,
 23,
 31,
 23,
 15,
 27,
 15,
 19,
 15,
 15,
 15,
 23,
 15,
 15,
 15,
 19,
 27,
 23,
 15,
 15,
 27,
 15,
 19,
 15,
 15,
 15,
 15,
 15,
 35,
 43,
 43,
 15,
 15,
 15,
 15,
 31,
 15,
 15,
 15,
 15,
 23,
 15,
 15,
 23,
 19,
 19,
 23,
 19,
 31,
 19,
 15,
 27,
 11,
 11,
 15,
 15,
 15,
 23,
 19,
 19,
 19,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 23,
 15,
 15,
 15,
 15,
 23,
 15,
 15,
 27,
 15,
 19,
 15,
 23,
 15,
 15,
 27,
 15,
 23,
 23,
 27,
 15,
 19,
 23,
 19,
 23,
 23,
 19,
 31,
 15,
 31,
 23,
 11,
 23,
 23,
 15,
 23,
 31,
 15,
 35,
 19,
 23,
 15,
 15,
 15,
 19,
 15,
 19,
 23,
 27,
 15,
 15,
 19,
 19,
 43,
 31,
 43,
 31,
 19,
 19,
 11,
 19,
 19,
 19,
 19,
 15,
 0,
 0,
 15,
 15,
 15,
 15,
 19,
 23,
 15,
 15,
 19,
 23,
 15,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 15,
 19,
 19,
 15,
 15,
 15,
 19,
 15,
 19,
 19,
 15,
 15,
 31,
 19,
 27,
 15,
 31,
 31,
 15,
 31,
 31,
 15,
 15,
 15,
 0,
 19,
 15,
 15,
 15,
 15,
 19,
 23,
 19,
 15,
 31,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 23,
 23,
 15,
 15,
 0,
 23,
 0,
 15,
 0,
 19,
 0,
 23,
 15,
 23,
 15,
 19,
 0,
 15,
 19,
 23,
 23,
 15,
 15,
 19,
 19,
 15,
 15,
 15,
 19,
 15,
 15,
 15,
 19,
 15,
 19,
 19,
 19,
 27,
 19,
 23,
 47,
 19,
 31,
 19,
 19,
 19,
 23,
 23,
 15,
 15,
 15,
 19,
 19,
 15,
 23,
 23,
 15,
 15,
 19,
 19,
 15,
 19,
 15,
 15,
 15,
 27,
 23,
 23,
 27,
 27,
 15,
 23,
 27,
 35,
 27,
 27,
 31,
 23,
 19,
 11,
 11,
 11,
 19,
 15,
 15,
 15,
 11,
 11,
 15,
 11,
 11,
 15,
 23,
 15,
 19,
 19,
 15,
 15,
 47,
 15,
 15,
 15,
 15,
 15,
 23,
 15,
 15,
 23,
 23,
 15,
 19,
 19,
 15,
 15,
 15,
 19,
 15,
 11,
 19,
 15,
 15,
 15,
 15,
 15,
 19,
 15,
 15,
 15,
 11,
 15,
 43,
 15,
 43,
 23,
 15,
 19,
 19,
 19,
 19,
 15,
 27,
 23,
 27,
 27,
 27,
 27,
 15,
 27,
 19,
 31,
 19,
 15,
 15,
 19,
 15,
 15,
 19,
 43,
 19,
 19,
 15,
 19,
 15,
 19,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 19,
 19,
 23,
 15,
 19,
 0,
 27,
 0,
 19,
 43,
 19,
 15,
 27,
 19,
 19,
 31,
 15,
 15,
 15,
 15,
 31,
 15,
 15,
 23,
 19,
 15,
 15,
 15,
 15,
 19,
 15,
 19,
 15,
 16,
 19,
 23,
 19,
 19,
 27,
 19,
 27,
 15,
 19,
 27,
 15,
 23,
 19,
 19,
 15,
 23,
 19,
 15,
 11,
 23,
 15,
 19,
 19,
 0,
 0,
 0,
 19,
 0,
 19,
 15,
 15,
 19,
 27,
 27,
 19,
 27,
 23,
 0,
 15,
 23,
 27,
 23,
 15,
 27,
 27,
 15,
 15,
 19,
 19,
 23,
 23,
 23,
 23,
 19,
 0,
 19,
 15,
 31,
 0,
 35,
 27,
 11,
 15,
 15,
 19,
 19,
 15,
 15,
 15,
 15,
 19,
 23,
 23,
 19,
 19,
 19,
 27,
 15,
 27,
 23,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 11,
 15,
 15,
 15,
 23,
 27,
 19,
 15,
 23,
 27,
 15,
 23,
 23,
 19,
 15,
 15,
 15,
 15,
 15,
 11,
 35,
 19,
 15,
 11,
 23,
 11,
 27,
 27,
 15,
 27,
 23,
 23,
 23,
 23,
 19,
 19,
 19,
 15,
 11,
 35,
 11,
 11,
 35,
 11,
 15,
 15,
 15,
 19,
 15,
 15,
 15,
 15,
 23,
 15,
 23,
 15,
 15,
 19,
 19,
 19,
 15,
 15,
 27,
 23,
 19,
 19,
 27,
 23,
 11,
 15,
 19,
 15,
 31,
 15,
 31,
 31,
 15,
 31,
 31,
 31,
 23,
 15,
 15,
 23,
 15,
 23,
 23,
 15,
 15,
 15,
 19,
 15,
 15,
 15,
 ...]

In [116]:
max(new_column_dpcapacity_to)

47

In [117]:
k_final['to_dpcapacity'] = new_column_dpcapacity_to

In [118]:
k_final.isnull().sum()

ride_id              0
rideable_type        0
start_time           0
end_time             0
from_station_name    0
from_station_id      0
to_station_name      0
end_station_id       0
start_lat            0
start_lng            0
end_lat              0
end_lng              0
usertype             0
start_date           0
end_date             0
from_dpcapacity      0
from_landmark        0
from_city            0
to_dpcapacity        0
to_landmark          0
to_city              0
dtype: int64

In [119]:
# making sure our values are different
new_column_dpcapacity_to == new_column_dpcapacity_from

False

In [120]:
k_final

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,...,end_lng,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city
0,EACB19130B0CDA4A,docked_bike,20:06:59,20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,...,-87.667400,member,2020-01-21,2020-01-21,15,112.0,Chicago,11,239.0,Chicago
1,8FED874C809DC021,docked_bike,14:22:39,14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,...,-87.664400,member,2020-01-30,2020-01-30,19,316.0,Chicago,15,321.0,Chicago
2,789F3C21E472CA96,docked_bike,19:29:26,19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,...,-87.653000,member,2020-01-09,2020-01-09,15,277.0,Chicago,23,69.0,Chicago
3,C9A388DAC6ABF313,docked_bike,16:17:07,16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,...,-87.620600,member,2020-01-06,2020-01-06,31,5.0,Chicago,15,262.0,Chicago
4,943BC3CBECCFD662,docked_bike,08:37:16,08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,...,-87.634300,member,2020-01-30,2020-01-30,19,21.0,Chicago,19,264.0,Chicago
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11952925,BC3BFA659C9AB6F1,classic_bike,01:41:29,01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,-87.670668,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago
11952926,ACD65450291CF95F,classic_bike,01:41:54,01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,-87.670668,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago
11952927,4AAC03D1438E97CA,classic_bike,09:34:11,10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,-87.638677,...,-87.626761,casual,2022-10-15,2022-10-15,0,0.0,Chicago,0,0.0,Chicago
11952928,8E6F3F29785E5D40,classic_bike,10:21:34,10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,-87.638677,...,-87.677856,member,2022-10-09,2022-10-09,0,0.0,Chicago,0,0.0,Chicago
11952929,8D14CBE672431920,docked_bike,13:17:13,13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,-87.636282,...,-87.626761,casual,2022-10-22,2022-10-22,0,0.0,Chicago,0,0.0,Chicago

In [121]:
# need to add a trip_duration, take into account overnight/ date changes when trying to figure out time difference between
# start of trip and end of trip, which means we will need to first build to handle cases where start/end date remains the same, 
# and then handle all cases where this isn't true

In [122]:
display(k_final)

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,...,end_lng,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city
0,EACB19130B0CDA4A,docked_bike,20:06:59,20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,...,-87.667400,member,2020-01-21,2020-01-21,15,112.0,Chicago,11,239.0,Chicago
1,8FED874C809DC021,docked_bike,14:22:39,14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,...,-87.664400,member,2020-01-30,2020-01-30,19,316.0,Chicago,15,321.0,Chicago
2,789F3C21E472CA96,docked_bike,19:29:26,19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,...,-87.653000,member,2020-01-09,2020-01-09,15,277.0,Chicago,23,69.0,Chicago
3,C9A388DAC6ABF313,docked_bike,16:17:07,16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,...,-87.620600,member,2020-01-06,2020-01-06,31,5.0,Chicago,15,262.0,Chicago
4,943BC3CBECCFD662,docked_bike,08:37:16,08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,...,-87.634300,member,2020-01-30,2020-01-30,19,21.0,Chicago,19,264.0,Chicago
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11952925,BC3BFA659C9AB6F1,classic_bike,01:41:29,01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,-87.670668,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago
11952926,ACD65450291CF95F,classic_bike,01:41:54,01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,-87.670668,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago
11952927,4AAC03D1438E97CA,classic_bike,09:34:11,10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,-87.638677,...,-87.626761,casual,2022-10-15,2022-10-15,0,0.0,Chicago,0,0.0,Chicago
11952928,8E6F3F29785E5D40,classic_bike,10:21:34,10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,-87.638677,...,-87.677856,member,2022-10-09,2022-10-09,0,0.0,Chicago,0,0.0,Chicago
11952929,8D14CBE672431920,docked_bike,13:17:13,13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,-87.636282,...,-87.626761,casual,2022-10-22,2022-10-22,0,0.0,Chicago,0,0.0,Chicago

In [123]:
start_times = k_final['start_time'].values

In [124]:
# figure out rules for a single start/end ride time

input_time = '20:06:59'
input_for_convert = input_time.split(':')
input_for_convert
seconds = (int(input_for_convert[0]) * 360) + (int(input_for_convert[1]) * 60) + (int(input_for_convert[2]))
seconds


input_time2 = '20:14:30'
input_for_convert2 = input_time2.split(':')
input_for_convert2
seconds2 = (int(input_for_convert2[0]) * 360) + (int(input_for_convert2[1]) * 60) + (int(input_for_convert2[2]))
seconds2

# if ride does not carry over a day
if seconds < seconds2:
    ride_duration = seconds2 - seconds
    
# if ride does carry over a day
if seconds > seconds2:
    limit = (23 * 360) + (59 * 60) + 59
    in_between = limit - sec1
    print(in_between + sec2)

In [125]:
end_times = k_final['end_time'].values

In [126]:
ride_durations = []

for i in range(len(start_times)):
    start_time = start_times[i].split(':')
    end_time = end_times[i].split(':')
    
    start_time = (int(start_time[0]) * 3600) + (int(start_time[1]) * 60) + (int(start_time[2]))
    end_time = (int(end_time[0]) * 3600) + (int(end_time[1]) * 60) + (int(end_time[2]))
    
    
    if start_time < end_time:
        ride_duration = end_time - start_time
    
    elif start_time > end_time:
        limit = (23 * 3600) + (59 * 60) + 59
        in_between = limit - start_time
        ride_duration = in_between + end_time

    elif start_time == end_time:
        ride_duration = 0
        
    ride_durations.append(ride_duration)
ride_durations

[451,
 223,
 171,
 529,
 332,
 289,
 289,
 297,
 295,
 203,
 196,
 380,
 529,
 465,
 1000,
 2147,
 1965,
 1927,
 2217,
 368,
 1801,
 658,
 1261,
 175,
 823,
 171,
 778,
 218,
 770,
 510,
 409,
 152,
 341,
 1795,
 482,
 324,
 666,
 586,
 686,
 270,
 276,
 295,
 574,
 479,
 424,
 913,
 2480,
 801,
 685,
 630,
 1967,
 650,
 374,
 397,
 318,
 441,
 1162,
 868,
 380,
 410,
 311,
 252,
 283,
 2088,
 1872,
 1831,
 992,
 291,
 340,
 666,
 258,
 287,
 162,
 266,
 490,
 1339,
 836,
 583,
 728,
 646,
 360,
 688,
 805,
 429,
 579,
 411,
 354,
 143,
 194,
 414,
 278,
 593,
 568,
 616,
 373,
 351,
 426,
 2222,
 1691,
 1300,
 642,
 532,
 1215,
 613,
 680,
 912,
 429,
 299,
 882,
 1033,
 491,
 431,
 613,
 506,
 868,
 783,
 897,
 498,
 509,
 1465,
 846,
 1038,
 943,
 627,
 301,
 405,
 533,
 410,
 226,
 361,
 439,
 659,
 795,
 1072,
 112,
 795,
 487,
 779,
 870,
 599,
 168,
 240,
 173,
 1163,
 1396,
 935,
 432,
 436,
 464,
 464,
 253,
 694,
 7473,
 178,
 1118,
 1502,
 216,
 589,
 135,
 467,
 352,
 1208,
 926,
 235,
 1089,
 579,
 1009,
 256,
 495,
 370,
 198,
 784,
 548,
 436,
 275,
 309,
 278,
 276,
 251,
 291,
 768,
 738,
 408,
 759,
 441,
 788,
 410,
 398,
 709,
 2479,
 6774,
 941,
 1697,
 136,
 1690,
 616,
 408,
 416,
 305,
 245,
 228,
 371,
 205,
 798,
 470,
 364,
 499,
 508,
 256,
 912,
 908,
 234,
 163,
 198,
 142,
 163,
 559,
 342,
 796,
 809,
 798,
 809,
 436,
 851,
 762,
 825,
 359,
 2422,
 514,
 1218,
 215,
 180,
 722,
 586,
 2447,
 396,
 361,
 1242,
 467,
 482,
 429,
 1084,
 386,
 683,
 399,
 374,
 477,
 572,
 1477,
 213,
 170,
 328,
 444,
 553,
 87,
 785,
 95,
 399,
 916,
 709,
 1023,
 374,
 141,
 556,
 1511,
 140,
 479,
 238,
 1216,
 631,
 417,
 431,
 582,
 390,
 497,
 480,
 530,
 141,
 642,
 329,
 406,
 450,
 655,
 1264,
 562,
 443,
 269,
 7,
 920,
 1080,
 828,
 486,
 746,
 357,
 329,
 360,
 382,
 891,
 1169,
 1498,
 1079,
 329,
 264,
 152,
 467,
 481,
 1473,
 162,
 179,
 1987,
 175,
 499,
 417,
 349,
 1803,
 418,
 299,
 563,
 677,
 244,
 322,
 449,
 444,
 406,
 325,
 322,
 218,
 380,
 231,
 254,
 291,
 416,
 276,
 329,
 252,
 412,
 71,
 306,
 295,
 241,
 108,
 331,
 211,
 371,
 290,
 276,
 402,
 276,
 385,
 351,
 523,
 337,
 296,
 262,
 343,
 713,
 901,
 627,
 684,
 666,
 259,
 321,
 688,
 1165,
 1384,
 1376,
 243,
 911,
 175,
 296,
 226,
 904,
 645,
 487,
 604,
 669,
 1085,
 417,
 306,
 331,
 467,
 357,
 323,
 979,
 548,
 364,
 595,
 503,
 388,
 540,
 173,
 131,
 301,
 397,
 440,
 313,
 240,
 93,
 158,
 282,
 793,
 788,
 917,
 814,
 996,
 227,
 205,
 160,
 438,
 269,
 275,
 199,
 258,
 1835,
 1369,
 1299,
 257,
 306,
 309,
 922,
 487,
 341,
 1382,
 365,
 378,
 339,
 592,
 1145,
 614,
 1121,
 1035,
 359,
 371,
 375,
 794,
 676,
 798,
 1138,
 387,
 2459,
 2291,
 821,
 1230,
 1125,
 374,
 1032,
 1070,
 932,
 825,
 1120,
 316,
 190,
 671,
 744,
 578,
 591,
 555,
 715,
 627,
 407,
 489,
 198,
 378,
 770,
 568,
 728,
 537,
 585,
 500,
 283,
 299,
 358,
 417,
 646,
 804,
 483,
 837,
 1317,
 630,
 376,
 558,
 728,
 641,
 521,
 998,
 531,
 823,
 844,
 806,
 1344,
 586,
 950,
 588,
 755,
 430,
 374,
 189,
 173,
 510,
 166,
 430,
 260,
 1478,
 259,
 300,
 678,
 804,
 522,
 506,
 349,
 214,
 708,
 630,
 214,
 613,
 529,
 963,
 1041,
 474,
 1087,
 620,
 503,
 601,
 657,
 747,
 161,
 619,
 397,
 1052,
 427,
 442,
 407,
 426,
 458,
 1349,
 41,
 429,
 468,
 528,
 504,
 687,
 1234,
 168,
 136,
 163,
 217,
 388,
 470,
 277,
 228,
 200,
 574,
 330,
 457,
 149,
 1144,
 362,
 689,
 772,
 419,
 411,
 599,
 1075,
 409,
 458,
 850,
 823,
 580,
 956,
 352,
 12,
 374,
 966,
 1061,
 1284,
 1289,
 1435,
 1596,
 1570,
 1458,
 1451,
 1538,
 717,
 356,
 168,
 295,
 237,
 664,
 211,
 1271,
 657,
 1439,
 389,
 529,
 579,
 608,
 922,
 711,
 489,
 218,
 239,
 821,
 401,
 712,
 1007,
 798,
 723,
 225,
 1007,
 666,
 168,
 951,
 696,
 1051,
 468,
 185,
 492,
 556,
 687,
 1031,
 260,
 352,
 294,
 168,
 411,
 859,
 767,
 819,
 998,
 373,
 405,
 708,
 821,
 863,
 761,
 619,
 598,
 454,
 2055,
 713,
 205,
 162,
 237,
 560,
 582,
 497,
 650,
 845,
 700,
 830,
 1327,
 613,
 586,
 546,
 264,
 711,
 288,
 609,
 816,
 492,
 546,
 638,
 829,
 581,
 1170,
 325,
 1590,
 1854,
 482,
 526,
 629,
 616,
 292,
 282,
 584,
 687,
 2821,
 545,
 140,
 267,
 571,
 177,
 561,
 178,
 666,
 2951,
 1443,
 290,
 509,
 154,
 160,
 207,
 367,
 157,
 286,
 642,
 265,
 558,
 466,
 632,
 287,
 483,
 625,
 591,
 756,
 539,
 535,
 676,
 565,
 634,
 773,
 862,
 6189,
 407,
 150,
 1517,
 1438,
 1313,
 339,
 1329,
 461,
 811,
 1390,
 207,
 178,
 1155,
 763,
 957,
 291,
 296,
 179,
 223,
 314,
 348,
 385,
 307,
 579,
 264,
 776,
 840,
 881,
 1106,
 165,
 1184,
 1631,
 568,
 612,
 717,
 579,
 653,
 268,
 769,
 536,
 731,
 336,
 1116,
 2055,
 1504,
 4723,
 471,
 573,
 343,
 277,
 314,
 436,
 173,
 1218,
 2362,
 300,
 310,
 334,
 333,
 271,
 317,
 314,
 2535,
 166,
 255,
 1410,
 1146,
 1186,
 942,
 1246,
 1006,
 506,
 836,
 300,
 243,
 2733,
 672,
 1026,
 1414,
 603,
 214,
 439,
 246,
 233,
 570,
 208,
 686,
 671,
 176,
 142,
 1212,
 328,
 348,
 2298,
 2815,
 390,
 589,
 441,
 150,
 491,
 264,
 246,
 204,
 221,
 200,
 263,
 582,
 240,
 213,
 433,
 187,
 646,
 1525,
 1178,
 839,
 816,
 291,
 1014,
 360,
 423,
 411,
 224,
 219,
 204,
 455,
 232,
 389,
 644,
 704,
 451,
 286,
 155,
 602,
 306,
 175,
 162,
 285,
 281,
 290,
 256,
 288,
 625,
 603,
 592,
 339,
 796,
 237,
 467,
 343,
 475,
 369,
 449,
 726,
 759,
 384,
 777,
 745,
 574,
 222,
 335,
 1544,
 337,
 829,
 1070,
 273,
 344,
 636,
 565,
 1795,
 932,
 646,
 453,
 3135,
 178,
 348,
 311,
 357,
 283,
 336,
 289,
 332,
 358,
 330,
 287,
 271,
 399,
 388,
 388,
 278,
 357,
 339,
 301,
 337,
 271,
 603,
 308,
 363,
 2220,
 530,
 824,
 320,
 190,
 321,
 377,
 271,
 868,
 373,
 830,
 332,
 325,
 359,
 361,
 787,
 1944,
 565,
 312,
 259,
 156,
 295,
 280,
 211,
 622,
 844,
 448,
 475,
 453,
 485,
 701,
 505,
 352,
 315,
 399,
 339,
 234,
 314,
 282,
 468,
 2051,
 1530,
 3386,
 641,
 560,
 377,
 397,
 639,
 499,
 375,
 379,
 626,
 393,
 1022,
 1036,
 948,
 501,
 626,
 629,
 753,
 291,
 275,
 662,
 508,
 437,
 445,
 665,
 380,
 772,
 379,
 668,
 596,
 269,
 680,
 678,
 742,
 533,
 296,
 292,
 686,
 144,
 263,
 565,
 533,
 855,
 329,
 183,
 345,
 683,
 1047,
 ...]

In [127]:
max(ride_durations)

86398

In [128]:
min(ride_durations)

0

In [129]:
k_final['ride_durations'] = ride_durations

In [130]:
k_final

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
0,EACB19130B0CDA4A,docked_bike,20:06:59,20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,...,member,2020-01-21,2020-01-21,15,112.0,Chicago,11,239.0,Chicago,451
1,8FED874C809DC021,docked_bike,14:22:39,14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,...,member,2020-01-30,2020-01-30,19,316.0,Chicago,15,321.0,Chicago,223
2,789F3C21E472CA96,docked_bike,19:29:26,19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,...,member,2020-01-09,2020-01-09,15,277.0,Chicago,23,69.0,Chicago,171
3,C9A388DAC6ABF313,docked_bike,16:17:07,16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,...,member,2020-01-06,2020-01-06,31,5.0,Chicago,15,262.0,Chicago,529
4,943BC3CBECCFD662,docked_bike,08:37:16,08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,...,member,2020-01-30,2020-01-30,19,21.0,Chicago,19,264.0,Chicago,332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11952925,BC3BFA659C9AB6F1,classic_bike,01:41:29,01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago,947
11952926,ACD65450291CF95F,classic_bike,01:41:54,01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago,915
11952927,4AAC03D1438E97CA,classic_bike,09:34:11,10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,-87.638677,...,casual,2022-10-15,2022-10-15,0,0.0,Chicago,0,0.0,Chicago,1750
11952928,8E6F3F29785E5D40,classic_bike,10:21:34,10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,-87.638677,...,member,2022-10-09,2022-10-09,0,0.0,Chicago,0,0.0,Chicago,1331
11952929,8D14CBE672431920,docked_bike,13:17:13,13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,-87.636282,...,casual,2022-10-22,2022-10-22,0,0.0,Chicago,0,0.0,Chicago,1741

In [131]:
k_final[(k_final['start_date'] != k_final['end_date'])]

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
1031,8E7BA80EB79CB5C6,docked_bike,15:43:14,07:53:13,Lincoln Ave & Fullerton Ave,127.0,Clark St & Drummond Pl,220.0,41.925900,-87.649300,...,casual,2020-01-14,2020-01-24,15,131.0,Chicago,19,123.0,Chicago,58198
1539,233F1AEC4D8962BC,docked_bike,23:54:35,00:00:31,Clarendon Ave & Leland Ave,251.0,Sheridan Rd & Lawrence Ave,323.0,41.968000,-87.650000,...,member,2020-01-26,2020-01-27,15,385.0,Chicago,15,384.0,Chicago,355
1926,9F192C7AF22C3A0D,docked_bike,23:59:54,00:04:04,Kingsbury St & Erie St,74.0,Dearborn St & Erie St,110.0,41.893800,-87.641700,...,member,2020-01-06,2020-01-07,23,265.0,Chicago,23,45.0,Chicago,249
2383,785A67FB11A02848,docked_bike,08:19:49,10:25:54,Clinton St & Jackson Blvd,638.0,Clark St & Lake St,38.0,41.878100,-87.639800,...,member,2020-01-17,2020-01-18,0,0.0,Chicago,27,547.0,Chicago,7565
2826,869B26EEDEFDF774,docked_bike,18:53:30,09:42:51,McClurg Ct & Illinois St,26.0,Franklin St & Jackson Blvd,36.0,41.890400,-87.617500,...,casual,2020-01-19,2020-01-23,23,51.0,Chicago,27,19.0,Chicago,53360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11952187,A60EC1FF63DA47FA,docked_bike,22:12:15,01:10:43,Clark St & Armitage Ave,13146,Halsted St & Roscoe St,TA1309000025,41.918306,-87.636282,...,casual,2022-10-07,2022-10-08,0,0.0,Chicago,0,0.0,Chicago,10707
11952260,BB99CBDD5BFD7E3E,classic_bike,15:58:52,13:30:34,Dodge Ave & Church St,600,Dodge Ave & Church St,600,42.048308,-87.698224,...,casual,2022-10-14,2022-10-15,0,0.0,Chicago,0,0.0,Chicago,77501
11952424,E95B1203FF0E45E2,classic_bike,23:42:49,00:15:55,Clarendon Ave & Junior Ter,13389,Sheridan Rd & Montrose Ave,TA1307000107,41.961004,-87.649603,...,member,2022-10-07,2022-10-08,0,0.0,Chicago,0,0.0,Chicago,1985
11952751,48AF8AD0E587279F,classic_bike,23:49:44,00:00:38,Clark St & Newport St,632,Clark St & Wellington Ave,TA1307000136,41.944540,-87.654678,...,casual,2022-10-29,2022-10-30,0,0.0,Chicago,0,0.0,Chicago,653
11952780,82657FBB05158657,electric_bike,23:58:05,00:06:52,Clark St & Newport St,632,Clark St & Armitage Ave,13146,41.944537,-87.654782,...,member,2022-10-05,2022-10-06,0,0.0,Chicago,0,0.0,Chicago,526

In [132]:
k_final[k_final['ride_durations'] == 86398]

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
155321,9461DFF13D8BA8AD,docked_bike,10:09:43,10:09:42,HQ QR,675.0,HQ QR,675.0,41.889900,-87.680300,...,casual,2020-02-28,2020-02-28,0,0.0,Chicago,0,0.0,Chicago,86398
435052,6EB323BCC83A9D1D,docked_bike,15:46:12,15:46:11,Francisco Ave & Foster Ave,471.0,Damen Ave & Clybourn Ave,163.0,41.975600,-87.701400,...,member,2020-04-05,2020-04-05,15,613.0,Chicago,15,271.0,Chicago,86398
500685,BA9FA2547D002402,docked_bike,21:08:00,21:07:59,State St & Harrison St,5.0,Fairbanks Ct & Grand Ave,24.0,41.874100,-87.627700,...,casual,2020-04-12,2020-04-12,19,30.0,Chicago,15,262.0,Chicago,86398
542525,0419646053F0CD9F,docked_bike,16:10:12,16:10:11,Wolcott Ave & Polk St,342.0,Halsted St & 21st St,135.0,41.871300,-87.673700,...,member,2020-05-19,2020-05-19,15,284.0,Chicago,11,162.0,Chicago,86398
543402,A33B261758CD58C8,docked_bike,14:54:59,14:54:58,Western Ave & Walton St,374.0,Western Ave & Walton St,374.0,41.898400,-87.686600,...,casual,2020-05-25,2020-05-25,15,662.0,Chicago,15,662.0,Chicago,86398
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6664132,7C194D321B885287,classic_bike,14:02:52,14:02:51,Throop St & Taylor St,13139,Throop St & Taylor St,13139,41.868968,-87.659141,...,member,2021-09-29,2021-09-29,0,0.0,Chicago,0,0.0,Chicago,86398
6735196,082A465904C062EF,classic_bike,11:15:17,11:15:16,Clark St & Elm St,TA1307000039,Clark St & Elm St,TA1307000039,41.902973,-87.631280,...,casual,2021-09-26,2021-09-26,0,0.0,Chicago,0,0.0,Chicago,86398
6953020,88BA6AC7326B179B,classic_bike,15:26:23,15:26:22,Kimbark Ave & 53rd St,TA1309000037,Kimbark Ave & 53rd St,TA1309000037,41.799568,-87.594747,...,member,2021-09-29,2021-09-29,0,0.0,Chicago,0,0.0,Chicago,86398
10857091,179F7874064251C8,classic_bike,16:35:21,16:35:20,Clark St & Montrose Ave,KA1503000022,Clark St & Montrose Ave,KA1503000022,41.961588,-87.666036,...,casual,2022-08-05,2022-08-05,0,0.0,Chicago,0,0.0,Chicago,86398
11194226,BB630AE8E6017B58,electric_bike,17:56:42,17:56:41,Millennium Park,13008,Millennium Park,13008,41.881182,-87.623962,...,casual,2022-09-05,2022-09-05,0,0.0,Chicago,0,0.0,Chicago,86398

In [133]:
# ok, so we need to factor in days as well. If more than a day passes, aka in between start_date and end_date, I will delete
# the row. additionally, if they entries are on the same day, the entries will be deleted if the start time is after the
# end time.

# test_start_date = ['2022-09-05','2022-09-07','2022-09-16','2022-09-26','2022-09-26','2021-09-26','2022-010-26','2022-09-26']
# test_end_date = ['2022-09-05','2022-09-06','2022-09-22', '2022-09-27','2021-09-26','2022-09-26','2022-09-26','2022-10-26']

def leap_year_check(year):
    if year % 4 == 0:
        
        if year % 100 != 0:
            if year % 400 == 0:
                return True
        else:
            return False
        
        return True
    
    else:
        return False



# this function takes start and end date combinations and checks if they are valid. It returns the index position of all invalid
# date combinations so that they can be dropped.
def date_checker(test_start_dates=[],test_end_dates=[]):
    month_max_days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    
    date_invalid_check = []
    
    
    for i in range(len(test_start_dates)):
    
        start_d_test = test_start_dates[i].split('-')
        end_d_test = test_end_dates[i].split('-')
        
        
        # These are our years
        st_year = int(start_d_test[0])
        ed_year = int(end_d_test[0])
        
        # These are our months
        st_month = int(start_d_test[1])
        ed_month = int(end_d_test[1])

        # These are our days
        st_day = int(start_d_test[2])
        ed_day = int(end_d_test[2])
        
        
        # if the years of the dates are not the same
        if st_year != ed_year:
            #print('Year: ', i)
            date_invalid_check.append(i)

        # If st_month is after ed_month
        elif st_month > ed_month:
            #print(st_month == ed_month)
            #print('Start Month occurs after end month: ', i)
            date_invalid_check.append(i)
        
        # if st_month is more than 1 month before ed_month
        elif ed_month - st_month > 1:    
            #print(st_month == ed_month)
            #print('Start Month is too far from end month: ', i)
            date_invalid_check.append(i)
        
        elif ed_month == st_month + 1 and ed_day != 1:
            date_invalid_check.append(i)
        
        
        # If the ed_day is more than one day after the st_day, this works regardless of month
        elif ed_day - st_day > 1:
            #print('Day: ', i)
            date_invalid_check.append(i)
        
        # if ed_day - st_day is negative, we have to examine why
        elif ed_day - st_day < 0:
            #print('Day difference Negative: ', i)
            
            # if the month is the same, this chronological difference make no sense
            if ed_month == st_month:
                #print('Month is same: ', i)
                date_invalid_check.append(i)
            
            # if the st_month is the month before ed_month and it is the first day of ed_month
            elif ed_month == st_month + 1 and ed_day == 1:
                #print('Start Month end to Next month beginning: ', i)
                month_max = month_max_days[st_month - 1]

                # accounting for february leap years
                if leap_year_check(st_year) and st_month == 2:
                    #print('February: ', i)
                    month_max = 29
                
                # if our st_day is not the last day of the respective st_month, the date is invalid
                if st_day - month_max != 0:
                    #print('Start Month not ended yet, or day does not exist: ', i)
                    date_invalid_check.append(i)

    

    return date_invalid_check

#start_date = ['2015-07-30', '2014-06-18', '2020-02-29', '2014-03-31', '2015-07-10', '2015-12-31']
#end_date = ['2015-07-31', '2014-08-18', '2020-03-01', '2014-04-01', '2014-07-10', '2015-12-01']

#date_checker(start_date, end_date)


# This function will be used in the final stage. This was just testing and implementation for a subset of the data.

In [134]:
invalid_dates = date_checker(k_final['start_date'].values, k_final['end_date'].values)

In [135]:
len(invalid_dates)

2387

In [136]:
k_final.loc[invalid_dates]

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
1031,8E7BA80EB79CB5C6,docked_bike,15:43:14,07:53:13,Lincoln Ave & Fullerton Ave,127.0,Clark St & Drummond Pl,220.0,41.925900,-87.649300,...,casual,2020-01-14,2020-01-24,15,131.0,Chicago,19,123.0,Chicago,58198
2826,869B26EEDEFDF774,docked_bike,18:53:30,09:42:51,McClurg Ct & Illinois St,26.0,Franklin St & Jackson Blvd,36.0,41.890400,-87.617500,...,casual,2020-01-19,2020-01-23,23,51.0,Chicago,27,19.0,Chicago,53360
7533,651C959936BA3227,docked_bike,17:15:59,17:12:44,Rush St & Superior St,161.0,LaSalle St & Illinois St,181.0,41.895800,-87.625900,...,casual,2020-01-15,2020-01-24,23,530.0,Chicago,19,430.0,Chicago,86204
8033,4FC4437B29C9BF1B,docked_bike,17:05:36,13:14:10,Lakeview Ave & Fullerton Pkwy,313.0,Lakeview Ave & Fullerton Pkwy,313.0,41.925900,-87.639000,...,casual,2020-01-05,2020-01-07,19,147.0,Chicago,19,147.0,Chicago,72513
9052,78A27956CF4E52FC,docked_bike,16:11:57,06:02:05,Michigan Ave & Madison St,197.0,Clark St & Ida B Wells Dr,50.0,41.882100,-87.625100,...,casual,2020-01-17,2020-01-20,19,36.0,Chicago,27,9.0,Chicago,49807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10327777,17405F31D17313B2,docked_bike,13:07:51,11:10:12,Dusable Harbor,KA1503000064,Green St & Randolph St*,chargingstx3,41.886976,-87.612813,...,casual,2022-07-22,2022-07-29,0,0.0,Chicago,0,0.0,Chicago,79340
10328182,DC510E6F98003A94,docked_bike,18:37:11,00:32:38,DuSable Lake Shore Dr & Monroe St,13300,Green St & Randolph St*,chargingstx3,41.880958,-87.616743,...,casual,2022-07-04,2022-07-27,0,0.0,Chicago,0,0.0,Chicago,21326
10862902,4464B4342DAC2E9D,docked_bike,15:35:28,12:55:24,Montrose Harbor,TA1308000012,Green St & Randolph St*,chargingstx3,41.963982,-87.638181,...,casual,2022-08-26,2022-08-28,0,0.0,Chicago,0,0.0,Chicago,76795
10993136,C999C6BBBEC63568,docked_bike,11:04:19,19:52:40,Dusable Harbor,KA1503000064,Wilton Ave & Diversey Pkwy*,chargingstx0,41.886976,-87.612813,...,casual,2022-08-06,2022-08-09,0,0.0,Chicago,0,0.0,Chicago,31701
11619010,B139FE7DF42819B0,docked_bike,14:37:54,08:01:42,Field Museum,13029,Bissell St & Armitage Ave*,chargingstx1,41.865312,-87.617867,...,casual,2022-10-24,2022-10-30,0,0.0,Chicago,0,0.0,Chicago,62627

In [137]:
k_final = k_final.drop(invalid_dates).reset_index()

In [138]:
k_final

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
0,0,EACB19130B0CDA4A,docked_bike,20:06:59,20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,...,member,2020-01-21,2020-01-21,15,112.0,Chicago,11,239.0,Chicago,451
1,1,8FED874C809DC021,docked_bike,14:22:39,14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,...,member,2020-01-30,2020-01-30,19,316.0,Chicago,15,321.0,Chicago,223
2,2,789F3C21E472CA96,docked_bike,19:29:26,19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,...,member,2020-01-09,2020-01-09,15,277.0,Chicago,23,69.0,Chicago,171
3,3,C9A388DAC6ABF313,docked_bike,16:17:07,16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,...,member,2020-01-06,2020-01-06,31,5.0,Chicago,15,262.0,Chicago,529
4,4,943BC3CBECCFD662,docked_bike,08:37:16,08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,...,member,2020-01-30,2020-01-30,19,21.0,Chicago,19,264.0,Chicago,332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11950538,11952925,BC3BFA659C9AB6F1,classic_bike,01:41:29,01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,...,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago,947
11950539,11952926,ACD65450291CF95F,classic_bike,01:41:54,01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,...,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago,915
11950540,11952927,4AAC03D1438E97CA,classic_bike,09:34:11,10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,...,casual,2022-10-15,2022-10-15,0,0.0,Chicago,0,0.0,Chicago,1750
11950541,11952928,8E6F3F29785E5D40,classic_bike,10:21:34,10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,...,member,2022-10-09,2022-10-09,0,0.0,Chicago,0,0.0,Chicago,1331
11950542,11952929,8D14CBE672431920,docked_bike,13:17:13,13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,...,casual,2022-10-22,2022-10-22,0,0.0,Chicago,0,0.0,Chicago,1741

In [139]:
max(k_final['ride_durations'].values)

86398

In [140]:
k_final[k_final['ride_durations'] == 86398]

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
155250,155321,9461DFF13D8BA8AD,docked_bike,10:09:43,10:09:42,HQ QR,675.0,HQ QR,675.0,41.889900,...,casual,2020-02-28,2020-02-28,0,0.0,Chicago,0,0.0,Chicago,86398
434826,435052,6EB323BCC83A9D1D,docked_bike,15:46:12,15:46:11,Francisco Ave & Foster Ave,471.0,Damen Ave & Clybourn Ave,163.0,41.975600,...,member,2020-04-05,2020-04-05,15,613.0,Chicago,15,271.0,Chicago,86398
500406,500685,BA9FA2547D002402,docked_bike,21:08:00,21:07:59,State St & Harrison St,5.0,Fairbanks Ct & Grand Ave,24.0,41.874100,...,casual,2020-04-12,2020-04-12,19,30.0,Chicago,15,262.0,Chicago,86398
542228,542525,0419646053F0CD9F,docked_bike,16:10:12,16:10:11,Wolcott Ave & Polk St,342.0,Halsted St & 21st St,135.0,41.871300,...,member,2020-05-19,2020-05-19,15,284.0,Chicago,11,162.0,Chicago,86398
543105,543402,A33B261758CD58C8,docked_bike,14:54:59,14:54:58,Western Ave & Walton St,374.0,Western Ave & Walton St,374.0,41.898400,...,casual,2020-05-25,2020-05-25,15,662.0,Chicago,15,662.0,Chicago,86398
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6661997,6664132,7C194D321B885287,classic_bike,14:02:52,14:02:51,Throop St & Taylor St,13139,Throop St & Taylor St,13139,41.868968,...,member,2021-09-29,2021-09-29,0,0.0,Chicago,0,0.0,Chicago,86398
6733052,6735196,082A465904C062EF,classic_bike,11:15:17,11:15:16,Clark St & Elm St,TA1307000039,Clark St & Elm St,TA1307000039,41.902973,...,casual,2021-09-26,2021-09-26,0,0.0,Chicago,0,0.0,Chicago,86398
6950854,6953020,88BA6AC7326B179B,classic_bike,15:26:23,15:26:22,Kimbark Ave & 53rd St,TA1309000037,Kimbark Ave & 53rd St,TA1309000037,41.799568,...,member,2021-09-29,2021-09-29,0,0.0,Chicago,0,0.0,Chicago,86398
10854707,10857091,179F7874064251C8,classic_bike,16:35:21,16:35:20,Clark St & Montrose Ave,KA1503000022,Clark St & Montrose Ave,KA1503000022,41.961588,...,casual,2022-08-05,2022-08-05,0,0.0,Chicago,0,0.0,Chicago,86398
11191840,11194226,BB630AE8E6017B58,electric_bike,17:56:42,17:56:41,Millennium Park,13008,Millennium Park,13008,41.881182,...,casual,2022-09-05,2022-09-05,0,0.0,Chicago,0,0.0,Chicago,86398

In [141]:
k_final

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
0,0,EACB19130B0CDA4A,docked_bike,20:06:59,20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,...,member,2020-01-21,2020-01-21,15,112.0,Chicago,11,239.0,Chicago,451
1,1,8FED874C809DC021,docked_bike,14:22:39,14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,...,member,2020-01-30,2020-01-30,19,316.0,Chicago,15,321.0,Chicago,223
2,2,789F3C21E472CA96,docked_bike,19:29:26,19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,...,member,2020-01-09,2020-01-09,15,277.0,Chicago,23,69.0,Chicago,171
3,3,C9A388DAC6ABF313,docked_bike,16:17:07,16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,...,member,2020-01-06,2020-01-06,31,5.0,Chicago,15,262.0,Chicago,529
4,4,943BC3CBECCFD662,docked_bike,08:37:16,08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,...,member,2020-01-30,2020-01-30,19,21.0,Chicago,19,264.0,Chicago,332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11950538,11952925,BC3BFA659C9AB6F1,classic_bike,01:41:29,01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,...,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago,947
11950539,11952926,ACD65450291CF95F,classic_bike,01:41:54,01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,...,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago,915
11950540,11952927,4AAC03D1438E97CA,classic_bike,09:34:11,10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,...,casual,2022-10-15,2022-10-15,0,0.0,Chicago,0,0.0,Chicago,1750
11950541,11952928,8E6F3F29785E5D40,classic_bike,10:21:34,10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,...,member,2022-10-09,2022-10-09,0,0.0,Chicago,0,0.0,Chicago,1331
11950542,11952929,8D14CBE672431920,docked_bike,13:17:13,13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,...,casual,2022-10-22,2022-10-22,0,0.0,Chicago,0,0.0,Chicago,1741

In [142]:
max(k_final['ride_durations'])

86398

In [143]:
k_final[k_final['ride_durations'] > 80000]

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
27860,27873,BFDAE7A25425F884,docked_bike,11:26:27,09:57:38,Clarendon Ave & Junior Ter,245.0,Sheridan Rd & Buena Ave,306.0,41.961000,...,casual,2020-01-27,2020-01-28,15,389.0,Chicago,15,374.0,Chicago,81070
34157,34172,5B1C8D097249361F,docked_bike,10:21:21,09:41:23,Austin Blvd & Madison St,544.0,Austin Blvd & Chicago Ave,524.0,41.880300,...,member,2020-01-31,2020-02-01,15,0.0,Chicago,11,0.0,Chicago,84001
35566,35581,0C6A6F38A75FC304,docked_bike,08:15:10,07:16:03,Milwaukee Ave & Grand Ave,84.0,Racine Ave & Randolph St,88.0,41.891600,...,member,2020-01-09,2020-01-10,19,33.0,Chicago,15,155.0,Chicago,82852
80224,80265,14BF3B05D43BC271,docked_bike,10:25:00,08:41:37,Buckingham Fountain,2.0,Buckingham Fountain,2.0,41.876500,...,casual,2020-01-19,2020-01-20,35,541.0,Chicago,35,541.0,Chicago,80196
80225,80266,2A1403BAA266FF75,docked_bike,10:24:12,08:47:24,Buckingham Fountain,2.0,Buckingham Fountain,2.0,41.876500,...,casual,2020-01-19,2020-01-20,35,541.0,Chicago,35,541.0,Chicago,80591
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11756866,11759253,03A545D927524313,classic_bike,12:59:29,12:16:14,Michigan Ave & Lake St,TA1305000011,Shore Dr & 55th St,TA1308000009,41.886024,...,casual,2022-10-08,2022-10-09,0,0.0,Chicago,0,0.0,Chicago,83804
11769382,11771769,B456C184D4DD27EC,classic_bike,16:59:57,15:21:30,Clark St & North Ave,13128,Racine Ave & Belmont Ave,TA1308000019,41.911974,...,casual,2022-10-14,2022-10-15,0,0.0,Chicago,0,0.0,Chicago,80492
11810305,11812692,833CF24D8B29AD90,classic_bike,13:00:04,11:51:52,Lincoln Ave & Fullerton Ave,TA1309000058,Southport Ave & Roscoe St,13071,41.924161,...,member,2022-10-14,2022-10-15,0,0.0,Chicago,0,0.0,Chicago,82307
11845870,11848257,0345839F42C05388,classic_bike,16:22:08,15:08:02,State St & 35th St,TA1307000129,900 W Harrison St,13028,41.831036,...,member,2022-10-08,2022-10-09,0,0.0,Chicago,0,0.0,Chicago,81953
11894058,11896445,104A2DC2523F8C7C,docked_bike,12:11:35,10:28:59,Michigan Ave & 8th St,623,Millennium Park,13008,41.872773,...,casual,2022-10-28,2022-10-29,0,0.0,Chicago,0,0.0,Chicago,80243

In [144]:
# I can see that Warehouse, Test, and some other entries that are invalid may be in the dataframe, so they must be deleted as

# so we can delete all rows with occurances of the phrase
k_final = k_final.drop(k_final[k_final['from_station_name'].str.lower().str.contains("base", regex=False, na=False) == True].index)
k_final = k_final.drop(k_final[k_final['to_station_name'].str.lower().str.contains("base", regex=False, na=False) == True].index)

In [145]:
k_final[k_final['ride_durations'] > 80000]

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
27860,27873,BFDAE7A25425F884,docked_bike,11:26:27,09:57:38,Clarendon Ave & Junior Ter,245.0,Sheridan Rd & Buena Ave,306.0,41.961000,...,casual,2020-01-27,2020-01-28,15,389.0,Chicago,15,374.0,Chicago,81070
34157,34172,5B1C8D097249361F,docked_bike,10:21:21,09:41:23,Austin Blvd & Madison St,544.0,Austin Blvd & Chicago Ave,524.0,41.880300,...,member,2020-01-31,2020-02-01,15,0.0,Chicago,11,0.0,Chicago,84001
35566,35581,0C6A6F38A75FC304,docked_bike,08:15:10,07:16:03,Milwaukee Ave & Grand Ave,84.0,Racine Ave & Randolph St,88.0,41.891600,...,member,2020-01-09,2020-01-10,19,33.0,Chicago,15,155.0,Chicago,82852
80224,80265,14BF3B05D43BC271,docked_bike,10:25:00,08:41:37,Buckingham Fountain,2.0,Buckingham Fountain,2.0,41.876500,...,casual,2020-01-19,2020-01-20,35,541.0,Chicago,35,541.0,Chicago,80196
80225,80266,2A1403BAA266FF75,docked_bike,10:24:12,08:47:24,Buckingham Fountain,2.0,Buckingham Fountain,2.0,41.876500,...,casual,2020-01-19,2020-01-20,35,541.0,Chicago,35,541.0,Chicago,80591
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11756866,11759253,03A545D927524313,classic_bike,12:59:29,12:16:14,Michigan Ave & Lake St,TA1305000011,Shore Dr & 55th St,TA1308000009,41.886024,...,casual,2022-10-08,2022-10-09,0,0.0,Chicago,0,0.0,Chicago,83804
11769382,11771769,B456C184D4DD27EC,classic_bike,16:59:57,15:21:30,Clark St & North Ave,13128,Racine Ave & Belmont Ave,TA1308000019,41.911974,...,casual,2022-10-14,2022-10-15,0,0.0,Chicago,0,0.0,Chicago,80492
11810305,11812692,833CF24D8B29AD90,classic_bike,13:00:04,11:51:52,Lincoln Ave & Fullerton Ave,TA1309000058,Southport Ave & Roscoe St,13071,41.924161,...,member,2022-10-14,2022-10-15,0,0.0,Chicago,0,0.0,Chicago,82307
11845870,11848257,0345839F42C05388,classic_bike,16:22:08,15:08:02,State St & 35th St,TA1307000129,900 W Harrison St,13028,41.831036,...,member,2022-10-08,2022-10-09,0,0.0,Chicago,0,0.0,Chicago,81953
11894058,11896445,104A2DC2523F8C7C,docked_bike,12:11:35,10:28:59,Michigan Ave & 8th St,623,Millennium Park,13008,41.872773,...,casual,2022-10-28,2022-10-29,0,0.0,Chicago,0,0.0,Chicago,80243

In [146]:
k_final

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
0,0,EACB19130B0CDA4A,docked_bike,20:06:59,20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,...,member,2020-01-21,2020-01-21,15,112.0,Chicago,11,239.0,Chicago,451
1,1,8FED874C809DC021,docked_bike,14:22:39,14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,...,member,2020-01-30,2020-01-30,19,316.0,Chicago,15,321.0,Chicago,223
2,2,789F3C21E472CA96,docked_bike,19:29:26,19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,...,member,2020-01-09,2020-01-09,15,277.0,Chicago,23,69.0,Chicago,171
3,3,C9A388DAC6ABF313,docked_bike,16:17:07,16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,...,member,2020-01-06,2020-01-06,31,5.0,Chicago,15,262.0,Chicago,529
4,4,943BC3CBECCFD662,docked_bike,08:37:16,08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,...,member,2020-01-30,2020-01-30,19,21.0,Chicago,19,264.0,Chicago,332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11950538,11952925,BC3BFA659C9AB6F1,classic_bike,01:41:29,01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,...,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago,947
11950539,11952926,ACD65450291CF95F,classic_bike,01:41:54,01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,...,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago,915
11950540,11952927,4AAC03D1438E97CA,classic_bike,09:34:11,10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,...,casual,2022-10-15,2022-10-15,0,0.0,Chicago,0,0.0,Chicago,1750
11950541,11952928,8E6F3F29785E5D40,classic_bike,10:21:34,10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,...,member,2022-10-09,2022-10-09,0,0.0,Chicago,0,0.0,Chicago,1331
11950542,11952929,8D14CBE672431920,docked_bike,13:17:13,13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,...,casual,2022-10-22,2022-10-22,0,0.0,Chicago,0,0.0,Chicago,1741

In [147]:
the_set = list(set(list(k_final['from_station_id'].values)))

for i in range(len(the_set)):
    print(the_set[i])

13150
2.0
3.0
4.0
5.0
6.0
7.0
309.0
9.0
524.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0
20.0
21.0
22.0
23.0
24.0
25.0
26.0
27.0
28.0
29.0
30.0
31.0
32.0
33.0
34.0
35.0
36.0
37.0
38.0
39.0
40.0
41.0
42.0
43.0
44.0
45.0
46.0
47.0
48.0
49.0
50.0
51.0
52.0
53.0
54.0
55.0
56.0
57.0
58.0
59.0
60.0
61.0
62.0
294.0
KA1503000070
KA1504000101
66.0
67.0
68.0
69.0
KA1706005015
71.0
72.0
73.0
74.0
75.0
76.0
77.0
71.0
15621
80.0
81.0
20214
84.0
85.0
86.0
87.0
88.0
89.0
90.0
91.0
92.0
93.0
94.0
95.0
96.0
97.0
98.0
99.0
100.0
101.0
102.0
103.0
KA1503000019
106.0
107.0
108.0
109.0
110.0
111.0
112.0
113.0
114.0
115.0
116.0
117.0
118.0
119.0
120.0
121.0
122.0
123.0
124.0
125.0
126.0
127.0
128.0
129.0
130.0
131.0
132.0
133.0
134.0
135.0
136.0
137.0
138.0
16940
140.0
141.0
142.0
143.0
144.0
145.0
146.0
147.0
148.0
149.0
150.0
20252.0
152.0
153.0
154.0
156.0
157.0
158.0
159.0
160.0
161.0
162.0
163.0
164.0
165.0
166.0
167.0
168.0
169.0
170.0
171.0
172.0
173.0
174.0
175.0
176.0
177.0
178.0
179.0
180.0
181.0
182.0
183.0
184.0
185.0
186.0
TA1309000011
188.0
915
190.0
191.0
192.0
193.0
194.0
195.0
196.0
197.0
198.0
199.0
200.0
201.0
202.0
203.0
204.0
205.0
206.0
207.0
208.0
209.0
210.0
211.0
212.0
213.0
214.0
215.0
216.0
217.0
218.0
219.0
220.0
654
222.0
223.0
224.0
225.0
226.0
227.0
228.0
229.0
230.0
231.0
232.0
233.0
234.0
236.0
237.0
238.0
239.0
240.0
241.0
242.0
243.0
244.0
245.0
246.0
247.0
248.0
249.0
250.0
251.0
252.0
253.0
254.0
255.0
256.0
257.0
258.0
259.0
260.0
261.0
262.0
263.0
264.0
265.0
267.0
268.0
270.0
271.0
272.0
273.0
274.0
275.0
276.0
277.0
278.0
279.0
280.0
281.0
282.0
283.0
284.0
285.0
286.0
287.0
288.0
289.0
290.0
291.0
292.0
293.0
294.0
295.0
296.0
297.0
298.0
299.0
300.0
301.0
302.0
303.0
304.0
305.0
306.0
307.0
308.0
309.0
310.0
311.0
312.0
313.0
314.0
315.0
316.0
317.0
318.0
319.0
320.0
321.0
322.0
323.0
324.0
325.0
326.0
327.0
328.0
329.0
330.0
331.0
332.0
333.0
334.0
335.0
336.0
337.0
338.0
339.0
340.0
341.0
342.0
343.0
344.0
345.0
346.0
347.0
348.0
349.0
350.0
351.0
352.0
353.0
354.0
355.0
356.0
353.0
573
359.0
KA1504000141
13193
427
967
364.0
365.0
366.0
367.0
368.0
369.0
370.0
599
TA1309000043
373.0
374.0
375.0
376.0
377.0
378.0
20101
381.0
382.0
383.0
384.0
385.0
386.0
15541
388.0
390.0
391.0
392.0
393.0
394.0
395.0
396.0
398.0
399.0
400.0
401.0
402.0
403.0
314.0
405.0
406.0
407.0
408.0
409.0
410.0
411.0
412.0
413.0
414.0
415.0
416.0
417.0
418.0
419.0
420.0
421.0
422.0
423.0
424.0
425.0
426.0
427.0
428.0
429.0
430.0
431.0
432.0
433.0
434.0
435.0
436.0
437.0
438.0
439.0
440.0
441.0
442.0
443.0
444.0
445.0
446.0
447.0
448.0
449.0
450.0
451.0
452.0
453.0
454.0
455.0
456.0
457.0
458.0
459.0
460.0
461.0
462.0
463.0
464.0
465.0
466.0
467.0
468.0
469.0
470.0
471.0
472.0
357
474.0
475.0
476.0
477.0
478.0
479.0
480.0
481.0
482.0
483.0
484.0
485.0
486.0
487.0
488.0
489.0
490.0
491.0
492.0
493.0
494.0
495.0
496.0
497.0
498.0
499.0
500.0
501.0
502.0
503.0
504.0
505.0
506.0
507.0
508.0
509.0
510.0
511.0
479.0
KA1503000034
514.0
515.0
TA1307000062
517.0
518.0
519.0
520.0
289.0
522.0
523.0
524.0
525.0
526.0
527.0
528.0
100.0
529.0
530.0
531.0
532.0
533.0
534.0
535.0
536.0
537.0
538.0
539.0
540.0
541.0
542.0
543.0
544.0
545.0
546.0
547.0
548.0
549.0
550.0
551.0
552.0
553.0
554.0
555.0
556.0
557.0
558.0
559.0
560.0
561.0
562.0
563.0
564.0
565.0
566.0
567.0
568.0
569.0
570.0
571.0
572.0
573.0
574.0
575.0
576.0
577.0
578.0
579.0
580.0
581.0
582.0
583.0
584.0
585.0
586.0
587.0
588.0
589.0
590.0
591.0
592.0
593.0
594.0
595.0
596.0
597.0
598.0
599.0
600.0
601.0
602.0
603.0
604.0
605.0
181.0
496.0
600
KA1504000110
755
20227
619.0
620.0
621.0
622.0
623.0
624.0
625.0
626.0
627.0
628.0
13191
630.0
631.0
632.0
346
838
635.0
636.0
637.0
638.0
639.0
640.0
641.0
642.0
643.0
644.0
645.0
646.0
647.0
648.0
649.0
650.0
651.0
652.0
653.0
654.0
655.0
656.0
657.0
658.0
659.0
660.0
661.0
662.0
663.0
664.0
665.0
666.0
670.0
672.0
673.0
674.0
675.0
KA1503000069
677.0
678.0
679.0
522.0
681.0
682.0
683.0
684.0
685.0
686.0
687.0
689.0
690.0
691.0
692.0
693.0
694.0
695.0
696.0
697.0
698.0
699.0
700.0
701.0
702.0
703.0
704.0
705.0
706.0
707.0
708.0
709.0
710.0
711.0
712.0
713.0
714.0
715.0
716.0
717.0
718.0
719.0
720.0
721.0
722.0
723.0
724.0
725.0
726.0
727.0
728.0
257.0
730.0
731.0
732.0
757
34.0
449.0
308
1052
15645
chargingstx5
487
91.0
703
110.0
829
TA1305000039
322
98.0
TA1308000022
439
737
432
383
957
TA1309000041
464
13241
647
73.0
305.0
465.0
863
44.0
710
759
596.0
854
163.0
736
20251.0
TA1308000002
846
DIVVY 001
248.0
TA1305000032
13011
111.0
16.0
720
LP-
13058
878
304
381
809
911
245.0
186.0
16916
887
327
TA1308000049
273.0
566
602.0
TA1308000035
905
488.0
51.0
483
940
KA1503000011
376
20237
508
RP-007
322.0
627.0
675
123.0
240.0
652
KA1504000139
852
699
684
557.0
986
552
256.0
968
13071
594
13276
31.0
KA1503000049
TA1309000051
TA1309000032
768
WL-012
678
196.0
TA1307000166
KA1503000075
13196
1067
38.0
58.0
752
13084
386
SL-008
374
15689
370
779
TA1309000064
TA1307000140
512
KA1503000022
202480.0
296.0
TA1307000161
134.0
898
602
299.0
15644
211.0
KA1504000133
339.0
486
756
TA1309000053
20233
87.0
13099
384
763
662
824
2059 Hastings Warehouse Station
147.0
2.0
TA1307000143
793
16907
81.0
13085
303
KA1503000074
15642
504
385
365.0
TA1307000153
690
587
320
700
688
16806
504.0
KA1503000052
chargingstx3
TA1305000004
TA1306000025
KA1504000082
511
518
67.0
374.0
97.0
723
327.0
121.0
13323
864
15652
1047
15615
464.0
553
KA1504000093
506.0
264.0
531
13217
TA1308000006
109.0
20108
431
650
310.0
52.0
13431
13162
491
283.0
609
724
TA1305000006
478
664.0
347.0
TA1307000107
TA1308000045
15691
13089
987
TA1307000156
1030
20218
666
4.0
687
545
886
639.0
157.0
499.0
TA1306000013
382
556
541
581
TA1309000026
89.0
1063
612
608
663.0
635.0
37.0
975
15631
942
KA1706005007
137.0
20224
20212
659
TA1309000039
498.0
TA1308000038
295.0
197.0
889
1036
648
TA1309000036
TA1309000021
445
TA1309000055
325
16920
348
912
TA1305000011
217.0
611
207.0
15535
465
966
KA1503000064
813
787
422.0
913
20204
TA1308000029
16951
625
446.0
176.0
337.0
204.0
586
959
531.0
86.0
194.0
20246.0
550
20232
984
72.0
305
chargingstx1
WL-008
567
TA1305000014
93.0
15651
977
421
728
TA1309000030
15686
TA1306000015
KA1504000114
480
15653
113.0
739
13213
277.0
607
429
13271
321.0
522
20102
613
402
330.0
TA1307000117
617
400
324
KA1504000091
15443
694
TA1309000049
1013
TA1309000037
268.0
TA1305000034
775
20255.0
1034
18017
316.0
422
KA1504000078
TA1308000012
657.0
665
20244
175.0
212.0
623.0
645.0
1068
645
191.0
TA1308000014
497
301.0
543
387
13008
TA1309000006
227.0
336.0
1015
667
KA1503000066
13134
TA1305000041
15640
568
15449
819
226.0
520.0
270.0
595.0
Wilton Ave & Diversey Pkwy - Charging
TA1307000064
46.0
KA1503000029
950
TA1309000024
20203
1046
660
446
722
479
938
41.0
15622
288.0
TA1307000001
326
717
20221
331.0
13243
956
20127
582
748
685
430
274.0
53.0
KA1503000043
13045
20123
583
965
398.0
13179
377
798
510
1012
15530
42.0
13139
TA1305000020
15545
287.0
18016
TA1307000159
KA1504000076
525
50.0
KA1504000152
691
TA1307000038
642
177.0
661
182.0
822
199.0
KA1503000054
21544
SL-011
KA1504000140
232.0
20124
580
947
198.0
818
13427
419
TA1305000003
TA1307000039
867
13001
511.0
656.0
16970
535
KA1504000128
13144
WL-011
492
555
985
424
454.0
458
1057
16953
644
KA1503000007
18067
15687
640
559
718
15575
16915
826
538
315.0
27.0
501
498
TA1308000005
13325
325.0
13331
150.0
351
514
15571
490
745
275.0
328.0
154.0
658
452.0
TA1309000050
TA1308000007
KA1503000021
290.0
693
TA1305000022
244.0
13292
13303
434
20254.0
179.0
527
61.0
55.0
20229
447.0
20256.0
20119
906
971
13253
310
13300
436
KA1504000147
13080
174.0
505
108.0
369
13028
59.0
106.0
16912
Lincoln Ave & Roscoe St - Charging
TA1307000126
SL-013
13075
13006
152.0
517
875
334.0
13042
LF-005
475.0
128.0
TA1305000035
341
153.0
20113
870
1011
16903
20207
13420
569
808
16010
TA1309000001
393
489
515
681
774
803
544
192.0
15576
426.0
143.0
TA1308000001
974
TA1307000129
904
495
KA1504000146
KA1503000009
932
593
404
KA1503000044
48.0
15632
13083
626
KA1503000025
20205
549
672.0
13257
117.0
KA150400009X
20126
13037
877
KA1504000127
RP-004
482.0
633
253.0
596
13154
13128
13290
627
482
TA1308000047
KA1504000155
224.0
601.0
20.0
730
KA1503000073
KA1503000030
15599
164.0
941
20248.0
881
49.0
20234
777
869
17660
13229
955
323.0
20116
780
525.0
20206
378.0
416
TA1309000029
523
606
391
TA1309000059
260.0
438
13434
527.0
KA1503000001
443
598
225.0
74.0
208.0
20103
25.0
TA1307000005
577
20243
TA1305000037
366.0
13242
KA1504000167
15470
KA1503000068
324.0
120.0
839
578
721
75.0
282.0
896
750
15634
54.0
363.0
451.0
TA1305000030
16950
318
367
856
171.0
TA1306000016
KA1503000055
21.0
20130
344
972
762
Hastings WH 2
369.0
958
834
424.0
727
KA1504000164
991
360
KA1504000104
KA1504000158
KA1504000168
313
988
47.0
335.0
389
833
114.0
655
20236
13138
523.0
542
TA1307000130
314
210.0
979
118.0
KA1504000129
SL-005
1055
353
KA1503000018
20106
TA1307000128
767
349
615
843
461.0
521
20112
KA1504000079
TA1309000014
TA1307000044
KA1503000046
TA1307000163
740
250.0
500
16933
462
341.0
13341
624.0
KA1504000106
20249.0
15624
13.0
321
546
1018
488
13164
TA1309000063
KP1705001026
13050
683
394.0
20105
15692
247.0
885
506
419.0
502
339
903
20134
TA1309000023
453.0
15666
13033
836
1020
326.0
13096
KA1503000041
499
362.0
TA1309000010
719
425.0
660.0
TA1306000007
13056
1039
TA1305000009
13269
919
340
15491
980
TA1307000113
561
849
TA1306000010
13288
1040
KA1503000003
783
845
13029
13277
20240
293.0
794
935
SL-007
13133
311.0
119.0
964
TA1308000019
428
13259
467.0
472
TA1307000066
TA1307000149
795
TA1307000048
481
866
992
57.0
629
395.0
149.0
TA1309000067
643
13156
933
13409
364.0
KA1503000045
TA1309000042
131.0
472.0
TA1307000127
620.0
13326
630
291.0
20215
584
KA1503000038
628.0
923
KA1504000086
13109
20239
13017
TA1307000144
229.0
1056
807
TA1306000011
5.0
418
KA1504000161
996
20257.0
706
20202
880
963
810
597.0
452
1019
231.0
537
890
116.0
TA1306000002
414
20230
899
860
758
1070
920
KA1503000027
397
20231
17.0
591
20109
558.0
788
317
589
021320
18.0
SL-009
16943
484
786
13036
24.0
395
533
420
292.0
77.0
13160
99.0
TA1307000142
614
15646
RP-002
TA1307000120
13194
707
1021
847
575
13354
604
654.0
414.0
DIVVY 001 - Warehouse test station
200.0
528
929
530
951
20999
15446
20225
338
TA1308000031
476
883
375
751
332.0
931
922
735
692
190.0
441
302.0
219.0
638
949
TA1309000018
383.0
13263
26.0
1060
861
13248
619
628
347
20208
346.0
20129
201022
320.0
15650
876
15578
425
800
481.0
195.0
626.0
KA1504000149
403
20260.0
1033
TA1305000010
TA1309000015
19.0
15654
934
SL-006
407
990
641.0
TA1309000058
33.0
13235
13319
TA1307000111
386.0
13081
823
610
621
300.0
799
18062
TA1306000029
666.0
7.0
TA1309000061
142.0
385.0
844
13102
KA1503000047
1061
999
579
251.0
66.0
15544
356
526
921
862
13059
421.0
TA1309000004
KA1504000162
916
15643
969
814
349.0
TA1307000124
13143
603
562
Divvy Valet - Oakwood Beach
13256
KA1503000005
343.0
625.0
16921
TA1309000033
871
TA1307000121
679
15534
233.0
KA1503000072
998
18058
835
267.0
13135
776
13157
16918
457.0
646
711
KA17018068
20133
TA1308000043
TA1308000046
KA1503000023
183.0
821
352
18069
900
355
340.0
KA1503000028
90.0
15546
396
473
742
973
318.0
TA1308000036
TA1305000002
792
13197
500.0
1045
350.0
657
45.0
20247.0
Throop/Hastings Mobile Station
280.0
168.0
624
129.0
536
605
319.0
902
TA1308000021
13137
738
KA17018054
56.0
485
442
KA1503000002
TA1307000134
354
TA1306000003
TA1305000029
13289
SL-010
TA1308000023
TA1306000032
TA1309000035
812
20220
TA1307000150
237.0
517.0
343
676
13034
572
13215
TA1309000066
13165
15585
350
1058
KA1504000156
13265
15529
255.0
524
302
954
KA1503000020
KA1503000051
20110
358
1054
TA1307000052
914
359.0
E006
715
80.0
632.0
539
KA1504000175
E008
989
632
13132
KA1504000109
16948
13389
336
144.0
20253.0
KA1503000014
KA1503000065
SL-012
388
112.0
857
695
444
KA1504000102
KA1504000097
337
TA1308000050
30.0
Bissell St & Armitage Ave - Charging
20115
TA1306000006
KA1504000130
702.0
784
28.0
1069
342.0
35.0
830
230.0
84.0
571
16937
948
653
15445
20128
493.0
641
588
893
312.0
13022
303.0
RP-008
20131
558
KA1504000171
13245
554
16906
chargingstx4
475
1038
595
158.0
13108
TA1307000151
13091
434.0
TA1307000139
655.0
361
592
RP-009
20121
323
426
689
165.0
13163
15542
263.0
368.0
88.0
KA1503000033
141.0
668
36.0
TA1307000138
KA1504000142
TA1306000009
22.0
491.0
918
234.0
622.0
459.0
238.0
20242
312
585
RP-005
126.0
213.0
15664
TA1307000136
43.0
601
15655
630.0
TA1307000160
20111
344.0
746
254.0
TA1305000005
20104
140.0
1065
20238
825
651
223.0
831
TA1307000006
1016
133.0
858
KA1503000015
13074
399
156.0
672
60.0
13294
345.0
519
560
301
173.0
185.0
494
13192
631
842
KA1504000080
DIVVY CASSETTE REPAIR MOBILE STATION
634
TA1308000026
15623
TA1306000014
20213
816
379
733
13016
TA1306000026
KA1504000160
20209
373
663
495.0
KA1504000143
246.0
764
805
415
13285
20201
RP-006
249.0
770
285.0
KA1503000013
13353
331
359
KA1504000126
166.0
496
937
13073
243.0
785
574
16932
304.0
TA1309000027
20107
242.0
371
1053
513
107.0
840
401
943
658.0
623
13278
KA1503000071
KA1504000148
29.0
161.0
944
15682
433
chargingstx0
13266
970
576
241.0
659.0
261.0
515.0
380
TA1305000001
927
172.0
13136
13124
476.0
20241
3.0
811
309
925
907
772
13221
392
342
832
13307
TA1308000013
69.0
1048
804
338.0
673.0
188.0
470.0
TA1307000164
636
547
540
15550
471
486.0
953
503
13053
394
313.0
351.0
868
749
306.0
796
714
KA1504000159
316
TA1308000009
138.0
KA1504000135
18003
40.0
507
649
125.0
13158
TA1307000131
15685
841
828
590
466
319
13430
406
162.0
TA1305000017
265.0
14.0
KA1503000031
KA1504000151
474
618
15648
696
E014
20210
284.0
6.0
13345
20235
20118
897
18022
16913
TA1309000002
KA1504000096
493
1062
859
KA1504000113
673
460
RN-
960
682
534
TA1309000007
145.0
702
13206
563
130.0
13224
TA1305000025
13021
509
13249
KA1503000053
KA1503000012
TA1307000115
TA1309000019
329.0
20222
E002
276.0
KA1503000010
760
662.0
TA1307000070
15668
20120
13432
333.0
76.0
639
435
345
520
180.0
TA1306000012
220.0
855
13146
20228
13155
420.0
39.0
20219
417.0
20125
18025
564
KA1503000032
TA1309000003
TA1307000119
13216
E007
565
423.0
KA1503000059
463.0
1032
9.0
13332
94.0
677
20114
698
KA1504000116
637
865
766
13268
570
674
13068
15597
417
E011
KA1503000004
448.0
621.0
801
13398
96.0
20223
KA1503000024
228.0
882
415.0
1072
901
115.0
1023
791
850
398
13258
20226
16991
KA1504000090
930
13304
13247
KA1503000040
TA1307000061
13338
20211
RP-001
743
993
458.0
239.0
827
KA1504000117
TA1307000041
13296
222.0
KA1504000103
15442
516
952
307
15628
KA1504000134
390
557
378
620
127.0
747
548
13379
1014
259.0
TA1307000158
15539
551
TA1306000008
753
460.0
13063
TA1309000012
354.0
16994
744
85.0
TA1309000008
15667
16905
13061
815
TA1309000025
20217
20245
532

In [148]:
# used this to investigate stand-out id entries and the like
k_final[k_final['from_station_id'] == 'DIVVY 001 - Warehouse test station']

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
8703569,8705946,599C6337A1F1635A,electric_bike,19:21:15,19:29:33,WEST CHI-WATSON,DIVVY 001 - Warehouse test station,Wood St & Taylor St (Temp),13285,41.851673,...,member,2022-05-07,2022-05-07,0,0.0,Chicago,0,0.0,Chicago,498
9197402,9199780,7A492BA13DC9849E,electric_bike,21:12:47,21:54:42,WestChi,DIVVY 001 - Warehouse test station,Mulligan Ave & Wellington Ave,351,41.934747,...,casual,2022-06-03,2022-06-03,0,0.0,Chicago,0,0.0,Chicago,2515
9657783,9660162,7325C8783518FE2F,electric_bike,19:58:33,20:00:46,WestChi,DIVVY 001 - Warehouse test station,Narragansett & Wrightwood,314,41.927299,...,member,2022-06-03,2022-06-03,0,0.0,Chicago,0,0.0,Chicago,133
9747690,9750069,226015676A82060F,electric_bike,15:08:17,15:25:14,WEST CHI-WATSON,DIVVY 001 - Warehouse test station,Milwaukee Ave & Fullerton Ave,428,41.924738,...,casual,2022-06-22,2022-06-22,0,0.0,Chicago,0,0.0,Chicago,1017
10203811,10206193,053289A38DEB1606,electric_bike,08:10:53,08:16:17,WestChi,DIVVY 001 - Warehouse test station,Pulaski Rd & 21st St,331.0,41.836699,...,member,2022-07-20,2022-07-20,0,0.0,Chicago,19,176.0,Chicago,324
10883127,10885512,0E2BDA1E247E7F0C,electric_bike,21:06:10,21:15:15,WEST CHI-WATSON,DIVVY 001 - Warehouse test station,Long & Irving Park,398,41.927669,...,casual,2022-08-13,2022-08-13,0,0.0,Chicago,0,0.0,Chicago,545
10968379,10970764,A80F66E86B532671,electric_bike,10:45:23,11:18:03,WestChi,DIVVY 001 - Warehouse test station,Normal Ave & Archer Ave,TA1308000014,41.932418,...,casual,2022-08-12,2022-08-12,0,0.0,Chicago,0,0.0,Chicago,1960

In [149]:
# id: '2059 Hastings Warehouse Station' delete rides with warehouse in the name, station name: 'NewHastings'

k_final = k_final.drop(k_final[k_final['from_station_id'] == '2059 Hastings Warehouse Station'].index)
k_final = k_final.drop(k_final[k_final['end_station_id'] == '2059 Hastings Warehouse Station'].index)

In [150]:
k_final.shape

(11948584, 23)

In [151]:
# delete these 'Hastings WH 2' , 'Throop/Hastings Mobile Station'

k_final = k_final.drop(k_final[k_final['from_station_id'] == 'Hastings WH 2'].index)
k_final = k_final.drop(k_final[k_final['end_station_id'] == 'Hastings WH 2'].index)

k_final = k_final.drop(k_final[k_final['from_station_id'] == 'Throop/Hastings Mobile Station'].index)
k_final = k_final.drop(k_final[k_final['end_station_id'] == 'Throop/Hastings Mobile Station'].index)

In [152]:
k_final[k_final['from_station_id'] == 'DIVVY 001 - Warehouse test station']

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
8703569,8705946,599C6337A1F1635A,electric_bike,19:21:15,19:29:33,WEST CHI-WATSON,DIVVY 001 - Warehouse test station,Wood St & Taylor St (Temp),13285,41.851673,...,member,2022-05-07,2022-05-07,0,0.0,Chicago,0,0.0,Chicago,498
9197402,9199780,7A492BA13DC9849E,electric_bike,21:12:47,21:54:42,WestChi,DIVVY 001 - Warehouse test station,Mulligan Ave & Wellington Ave,351,41.934747,...,casual,2022-06-03,2022-06-03,0,0.0,Chicago,0,0.0,Chicago,2515
9657783,9660162,7325C8783518FE2F,electric_bike,19:58:33,20:00:46,WestChi,DIVVY 001 - Warehouse test station,Narragansett & Wrightwood,314,41.927299,...,member,2022-06-03,2022-06-03,0,0.0,Chicago,0,0.0,Chicago,133
9747690,9750069,226015676A82060F,electric_bike,15:08:17,15:25:14,WEST CHI-WATSON,DIVVY 001 - Warehouse test station,Milwaukee Ave & Fullerton Ave,428,41.924738,...,casual,2022-06-22,2022-06-22,0,0.0,Chicago,0,0.0,Chicago,1017
10203811,10206193,053289A38DEB1606,electric_bike,08:10:53,08:16:17,WestChi,DIVVY 001 - Warehouse test station,Pulaski Rd & 21st St,331.0,41.836699,...,member,2022-07-20,2022-07-20,0,0.0,Chicago,19,176.0,Chicago,324
10883127,10885512,0E2BDA1E247E7F0C,electric_bike,21:06:10,21:15:15,WEST CHI-WATSON,DIVVY 001 - Warehouse test station,Long & Irving Park,398,41.927669,...,casual,2022-08-13,2022-08-13,0,0.0,Chicago,0,0.0,Chicago,545
10968379,10970764,A80F66E86B532671,electric_bike,10:45:23,11:18:03,WestChi,DIVVY 001 - Warehouse test station,Normal Ave & Archer Ave,TA1308000014,41.932418,...,casual,2022-08-12,2022-08-12,0,0.0,Chicago,0,0.0,Chicago,1960

In [153]:
# delete all 'DIVVY 001 - Warehouse test station' entries, either way

k_final = k_final.drop(k_final[k_final['from_station_id'] == 'DIVVY 001 - Warehouse test station'].index)
k_final = k_final.drop(k_final[k_final['end_station_id'] == 'DIVVY 001 - Warehouse test station'].index)

In [154]:
# 'Clark St & 9th St (AMLI)' id is messed up, it is 394 on some and SL-009 on others, needs replacement

k_final.loc[k_final['from_station_name'] == 'Clark St & 9th St (AMLI)', 'from_station_id'] = 'SL-009'
k_final.loc[k_final['to_station_name'] == 'Clark St & 9th St (AMLI)', 'end_station_id'] = 'SL-009'

# may do this check for each value to make sure everything is mapped to one id only
set(list(k_final.from_station_id[k_final['from_station_name'] == 'Clark St & 9th St (AMLI)'].values))

{'SL-009'}

In [155]:
k_final[k_final['from_station_name'] == 'Clark St & 9th St (AMLI)']

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
4566,4568,0900021397DF495A,docked_bike,06:16:43,06:22:32,Clark St & 9th St (AMLI),SL-009,Franklin St & Monroe St,287.0,41.870800,...,member,2020-01-07,2020-01-07,15,0.0,Chicago,23,57.0,Chicago,349
4570,4572,155033D91BC55315,docked_bike,17:50:28,18:07:05,Clark St & 9th St (AMLI),SL-009,Damen Ave & Madison St,215.0,41.870800,...,member,2020-01-15,2020-01-15,15,0.0,Chicago,15,134.0,Chicago,997
4571,4573,1DD9D4BB4CDC986C,docked_bike,06:20:58,06:26:41,Clark St & 9th St (AMLI),SL-009,Franklin St & Monroe St,287.0,41.870800,...,member,2020-01-27,2020-01-27,15,0.0,Chicago,23,57.0,Chicago,343
5391,5393,C39D5171DF851BE5,docked_bike,12:19:47,12:29:44,Clark St & 9th St (AMLI),SL-009,State St & Van Buren St,33.0,41.870800,...,casual,2020-01-31,2020-01-31,15,0.0,Chicago,27,3.0,Chicago,597
6566,6568,5D314128CC06B755,docked_bike,09:34:07,09:52:58,Clark St & 9th St (AMLI),SL-009,Paulina St & Flournoy St,383.0,41.870800,...,member,2020-01-06,2020-01-06,15,0.0,Chicago,23,669.0,Chicago,1131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11947393,11949780,273D9699DD69E496,classic_bike,12:58:25,13:26:34,Clark St & 9th St (AMLI),SL-009,Rush St & Hubbard St,KA1503000044,41.870816,...,casual,2022-10-08,2022-10-08,0,0.0,Chicago,0,0.0,Chicago,1689
11947411,11949798,35C45A0F35075F1E,classic_bike,20:36:12,20:56:12,Clark St & 9th St (AMLI),SL-009,Aberdeen St & Jackson Blvd,13157,41.870816,...,member,2022-10-15,2022-10-15,0,0.0,Chicago,0,0.0,Chicago,1200
11947412,11949799,1BA94D176F4369C7,classic_bike,19:13:44,19:56:04,Clark St & 9th St (AMLI),SL-009,Aberdeen St & Jackson Blvd,13157,41.870816,...,member,2022-10-28,2022-10-28,0,0.0,Chicago,0,0.0,Chicago,2540
11947424,11949811,AD06BD156FB5884F,classic_bike,12:58:31,13:26:40,Clark St & 9th St (AMLI),SL-009,Rush St & Hubbard St,KA1503000044,41.870816,...,casual,2022-10-08,2022-10-08,0,0.0,Chicago,0,0.0,Chicago,1689
11947646,11950033,0B618A49B3F62512,classic_bike,19:14:33,19:56:00,Clark St & 9th St (AMLI),SL-009,Aberdeen St & Jackson Blvd,13157,41.870816,...,member,2022-10-28,2022-10-28,0,0.0,Chicago,0,0.0,Chicago,2487

In [156]:
set(list(k_final.end_station_id[k_final['to_station_name'] == 'Clark St & 9th St (AMLI)'].values))

{'SL-009'}

In [157]:
# check validity of these
# 'Bissell St & Armitage Ave - Charging', 'chargingstx0'
# basically want to delete all rides that start and end with 'charging' or 'charge' in the station name/id, because these are
# not actual rides, they are charging sessions that are clocked with a ridetime

term1 = (k_final['from_station_name'].str.lower().str.contains("charg", regex=False, na=False) == True)
term2 = (k_final['to_station_name'].str.lower().str.contains("charg", regex=False, na=False) == True)
term3 = (k_final['ride_durations'] < 65)

k_final = k_final.drop(k_final[term1 & term2 & term3].index)

In [158]:
k_final[k_final['from_station_name'].str.lower().str.contains("charg", regex=False, na=False) == True]

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
8135551,8137905,76C6AD16440C64D4,electric_bike,15:56:55,16:01:33,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,41.932303,...,casual,2022-02-09,2022-02-09,0,0.0,Chicago,0,0.0,Chicago,278
8143185,8145539,B17C6D61C8E1389D,electric_bike,11:56:32,12:01:23,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Wells St & Concord Ln,TA1308000050,41.918497,...,casual,2022-03-27,2022-03-27,0,0.0,Chicago,0,0.0,Chicago,291
8144652,8147006,540029D3110BB9A3,classic_bike,06:45:40,06:54:24,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Larrabee St & Webster Ave,13193,41.932418,...,member,2022-03-23,2022-03-23,0,0.0,Chicago,0,0.0,Chicago,524
8144744,8147098,54EB9671F6D538C6,classic_bike,13:47:17,13:56:02,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Belmont Ave,TA1307000134,41.932418,...,casual,2022-03-25,2022-03-25,0,0.0,Chicago,0,0.0,Chicago,525
8150747,8153102,535BD63805CC5965,electric_bike,17:39:52,17:54:17,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Greenview Ave & Fullerton Ave,TA1307000001,41.932272,...,member,2022-03-21,2022-03-21,0,0.0,Chicago,0,0.0,Chicago,865
8156855,8159210,B72A59643F35031E,classic_bike,11:51:41,12:00:29,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Lincoln Ave & Diversey Pkwy,TA1307000064,41.918018,...,member,2022-03-28,2022-03-28,0,0.0,Chicago,0,0.0,Chicago,528
8158466,8160821,A7DEC4A909D6B88C,classic_bike,18:55:50,19:03:53,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Sheffield Ave & Willow St,TA1306000032,41.932418,...,member,2022-03-27,2022-03-27,0,0.0,Chicago,0,0.0,Chicago,483
8163558,8165913,0B3C81597B6FE13A,electric_bike,11:18:21,11:25:31,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Clark St & Lincoln Ave,13179,41.918529,...,casual,2022-03-27,2022-03-27,0,0.0,Chicago,0,0.0,Chicago,430
8170911,8173267,AE20848CB28E3381,classic_bike,22:45:36,22:48:54,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Sheffield Ave & Fullerton Ave,TA1306000016,41.918018,...,member,2022-03-24,2022-03-24,0,0.0,Chicago,0,0.0,Chicago,198
8174025,8176382,5AEA7589177D53DD,classic_bike,19:12:22,19:17:42,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Sheffield Ave & Webster Ave,TA1309000033,41.932418,...,member,2022-03-22,2022-03-22,0,0.0,Chicago,0,0.0,Chicago,320
8179392,8181749,2393F24302999195,classic_bike,23:43:29,23:54:50,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,DuSable Lake Shore Dr & Belmont Ave,TA1309000049,41.932418,...,member,2022-03-25,2022-03-25,0,0.0,Chicago,0,0.0,Chicago,681
8180891,8183248,A25EFDB8B251726A,classic_bike,19:48:41,20:05:40,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Damen Ave & Leland Ave,TA1307000158,41.932418,...,member,2022-03-24,2022-03-24,0,0.0,Chicago,0,0.0,Chicago,1019
8189378,8191735,14C2657A61891453,classic_bike,13:46:26,13:54:36,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Racine Ave & Wrightwood Ave,TA1309000059,41.918018,...,member,2022-03-27,2022-03-27,0,0.0,Chicago,0,0.0,Chicago,490
8194102,8196459,1FDCFA22DDDDCBCB,classic_bike,18:25:05,18:32:07,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Greenview Ave & Fullerton Ave,TA1307000001,41.932418,...,member,2022-03-25,2022-03-25,0,0.0,Chicago,0,0.0,Chicago,422
8195331,8197688,CFA69E3FD12BC922,classic_bike,07:42:42,07:52:57,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Southport Ave & Wrightwood Ave,TA1307000113,41.918018,...,casual,2022-03-24,2022-03-24,0,0.0,Chicago,0,0.0,Chicago,615
8199271,8201628,0D29DCA23C7D6619,classic_bike,07:09:47,07:28:45,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Lincoln Ave & Roscoe St,TA1307000138,41.918018,...,casual,2022-03-24,2022-03-24,0,0.0,Chicago,0,0.0,Chicago,1138
8201540,8203897,4F701D6A5C73AC28,classic_bike,16:05:38,16:08:41,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Halsted St & Wrightwood Ave,TA1309000061,41.932418,...,member,2022-03-25,2022-03-25,0,0.0,Chicago,0,0.0,Chicago,183
8201983,8204340,F8516F4BCCC0EC6F,classic_bike,17:38:37,17:50:23,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Clark St & Drummond Pl,TA1307000142,41.918018,...,member,2022-03-16,2022-03-16,0,0.0,Chicago,0,0.0,Chicago,706
8205028,8207386,79D79C3DFF534AA5,classic_bike,18:06:05,18:15:54,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Orleans St & Elm St,TA1306000006,41.918018,...,member,2022-03-25,2022-03-25,0,0.0,Chicago,0,0.0,Chicago,589
8213897,8216255,CAF228EA1C5C8885,electric_bike,18:15:38,18:18:35,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Southport Ave & Clybourn Ave,TA1309000030,41.918523,...,member,2022-03-28,2022-03-28,0,0.0,Chicago,0,0.0,Chicago,177
8221505,8223864,50D7F8189433BE6F,electric_bike,18:36:25,18:44:08,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Damen Ave & Wabansia Ave,20.0,41.918468,...,member,2022-03-22,2022-03-22,0,0.0,Chicago,15,154.0,Chicago,463
8239820,8242183,E7D53D8C78C9B27A,classic_bike,16:40:02,17:00:51,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Orleans St & Merchandise Mart Plaza,TA1305000022,41.932418,...,member,2022-03-21,2022-03-21,0,0.0,Chicago,0,0.0,Chicago,1249
8240710,8243073,F7CD840F30B42DAF,classic_bike,22:09:38,22:16:33,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Dayton St & North Ave,13058,41.918018,...,member,2022-03-31,2022-03-31,0,0.0,Chicago,0,0.0,Chicago,415
8241293,8243656,01D02516F8B03019,classic_bike,22:10:05,22:16:23,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Dayton St & North Ave,13058,41.918018,...,member,2022-03-31,2022-03-31,0,0.0,Chicago,0,0.0,Chicago,378
8255756,8258121,CD99545D5BF826CA,electric_bike,00:05:52,00:08:09,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Larrabee St & Armitage Ave,TA1309000006,41.918488,...,member,2022-03-26,2022-03-26,0,0.0,Chicago,0,0.0,Chicago,137
8255774,8258139,75EA99C62F82789A,classic_bike,09:44:13,09:51:40,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Larrabee St & Armitage Ave,TA1309000006,41.918018,...,member,2022-03-30,2022-03-30,0,0.0,Chicago,0,0.0,Chicago,447
8264326,8266691,7D0F3F54DB530E83,classic_bike,21:26:20,21:30:31,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Sheffield Ave & Fullerton Ave,TA1306000016,41.932418,...,member,2022-03-30,2022-03-30,0,0.0,Chicago,0,0.0,Chicago,251
8277206,8279575,22C430A9D436BB6C,electric_bike,06:08:19,06:23:30,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,McClurg Ct & Erie St,KA1503000041,41.932338,...,member,2022-03-30,2022-03-30,0,0.0,Chicago,0,0.0,Chicago,911
8287525,8289894,E087EFEB39D8B6FD,classic_bike,01:53:16,02:02:11,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Broadway & Cornelia Ave,13278,41.932418,...,casual,2022-03-27,2022-03-27,0,0.0,Chicago,0,0.0,Chicago,535
8297854,8300223,826D413E4319C7B4,electric_bike,18:39:42,18:44:00,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,41.932281,...,casual,2022-03-21,2022-03-21,0,0.0,Chicago,0,0.0,Chicago,258
8313130,8315500,390E914A91EEC763,classic_bike,18:02:28,18:17:16,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Sheffield Ave & Wellington Ave,TA1307000052,41.918018,...,member,2022-03-27,2022-03-27,0,0.0,Chicago,0,0.0,Chicago,888
8333003,8335374,41E287865EA265B7,electric_bike,06:49:22,07:07:30,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Clinton St & Madison St,TA1305000032,41.932321,...,casual,2022-03-24,2022-03-24,0,0.0,Chicago,0,0.0,Chicago,1088

In [159]:
# I will apply the same rule to charging station ids
k_final[k_final['from_station_id'].str.lower().str.contains("charg", regex=False, na=False) == True]

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
8135551,8137905,76C6AD16440C64D4,electric_bike,15:56:55,16:01:33,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,41.932303,...,casual,2022-02-09,2022-02-09,0,0.0,Chicago,0,0.0,Chicago,278
8143185,8145539,B17C6D61C8E1389D,electric_bike,11:56:32,12:01:23,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Wells St & Concord Ln,TA1308000050,41.918497,...,casual,2022-03-27,2022-03-27,0,0.0,Chicago,0,0.0,Chicago,291
8144652,8147006,540029D3110BB9A3,classic_bike,06:45:40,06:54:24,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Larrabee St & Webster Ave,13193,41.932418,...,member,2022-03-23,2022-03-23,0,0.0,Chicago,0,0.0,Chicago,524
8144744,8147098,54EB9671F6D538C6,classic_bike,13:47:17,13:56:02,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Belmont Ave,TA1307000134,41.932418,...,casual,2022-03-25,2022-03-25,0,0.0,Chicago,0,0.0,Chicago,525
8150747,8153102,535BD63805CC5965,electric_bike,17:39:52,17:54:17,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Greenview Ave & Fullerton Ave,TA1307000001,41.932272,...,member,2022-03-21,2022-03-21,0,0.0,Chicago,0,0.0,Chicago,865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11945929,11948316,C52E308D6F3E8FC4,classic_bike,16:38:57,16:43:36,Morgan St & Lake St*,chargingstx4,Aberdeen St & Jackson Blvd,13157,41.885492,...,casual,2022-10-06,2022-10-06,0,0.0,Chicago,0,0.0,Chicago,279
11945932,11948319,6428BBD05DE0B412,electric_bike,23:13:32,23:20:03,Morgan St & Lake St*,chargingstx4,Rush St & Hubbard St,KA1503000044,41.885452,...,member,2022-10-09,2022-10-09,0,0.0,Chicago,0,0.0,Chicago,391
11946093,11948480,13B866475AB890E2,electric_bike,11:10:14,11:16:31,Morgan St & Lake St*,chargingstx4,Aberdeen St & Jackson Blvd,13157,41.885410,...,member,2022-10-12,2022-10-12,0,0.0,Chicago,0,0.0,Chicago,377
11946094,11948481,02418DAFCCC881C4,electric_bike,15:42:59,15:47:38,Morgan St & Lake St*,chargingstx4,Aberdeen St & Jackson Blvd,13157,41.885509,...,casual,2022-10-05,2022-10-05,0,0.0,Chicago,0,0.0,Chicago,279
11950217,11952604,2936E4256BF4459E,electric_bike,15:49:56,15:53:18,Morgan St & Lake St*,chargingstx4,Aberdeen St & Jackson Blvd,13157,41.885556,...,casual,2022-10-11,2022-10-11,0,0.0,Chicago,0,0.0,Chicago,202

In [160]:
term_1 = (k_final['from_station_id'].str.lower().str.contains("charg", regex=False, na=False) == True)
term_2 = (k_final['end_station_id'].str.lower().str.contains("charg", regex=False, na=False) == True)
term_3 = (k_final['ride_durations'] < 65)

k_final = k_final.drop(k_final[term_1 & term_2 & term_3].index)

In [161]:
k_final[k_final['from_station_id'].str.lower().str.contains("charg", regex=False, na=False) == True]

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
8135551,8137905,76C6AD16440C64D4,electric_bike,15:56:55,16:01:33,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,41.932303,...,casual,2022-02-09,2022-02-09,0,0.0,Chicago,0,0.0,Chicago,278
8143185,8145539,B17C6D61C8E1389D,electric_bike,11:56:32,12:01:23,Bissell St & Armitage Ave - Charging,Bissell St & Armitage Ave - Charging,Wells St & Concord Ln,TA1308000050,41.918497,...,casual,2022-03-27,2022-03-27,0,0.0,Chicago,0,0.0,Chicago,291
8144652,8147006,540029D3110BB9A3,classic_bike,06:45:40,06:54:24,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Larrabee St & Webster Ave,13193,41.932418,...,member,2022-03-23,2022-03-23,0,0.0,Chicago,0,0.0,Chicago,524
8144744,8147098,54EB9671F6D538C6,classic_bike,13:47:17,13:56:02,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Belmont Ave,TA1307000134,41.932418,...,casual,2022-03-25,2022-03-25,0,0.0,Chicago,0,0.0,Chicago,525
8150747,8153102,535BD63805CC5965,electric_bike,17:39:52,17:54:17,Wilton Ave & Diversey Pkwy - Charging,Wilton Ave & Diversey Pkwy - Charging,Greenview Ave & Fullerton Ave,TA1307000001,41.932272,...,member,2022-03-21,2022-03-21,0,0.0,Chicago,0,0.0,Chicago,865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11945929,11948316,C52E308D6F3E8FC4,classic_bike,16:38:57,16:43:36,Morgan St & Lake St*,chargingstx4,Aberdeen St & Jackson Blvd,13157,41.885492,...,casual,2022-10-06,2022-10-06,0,0.0,Chicago,0,0.0,Chicago,279
11945932,11948319,6428BBD05DE0B412,electric_bike,23:13:32,23:20:03,Morgan St & Lake St*,chargingstx4,Rush St & Hubbard St,KA1503000044,41.885452,...,member,2022-10-09,2022-10-09,0,0.0,Chicago,0,0.0,Chicago,391
11946093,11948480,13B866475AB890E2,electric_bike,11:10:14,11:16:31,Morgan St & Lake St*,chargingstx4,Aberdeen St & Jackson Blvd,13157,41.885410,...,member,2022-10-12,2022-10-12,0,0.0,Chicago,0,0.0,Chicago,377
11946094,11948481,02418DAFCCC881C4,electric_bike,15:42:59,15:47:38,Morgan St & Lake St*,chargingstx4,Aberdeen St & Jackson Blvd,13157,41.885509,...,casual,2022-10-05,2022-10-05,0,0.0,Chicago,0,0.0,Chicago,279
11950217,11952604,2936E4256BF4459E,electric_bike,15:49:56,15:53:18,Morgan St & Lake St*,chargingstx4,Aberdeen St & Jackson Blvd,13157,41.885556,...,casual,2022-10-11,2022-10-11,0,0.0,Chicago,0,0.0,Chicago,202

In [162]:
# deleted 2046 rows. Now I want to examine how many entries have 0 second entries for ride time, so I can delete those as well.

In [163]:
k_final[k_final['ride_durations'] == 0]

,index,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
154090,154161,23EF1DCC9FCA40BA,docked_bike,11:34:40,11:34:40,HQ QR,675.0,HQ QR,675.0,41.889900,...,casual,2020-02-28,2020-02-28,0,0.0,Chicago,0,0.0,Chicago,0
162810,162888,86163D9676BBBE62,docked_bike,14:41:16,14:41:16,HQ QR,675.0,HQ QR,675.0,41.889900,...,casual,2020-02-26,2020-02-26,0,0.0,Chicago,0,0.0,Chicago,0
171299,171382,836931C569802344,docked_bike,09:56:47,09:56:47,HQ QR,675.0,HQ QR,675.0,41.889900,...,casual,2020-02-27,2020-02-27,0,0.0,Chicago,0,0.0,Chicago,0
172304,172387,07CD3CBC94106B37,docked_bike,10:02:30,10:02:30,HQ QR,675.0,HQ QR,675.0,41.889900,...,casual,2020-02-28,2020-02-28,0,0.0,Chicago,0,0.0,Chicago,0
183884,183972,83D849E5C5716FA3,docked_bike,10:39:01,10:39:01,HQ QR,675.0,HQ QR,675.0,41.889900,...,casual,2020-02-28,2020-02-28,0,0.0,Chicago,0,0.0,Chicago,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11887485,11889872,53C0EA485F89ED0E,classic_bike,15:40:18,15:40:18,Sheffield Ave & Kingsbury St,13154,Sheffield Ave & Kingsbury St,13154,41.910522,...,member,2022-10-07,2022-10-07,0,0.0,Chicago,0,0.0,Chicago,0
11925855,11928242,411F609A2E4C54F2,electric_bike,15:19:21,15:19:21,Kimball Ave & Belmont Ave,KA150400009X,Public Rack - Christiana Ave & Belmont Ave,499,41.939404,...,member,2022-10-07,2022-10-07,0,0.0,Chicago,0,0.0,Chicago,0
11929536,11931923,2896635694A8BC24,electric_bike,17:01:13,17:01:13,Sheffield Ave & Wrightwood Ave,TA1309000023,Sheffield Ave & Wrightwood Ave,TA1309000023,41.928549,...,member,2022-10-23,2022-10-23,0,0.0,Chicago,0,0.0,Chicago,0
11949457,11951844,088C9ADC2E7E3852,electric_bike,15:13:23,15:13:23,Clark St & Armitage Ave,13146,Clark St & Armitage Ave,13146,41.918334,...,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago,0
11949807,11952194,39D610E4F25FBC78,electric_bike,16:04:39,16:04:39,Sheridan Rd & Montrose Ave,TA1307000107,Sheridan Rd & Montrose Ave,TA1307000107,41.961566,...,member,2022-10-26,2022-10-26,0,0.0,Chicago,0,0.0,Chicago,0

In [164]:
# Now that I have observed HQ QR, I will delete all station names: 'HQ QR' and 675.0 in addition to all ride_durations = 0

k_final = k_final.drop(k_final[k_final['ride_durations'] == 0].index)

k_final = k_final.drop(k_final[k_final['from_station_id'] == '675.0'].index)
k_final = k_final.drop(k_final[k_final['end_station_id'] == '675.0'].index)


k_final = k_final.drop(k_final[k_final['from_station_name'] == 'HQ QR'].index)
k_final = k_final.drop(k_final[k_final['to_station_name'] == 'HQ QR'].index)

In [167]:
k_final.isnull().sum()

index                0
ride_id              0
rideable_type        0
start_time           0
end_time             0
from_station_name    0
from_station_id      0
to_station_name      0
end_station_id       0
start_lat            0
start_lng            0
end_lat              0
end_lng              0
usertype             0
start_date           0
end_date             0
from_dpcapacity      0
from_landmark        0
from_city            0
to_dpcapacity        0
to_landmark          0
to_city              0
ride_durations       0
dtype: int64

In [171]:
k_final = k_final.drop('index',axis=1)

In [172]:
k_final

,ride_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,...,usertype,start_date,end_date,from_dpcapacity,from_landmark,from_city,to_dpcapacity,to_landmark,to_city,ride_durations
0,EACB19130B0CDA4A,docked_bike,20:06:59,20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,...,member,2020-01-21,2020-01-21,15,112.0,Chicago,11,239.0,Chicago,451
1,8FED874C809DC021,docked_bike,14:22:39,14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,...,member,2020-01-30,2020-01-30,19,316.0,Chicago,15,321.0,Chicago,223
2,789F3C21E472CA96,docked_bike,19:29:26,19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,...,member,2020-01-09,2020-01-09,15,277.0,Chicago,23,69.0,Chicago,171
3,C9A388DAC6ABF313,docked_bike,16:17:07,16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,...,member,2020-01-06,2020-01-06,31,5.0,Chicago,15,262.0,Chicago,529
4,943BC3CBECCFD662,docked_bike,08:37:16,08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,...,member,2020-01-30,2020-01-30,19,21.0,Chicago,19,264.0,Chicago,332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11950538,BC3BFA659C9AB6F1,classic_bike,01:41:29,01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago,947
11950539,ACD65450291CF95F,classic_bike,01:41:54,01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago,915
11950540,4AAC03D1438E97CA,classic_bike,09:34:11,10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,-87.638677,...,casual,2022-10-15,2022-10-15,0,0.0,Chicago,0,0.0,Chicago,1750
11950541,8E6F3F29785E5D40,classic_bike,10:21:34,10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,-87.638677,...,member,2022-10-09,2022-10-09,0,0.0,Chicago,0,0.0,Chicago,1331
11950542,8D14CBE672431920,docked_bike,13:17:13,13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,-87.636282,...,casual,2022-10-22,2022-10-22,0,0.0,Chicago,0,0.0,Chicago,1741

In [173]:
k_final = k_final.rename(columns={'ride_id' : 'trip_id', 'from_dpcapacity' : 'end_dpcapacity', 'to_dpcapacity' : 'start_dpcapacity', 'ride_durations' : 'tripduration'})

In [174]:
k_final

,trip_id,rideable_type,start_time,end_time,from_station_name,from_station_id,to_station_name,end_station_id,start_lat,start_lng,...,usertype,start_date,end_date,end_dpcapacity,from_landmark,from_city,start_dpcapacity,to_landmark,to_city,tripduration
0,EACB19130B0CDA4A,docked_bike,20:06:59,20:14:30,Western Ave & Leland Ave,239.0,Clark St & Leland Ave,326.0,41.966500,-87.688400,...,member,2020-01-21,2020-01-21,15,112.0,Chicago,11,239.0,Chicago,451
1,8FED874C809DC021,docked_bike,14:22:39,14:26:22,Clark St & Montrose Ave,234.0,Southport Ave & Irving Park Rd,318.0,41.961600,-87.666000,...,member,2020-01-30,2020-01-30,19,316.0,Chicago,15,321.0,Chicago,223
2,789F3C21E472CA96,docked_bike,19:29:26,19:32:17,Broadway & Belmont Ave,296.0,Wilton Ave & Belmont Ave,117.0,41.940100,-87.645500,...,member,2020-01-09,2020-01-09,15,277.0,Chicago,23,69.0,Chicago,171
3,C9A388DAC6ABF313,docked_bike,16:17:07,16:25:56,Clark St & Randolph St,51.0,Fairbanks Ct & Grand Ave,24.0,41.884600,-87.631900,...,member,2020-01-06,2020-01-06,31,5.0,Chicago,15,262.0,Chicago,529
4,943BC3CBECCFD662,docked_bike,08:37:16,08:42:48,Clinton St & Lake St,66.0,Wells St & Hubbard St,212.0,41.885600,-87.641800,...,member,2020-01-30,2020-01-30,19,21.0,Chicago,19,264.0,Chicago,332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11950538,BC3BFA659C9AB6F1,classic_bike,01:41:29,01:57:16,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago,947
11950539,ACD65450291CF95F,classic_bike,01:41:54,01:57:09,Clifton Ave & Armitage Ave,TA1307000163,Lincoln Ave & Roscoe St*,chargingstx5,41.918216,-87.656936,...,casual,2022-10-30,2022-10-30,0,0.0,Chicago,0,0.0,Chicago,915
11950540,4AAC03D1438E97CA,classic_bike,09:34:11,10:03:21,Sedgwick St & North Ave,TA1307000038,Wabash Ave & Grand Ave,TA1307000117,41.911386,-87.638677,...,casual,2022-10-15,2022-10-15,0,0.0,Chicago,0,0.0,Chicago,1750
11950541,8E6F3F29785E5D40,classic_bike,10:21:34,10:43:45,Sedgwick St & North Ave,TA1307000038,Damen Ave & Clybourn Ave,13271,41.911386,-87.638677,...,member,2022-10-09,2022-10-09,0,0.0,Chicago,0,0.0,Chicago,1331
11950542,8D14CBE672431920,docked_bike,13:17:13,13:46:14,Clark St & Armitage Ave,13146,Wabash Ave & Grand Ave,TA1307000117,41.918306,-87.636282,...,casual,2022-10-22,2022-10-22,0,0.0,Chicago,0,0.0,Chicago,1741

In [175]:
k_final.to_csv('merged2020_2022.csv')